view/frontend/templates/js/replacejs.phtml

Before this PR, we use `cart.orderToken` as flag and set empty value to indicate "there is ongoing request" but it was problematic because race condition can lead bolt to read empty order token.

Use explicit flag to check if there is on-going request to server

---

Controller/Cart/Email.php
Controller/Shipping/Prefetch.php
view/frontend/templates/js/replacejs.phtml

Small fix, tested. The abandoned cart email was assigned to immutable quote (status active = false) instead of parent, active quote. No emails were sent. Reported on Capillus.
Should be propagated / merged into master.

abandoned email hotfix

---

Controller/Adminhtml/Cart/Data.php
Controller/Cart/Data.php
Controller/Shipping/Prefetch.php
Helper/Cart.php
Helper/Order.php
Model/Api/ShippingMethods.php
view/frontend/templates/js/replacejs.phtml

Set the order_reference to the parent quote id, preventing order duplication on Bolt side, thus preventing it on Magento too.
Use cloned quote id (immutable quote) on Magento side to prevent cart data mismatches.
Transmit cloned quote id in display_id field alongside reserved order id, concatenated by ' / '.

Cart data cloned quote id placeholder

---

Helper/Cart.php
Model/Api/DiscountCodeValidation.php
view/frontend/templates/js/replacejs.phtml

Error might or might not nullify the previously applied discount. it depends when it happens.
The cart data is returned in error response whenever it is available so the checkout cart could be updated accordingly.
Removed payment_only cart creation option. will add it later when we start to support it.

Discount validation implement with cloned quote

---

view/frontend/templates/js/replacejs.phtml

Currently our custom dialog (`showBoltErrorMessage`) is hidden under Bolt checkout modal with infinite spinner.

Call callback even when order creation AJAX fails

---

Helper/Order.php

We need the ability to store an order comment in a different manner other than as a status history comment. In order to push to our ERP, we need to integrate this with an already defined order field. Unnesting the code that assigns the order comment to it's own function allows us to internally rewrite just that function and change where the comment is saved.

unnested order note assignment

---

Helper/Order.php

Hot fix successfully applied to RS prod. The assumption was somewhere in a third party extension $order->setCustomerNoteNotify is set.

fix for order confirmation emails stopped going from magento

---

Model/Api/DiscountCodeValidation.php

The GiftCert module throws an exception like:
`throw NoSuchEntityException::doubleField('cert_id', $certId, 'cert_number', $certId);`
if cannot find cert data in DB.
P.S.: Task "https://app.asana.com/0/941920570700290/936157624042566/f"

Unirgy_GiftCert module: Fixed throwing exception.

---

etc/webapi_rest/di.xml

This needs to be deployed to Taos as a Returnly (and others) oauth authorization fix.

hook context overriding oauth context fix

---

Helper/Cart.php
Helper/Discount.php
Helper/Order.php

All cart manipulation from Bolt side was previously done to the immutable quote - saving address, shipping method, user data (email) and payment method. And the order was created out of that quote, deleting the parent and all other immutable quotes. 
On the other hand, only one (the parent) quote can have the active status for the cart / session. There are event listeners to cart events on the active quote. Third party plugins use them, Bronto among them. 
The solution provided here is to replicate immutable quote data back into the parent before order creation and then do the save on the parent quote model after any particular change (address, method, payment..) so the listened events get fired in the expected sequence. And, naturally, transform the parent quote into order and delete all …

Create order from parent quote

---

Controller/Cart/Email.php

Note: after merging to master re-tag should be done for the current release or creating a new one and merge master into develop. This addresses the request from Coastal Business so it probably should not wait for the next release cycle.

fix for send store order notiffications to email collected from Bolt checkout

---

Plugin/QuotePlugin.php
etc/di.xml

Inactive quote is usually considered complete by Bronto and Magento. It is set to active->false only after order is created. It is dead after that waiting for the cleanup. No additional save called upon it, so no after save events fired.
However, our plugin depends on using inactive quotes to store immutable quote data. Multiple ones per parent. After save events get fired on every immutable quote generation and shipping and tax calls and Bronto started to receive junk, lots of it.

 Prevent dispatching sales_quote_save_after event for inactive quote

---

Helper/Cart.php
Helper/Discount.php
Model/Api/ShippingMethods.php
etc/di.xml

The Unirgy_Giftcert add a discount which covers only product price (subtotal).
The Unirgy_Giftcert accumulate correct balance only after address collectTotals, but if i am trying to get  Unirgy_Giftcert balance at shipping_methods step i have no correct price value - i have only product price discount.
We should get the whole balance at first of the Unirgy_Giftcert.
P.S.: Unirgy_Giftcert - also want to mention that some part of the module is encoded (the part like "add the Giftcert to the quote/cart" and some save "after update quote" event)

Unirgy_Giftcert plugin support

---

Helper/Cart.php
Helper/Discount.php
Helper/Order.php
Setup/UpgradeSchema.php

Some 3rd party plugins read Quote::getReservedOrderId() value and if set consider the quote to be a complete order. It is set by calling Quote::reserveOrderId(). We used to call it on the parent quote before creating the immutable quote. Now it is called on the first created immutable quote and stored in the separate field added to the quote model to be set on the parent quote just before order creation.

Reserve Order ID for the child quote, copy it to parent just before the quote to order submit

---

Helper/Cart.php
Helper/Order.php

Backend quotes don't have active flag set. The execution failed at the beginning of Helper\Order::createOrder(). Loosening active restriction is harmless due to the duplicate order creation check some lines below.

remove active quote restriction on order creation

---

Helper/Order.php

If a field, email for example, is empty, it used to clear what was already stored in quote address.
Missing emails had to be fixed on Bolt end. This way that could be done on store end as well.

Do not save empty address fields

---

view/frontend/templates/js/replacejs.phtml

Create order is called on js load on every page. When the cart is empty the cart promise gets rejected with an error shown in the console.

remove console error on empty cart

---

Helper/Cart.php

```php
if (( $amount = @$address->getDiscountAmount()) || ( $coupon_code = @$address->getCouponCode()))
```
If the first part of the condition ($amount) evaluates to true, evaluating of the second one is skipped throwing an error here:
```php
$cart['discounts'][] = [
...
'reference'   => $coupon_code
];
```

coupon_code undefined / not evaluated if amount exists fix

---

Helper/Order.php

Asana task: https://app.asana.com/0/564264490825835/1119769573602581
This PR allows the order to create an online credit memo even if a mismatch occurs

Move holdOnTotalsMismatch after order creation

---

Controller/Adminhtml/Order/Save.php
Helper/Cart.php
Helper/Session.php
Model/Api/CreateOrder.php

In order the redirect URL to work it needs to include the correct key a segment.
The URL is generated in vendor/magento/module-backend/Model/Url::getUrl() and calls
vendor/magento/module-backend/Model/Url::getSecretKey() which uses the form key as a salt for generating the hash (key), $salt = $this->formKey->getFormKey();
Form key is generated and stored in the session. We need to pass it to (session-less) CreateOrder API endpoint where the redirect URL is generated. The solution implemented is to use Magento cache on cart creation to store the form key with the immutable quote id as cache identifier. I tried to avoid adding another field to the quote table. I tested this and it works even with all the available Magento cache types disabled.

M 2.3.x back-office redirect url secret / form key issue

---

Block/Js.php

Task - https://app.asana.com/0/941920570700290/1125041703113784/f
The problem was at returned 0 instead of null if we have clean quote.
Magento could not find store with id 0 in 1 case (see below).
We have several cases for multi-store which already covered:

Multi-website: fix disappearing Bolt button at first load in admin side

---

.github/CODEOWNERS

Adding `CODEOWNERS` file to automatically request reviews.
https://github.blog/2017-07-06-introducing-code-owners/

Add m2 codeowners

---

Helper/Config.php
Helper/Session.php
etc/adminhtml/system.xml
etc/config.xml

This method:
```php
private function setSession($session, $sessionID, $storeId)
{
// close current session
$session->writeClose();
// set session id (to value loaded from cache)
$session->setSessionId($sessionID);
// re-start the session
$session->start();
}
```
Invalidated logged in customer session when Stores -> Configuration -> General -> Web -> Session Validation Settings -> Validate HTTP_USER_AGENT option is turned ON (Scentlok websites).
This PR adds a configuration option so we can bypass this method when needed. It remains ON by default.

make emulate session in API calls configurable, on by default - backward compatible

---

Helper/Cart.php
Model/Api/ShippingMethods.php
Test/Unit/Helper/CartTest.php

https://app.asana.com/0/941920570700290/1125788326073905/f
Code refactored a bit to remove repeating in shipping and tax call.
This is the main change:
```php
/** @var \Magento\Catalog\Model\ProductFactory */
$productFactory = $this->productFactory->create();
$productId = $productFactory->getIdBySku($item->getSku());
/** @var \Magento\Catalog\Model\Product */
$_product = $productFactory->load($productId);
```

duplicate item.reference fix, using the actual product id instead of the parent one

---

.github/CODEOWNERS

The group has @daisy1754 and @akshayas. This reduces the number of admins to only a few people. if this works, we will move all but matt into the group and remove them from the file. also makes adding and removing owners easily

Add merchant exp admins

---

.circleci/config.yml
Test/scripts/install_magento.sh
operations/docker/php70/Dockerfile
operations/docker/php71/Dockerfile
operations/docker/php72/Dockerfile

- cache composer packages
- re-use image with needed packages installed.
rough saving ~5 to 6 mins per workflow (and ~2 minutes per build) 
prior to optimization: 
post optimization

Optimize Circle build pipeline

---

.circleci/config.yml
Test/scripts/ci.sh

We will get coverage reports. The report for this branch will not be as accurate till we merge and have a run for the base branch (i.e. `develop`)
For an example look at hail or storm.

 [Coverage] Add codecov to magento2

---

Model/Api/ShippingMethods.php

**Issue:**
Getting the quote prevents the quote totals from being collected and it breaks the changes that we made in the past for adding the discount back to the shipping amount when the address doesn’t allow a discount. See the previous PR here https://github.com/BoltApp/bolt-magento2/pull/252.
**Proposed solution:**
Collect the totals when checking if the coupon is invalid for the shipping address
Asana task: https://app.asana.com/0/941920570700290/1116347704823454

Collect immutable quote totals when checking if the coupon is invalid  for the shipping address

---

Helper/Cart.php

Fix for apple pay incorrect prefill.
Reference: https://github.com/BoltApp/bolt-magento1/pull/399/files
https://app.asana.com/0/932047656377869/1129810277275150

Add apple pay prefill hints fix

---

Helper/Cart.php
Model/Api/CreateOrder.php
Model/Api/ShippingMethods.php
Test/Unit/Helper/CartTest.php
Test/Unit/Model/Api/ShippingMethodsTest.php

Custom address field (e.g. commercial / residential flag used by restaurant supply) does not get taken into account when creating bolt order / caching bolt order token.

Add custom address fields to order token cache identifier

---

view/frontend/templates/js/boltjs.phtml

Kill BoltCheckout.configure({}, {}, {check: function(){return false;})
https://github.com/BoltApp/bolt-magento2/blob/fab9d021a57089f64ffe2ddf9f54d46d34c451ae/view/frontend/templates/js/boltjs.phtml#L47
Can we get rid of this? I think if merchant clicks too soon we should show error (which will be default behaviour if you don't call configure) rather than silently swallowing click
Fixes: (link Asana Tank)
https://app.asana.com/0/941920570700290/1131786986588439/f

Remove redundant BoltCheckout.configure

---

Block/Js.php
Controller/Adminhtml/Cart/Data.php
Helper/Config.php
Test/Unit/Block/JsTest.php
etc/adminhtml/system.xml
etc/config.xml
view/adminhtml/templates/boltpay/js/replacejs.phtml
view/frontend/templates/js/replacejs.phtml

There is a redundant order/save call from the non pre-auth flow still present when pre-auth is turned on. It throws and error on HUF. Removing it fixes the issue.
Removing the call via configuration option, Pre-Auth order creation.
Fixes:
https://app.asana.com/0/941920570700290/1133661540833258/f

Implement different success processing for pre-auth and non-pre-auth orders

---

Helper/Order.php

The rejection hook is accepted by the plugin for the firstly received transaction, but is not expected for the second one cause the order was already canceled.
So the second hook fails, though redundant.
Fixes:
https://app.asana.com/0/474713171217346/1133992781429888/f
https://app.asana.com/0/0/1132873196131387/f

Multiple, subsequent irreversible rejected hooks fix

---

Controller/Adminhtml/Cart/Data.php
Controller/Cart/Data.php
Helper/Config.php
README.md
Test/Unit/Helper/ConfigTest.php
etc/adminhtml/system.xml
etc/config.xml

Removes authcapture settings from plugin, allowing admin dash settings to be the only source for this toggle.
Fixes: https://app.asana.com/0/941920570700290/1129108918946356/f

Remove authcapture settings

---

Controller/ReceivedUrlTrait.php
Helper/Discount.php
Helper/Order.php
Model/Api/ShippingMethods.php
Plugin/OrderPlugin.php
Test/Unit/Helper/OrderTest.php

Postpone dispatching checkout_submit_all_after event to after order is approved. This has 2 purposes:
1. Prevent ERPs that listen to it to pull in the order that can potentially be deleted due to the failed_payment hook
2. Speed up pre-auth order creation by deferring the order post-processing to redirect_url (success) call
Fixes:
https://app.asana.com/0/941920570700290/1135919168579417/f

Postpone checkout submit all after

---

Helper/Cart.php

The issue is in copy data from parentQuote to immutableQuote.
In plugin we tried to copy data from Magento parentQuote to our new immutableQuote. 
Inside one of the `ShippingAddress` child objects in immutableQuote I found an object that is a copy of parentQuote, instead of an immutableQuote object.
So, the Cloud Magento 2.3.x  for discount process use some parameter from address object and here we have an issue because Magento found incorrect object with incorrect data.
The problem touch such calls:
- `\Magento\Quote\Model\Quote\Address::getAllItems()` - there is a cache key which also copied
- `\Magento\SalesRule\Model\Validator::_getRules` - which consist an `address_sales_rule_id` cache key.  Which also be copied.
- Hidden address object field `cart_fixed_rules` which contain . copy …

Fix DiscountAmount for Magento 2.3 Cloud

---

Helper/Config.php
Model/Api/CreateOrder.php
Test/Unit/Helper/OrderTest.php
Test/Unit/Model/Api/CreateOrderTest.php

For orders that cannot be created because a minimum price is not met we should use 2001011 instead of General Error
Fixes:
https://app.asana.com/0/1118494470563243/1138306608527986/f
https://app.asana.com/0/0/1138306608527988/f

Crete order - minimum order amount validation

---

Helper/Order.php

This PR removes state transition checks. The reason being that as we add more processors and introduce new state, keeping the state in check involves releasing a new version of the plugin making roll outs harder.
In this new flow, we will not check state transitions and rather implicitly trust the bolt modal.
Fixes: https://app.asana.com/0/1120201793092521/1135349256216762

Remove state transition checks to support paypal

---

Helper/Order.php
Test/Unit/Helper/OrderTest.php

Multiple failed_payment hooks can come through, resulting in an error if the order has been deleted by previous hook. Solution: If the order does not exist do not throw, return OK.
Fixes:
https://app.asana.com/0/0/1138340753398482/f
https://app.asana.com/0/941920570700290/1138909039528777/f

do not throw on failed_payment hook delete order if order is already deleted

---

Helper/Order.php
Model/Api/CreateOrder.php

There was a potential bug in deleting and recreating a previously canceled order. Moving the canceled check up the flow.
Fixes:
https://app.asana.com/0/0/1139914171866907/f

check if order was canceled when loading the existing order

---

Helper/Config.php
Model/Api/ShippingMethods.php
Test/Unit/Helper/ConfigTest.php
Test/Unit/Model/Api/ShippingMethodsTest.php

Modified coupon logic check to be case-insensitive
Fixes: https://app.asana.com/0/564264490825835/1140469195577209

Modified coupon logic check to be case-insensitive

---

Helper/Order.php

This reverts commit 8320dc1410adc1b923884d1901ee49a7ab516e92.
We believe something about these state transition checks was necessary to prevent Bolt from handling state transitions from non-Bolt payment methods. We're rolling back the changes as we investigate the issues.

Revert "Remove state transition checks to support paypal (#367)"

---

Helper/MetricsClient.php
Test/Unit/Helper/MetricsClientTest.php

Added Batching to Merchant Metrics. Allowing us to specify the frequency for which these metrics are uploaded to not overwhelm the server. This approach leverages magento class to keep a global timestamp to accomplish this. 

Merchant metrics batching

---

Helper/Order.php

Skip inventory verification in success redirect call and hooks. At this point the order is already created and inventory reserved.
Magento core team intended the checkout_submit_all_after  event and $this->quoteManagement->submit($quote, $orderData) to be raised/called in the same execution.
Quote management submit method raises sales_model_service_quote_submit_before, which executes \Magento\CatalogInventory\Observer\SubtractQuoteInventoryObserver.
Event checkout_submit_all_after calls \Magento\CatalogInventory\Observer\CheckoutAllSubmitAfterObserver which, in turn calls \Magento\CatalogInventory\Observer\SubtractQuoteInventoryObserver.
Magento core team avoided  this by using inventory_processed data property on Quote object (if set, skip observer execution). Because we separated the …

Skip inventory verification in post checkout events

---

Helper/Order.php

If we enable Automatic Assignment to Customer Group https://screencast.com/t/wL9IfyT627M , the quote customer email is set to null before creating the order. This ensures the email is set back to the quote before saving the order
Fixes: https://app.asana.com/0/564264490825835/1143022171544385

Ensure customer email is set to the quote before saving the order

---

Test/scripts/ci-integration.sh

When running integration test there is no need to copy entire history of repo. Adding depth=1 param for better performance
- [ x ] New feature (change which adds functionality)
- [ x ] Successfully tested on a staging or sandbox server

Add depth 1 when cloning integraiotn test repo

---

Helper/Order.php
Model/Service/InvoiceService.php

Bolt constructor isn’t working on Magento 2.3.3, Bolt\Boltpay\Model\Service\InvoiceService.
Remove overriding constructor.
Fixes: https://app.asana.com/0/941920570700290/1144761542527713/f

remove InvoiceService constructor override

---

Plugin/OrderPlugin.php

Fatal error: Uncaught Error: Call to a member function getMethod() on null in app/code/Bolt/Boltpay/Plugin/OrderPlugin.php:60
Fixes: https://app.asana.com/0/564264490825835/1145190992675985

Ignore before plugins if order payment isn't set

---

Helper/Order.php
Model/Api/OrderManagement.php
Test/Unit/Helper/OrderTest.php
Test/Unit/Model/Api/OrderManagementTest.php

After overriding the initial order statuses and split the order processing into initial order creation and hook processing, due to ERP support and checkout speed up, some edge case flows were broken leading to unwanted results. Check the description in Asana task linked below.
Fixes: https://app.asana.com/0/941920570700290/1144813337953035/f

Multiple Bolt transactions associated with same order fix

---

Helper/Order.php

I faced a rounding issue in the validation method when working on merchant integration and saw an exception was raised. Debug let me see the values of an order object might not be rounded.
---------
Example 1.
As of the previous behavior, we had:
```
$captureAmount: 203.29
$order->getTotalInvoiced(): [empty]
$order->getGrandTotal(): 203.2874
203.29 + 0 > 203.2874 [ = true ] -> leads to raise an exception
```
This way, an exception is raised here. To avoid it, the same rounding algorithm was applied on each of operands and now it works well. The webhook was failed but it shouldn't. After the fix has been applied the webhook succeeded.
Now it works as it should:
```
getRoundAmount($order->getTotalInvoiced()) [0] + getRoundAmount($captureAmount) [20329]: 20329 …
```

Fixed validation of capture amount by using correct rounding algorithm

---

Block/Js.php
Helper/Config.php
Test/Unit/Block/JsTest.php
etc/adminhtml/system.xml
etc/config.xml
view/frontend/layout/checkout_index_index.xml
view/frontend/templates/js/checkout_funnel.js.phtml

This PR adds boiler plate code for 1) new config named "Track checkout funnel" and 2) injecting JavaScript in magento's onepage checkout if config is set
Idea is we use this when we A/B test to track checkout funnel transition in onepage checkout.
- [ x ] New feature (change which adds functionality)
- [ x ] Successfully tested on a staging or sandbox server

Adds boilerplate code to insert code for checkout funnel tracking

---

phpcs.xml

It seems Magento2.Files.LineLength was removed? CI was failing https://circleci.com/gh/BoltApp/bolt-magento2/6155?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
This PR replaces Magento2.Files.LineLength with Generic.Files.LineLength.

Use Generic.Files.LineLength instead of Magento2.Files.LineLength

---

view/adminhtml/templates/boltpay/button.phtml

Instead of clicking on the Bolt checkout button to create an admin order, the administrator sometimes chooses Bolt as the payment method and then clicks on the default submit order button and that causes Bolt order to be created without a payment. This adds the validation logic to prevent the user from submitting the order using the default submit order button like Magento 1
Fixes: https://app.asana.com/0/564264490825835/1147246218770177
#changelog
Force admin user to use Bolt checkout button instead of the Magento submit order button

Force admin user to use Bolt checkout button instead of the Magento submit order button

---

Helper/Order.php
Test/Unit/Helper/OrderTest.php

When Bolt rejects the payment irreversibly, a webhook is sent to Magento to cancel the order. The order state and status are updated to canceled but the product isn’t restocked as the underlining logic for canceling the order isn’t run. More specifically, Magento doesn’t allow the order to cancel when its status is payment review. This PR adds the logic to restock the product quantity for the rejected irreversible hook.
Fixes: https://app.asana.com/0/564264490825835/1147250679267337
#changelog
Restock product quantity when the payment is irreversibly rejected

Restock product quantity when the payment is irreversibly rejected

---

Helper/Discount.php
Model/Api/ShippingMethods.php

Ensure Miravist reward points are applied to the immutable quote before the totals are calculated in webhook requests
Fixes: https://app.asana.com/0/1125081140214268/1146933633809759

Ensure Miravist reward points are applied to the immutable quote before the totals are calculated in webhook requests

---

Helper/Order.php
Test/Unit/Helper/OrderTest.php

When creating order invoice, the plugin would first compare ($order->getTotalInvoiced() + $amount) with $order->getGrandTotal() , but neither of the two values get rounded before comparison, so for some instance, eg. $order->getTotalInvoiced() + $amount = 121.64 and $order->getGrandTotal() = 121.6406, they are not equal and we call function $this->invoiceService->prepareInvoiceWithoutItems($order, $amount); to create inoivce without item.
Solution: round the value before comparison.
Fixes: https://app.asana.com/0/941920570700290/1148920165401345/f
\#changelog

Fix Bug - the invoice is created with no item

---

Block/Js.php
Test/Unit/Block/JsTest.php

Currently, the logic to get the publishable key is to check the multi-step key and use it if it’s not empty. If it is empty then the payment only key will be used.
This causes an issue when we want to use both checkout divisions for the storefront. This PR loads the correct key based on the request. If the request is from the checkout page, then use the payment only key, otherwise, use the multiple-step key.
Fixes: https://app.asana.com/0/564264490825835/1148566476960345

Load the correct frontend division key configuration

---

Block/Js.php
Test/Unit/Block/JsTest.php
view/frontend/templates/js/replacejs.phtml

Move all php code in replacejs.phtml into top of file so in subsequent PR I can move js into separate file
https://app.asana.com/0/941920570700290/1147770190679403/f
Refactoring. It changes scope of variables a bit but shouldn't change any functionality.
- [ x ] Successfully tested on a staging or sandbox server

Refactor replace.js - move php code into one place

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

When the attribute value is a boolean, Bolt recognizes it as an invalid JSON and doesn’t allow the order to be created on Bolt. This ensures the attribute value is converted to string if it's a boolean when sending it to Bolt.
Fixes: https://app.asana.com/0/564264490825835/1142017681006690

Convert attribute to string if it's a boolean before sending to the Bolt API

---

Model/Payment.php
Test/Unit/Model/PaymentTest.php

Skip capture hook notification when creating an online invoice on Magento
This resolves the mismatch issue described in the following case:
1. The customer places an order (Bolt transaction and Magento order match)
2. The administrator updates the Magento order total to less than its original total (this functionality is provided by a custom module)
3. The administrator creates an online invoice for the order on Magento
4. Magento sends capture API to Bolt to capture the payment
5. The payment is captured, Bolt sends back a capture hook to Magento to create an invoice which is already created on #3
6. Mismatch issue occurs.
On M1, we ignore the hook notification and the capture hook never gets sent back to Magento. This applies the same logic for creating the online invoice on Magento. …

Skip capture hook notification when creating an online invoice on Magento

---

view/frontend/layout/checkout_index_index.xml
view/frontend/templates/js/checkout_funnel.js.phtml
view/frontend/web/js/track-checkout.js

This PR adds a JavaScript running on one page checkout. Lots of (hacky) DOM scraping to detect checkout funnel transition and send it to Bolt via `BoltTrack.recordEvent`. 
I was looking for better way to hook into native magento's event but wasn't able to find - welcome for comment and suggestions
I'll add test with subsequent PR. We currently don't have JavaScript test so adding test requires good amount of new code and config files.

Add JavaScript to track checkout funnel in onepage checkout

---

Helper/Order.php
Test/Unit/Helper/OrderTest.php

Base currency can be different than order currency. If you have USD store that also process EUR, before this PR we were displaying comment with wrong currency. This PR fixes that.
#changelog update comment in order history (admin view) so we can properly handle different currency
- [ x ] Bug fix (change which fixes an issue)
- [ x ] Successfully tested on a staging or sandbox server
- [ x ] My code follows the style guidelines of this project.
- [ x ] I have performed a self-review of my own code.
- [ x ] I have commented my code, particularly in hard-to-understand areas.
- [ x ] I have added my Asana task link and provided a changelog …

Use order currency for showing amount in comment

---

Model/Api/ShippingMethods.php
Test/Unit/Model/Api/ShippingMethodsTest.php

Shipping and tax needs Store's current currency to properly set as quote's currency so it can calculate product price properly
related magento code: https://github.com/magento/magento2/blob/1773f4184d00017a1636083610726c13964f2ae7/app/code/Magento/Directory/Model/PriceCurrency.php#L114
\#changelog support multi currency in shipping and tax endpoint

Set store's current currency in shipping tax hook

---

Model/Api/ShippingMethods.php
Test/Unit/Model/Api/ShippingMethodsTest.php

It seems `checkCartItems` has rounding error. we're essentially comparing `$item['total_amount'] === round($item->getQty() * $item->getCalculationPrice())` but these two could be different when `$item->getCalculationPrice()` returns fraction of cents ( see unit test )
`getCalculationPrice` can return fraction of cents due to currency conversion for instance

Fix rounding error in checkCartItems

---

Helper/Cart.php
Helper/Order.php
Helper/Shared/CurrencyUtils.php
Model/Api/ShippingMethods.php
Model/Payment.php
Test/Unit/Helper/Shared/CurrencyUtilsTest.php

This PR introduces utility function `toMinor` to convert major (dollar) to minor (cents).
old code: `$amount * 100`
new code: `toMinor($amount, "USD")`
Note we still hard-code "USD" (so this PR shouldn't change any behaviour). In subsequent PRs I'll replace hardcoded "USD" into appropriate currency code. 

Introduce toMinor method for currency conversion

---

Helper/Order.php
Helper/Shared/CurrencyUtils.php
Model/Api/ShippingMethods.php
Test/Unit/Helper/Shared/CurrencyUtilsTest.php

This PR introduces utility function toMajor to convert minor (cents) to major (dollar)
old code: $amount / 100
new code: toMajor($amount, "USD")
Note we still hard-code "USD" (so this PR shouldn't change any behaviour). In subsequent PRs I'll replace hardcoded "USD" into appropriate currency code.
See also: https://github.com/BoltApp/bolt-magento2/pull/450

Introduce toMajor method for currency conversion

---

Model/Payment.php
Test/Unit/Model/PaymentTest.php

Magento's Payment class pass currency in store currency. This PR adds logic to get capture amount in proper (order's) currency when calling Bolt's capture API
Fixes: https://app.asana.com/0/1145430477677801/1152698132445867/f
\#changelog support invoice creation in different currency

Update capture logic to handle different currency

---

Model/Payment.php
Test/Unit/Model/PaymentTest.php

Magento's refund method pass amount in store's currency. In order to handle different currency (eg US store that also sell things in CAD), this PR get currency from credit memo.
\#changelog update refund to handle different currency

Update refund to handle multi-currency

---

Helper/Config.php
Test/Unit/Helper/ConfigTest.php

shouldTrackCheckoutFunnel method was reading wrong config value. This PR fixes it
unit test

Fix Config.shouldTrackCheckoutFunnel - was reading wrong config

---

Block/Checkout/Success.php
Test/Unit/Block/Checkout/SuccessTest.php
view/frontend/templates/checkout/success.phtml

This PR adds `BoltTrack.recordEvent("OrderConfirmationView")` to order confirmation page when config is enabled. This will be used when merchant A/B test.
Fixes: https://app.asana.com/0/941920570700290/1136465306941030/f

Add OrderConfirmation view on success page for A/B test

---

Controller/Adminhtml/Order/ReceivedUrl.php
Model/Api/CreateOrder.php
Test/Unit/Model/Api/CreateOrderTest.php

Back-office success page redirect does not work for pre-auth configured stores that are not under the default website.
Fixes: https://app.asana.com/0/941920570700290/1154082745428809/f
\#changelog

Fix multi-store pre-auth back-office success page redirect

---

view/frontend/templates/js/replacejs.phtml

Seems like Magento minifies php portions of  .phtml templates, at least removes new lines. This breaks heredoc string syntax. 
Fixes: https://app.asana.com/0/941920570700290/1153919575235679/f
\#changelog

remove heredoc from phtml

---

Block/Checkout/Cart/ComponentSwitcherProcessor.php
Helper/Config.php
Helper/Order.php
Test/Unit/Block/Checkout/Cart/ComponentSwitcherProcessorTest.php
etc/adminhtml/system.xml
etc/config.xml
view/frontend/layout/checkout_cart_index.xml

Currently rewards can be used from the native checkout only.
Move reward points application to the shopping cart page.
As it was done with store credit. 
There's an exception thrown by Magento_Reward (Commerce Edition only) in success redirect call of pre-auth order creation flow.
Order::getAppliedRuleIds is expected to be a sting (empty string if no rules were applied). It is so in the legacy flow - all processing in one request / session. However, when empty, this field is saved to DB as null (by Magento, no alter at our plugin side) in the create order pre-auth call. When order is fetched later, in success redirect call, if the field is null the aforementioned error is thrown. Check for null and set it to empty string before further order processing (dispatch events).
Fixes: …

Ee rewards on cart page support

---

Helper/Cart.php
Helper/Order.php
Model/Api/CreateOrder.php
Model/Api/DiscountCodeValidation.php
Model/Api/ShippingMethods.php
Test/Unit/Helper/OrderTest.php
Test/Unit/Model/Api/CreateOrderTest.php
Test/Unit/Model/Api/DiscountCodeValidationTest.php
Test/Unit/Model/Api/ShippingMethodsTest.php

getRoundAmount implicitly assume USD. This PR replace it with CurrencyUtils::toMinor with proper currency code.

Remove CartHelper.getRoundAmount

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

This change adds two new properties color and size to item return type.
Currently these are within item properties in Magento2 with labels "Color" and "Size".
This would be used to be displayed in SideCart of Checkout
#changelog
Return color and size of items

Add Color and size properties to item return type

---

Helper/Cart.php

Currently variant images are not populated correctly. It still shows the main product image rather than the configurable image
\#changelog
Return variant image is exists rather than the main product image.
Before:
After:

Add variant image rather than main product image

---

Model/Api/ShippingMethods.php
Test/Unit/Model/Api/ShippingMethodsTest.php

Set property fromBolt to true when the shipping hook request is sent to Magento
Fixes: https://app.asana.com/0/564264490825835/1156190790999569

Set property fromBolt to true when the shipping hook request is sent to Magento

---

Model/Payment.php
Test/Unit/Model/PaymentTest.php

This resolves the mismatch issue described in the following case:
1. The customer places an order (Bolt transaction and Magento order match)
2. The administrator updates the Magento order total to less than its original total (this functionality is provided by a custom module)
3. The administrator voids or refunds the payment online for the order on Magento
4. Magento sends the void or refund API to Bolt to update the payment
5. The payment is voided or refunded, Bolt sends back hook requests to Magento to update the order
6. Mismatch issue occurs.
On M1, we ignore the hook notification and the void or refund hook never gets sent back to Magento. This applies the same logic for voiding and refunding the order on Magento
Fixes: https://app.asana.com/0/564264490825835/1155179630570777 …

Skip hook notifications when voiding or refunding the order on magento

---

Helper/FeatureSwitch/Decider.php

\Bolt\Boltpay\Helper\FeatureSwitch\Decider::isSwitchEnabled
Fatal error: Cannot use isset() on the result of an expression
Fixes: https://app.asana.com/0/941920570700290/1159433394644281/f
\#changelog

php5.6 compatibility fix

---

Block/Js.php
Controller/ReceivedUrlTrait.php
Helper/Cart.php
Helper/Order.php
Model/Api/DiscountCodeValidation.php
Test/Unit/Block/JsTest.php
Test/Unit/Controller/Order/ReceivedUrlTest.php
Test/Unit/Helper/CartTest.php
Test/Unit/Helper/OrderTest.php
Test/Unit/Model/Api/DiscountCodeValidationTest.php
view/frontend/templates/button_product_page.phtml

- Add support for multistore
- Set PPC quote active to false (otherwise PPC quote for logged in user is tied to session and can become session quote when regular cart checkout complete
- In all cases when we need to check if an order exists check not only by order_id but for quote_id also (PPC case)

Fix some bugs related to Product page checkout

---

Helper/Order.php
Model/Payment.php
Test/Unit/Helper/OrderTest.php

Void the Bolt transaction when its status is either authorized or canceled and the Magento quote is missing
Fixes: https://app.asana.com/0/564264490825835/1157946616328022

Void the Bolt transaction when its status is either authorized or canceled and the Magento quote is missing

---

view/frontend/templates/js/replacejs.phtml

If guest checkout is not allowed clicking the Bolt button forces customer to log in or create an account. After login the customer is redirected to the shopping cart page and the bolt checkout is opened automatically. The last part did not work after changing createOrder call logic a while ago.
\#changelog

fix automatic modal popup after forced login

---

view/frontend/templates/js/replacejs.phtml

Get a hold of cart promise reference and always pass it to BoltCheckout.configure.
Use barrier, an externally-resolved promise, to pass hints, updated with cart promise resolve,
to BoltCheckout.configure.
\#changelog

keep and reuse cart promise, pass hints as externally resolved promise

---

Block/JsProductPage.php
Test/Unit/Block/JsProductPageTest.php
view/frontend/templates/button_product_page.phtml

Now we check if we have the necessary inventory on PPC frontend but it doesn't work correctly due to the caching issue.
As we discussed here https://docs.google.com/document/d/10cMe0LwsgrO0oWtM-bskIAg-1slZByJUtA3Wh8aoPXY/edit?usp=sharing the best solution is to do inventory checking on bolt server side.
Fixes: https://app.asana.com/0/0/1156147394609521/f

Remove quantity check from PPC frontend

---

view/frontend/templates/js/replacejs.phtml

Legacy (post auth) flow: the pop up message is missing on failed save order call, checkout popup remains open indefinitely.
Fixes: https://app.asana.com/0/941920570700290/1162195122723324/f
\#changelog

Missing Bolt error message popup fix

---

view/frontend/templates/js/replacejs.phtml

If Bolt button (re)placement takes place after connect.js loads and  BoltCheckout.configure is called the button is not processed, ie visible on the page.
Solution: Additional / conditional call to BoltCheckout.configure after the button is injected.
Note: not sure if this is caused by recent plugin changes or some core / checkout related work. Anyway, this fixes it.
Fixes: https://app.asana.com/0/941920570700290/1162195122723316/f
\#changelog

Bolt button missing in minicart fix

---

Controller/ReceivedUrlTrait.php

Always call it from the hook allows us to inject additional processing here, one time only on the first status change. Required for https://github.com/BoltApp/bolt-magento2/pull/511
Fixes: https://app.asana.com/0/941920570700290/1162195122723305/f
\#changelog

Remove redundant resetOrderState from ReceivedUrlTrait, call it from hook only

---

Model/Api/CreateOrder.php

Display id gets changed to hold parent instead of immutable quote id. This is a subtle bug present for quote a while, luckily with no noticeable impact so far, spotted when checking this https://github.com/BoltApp/bolt-magento2/pull/523 which it would impact.
Fixes: https://app.asana.com/0/941920570700290/1162023400086868/f
\#changelog

pre-auth create order display id fix

---

Block/JsProductPage.php
Test/Unit/Block/JsProductPageTest.php
view/frontend/templates/button_product_page.phtml

We support the only case when a store has one currency everywhere.
In this case, it's enough to add correct currency to **configureProductCheckout** to show correct currency on bolt modal
When we handle **cart.create** we don't need to do something special
Fixes: https://app.asana.com/0/0/1155768935724793/f

Product page checkout: add support for foreign currencies

---

Helper/Order.php
Model/Api/ShippingMethods.php
Test/Unit/Helper/OrderTest.php
Test/Unit/Model/Api/ShippingMethodsTest.php

We have a temporary code to handle the issue: bolt server doesn't save display_id when cart is created via cart.create https://app.asana.com/0/941920570700290/1155187242723681/f
Now the bug is fixed and we can remove temporary code 
Fixes: https://app.asana.com/0/0/1159061667010227/f

Product page checkout: Remove temporary fix around display_id

---

Helper/Cart.php
Helper/Discount.php
Test/Unit/Helper/CartTest.php
Test/Unit/Helper/DiscountTest.php

In the new version of the Mageplaza_GiftCard module, the gift card amount isn’t applied to Bolt properly as they don’t use the session to get the gift codes, instead, they use the quote to get the gift codes.
This PR adds the ability to apply both the old logic to use the session and the new logic to use the quote to get the gift codes. 
Fixes: https://app.asana.com/0/564264490825835/1162214533019681

Update the logic for module Mageplaza_GiftCard on the new version

---

Helper/Order.php
Test/Unit/Helper/OrderTest.php

After you observe decline error message you could reload cart page and you'll see that cart is empty!
Fixes: https://app.asana.com/0/941920570700290/1158209273889109/f
\#changelog

reactivate session quote on order deletion upon failed payment hook

---

Helper/Order.php
Test/Unit/Helper/OrderTest.php

ERP systems can pull orders too early, when we set order state to new (status pending). If done in success redirect call, we don't have transaction info yet and can not save some required data, eg. cc type and last4.
Fixes: https://app.asana.com/0/941920570700290/1162518950067661/f
\#changelog

postpone panding_payment to pending order status transition to webhook

---

Helper/Order.php
Test/Unit/Helper/OrderTest.php

Credit card type and last4 digits info is missing in pre-auth. It is attempted to be saved to quote before the quote to order submission. ERP pulls the order without that info. It is expected to be there be some merchants. 
Fixes: https://app.asana.com/0/941920570700290/1162518950067666/f
\#changelog

save cc type and last4 info to order payment

---

etc/catalog_attributes.xml

Payment transactions processed via Stripe require a field "description" for level 3 processing. Now this field is missing in the quote item collection
Fixes: https://app.asana.com/0/941920570700290/1153065154514665/f
\#changelog

Add description field to the quote item collection.

---

Controller/ReceivedUrlTrait.php
Test/Unit/Controller/Order/ReceivedUrlTest.php

We do addStatusHistoryComment to the order in Controller\ReceivedUrlTrait::execute but do not actually save the order.
This is useful to have on the order info page in case the hooks fail. It is shown as a direct link to transaction in merchant dashboard.
Fixes: https://app.asana.com/0/941920570700290/1162870276879154/f
\#changelog

save transaction reference to order history

---

view/frontend/templates/button_product_page.phtml

Buy Now - Modal not opening if button clicked too early.
The required Magento module, mage/validation/validation hasn't been loaded on the time of the button click. Happens mainly on a first page load, before it's cached.
Fixes: https://app.asana.com/0/941920570700290/1162870276879145/f
\#changelog

wait for form validation module initialization

---

Model/Api/OrderManagement.php
Test/Unit/Model/Api/OrderManagementTest.php

Adds `failed` to the `failed_payment` check, not allowing the Order Helper to error if it encountered the `failed` transaction status from Bolt.
Fixes: https://app.asana.com/0/941920570700290/1158440956322913/f

Add catch for failed transaction status from Bolt

---

view/frontend/templates/button_product_page.phtml

Show the PPC button disabled and enable it when the required data (hints with encrypted customer id)  is loaded. Prevent dead clicks and errors. Do not hardcode the solution (eg. CSS selectors), make it work via Magento configuration.
Solution: 
1. trigger a custom JS event from the core plugin code when data is loaded (ppc-hints-set)
2. through Magento config add "ppc-disabled" CSS class and JavaScript that listens to the aforementioned event and removes "ppc-disabled" class.
Magento Bolt Pay configuration:
**Additional Checkout Button Class**:
```
ppc-disabled
```
**Global CSS**:
```css
.bolt-product-checkout-button.ppc-disabled {
opacity: 0.5;
cursor: default;
pointer-events: none;
}
```
**Additional Javascript**:
```javascript
$(document).on('ppc-hints-set', function(){ …
```

trigger a custom JS event when hints are set (button ready)

---

Helper/Cart.php

Fix for: when hints prefill is empty it is sent as an array instead of an object
Fixes: https://app.asana.com/0/941920570700290/1165294438865863/f
#changelog always return hints prefill as object

always return hints prefill as object

---

view/frontend/templates/button_product_page.phtml

For now, under some fairly rare conditions we can ask hints from server few times:
- AJAX hints call works long time
- User change cart (quantity or product attribute) before AJAX call is finished.
Fixes: https://app.asana.com/0/941920570700290/1165280808501785/f
#changelog  PPC: retrieve hints from server only once

 PPC: retrieve hints from server only once

---

Block/BlockTrait.php
Block/Checkout/Success.php
Block/Customer/CreditCard.php
Block/Js.php
Test/Unit/Block/Checkout/SuccessTest.php
Test/Unit/Block/Customer/CreditCardTest.php
Test/Unit/Block/JsTest.php
view/frontend/templates/button.phtml
view/frontend/templates/button_product_page.phtml
view/frontend/templates/checkout/success.phtml
view/frontend/templates/css/boltcss.phtml
view/frontend/templates/customer/creditcard.phtml
view/frontend/templates/js/boltjs.phtml
view/frontend/templates/js/checkout_funnel.js.phtml
view/frontend/templates/js/replacejs.phtml
view/frontend/templates/popup.phtml

Plugin is publicly available via composer. Anybody can install it. Prevent communication with Bolt if the keys are not set.
- move common methods, shouldDisableBoltCheckout and methods called within, to BlockTrait and use the trait in blocks
- add isKeyMissing check to shouldDisableBoltCheckout
- call shouldDisableBoltCheckout at the begining of templates
Fixes: https://app.asana.com/0/941920570700290/1164917024563610/f
#changelog don't send API request when merchant key is empty

don't send API request when merchant key is empty

---

Controller/Adminhtml/Cart/Data.php
Controller/Cart/Data.php

Don't log a failed order token metric when `$boltpayOrder->getResponse()` isn't even called.
Fixes: [ENG-288]
#changelog Don't log a failed order token metric on empty carts
[ENG-288]: https://boltpay.atlassian.net/browse/ENG-288

ENG-288 - Don't logged failed order token when cart is empty

---

Model/Api/Debug.php
Test/Unit/Model/Api/DebugTest.php

This PR adds support to retrieve PHP version and platform version in debug endpoint.
Fixes: [ENG-301] [ENG-304]
#changelog Debug Endpoint: add support to retrieve php version and platform version
[ENG-301]: https://boltpay.atlassian.net/browse/ENG-301
[ENG-304]: https://boltpay.atlassian.net/browse/ENG-304

[Debug Endpoint] Add support to retrieve php version and platform version ENG-301 ENG-304

---

Model/Api/Debug.php
Test/Unit/Model/Api/DebugTest.php

Add HMAC check for requests to the debug endpoint. It is needed because this endpoint is exposing some sensitive server information (eg: php version, platform verstion, bolt settings etc) of the merchant. 
Tech Spec: https://docs.google.com/document/d/1Q-0NZHQew1ALm4MOyVGl2m0-JUG_mnmhcn9zPcqJo98/edit#heading=h.cunzcjjb9kz
Fixes: [ENG-363]
#changelog [Debug Endpoint] Add HMAC check for requests
[ENG-363]: https://boltpay.atlassian.net/browse/ENG-363

[Debug Endpoint] ENG-363 Add HMAC check for requests

---

Helper/ModuleRetriever.php
Model/Api/Debug.php
Test/Unit/Helper/ModuleRetrieverTest.php
Test/Unit/Model/Api/DebugTest.php

Add support to retrieve installed modules from the database. It does not leverage \Magento\Framework\Module\FullModuleList because that would retrieve modules from Magento core which we are not interested in. (eg: things like Magento_Directory, Magento_Theme would be returned from FullModuleList)
Fixes: [ENG-216]
#changelog [Debug Endpoint] Add support to retrieve installed modules
[ENG-216]: https://boltpay.atlassian.net/browse/ENG-216

[Debug Endpoint] ENG-216 Add support to retrieve installed modules

---

Controller/Order/Save.php
Test/Unit/Controller/Order/SaveTest.php

We already did it for pre-auth, https://github.com/BoltApp/bolt-magento2/pull/543/, need to do the same for non-preauth flow.
Fixes: https://app.asana.com/0/941920570700290/1162663341983417/f
#changelog Don't empty cart after successful PPC checkout (w/o preauth)

Don't empty cart after successful PPC checkout (w/o preauth)

---

Test/Unit/Block/FormTest.php
Test/Unit/Helper/OrderTest.php

Maybe it depends on phpunit version, but tests fail on my local env without this fix.
https://github.com/BoltApp/bolt-magento2/pull/new/vitaliy/credit-cart-test-fix
Error is
1) Bolt\Boltpay\Test\Unit\Block\FormTest::getCustomerCreditCardInfo with data set #0 (array('1111', array(Magento\Framework\DataObject Object (...))))
ArgumentCountError: Too few arguments to function Bolt\Boltpay\Model\ResourceModel\CustomerCreditCard\CollectionFactory::__construct(), 0 passed in /var/www/html/vendor/phpunit/phpunit-mock-objects/src/Generator.php on line 227 and at least 1 expected
/var/www/html/generated/code/Bolt/Boltpay/Model/ResourceModel/CustomerCreditCard/CollectionFactory.php:29
/var/www/html/vendor/boltpay/bolt-magento2/Test/Unit/Block/FormTest.php:107 …

Fix test for customerCreditCardCollectionFactory

---

Model/CustomerCreditCard.php
Observer/Adminhtml/Sales/RechargeCustomer.php
Test/Unit/Observer/Adminhtml/Sales/RechargeCustomerTest.php

Add source field to the API request data and add transaction reference to the order status history when recharging the customer
Add source field to the API request data and add transaction reference to the order status history when recharging the customer
Fixes: https://app.asana.com/0/564264490825835/1167109004841033
#changelog  Add source field to the API request data and add transaction reference to the order status history when recharging the customer

 Add source field to the API request data and add transaction reference to the order status history when recharging the customer

---

Cron/DeleteOldWebHookLogs.php
Model/ResourceModel/WebhookLog.php
Model/WebhookLog.php
Setup/UpgradeSchema.php
Test/Unit/Cron/DeleteOldWebHookLogsTest.php
Test/Unit/Model/WebhookLogTest.php
etc/crontab.xml

Add a cron job to clean webhook logs older than 30 days
Fixes: https://app.asana.com/0/564264490825835/1167004891081257
#changelog Add a cron job to clean webhook logs older than 30 days

Add a cron job to clean webhook logs older than 30 days

---

Helper/Order.php
Test/Unit/Helper/OrderTest.php

We do few API calls transaction/<reference> when we handle pending hook.
By this PR we add caching in function OrderHelper::fetchTransactionInfo, like we already do caching in CartHelper::getQuoteById
Fixes: https://app.asana.com/0/941920570700290/1163893469797548/f
#changelog Cache result of transaction/<reference> API call

Cache result of transaction/<reference> API call

---

view/adminhtml/templates/boltpay/js/replacejs.phtml

The window object may be reset during backoffice creation for some reasons, as a result, the variable settings fail to keep in sync with window.boltConfig, so we use Proxy object to make sure settings always point to the updated window.boltConfig.
Fixes: https://app.asana.com/0/941920570700290/1167452929959226/f
#changelog Fix Bug - undefined store id result in the failure of  backoffice order creation 

Fix Bug - undefined store id result in the failure of  backoffice order creation 

---

Plugin/CheckSettingsUpdate.php
Test/Unit/Plugin/CheckSettingsUpdateTest.php
etc/adminhtml/di.xml

We should make GetFeatureSwitch call each time when plugin is installed / updated, but now we don't do it when plugin is installed: at this moment merchant key is empty and API call fails.
**Solution:**
Call GetFeatureSwitch  each time when merchant key is changed
Fixes: https://app.asana.com/0/941920570700290/1162717349359250/f
#changelog Make GetFeatureSwitch call when merchant key is changed

Make GetFeatureSwitch call when merchant key is changed

---

Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Helper/Order.php
Test/Unit/Helper/OrderTest.php

Create Magento offline credit memos for refund webhooks
Demo screenshot: https://www.screencast.com/t/qbv3wZ64bsdM
Fixes: https://app.asana.com/0/564264490825835/898124257920178
#changelog Create Magento offline credit memos for refund webhooks

Create Magento offline credit memos for refund webhooks

---

Block/Js.php
Helper/Config.php
Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Test/Unit/Helper/ConfigTest.php
etc/adminhtml/system.xml
etc/config.xml
view/frontend/layout/default.xml
view/frontend/templates/boltaccount.phtml

add <div class="bolt-track-order"></div> and include core script account.js to show bolt account button
Fixes: [ENP-25]
#changelog Show bolt account button (order management)
Project summary:
Frontend changes:
add &lt;div class="bolt-track-order"&gt;&lt;/div&gt;
include core script account.js
As a result "account" button is shown
2. When a user clicks on the "account" button, they see iFrame with a prompt to enter an email.
3. Bolt server calls the new plugin endpoint to know if there is magento2 user with this email.
If yes, a user is redirected to M2 login page
If no, a user fills in the phone number, enters SMS code, and sees a page with all orders from this store.
4. When merchant staff add track number into order plugin, send it to bolt so that a user can see it in account iFrame
See …

[Order management] ENP-25 show bolt account button

---

etc/adminhtml/system.xml

Our plugin cfg settings are all different in each shopping cart dashboard. The actual wording we use differs for each configuration setting as well as what we allow to set. As our team scales, it is getting difficult to know what settings map to each config for all our plugins. We need to standardize this for all plugins so we are on the same page.
Fixes: [M2P-9]
#changelog Reformat admin configuration settings

[M2P-9] Standardize admin configuration settings

---

view/adminhtml/templates/boltpay/js/replacejs.phtml

Deleting unused code. I believe these code was copied from `frontend/templates/js/replacejs.html` without much thought. These are completely unnecessary (details below).
- setCheckoutTypeStyle: not needed, we only have one checkout type.
- selectorApply, checkoutButtonApply: no longer used after deleting setCheckoutTypeStyle
- billing_address_selector, place_order_payload_id: unused
- multi_step_css_class, bolt_button_selector: no longer used after deleting setCheckoutTypeStyle
- "loop through selectors array and set up the replacement": not needed, in admin we embed bolt button in phtml, no need to dynamically replace
- "Monitor Country DOM element change and update hints": no need, since admin order is paymentonly these hints are not used at all
#changelog Remove unnecessary code in …

Remove unnecessary code in adminhtml/replacejs

---

Block/Form.php
Test/Unit/Block/FormTest.php
view/adminhtml/templates/boltpay/button.phtml

Currently we always show Bolt dropdown UI in admin order creation page but Bolt is useless unless key is configured. This PR adds message indicating you need to set key.
Before:
After:
#changelog Show message in backoffice when key is not set

Show message in backoffice when key is not set

---

Plugin/Magento/Sales/Model/AdminOrder/CreatePlugin.php
Test/Unit/Plugin/Magento/Sales/Model/AdminOrder/CreatePluginTest.php
etc/adminhtml/di.xml

This PR supports the following case in the backoffice:
When the In-Store Pickup Feature is enabled and the customer chose the shipping method which has the same code as the In-Store Pickup Shipping Method Code, it automatically uses the In-Store Pickup Address as the shipping address to calculate the tax and create the order
Here are some of the screenshots:
http://prntscr.com/rqxymm
http://prntscr.com/rqxq2a
http://prntscr.com/rqxxto
Fixes: https://app.asana.com/0/564264490825835/1169894609956309
https://app.asana.com/0/1142111051828235/1143602415454165
#changelog In-Store Pickup feature in the backoffice

In-Store Pickup feature in the backoffice

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

Prevent Bolt order creation if the order already exists
Fixes: https://app.asana.com/0/564264490825835/1170646880319281
#changelog Prevent Bolt order creation if the order already exists

Prevent Bolt order creation if the order already exists

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

When you opened ApplePay, then closed it and opened Bolt checkout we would put some placeholders (na@bolt.com, address=tbd) that looked ugly. We needed to update the strings we were checking against in prefill data 
https://app.asana.com/0/951157735838091/1169706392384129/f
#changelog [Applepay] - use correct email to skip prefill

[Applepay] - use correct email to skip prefill

---

Model/Payment.php
Test/Unit/Model/PaymentTest.php

1. Order amounting to $100 is created on Magento and Bolt
2. The merchant does a partial capture of $1 on Bolt => the Bolt transaction status changes to Completed
3. The merchant goes to Magento admin and clicks on the Void button
4. The remaining authorization amount ($99) is voided on Bolt but on Magento, the exception “Payment void error“ is thrown since the Bolt transaction status is not canceled
The expected behavior for step #4 is that there shouldn't be any exception thrown and the Magento payment is voided
The expected behavior for step #4 is that there isn’t be any exception thrown and the Magento payment is voided
Fixes: https://app.asana.com/0/564264490825835/1172249160918697
#changelog Fix void issue
Please validate that you have tested …

Fix void issue

---

etc/adminhtml/system.xml

Remove beta from ppc admin setting label because it's GA
#changelog Remove beta because PPC is GA

Remove beta because PPC is GA

---

view/frontend/templates/button_product_page.phtml

Preconditions:
Product with two or more customizable options is created
Product Page Checkout is enabled
User is on the product page
Steps to reproduce:
1. Select the fist customizable option
2. Select the second customizable option
3. Open bolt modal
Actual result:
Price from the first option is counted up. Price from the both options is counted up in a few seconds.
Expected result:
Price from the both options is counted up immediately.
Fixes: https://app.asana.com/0/941920570700290/1168880447444715/f
#changelog PPC support for products with two or more customizable options

PPC support for products with two or more customizable options

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

Items which have special prices set are not picked up by Bolt in the Admin checkout
Fixes: https://boltpay.atlassian.net/browse/M2P-44
#changelog Add catalog price rule support for backend orders

Add catalog price rule support for backend orders

---

Controller/Order/ReceivedUrl.php
Helper/Cart.php
Model/Api/CreateOrder.php
Setup/UpgradeSchema.php
Test/Unit/Controller/Order/ReceivedUrlTest.php
Test/Unit/Helper/CartTest.php
Test/Unit/Model/Api/CreateOrderTest.php
Test/Unit/Model/Service/InvoiceServiceTest.php

Replace **bolt_is_backend_order** quote table column with **bolt_checkout_type**
so we can use it to cover more cases, PPC being one of them.
Needed for shipping and tax split to work.
Fixes: https://app.asana.com/0/941920570700290/1172688451409921/f
#changelog Add bolt checkout type to quote

Add bolt checkout type to quote

---

Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Model/Api/OrderManagement.php
Test/Unit/Model/Api/OrderManagementTest.php

In some cases, we need to ignore Bolt hooks for the invoice creation and credit memo creation in order to support the merchant's ERP flow.
Fixes: 
https://app.asana.com/0/1142111051828235/1165846798496323
https://app.asana.com/0/564264490825835/1172269575436441
#changelog Ignore Bolt hooks for the invoice creation and credit memo creation with default switch is off

Ignore Bolt hooks for the invoice creation and credit memo creation with default switch is off

---

view/frontend/templates/button_product_page.phtml

[M2 v2.6.0 production readiness bug] PPC button is missing in IE
Fixes: https://boltpay.atlassian.net/browse/M2P-47
#changelog PPC button missing in IE fix

PPC button missing in IE fix

---

Helper/Order.php
Model/Api/OrderManagement.php
Test/Unit/Helper/OrderTest.php
Test/Unit/Model/Api/OrderManagementTest.php

1. Customer added items to cart, clicked the Bolt button, finished the first and second steps in the Bolt modal
2. During the third step, somehow the parent quote was deleted
3. Customer clicked the 'Pay' button in the Bolt modal and the exception "PHP Fatal error:  Uncaught Error: Call to a member function getCustomerId() on bool in vendor/boltpay/bolt-magento2/Helper/Order.php:867" was thrown so the order wasn't created on Magento
The PR fixes the save credit card failure by allowing order to be created with the immutable quote even when the parent quote has been deleted
Fixes: 
https://app.asana.com/0/1125081140214268/1173245397463499
https://app.asana.com/0/564264490825835/1174039461828337
#changelog  Fix the save credit card failure by allowing order to be created with the immutable …

 Fix the save credit card failure by allowing order to be created with the immutable quote even when the parent quote is deleted

---

Model/Api/ShippingMethods.php
Test/Unit/Model/Api/ShippingMethodsTest.php

Some customers don’t know that reloading the page will resolve the issue so this PR to show the error message when estimating shipping and tax in the Bolt popup
Fixes: 
https://app.asana.com/0/564264490825835/1174575430604089
https://app.asana.com/0/1137788479595677/1161674658962066
#changelog Show the error message when estimating shipping and tax in the Bolt popup

Show the error message when estimating shipping and tax in the Bolt popup

---

Helper/Order.php
Test/Unit/Helper/OrderTest.php

1. The customer clicked the Pay button in the Bolt modal and the order was created on both Bolt and Magento.
2. The first pending hook was sent to Magento and the exception “Unprocessable Entity: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock“ was thrown ( See here: http://prntscr.com/rnr9cp). The deadlock exception is an edge case exception.
3. Since the first pending hook failed, Bolt re-sent the second pending hook to Magento to re-authorize the order. But the odd thing here is that it skipped because of this code http://prntscr.com/sb7lgg
So I create the PR to allow the retry pending hook to authorize the order if it's status is pending payment so the #3 above won’t occur.
Fixes: …

Allow the retry pending hook to authorize the order if its status is pending payment

---

Controller/Adminhtml/Cart/Data.php
Controller/Adminhtml/Order/ReceivedUrl.php
Controller/Order/ReceivedUrl.php
Test/Unit/Controller/Adminhtml/Order/ReceivedUrlTest.php
Test/Unit/Controller/Order/ReceivedUrlTest.php
view/adminhtml/templates/boltpay/js/replacejs.phtml

Switch to using raw header value for referrer, as the method used previously doesn't work for different (sub)domains. Don't use secret key when generating admin create order url to compare referrer against as they won't always match. Disable secret key validation for admin received url endpoint as there is no good way to generate it from frontend.
Fixes: https://boltpay.atlassian.net/browse/M2P-66
#changelog Success order redirect does not work for back-office orders

Success order redirect does not work for back-office orders

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

This causes errors with older Magento versions. Turns out it is not necessary.
#changelog remove cloning extension attributes

remove cloning extension attributes

---

etc/events.xml

If the order was created through pre-auth process and then deleted on magento side due to failed payment transaction, which was declined by Vantiv, we should restore a gift card afterword.
Fixes https://boltpay.atlassian.net/browse/SUP-132
#changelog Added recovery of gist cards after a failed payment transaction

Added gift cards recovery after failed payment transaction

---

Helper/Order.php
Test/Unit/Helper/OrderTest.php

M2P-75 When refund (Credit Memo) is triggered from the store, the plugin should not explicitly create it because it is implicitly created by Magento.
Fixes: https://boltpay.atlassian.net/browse/M2P-75
#changelog M2P-75 prevent additional credit memo creation attempt

M2P-75 prevent additional credit memo creation attempt

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

For bundle product in the cart, its sku is a combination with bundle selections, format as "bundleproductsku-selection1sku-selection2sku-..." , and it cause an exception "Could not retrieve product from repository" when trying to get the main product image (https://github.com/BoltApp/bolt-magento2/pull/485/commits/822d481d4d0e0e2cde1c148d7561cd1b06fa3532)
So we need to get the proper SKU for bundle product.
Fixes: [M2P-72](https://boltpay.atlassian.net/browse/M2P-72)
#changelog Retrieve bundle product by SKU properly when getting the main product image

M2P-72 Retrieve bundle product by SKU properly when getting the main product image

---

Block/Js.php

Fix bug with instant checkout for cart casting to boolean.
Fixes: [MX-888 Roll out checkout button v2 to M2](https://github.com/BoltApp/bolt-magento2/pull/695)
#changelog return boolean

Instant Checkout Fix to return Bool instead of string.

---

Controller/Cart/Data.php
Test/Unit/Controller/Cart/DataTest.php

[MX-859](https://boltpay.atlassian.net/browse/MX-859)
Merchant_order_token.failure metric is captured more often than success. Failure is only captured by a few merchants, possible they are not on the latest update. Bugsnag is not notified when a failed metric is captured for these merchants. A fix for now is to notify Bugsnag whenever order_token.failure is processed in the plugin code. We can push merchants to update their plugin to continue further with this issue. 
#changelog Notify Bugsnag when BoltException is caught

Notify Bugsnag when BoltException is caught

---

Block/Js.php
Helper/Config.php
Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Test/Unit/Block/JsTest.php
Test/Unit/Helper/ConfigTest.php
etc/adminhtml/system.xml
view/frontend/templates/js/replacejs.phtml

Introducing the always present checkout button into the M2 code base. The button appears and enables initiation of checkout from any white listed when there are one or more items in the cart. The feature exists behind a feature switch. We respect the Bolt Everywhere flag for minicart and appears on whitelisted pages (the same as minicart). We likely will disable minicart for merchants who use this button but the code should still support minicart and always present checkout button on the same page.
The button is:
Hidden when no items in cart.
When an item is added to cart the Buy Now button appears. Minicart animates.
When navigating to another product or category page the Buy Now button appears.
To setup the button call BoltCheckout.configure with {floatingButtonOption: "show_cart"} or …

Always Present Checkout button.

---

Model/Payment.php
Test/Unit/Model/PaymentTest.php

https://github.com/BoltApp/bolt-magento2/blob/master/Model/Payment.php#L558
The parameter $quote is missing when calling its parent method isAvailable
Fixes: https://boltpay.atlassian.net/browse/M2P-77
#changelog Fix bug - Parameter is missing when calling parent method

[M2P-77] Fix bug - Parameter is missing when calling parent method

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

This will let us use the same method when creating carts for non-Bolt orders. Was not sure how to test locally, so will be looking into that next-- although this is just a simple refactor so is low risk.
#changelog Refactor methods to expose them for new use cases

Factor out logic to build cart from standard quote

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

This makes the method more generic as it doesn't rely on an attribute of the CartHelper being set.
#changelog Pass immutableQuote as parameter rather than as attribute
Refactor collectDiscounts to enable a $quote to be passed rather than pulled from the CartHelper

Pass immutableQuote as parameter rather than as attribute

---

.eslintignore
.eslintrc.json
.gitignore
package-lock.json
package.json
view/frontend/templates/boltaccount.phtml

- bandaid fix for ES version compatibility for IE11 users
- added git pre commit check using eslint and husky
- No clean way of checking for ES version in `.phtml` files using composer, so added some npm dev dependencies. These can be removed once refactoring to move JS files out of M2 into source is accomplished. Dependencies can then be accessed from source. 
- A more sustainable change would be to use a transpiler (such as babel and webpack) to convert es6+ syntax into es5 during the build stage. This solution can be further looked into after the JS refactor, and assets are loaded into M2 from source.
Fixes: [MX-504](https://boltpay.atlassian.net/browse/MX-504)
#changelog [MX-504] Added ES version check for IE11 compatibility
- added pre commit hooks and linting instructions
- modified …

[MX-504] Added ES version check for IE11 compatibility

---

view/frontend/layout/default.xml
view/frontend/templates/js/boltglobaljs.phtml
view/frontend/templates/js/replacejs.phtml

If PPC is enabled while MiniCart is disabled, then PPC does not work in the product page due to the Js errors "Uncaught TypeError: Cannot read property 'trackCallbacks' of undefined" and “whenDefined is not defined“, it is because window.boltConfig.trackCallbacks and window.whenDefined are not initialized.
So we move the window.boltConfig and window.whenDefined to a separate js file for global reference.
Fixes: https://boltpay.atlassian.net/browse/M2P-83
#changelog Fix bug - PPC is broken if "MiniCart" setting field is set to "No"

M2P-83 Fix bug - PPC is broken if "MiniCart" setting field is set to "No"

---

Helper/Api.php
Helper/Cart.php
Observer/NonBoltOrderObserver.php
Test/Unit/Observer/NonBoltOrderObserverTest.php
etc/events.xml

This observer will trigger on all completed orders, and conditionally send non-Bolt order information to the Bolt backend. This is part of the non-Bolt order management project, which will let shoppers see all of the purchases in the Bolt shopper dashboard regardless of how they paid.
Tested locally with my Magento 2 devbox-- Bolt orders were ignored and non-Bolt order information was successfully sent to the Hail backend and stored in the DB.
#changelog Add observer on order creation event to injest non-Bolt orders
Add observer for all completed orders to ingest non-Bolt order information.

Add observer on order creation event to injest non-Bolt orders

---

Model/Api/CreateOrder.php
Plugin/QuotePlugin.php
Test/Unit/Model/Api/CreateOrderTest.php
Test/Unit/Plugin/QuotePluginTest.php

This PR disables both Bolt internal and Magento built-in minimum order amount validation for Bolt backoffice orders.
Fixes: https://boltpay.atlassian.net/browse/M2P-84
#changelog Removal of Backoffice Orders Triggering Minimum Amount Validation

Removal of Backoffice Orders Triggering Minimum Amount Validation

---

Controller/Adminhtml/Cart/Data.php
Test/Unit/Controller/Adminhtml/Cart/DataTest.php

Remove unsed parameter `place_order_payload` in the Bolt cart creation of backoffice order.
Fixes: https://boltpay.atlassian.net/browse/M2P-86
#changelog Remove unused code

M2P-86 Remove unused code

---

view/frontend/templates/button_product_page.phtml

If the product name contains any single quote, then the frontend js script of Bolt PPC would run into an error `Uncaught SyntaxError: Unexpected identifier`.
So we need to escape the product name that they pass otherwise this will cause things to break on the product page anytime a single quote is used in the product name. 
Fixes: https://boltpay.atlassian.net/browse/M2P-88
#changelog Fix bug - Bolt PPC is broken if the product name contains single quote

M2P-88 Fix bug - Bolt PPC is broken if the product name contains single quote

---

Controller/Cart/CheckoutConfig.php
Helper/Config.php
Plugin/Magento/Rewards/Controller/Cart/RemoveActionPlugin.php
Test/Unit/Controller/Cart/CheckoutConfigTest.php
Test/Unit/Helper/ConfigTest.php
Test/Unit/Plugin/Magento/Rewards/Controller/Cart/RemoveActionPluginTest.php
Test/Unit/ViewModel/MinicartAddonsTest.php
ViewModel/MinicartAddons.php
etc/adminhtml/system.xml
etc/config.xml
etc/frontend/di.xml
view/frontend/layout/default.xml
view/frontend/templates/checkout/minicart_addons.phtml
view/frontend/templates/js/replacejs.phtml

This PR adds support for Magento EE Reward Points to minicart.
Fixes: https://boltpay.atlassian.net/browse/EN-188
#changelog Reward points need to be displayed in the minicart [EN-188]

Reward points need to be displayed in the minicart [EN-188]

---

Helper/Order.php
Test/Unit/Helper/OrderTest.php
etc/events.xml

The Commerce Edition module observer, Magento\GiftCardAccount\Observer\RevertGiftCardAccountBalance,  is configured in events.xml but the class is not present in Community Edition.
The exception is thrown in failed_payment hook processing. Order gets cancelled but not deleted.
In such cases it blocks further checkouts for registered customers so this is a high severity bug.
The solution is to dispatch `sales_model_service_quote_submit_failure`, that the aforementioned observer listens to, if present.
This event is also observed by (some) other gift card / store credit / reward points modules for balance reverting so it is a universal solution.
Fixes: https://boltpay.atlassian.net/browse/M2P-91
#changelog Unknown RevertGiftCardAccountBalance fix …

Unknown RevertGiftCardAccountBalance fix

---

Block/Info.php
Helper/Order.php
Test/Unit/Block/InfoTest.php
view/adminhtml/templates/info/default.phtml
view/frontend/templates/info/default.phtml

To modify the Payment Method from Bolt Pay to Bolt-<APM> in the Payment Method. For PayPal it would be Bolt-PayPal , for Afterpay Bolt-Afterpay.
The reason is that we want this field to be represented the same across all platforms where possible. By adding this extra Paid via input in Magento, we complicate maintenance, communication and support.
Frontend
Backend
Fixes: https://boltpay.atlassian.net/browse/M2P-78
#changelog Fix display of APM/PayPal Transactions within Magento 2 Dashboard

M2P-78 Fix display of APM/PayPal Transactions within Magento 2 Dashboard V2

---

Helper/Order.php
Test/Unit/Helper/OrderTest.php

While some versions of Magento have been tested and have been updated to check email configurations before sending out invoice emails, (where I tested 2.2.7 and 2.3.3), other versions do not.  This adds a check from our end just in case.
Fixes: https://boltpay.atlassian.net/browse/M2P-13
#changelog Add configuration check before sending invoice email

Add configuration check before sending invoice email

---

Model/Payment.php
Test/Unit/Model/PaymentTest.php

Currently, some merchants have this bug http://prntscr.com/sxj29a when creating online credit memos in the back-office.
This PR resolves it by rounding the amount before calling the refund API
Fixes: https://boltpay.atlassian.net/browse/M2P-93
#changelog Rounding the amount before calling the refund API

Rounding the amount before calling the refund API

---

view/frontend/templates/js/replacejs.phtml

- Call configure with promises if createOrder calls first time
- Add listener for magento section with bolt cart and hints
- In listener:
-- If cart isn't changed do nothing
-- If cart changed and we didn't have cart before - resolve promises we passed to configure
-- If cart changed and we do have old cart - call configure again
#changelog Plugin refactoring

M2P-82 Read bolt cart from sections instead of AJAX call

---

view/frontend/templates/js/replacejs.phtml

* When always present button enable we can't resolve promises, because configure expect promises only for the two first arguments. So we should re-call reconfigure.
It can cause dead click and probably should be resolved on server side down the road
* When a user clicks "add to cart" we set a flag and use it a few seconds later - when the updated cart comes from Magento server
Fixes: M2P-82
#changelog M2P-82 Update always present checkout button code

M2P-82 Update always present checkout button code

---

Helper/Order.php
Test/Unit/Helper/OrderTest.php

1. Customer placed an order and it was created successfully on both Magento and Bolt
2. The captures are saved into the payment info in http://prntscr.com/synm4g
3. The pending hook was sent to Magento and the exception “Unprocessable Entity: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock“ was thrown in http://prntscr.com/syo29u. The deadlock exception is an edge case exception. 
4. After that, the re-try pending hook and the payment hook were sent to Magento and they were ignored because of this check http://prntscr.com/sy64s5
5. The order was stuck in Pending Payment status and the invoice wasn’t created
So I create the PR to fix the issue by not allowing the captures to be saved in the payment info until the …

M2P-96 Not allowing the captures to be saved in the payment info until the invoice is created

---

Observer/NonBoltOrderObserver.php
Test/Unit/Observer/NonBoltOrderObserverTest.php

Also add more robust methods to pull email, first name, and last name
from the Cart/Customer objects.
#changelog Send payment method in Bolt request and set transaction reference
Set payment method in request

Send payment method in Bolt request and set transaction reference

---

Test/Unit/ViewModel/MinicartAddonsTest.php
ViewModel/MinicartAddons.php
etc/frontend/sections.xml
view/frontend/templates/checkout/minicart_addons.phtml
view/frontend/templates/js/replacejs.phtml

This PR adds compatibility for Reward Points minicart feature when using new `boltcart` customer section. Minicart rewards functionality depends on `createOrder` function always creating an order with the latest data. It is expected to be called after both [adding](https://github.com/BoltApp/bolt-magento2/blob/011d6dafbef37de5c604df7f90e833f4f70b6d55/view/frontend/templates/checkout/minicart_addons.phtml#L78) and [removing](https://github.com/BoltApp/bolt-magento2/blob/011d6dafbef37de5c604df7f90e833f4f70b6d55/view/frontend/templates/checkout/minicart_addons.phtml#L41) reward points by triggering `bolt:createOrder` event which is tied to `createOrder` [here](https://github.com/BoltApp/bolt-magento2/blob/03f38eed8dc0c88f7ee9630a375420d0f3aca851/view/frontend/templates/js/replacejs.phtml#L107 …

Reward Points minicart compatibility with replace.js refactor

---

Plugin/Magento/TogglePaymentMethodsPlugin.php
Test/Unit/Plugin/Magento/TogglePaymentMethodsPluginTest.php
etc/di.xml

When Magento Commerce edition Gift Card, Store Credit or Reward Points amount used covers the whole order price (items, shipping and tax) the order creation fails with Bolt payment. The above modules expect the Payment method to be Zero Subtotal Checkout in such cases. We, on the other hand, need to keep it as Bolt Pay. The solution is to create a plugin that overrides the payment_method_is_active observers defined in these modules to allow Bolt Pay.
Fixes: [M2P-100](https://boltpay.atlassian.net/browse/M2P-100)
#changelog Zero subtotal order creation error fix

M2P-100 zero subtotal order creation error fix

---

Helper/Order.php
Test/Unit/Helper/OrderTest.php

When the Gift Card is purchased two gc instances get created in the Magento system.
They are created upon invoice save and it appears that we are calling it twice, once directly and another time as the order related object. 
Proposed solution: remove one of the calls.
Fixes: [M2P-102](https://boltpay.atlassian.net/browse/M2P-102)
#changelog Magento Commerce duplicate gift card creation on invoice save fix

M2P-102 Magento Commerce duplicate gift card creation on invoice save fix

---

view/frontend/templates/js/replacejs.phtml

When user closes bolt checkout we should reload magento section to have updated bolt cart (for example if user applied a discount on bolt modal)
Fixes: [M2P-106]
#changelog M2P-106 Reload bolt cart when user closes bolt checkout

M2P-106 Reload bolt cart when user closes bolt checkout

---

etc/frontend/sections.xml

Applying the Magento store credit (Customer Balance) doesn't automatically trigger a Magento cart section refresh and therefore does not trigger the boltcart section to update.  We explicitly register that action here.
Fixes: https://boltpay.atlassian.net/browse/M2P-112
#changelog Add support for Magento CustomerBalance to boltcart section

Add support for Magento CustomerBalance to boltcart section

---

view/frontend/templates/js/replacejs.phtml

If user updated carts (add discount / change quanity / remove item) and click bolt checkout right after that user can see checkout with old cart.
It happens because of magento didn't update cart yet.
In this PR we are fixing it by calling configure() with promises in all cases when we know cart will be updated in a next few seconds.
If user clicks bolt button before promises are resolved user just waits for resolve. 
Fixes: [M2P-104]
#changelog M2P-104 Call configure() with promises when we know cart will be updating soon

M2P-104 Call configure() with promises when we know cart will be updating soon

---

view/frontend/templates/js/replacejs.phtml

When a user closes bolt modal we call configure() with promises to make sure user can't open checkout with the old cart.
But if cart wasn't changed we do nothing and don't resolve promises.
Solution: resolve promises even if bolt cart wasn't change.
#changelog Fix issue when user close bolt modal and open again

Fix issue when user close bolt modal and open again

---

view/frontend/templates/js/replacejs.phtml

When we render bolt button on popup after user clicks "add to cart" we don't call BoltCheckout.configure() so bolt button isn't showed.
Proposal:
1. fix it and call BoltCheckout.configure(). We no need to update bolt cart in those cases.
2. if we render bolt button after we call configure with promises, postpone new configure call. Otherwise, we can have dead click on others checkout buttons
3. Add delay 0 to call configure after magento triggers add to cart events. If we do this, new bolt button is rendered meanwhile and shows right after we make postponed call.
Actually (3) is enough to fix the known issue for PolyWood but step (1) and (2) add some reliability for other cases (when new bolt button is rendered in any moment different from add to cart). …

Bugfix: Call configure after we render new bolt button

---

Helper/Order.php
Model/Api/OrderManagement.php
Test/Unit/Helper/OrderTest.php
Test/Unit/Model/Api/OrderManagementTest.php

Some merchants are using ERP. Here are two cases that are needed to be fixed:
Case 1:
1. The auto-capture setting is disabled on Bolt
2. The $0 order is created on both Bolt and Magento
3. Bolt sends a payment hook request to Magento to authorize the order and create an invoice automatically
4. The ERP system sends a request to Magento to create an invoice and it causes an error because the invoice was already created on #3
Case 2:
1. The auto-capture setting is enabled on Bolt
2. The order is created on both Bolt and Magento
3. Bolt sends a payment hook request to Magento to authorize the order and create an invoice automatically
4. The ERP system sends a request to Magento to create an invoice and it causes an error because the invoice was already created on #3
This PR resolves the …

M2P-122 Ignore invoice creation when the payment hook is sent to Magento

---

view/frontend/templates/js/replacejs.phtml

After the refactoring bolt button on add-on-cart popup was broken, the fix handles it as well as other cases when we add a new bolt button in the DOM.
The **first commit** is the same as in https://github.com/BoltApp/bolt-magento2/pull/769. I reverted it yesterday becuase it affected on integration tests.
The **second commit** fixes an issue that happens when user clicks the first bolt button before we render the second one.
Although eventually, we want to fix this is the storm [EN-340], we are pretty good with this interim solution. See also [M2P-124](https://boltpay.atlassian.net/browse/M2P-124), [M2P-129](https://boltpay.atlassian.net/browse/M2P-124)
#changelog Handle case when we render the one more bolt button
Please validate that you have tested your change …

Handle case when we render one more bolt button

---

Model/Api/Tax.php
Test/Unit/Model/Api/TaxTest.php

Currently, if the shipping reference is shqshared_GROUND_HOME_DELIVERY
together with this logic - https://github.com/BoltApp/bolt-magento2/blob/master/Model/Api/Tax.php#L108 , the shipping carrier code will be **shqshared**, the shipping method code will be **GROUND** and this isn’t expected.
This PR fixes the issue by getting the first string until the first underscore is the shipping carrier code (in this case, it’s **shqshared**) and the rest of the string after the first underscore is the method code regardless if it contains other underscore characters (in this case, it’s **GROUND_HOME_DELIVERY**). 
Fixes: 
https://boltpay.atlassian.net/browse/ON-88
https://boltpay.atlassian.net/browse/M2P-134
#changelog Correct the shipping method code …

M2P-134 Correct the shipping method code

---

Helper/Cart.php
Helper/Config.php
Test/Unit/Helper/CartTest.php
Test/Unit/Helper/ConfigTest.php
etc/adminhtml/system.xml

Adds magento product attributes into bolt cart.
We need this for using attrubutes in custom rules.
Merchant can select which attributes will be added into cart.
Fixes: [M2P-133]
Tech discussion and following steps https://docs.google.com/document/d/1KGH7Ov9VgC5F6cOcHchBriZxduTS02rNPSk15rCuAs4/edit#heading=h.vv6izgxam70a
#changelog M2P-133 Add custom product attributes to bolt cart

M2P-133 Add custom product attributes to bolt cart

---

.circleci/config.yml

For whatever reason there's a disconnect between the message composed by the circleci notify orb and slack, causing only the first of the tags to be an actual tag. We're changing this here so Pavel gets the real tag, but leaving Oleksii in just in case something changes on circle or slack that causes it to work properly in the future.
#changelog Change to be tagging Pavel for tag notifications

Change to be tagging Pavel for tag notifications

---

.circleci/README.md
.circleci/scripts/auto-rebase.sh

The auto-rebase result for branch <auto-rebase-branch> result will be pushed to ci/<auto-rebase-branch> instead directly to  <auto-rebase-branch> because many merchant branches are directly referenced in merchant's composer file and we don't want to upgrade them without notifying merchants for testing
Fixes: [MX-1413] 
#changelog Push auto-rebase result to ci branches instead of overwriting the branch history
[MX-1413]: https://boltpay.atlassian.net/browse/MX-1413

[MX-1413] Push auto-rebase result to ci branches instead of overwriting the branch history

---

etc/events.xml

Remove registration of `NonBoltOrderObserver`
Reference: https://github.com/BoltApp/bolt-magento2/issues/790
#changelog Remove NonBoltOrderObserver registration
#mergeWhenGreen

Remove nonBoltObserver registration

---

view/frontend/templates/js/replacejs.phtml

If a third party plugin doesn't update Magento cart after discount applying we don't update bolt cart as well.
Solution: invalidate bolt cart if quote total was updated and we don't know a reason.
We don't want to invalidate bolt date if quote total updated when page is loaded, or after on of magento event (add to cart, etc)
Fixes: [M2P-140]
#changelog Fix an issue with some third party discounts modules

M2P-140 Listen if 3p modules update quote total

---

Helper/Order.php
Test/Unit/Helper/OrderTest.php

Currently, after creating credit memos by credit hooks, if the total refunded is equal to the grand total and the total paid, the order status is Processing. This isn’t expected. The order status should be Closed.
This PR solves that issue by setting the order status to Closed.
Here are the test screenshots:
- Before fix:  https://prnt.sc/tfh6e9
- After fix: https://prnt.sc/tfhnz2
Fixes: https://boltpay.atlassian.net/browse/M2P-141
#changelog M2P-141 Set order status to closed if total refunded is equal to total paid and grand total

M2P-141 Set order status to closed if total refunded is equal to total paid and grand total

---

view/frontend/templates/js/replacejs.phtml

When we handle quote total updating we need to do:
- call BoltCheckout.Configure with promises
- invalidate bolt cart
- resolve promises once we receive a new bolt cart
It allows us to handle properly clicks that users do while we update bolt cart.
It the same as we do in all other situations when we know that Magento cart was updated.
Fixes: [M2P-140]
#changelog [M2P-140] Call bolt with promises when 3p module updated the quote total

[M2P-140] Call bolt with promises when 3p module updated the quote total

---

Helper/Cart.php
Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Test/Unit/Helper/CartTest.php

There is a merchant that doesn’t want to use the logic pre-fill address from Bolt for the logged-in customer. 
So I created this PR to implement a feature switch to toggle that logic
Fixes: 
https://boltpay.atlassian.net/browse/M2P-147
https://boltpay.atlassian.net/browse/EN-395
#changelog M2P-147 Implement a feature switch to toggle the logic to pre-fill address from Bolt for the logged-in customer

M2P-147 Implement a feature switch to toggle the logic to pre-fill address from Bolt for the logged-in customer

---

Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Observer/NonBoltOrderObserver.php
Observer/TrackingSaveObserver.php
Test/Unit/Observer/NonBoltOrderObserverTest.php
etc/events.xml

Added a feature switch around the non-Bolt observer.
This does not re-register the observer, so as of now it still does not do anything.
#changelog Add feature switch around Non-Bolt Observer and re-register event
Add a feature switch for the NonBoltOrderObserver
Re-register the observer with two order placed events

Add feature switch around Non-Bolt Observer

---

Block/Js.php
Helper/Config.php
Test/Unit/Block/JsTest.php
Test/Unit/Helper/ConfigTest.php
etc/adminhtml/system.xml
view/frontend/templates/boltaccount.phtml
view/frontend/templates/js/replacejs.phtml

Now we can the bolt management button only into the header menu. We do it via backend.
This way doesn't work for some Magento themes, so in this PR we add an alternative approach, insterting necessary div after CSS selector added into plugin setting.
For example if we add *#newsletter* into settings it looks like:
Fixes: [M2P-50]
#changelog Add option to show bolt management button after the specific dom element

M2P-50 Add option to show bolt management button after the specific dom element

---

view/frontend/templates/js/replacejs.phtml

An issue was introduced in https://github.com/BoltApp/bolt-magento2/pull/801 (2.10.0)
After this PR it's possible that we use Magento sections functional before it initialized properly.
It happens on cart page only, when Magento tried to render order total.
As a result, the order total isn't rendered. Bolt button is shown and it can work if bolt order was loaded before the issue happened.
If, for example, a user clicked add to cart, wait 10 seconds and then go to cart page we can expect bolt button works.
If a user goes to the cart page right after they added something to the cart bolt button doesn't work.
If the bolt button doesn't …

[M2P-161] Fix issue with IE11: cart total isn't shown under some condition

---

Helper/Bugsnag.php
Helper/Config.php
Model/Api/Data/DebugInfo.php
Model/Api/Debug.php
Test/Unit/Block/Checkout/Cart/ComponentSwitcherProcessorTest.php
Test/Unit/Block/Checkout/SuccessTest.php
Test/Unit/Block/JsProductPageTest.php
Test/Unit/Block/JsTest.php
Test/Unit/Helper/BugsnagTest.php
Test/Unit/Helper/ConfigTest.php
Test/Unit/Model/Api/Data/DebugInfoTest.php
Test/Unit/Model/Api/DebugTest.php

Sometimes, it’s useful to know the merchant’s composer version, especially for debugging an issue without the codebase access.
This PR provides the ability to log the composer version to Bugsnag and Debug Webhook.
See demo screenshots below: 
https://prnt.sc/ti602e
https://prnt.sc/tiyn61
Fixes: https://boltpay.atlassian.net/browse/M2P-149
#changelog M2P-149 Log composer version for debugging

M2P-149 Log composer version for debugging

---

view/frontend/templates/js/replacejs.phtml

In rare cases, connect.js can be loaded after JS plugin code is executed.
This PR adds check to all cases when we call BoltCheckout.configure.
Fixes: M2P-178
#changelog M2P-178 Check if BoltCheckout loaded before we call it

M2P-178 Check if BoltCheckout loaded before we call it

---

view/frontend/templates/js/replacejs.phtml

When users open the first page of the site they don't have any data in local storage.
I assumed that in this case Magento2 always loads the data, including bolt cart.
So before this PR if we didn't have a bolt cart at all we did nothing because we were waiting to have a new bolt cart in a few seconds.
This assumption works well, but we have one exception:
When a user opens the first page, Magento asks all data from the server in one AJAX request. If a user closes their first page very quickly, we don't have data in local storage. Unfortunately, on the next page loading, Magento doesn't care about the issue. It just cares about its data like in this code.
It's not a big deal for us, because we ask for new bolt cart [in 10 seconds after page …

M2P-175 Reload bolt cart if we have Magento cart only

---

view/frontend/templates/js/replacejs.phtml

We introduced an issue in https://github.com/BoltApp/bolt-magento2/pull/796. Actually it was known magento issue that was fixed in new Magento versions, see https://github.com/magento/magento2/pull/23099 , https://github.com/magento/magento2/issues/14412, https://github.com/magento/magento2/pull/21432
Under some conditions, Magento JS script produced an error because they initialated wrong.
We had a fix https://github.com/BoltApp/bolt-magento2/pull/808 but now I see it doesn't affect the root of the issue.
In PR 796 we added `require(['Magento_Checkout/js/model/quote'] ...)` thing. This requireJS API means we push `model/quote` script to load if it wasn't loaded before. Under some very rare conditions, it triggers incorrect initializing.
So solution the same as in …

M2P-161 Stop pushing model/quote JS script

---

.circleci/scripts/auto-rebase-branches.txt

We can return them once we update branches. We can't auto rebase them for now.
#changelog Remove yogibo and nmwa from auto rebases branches

Remove yogibo and nmwa from auto rebases branches

---

Helper/Config.php
Test/Unit/Helper/ConfigTest.php

Fix Uncaught Error: Call to a member function getVersion() on null 
See here: https://prnt.sc/tqsidc
This error occurs in case Bolt is installed in the folder app/code, not via the composer
Fixes: https://boltpay.atlassian.net/browse/M2P-185
#changelog Fix Uncaught Error: Call to a member function getVersion() on null

M2P-185 Fix Uncaught Error: Call to a member function getVersion() on null

---

.circleci/config.yml

when-condition things are compiled before executing, so we can't use shell variables in conditions.
As result we always notify greenkeeper slack channel if the build fails.
Solution: use `circleci-agent step halt` instead
#changelog Fix issue with conditionally notify greenkeeper step

Fix issue with conditionally notify greenkeeper step

---

Observer/TrackingSaveObserver.php
Plugin/NonBoltOrderPlugin.php
Setup/UpgradeSchema.php
Test/Unit/Observer/TrackingSaveObserverTest.php
Test/Unit/Plugin/NonBoltOrderObserverTest.php
etc/di.xml

There were several issues with using an observer to ingest non-Bolt orders.
First of all, there isn't any consistency across various payment methods
on which events are emitted on order creation. Second of all, the order may
be in various states and possible incomplete/not saved at the time of the
event being emitted. This can lead to all sorts of weird behaviors. Instead,
this PR uses a plugin that should consistently fire after the initial order
is placed and saved.
#changelog Use plugin for afterPlace rather than observer for orders …

Use plugin for afterPlace rather than observer for orders

---

Helper/Discount.php
Model/Api/DiscountCodeValidation.php
Model/ThirdPartyModuleFactory.php
Test/Unit/Helper/DiscountTest.php
Test/Unit/Model/ThirdPartyModuleFactoryTest.php
etc/di.xml

Since v2.0.0, the Amasty team completely overhauled Amasty GiftCard module, as a result, Bolt M2 plugin does not work with the latest version of Amasty GiftCard. So we need to update the related code to support.
Fixes: https://boltpay.atlassian.net/browse/M2P-137
#changelog General plugin support for Amasty GiftCard 2.0.0 or later

M2P-137 General plugin support for Amasty GiftCard 2.0.0 or later

---

Helper/FeatureSwitch/Definitions.php

Disable the non-Bolt plugin by default
#changelog Disable Non-Bolt Order plugin by default

Disable Non-Bolt Order plugin by default

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

Currently, the module can’t detect the updates after adding the Gift Wrapping and it is using the previous token which doesn’t have any Gift Wrapping.
This PR is to add gift wrapping info into the cart cache identifier
Fixes: 
https://boltpay.atlassian.net/browse/M2P-184
https://app.asana.com/0/1142111051828235/1181220571495009
#changelog M2P-184 Add gift wrapping info into the cart cache identifier

M2P-184 Add gift wrapping info into the cart cache identifier

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

This PR is to correct the logic to get the product images for the Bolt cart just like the logic to get the cart item images.
Fixes: https://boltpay.atlassian.net/browse/M2P-181
#changelog M2P-181 Correct logic to get product images for the Bolt cart

M2P-181 Correct logic to get product images for the Bolt cart

---

Helper/Cart.php
Model/Api/DiscountCodeValidation.php
Test/Unit/Helper/CartTest.php
Test/Unit/Model/Api/DiscountCodeValidationTest.php

Improvement upon https://github.com/BoltApp/bolt-magento2/pull/806
Actually proved to be a bigger issue affecting other (all?) discounts applied from Bolt modal where cached Bolt cart (order token) would be re-used. This was confirmed and tested for Amasty_GiftCard and Magento Discount Coupon.
Fixes: https://boltpay.atlassian.net/browse/M2P-155
#changelog Resolve issue with discounts applied from Bolt modal persisting after being removed

Resolve issue with discounts applied from Bolt modal persisting after being removed

---

Helper/Order.php
Test/Unit/Helper/OrderTest.php

Currently, if the merchant cancels the order on Bolt or the Magento admin, the order status goes to cancel. However, the order item status doesn’t. As a result, the salable quantity isn’t restored.
This PR resolves that issue by removing the issued code.
See screenshot for testing:
Before fix: https://prnt.sc/ttf2pe
After fix: https://prnt.sc/ttez8u
Fixes: https://boltpay.atlassian.net/browse/M2P-199
#changelog M2P-199 Restock product saleable quantity when canceling order

M2P-199 Restock product saleable quantity when canceling order

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

Correct logic to get product images for the Bolt cart (compatible with all Magento version)
Fixes:  https://boltpay.atlassian.net/browse/M2P-181
#changelog M2P-181 Correct logic to get product images for the Bolt cart (compatible with all Magento version)

M2P-181 Correct logic to get product images for the Bolt cart (compatible with all Magento version)

---

composer.json

Fix composer requirements so plugin installs on Magento 2.4.
Note: You must install Elasticsearch before installing Magento Commerce or Magento Open Source 2.4.0. See https://devdocs.magento.com/guides/v2.4/install-gde/prereq/elasticsearch.html for details.
Also, there's a Two-Factor Authorization enabled by default for the admin area. It can be turned off by disabling Magento_TwoFactorAuth module.
Fixes: [https://boltpay.atlassian.net/browse/M2P-201]
#changelog M2P-201 - Magento 2.4 requirements update

M2P-201 - Magento 2.4 requirements update

---

Model/Api/ShippingMethods.php
Test/Unit/Model/Api/ShippingMethodsTest.php

Shipping estimation currently saves shipping information of the last shipping method onto shipping address after shipping estimation webhook. It was detected during an integration as it caused a conflict with Mageplaza_Simpleshipping. This PR resolves the issue by re-collecting totals after the shipping estimation with the shipping method set to null.
Fixes: https://boltpay.atlassian.net/browse/M2P-182
#changelog

Cleanup shipping address data after shipping estimation

---

Helper/Cart.php
Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Test/Unit/Helper/CartTest.php

In current Bolt checkout flow, the shipping and tax endpoint is not called for virtual carts,
It means we don't support taxes for virtual product.
In this PR we add feature switch to handle all virtual products as physical, so it's a workaround for known issue.
and should handle all products as physical
Fixes: [M2P-151]
#changelog M2P-151 Add feature switch to handle with virtual products as physical

M2P-151 Add feature switch to handle with virtual products as physical

---

Helper/Discount.php
Test/Unit/Helper/DiscountTest.php

On the latest Mageplaza_GiftCard, we can’t apply the gift card code via the Bolt modal
This PR resolves it.
Fixes: https://boltpay.atlassian.net/browse/M2P-145
#changelog M2P-145 Update logic for applying Mageplaza gift card via Bolt modal on the latest version

M2P-145 Update logic for applying Mageplaza gift card via Bolt modal on the latest version

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

Refactor the code to use assigned variable $parentProduct instead of item->getProduct() per Vitaliy’s feedback in PR https://github.com/BoltApp/bolt-magento2/pull/867/files
Fixes: https://boltpay.atlassian.net/browse/M2P-204
#changelog M2P-204 Refactor the code to use assigned variable $parentProduct instead of item->getProduct() 

M2P-204 Refactor the code to use assigned variable $parentProduct instead of item->getProduct() 

---

view/frontend/templates/js/replacejs.phtml

Magento2 plugin needs to know Magento settings before answer on check() callback.
But this info loaded asynchronously and isn't available during 1-2 seconds after we show bolt button.
So right now if user clicks on bolt button very fast, we return false in check() callback.
It's not an ideal and by this PR we return promise in check(). Storm PR that allows this is under review. I've tested the workflow on my local dev site. 
By this PR we allow plugin to return promise in check() callback. Solution was discussed with @pschutz93 by slack.
Fixes: [M2P-179](https://boltpay.atlassian.net/browse/M2P-179)
#changelog M2P-179 Return promise in check() callback

M2P-179 Return promise in check() callback

---

Model/Api/CreateOrder.php
Test/Unit/Model/Api/CreateOrderTest.php

Move the order creation portion of the web hook into a helper function. This will be useful when we implement the universal merchant api because then we can just use dependency injection to inject this class into the universal endpoint and then just call this helper function. 
Fixes: [MP-1302]
#changelog Refactor the Create Order Web hook [MP-1302]
[MP-1302]: https://boltpay.atlassian.net/browse/MP-1302

Refactor the Create Order Web hook [MP-1302]

---

Block/Js.php
Helper/Cart.php
Test/Unit/Block/JsTest.php
view/frontend/templates/js/replacejs.phtml

* Reuse existing bolt plugin setting toggle_checkout. It was developed to allow toggle Bolt/Magento checkout depends on the cart content
* If toggle_checkout enabled hide bolt button by default. We show it again when call configure() if conditions are met
* Change the method how we show/hide Magento buttons for toggle_checkout. Now it works with “display:none!important” which is default setting.
* Move variable restricted for toggle_checkout into BoltState
* Create variable globalRestricted for disabling bolt for each cart (for example, depending on user type)
* Add barrier to allow extensions postpone configure() calls
Extension JS code example (it shows native Magento buttons after 10 seconds:  
```
BoltState.beforeConfigureBarrier = boltBarrier();
setTimeout(function () { …
```

M2P-197 Allow merchant extensions to hide bolt button under certain conditions

---

Block/JsProductPage.php
Helper/Config.php
Test/Unit/Block/JsProductPageTest.php
Test/Unit/Helper/ConfigTest.php

Currently, the product page checkout doesn’t work for the downloadable product. This PR adds the ability to support it.
Here is the screenshot for testing - https://prnt.sc/u2btgj
Fixes: https://boltpay.atlassian.net/browse/M2P-214
#changelog M2P-214 Support product page checkout for the downloadable product

M2P-214 Support product page checkout for the downloadable product

---

Helper/Discount.php
Test/Unit/Helper/DiscountTest.php

For store integral discount coupon code could be empty and we need to return empty discount type.
Without this fix magento generates exception and checkout is blocked for users.
#changelog M2P-217 Return empty discount type for empty coupon code

M2P-217 Return empty discount type for empty coupon code

---

view/frontend/templates/js/replacejs.phtml

This refactoring opens the opportunity to use promises from the beginning of the code.
In IE11 we use polyfill library from connect.js that allows promises.
So if we use promises before connect.js loading it's not IE compatible.
In this PR:
- move Magento cart listener into function createOrder
- check if Magento cart or Bolt cart was initialized before we setup listener (I can't reproduce this but potentially it could be an issue.
- make sure we call createOrder exactly once (for multistep for now; will fix payment only in the corresponding task
- rename createOrder to boltCheckoutSetup
#changelog M2P-179 JS refactoring

M2P-179 JS refactoring

---

Block/JsProductPage.php
Helper/Cart.php
Helper/Config.php
Test/Unit/Block/JsProductPageTest.php
Test/Unit/Helper/CartTest.php
etc/module.xml
view/frontend/templates/button_product_page.phtml

Currently, the product page checkout doesn’t work for the grouped product. This PR adds the ability to support it.
Here is the screenshot for testing - https://prnt.sc/u3nv9m
Fixes: https://boltpay.atlassian.net/browse/M2P-218
#changelog Support product page chekcout for grouped product

Support product page checkout for grouped product

---

Helper/Order.php
Test/Unit/Helper/OrderTest.php

This PR resolves the following case by using the parent quote id to get the existing order
1. The customer clicks the Pay button in the Bolt modal
2. The create_order hook is sent to Magento and receives a time out error
3. There is a third party that updates the Magento increment id for the created order
4. Because of #2, there isn’t any successful response sent back to Bolt, so the Bolt increment id isn’t updated on Bolt
5. The pending hook is sent to Magento, it isn’t able to get the existing order by the Bolt increment id, so it tries to create the order and then it throws an exception
=> The expected behavior for #5 is that the pending hook is able to get the existing order to authorize and update the order
Fixes: https://boltpay.atlassian.net/browse/M2P-223
#changelog M2P-223 Use …

M2P-223 Use parent quote id as a fallback to get the existing order

---

Helper/Session.php
Model/EventsForThirdPartyModules.php
Test/Unit/Helper/SessionTest.php
Test/Unit/Model/EventsForThirdPartyModulesMock.php
Test/Unit/Model/EventsForThirdPartyModulesTest.php
Test/Unit/Model/ListenerMock.php
ThirdPartyModules/Mageplaza/ShippingRestriction.php
etc/di.xml

Revert https://github.com/BoltApp/bolt-magento2/pull/877/ and make the same plugin customization using new scalable approach.
Instead of injecting ThirdPartyModuleFactory class for each third party class we want to support this PR introduces new class with the following responsibility:
- Persist (in const) list of events with classes we need to run when the event happened and if classes exist
- Check that 3p classes exists and call the specific method if so.
Details:
https://docs.google.com/document/d/1d46e2IQSk9Eih1FqYbu3JP1ZvxbEHVJCf7dMZRPf2b4/edit#
Fixes: [M2P-92](https://boltpay.atlassian.net/browse/M2P-92)
#changelog M2P-92 Add class for support third party plugins

M2P-92 Add class for support third party plugins

---

Helper/Discount.php
Test/Unit/Helper/DiscountTest.php
etc/di.xml

The merchant `Andrew Christian B2C & Wholesale` use an old version of Mirasvit Store Credit plugin in their site, and the Bolt plugin can not create instance of \Mirasvit\Credit\Api\Config\CalculationConfigInterface properly with that version, so we need to fix this compatibility issue.
#changelog Compatibility fix for old versions of Mirasvit Store Credit plugin

Compatibility fix for old versions of Mirasvit Store Credit plugin

---

Helper/Order.php
Model/Api/OrderManagement.php
Test/Unit/Helper/OrderTest.php
Test/Unit/Model/Api/OrderManagementTest.php

Fix issue we added recently around working with immutable_quote_id in hook handling.
Fixes: [M2P-226](https://boltpay.atlassian.net/browse/M2P-226) 
#changelog  M2P-226 Fix immutable_quote_id retriving in hook handling

 M2P-226 Fix immutable_quote_id retriving in hook handling

---

Model/Api/DiscountCodeValidation.php
Test/Unit/Model/Api/DiscountCodeValidationTest.php

Fix display_id using and immutable_quote_id retrieving after refactoring we did recently.
This bug didn't lead to any serious issues, because we use parent_id when we don't have immutable_quote_id
#changelog Check display_id using in discount validation class

Check display_id using in discount validation class

---

Helper/Cart.php
Helper/Order.php
Model/Api/ShippingMethods.php
Model/Api/ShippingTax.php
Test/Unit/Helper/CartTest.php
Test/Unit/Model/Api/ShippingTaxTest.php

Allow users to finish checkout if the order was created in the previous plugin version.
Fixes: [M2P-226](https://boltpay.atlassian.net/browse/M2P-226)
#changelog M2P-226 Add backward compatibility for order_reference refactoring

M2P-226 Add backward compatibility for order_reference refactoring

---

Model/Api/UpdateCart.php
Model/Api/UpdateCartCommon.php
Test/Unit/Model/Api/UpdateCartCommonTest.php
Test/Unit/Model/Api/UpdateCartTest.php

Address changes we did with bolt cart:
- we can't use reserved order id anymore
- in update_order call bolt server sends immutable quote id as order_reference
#changelog Fix update_order after display_id refactoring

Fix update_order after display_id refactoring

---

Test/scripts/ci-unit.sh

For now memory limit for unit tests is 128MB. Consumed memory grows linearly with the number of tests and recently we crossed this threshold for PHP 7.2
#changelog Increase memory limit for unit tests

Increase memory limit for unit tests

---

view/frontend/templates/js/replacejs.phtml

**Steps to reproduce a bug:**
- go to the product page
- click add to cart and go to cart page very fast (it happens if Magento redirects to the cart page or just user click very fast)
- on the cart page click bolt button right after it appears.
**Actual behavior**
User sees unactual cart on bolt modal (or even error if the cart was empty before adding to cart)
To fix this we need to set a flag in local storage when updating the cart is started and remove it when the new bolt cart is delivered.
If we see the flag on the page loading it means the previous page didn't finish updating and current bolt cart is unactual.
Fixes: [M2P-233](https://boltpay.atlassian.net/browse/M2P-233)
#changelog M2P-233 Check if previous page updated bolt cart properly …

M2P-233 Check if previous page updated bolt cart properly

---

ThirdPartyModules/Aheadworks/Giftcard.php

Current, the Bugsnag property is missing in class Bolt\Boltpay\ThirdPartyModules\Aheadworks\Giftcard and it's not logging the exception to Bugsnag. See here - https://prnt.sc/udu0cv
This PR creates the missing Bugsnag property for class Bolt\Boltpay\ThirdPartyModules\Aheadworks\Giftcard
Fixes: https://boltpay.atlassian.net/browse/M2P-239
#changelog M2P-239 Create the missing Bugsnag property for class Bolt\Boltpay\ThirdPartyModules\Aheadworks\Giftcard

M2P-239 Create the missing Bugsnag property for class Bolt\Boltpay\ThirdPartyModules\Aheadworks\Giftcard

---

view/frontend/templates/js/replacejs.phtml

Description
After recent changes, we calculate the condition for check() once when the page is loaded, but the user can add to the cart products that restricted for guest users.
So we need to recalculate the condition when Magento cart is updated.
Fixes: [M2P-236](https://boltpay.atlassian.net/browse/M2P-236)
#changelog M2P-236 Recalculate condition for check() call each time when magento cart is updated

M2P-236 Recalculate condition for check() call each time when magento cart is updated

---

ThirdPartyModules/Mirasvit/Credit.php

When creating the Bolt cart, it should collect Mirasvit store credit only if the quote has used credits.
#changelog Bugfix: collect Mirasvit store credit only if the quote has used credits

Bugfix: collect Mirasvit store credit only if the quote has used credits

---

Helper/Cart.php

Steps to reproduce:
- add product to cart with bolt version 2.13.0
- finish checkout with version 2.14.0-rc2
Actual behavior:
Order is created but stuck in pending status
Fixes: [M2P-250](https://boltpay.atlassian.net/browse/M2P-250)
#changelog M2P-250 Don't generate notice if display_id does not contain "/"

M2P-250 Don't generate notice if display_id does not contain "/"

---

Helper/Cart.php
Helper/Order.php
Test/Unit/Helper/CartTest.php
Test/Unit/Helper/OrderTest.php

1. The customer clicked the Pay button on the Bolt modal
2. The create_order hook (thread 1) was sent to Magento and received a timeout response because **$this->quoteManagement->submit($quote);** took a long time to run. See here - https://prnt.sc/u97pim . The order was created with the status of Pending Payment, and the create_hook process was still running.
3. The authorize/payment hook (thread 2) was sent to Magento to update the order state to processing.
4. The create_order hook (thread 1) updated the order state to pending payment.
This PR fixes the above case by ensuring the returned order in the create_order hook is the latest updated order to prevent #4 from happening.
Fixes: https://boltpay.atlassian.net/browse/EN-674
#changelog Ensure the …

EN-674 Ensure the returned order in the create_order hook is the latest updated order

---

Model/Api/ShippingTax.php
Test/Unit/Model/Api/ShippingTaxTest.php

Move core logic of split shipping/tax to helper fn. This will be useful when we implement the UniveralMerchantAPI. 
Fixes: https://boltpay.atlassian.net/browse/MA-85?atlOrigin=eyJpIjoiMzRhZTE3Y2UxYzEwNGE1NGI3MTUwZjdiZDFmMGQyZDIiLCJwIjoiaiJ9
#changelog [MA-85] Move core logic of split shipping/tax to helper fn

[MA-85] Move core logic of split shipping/tax to helper fn

---

Model/Api/ShippingMethods.php
Test/Unit/Model/Api/ShippingMethodsTest.php

Move the core logic to get the shipping_and_tax information into a helper function. This will be useful when we we switch over to the Universal API. 
Fixes: https://boltpay.atlassian.net/browse/MA-85?atlOrigin=eyJpIjoiNTkyYTM1NTYwN2Q2NGRlMDhmMTAzMGM1OWIyNzU1YjEiLCJwIjoiaiJ9
#changelog Split shipping_and_tax logic into helper

Split shipping_and_tax logic into helper [MA-85]

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

Move the core logic of create_cart to a helper function. This will be useful when we implement the universal endpoint and we have to handle the `cart.create` call - it allows us to call the new fn without having to worry about how the request is formatted.
Fixes: https://boltpay.atlassian.net/browse/MA-87?atlOrigin=eyJpIjoiZjA5YWRhZDBhZmYxNDQ0YTk3MWZiZDEzOGQwMjhkYzIiLCJwIjoiaiJ9
#changelog Move cart_create logic to helper fn

[MA-87] Move cart_create logic to helper fn

---

Helper/Cart.php
Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Test/Unit/Helper/CartTest.php

Add user group id into bolt cart under feature switch
Fixes: [M2P-254](https://boltpay.atlassian.net/browse/M2P-254)
#changelog M2P-254 Add user group id into bolt cart under feature switch

M2P-254 Add user group id into bolt cart under feature switch

---

view/frontend/templates/js/replacejs.phtml

If settings "redirect to cart after add to cart" enabled we have an issue during a couple of seconds after cart page loading: Magento cart wasn't loaded on the previous page so we called configure() with an unactual bolt cart.
In https://github.com/BoltApp/bolt-magento2/pull/917 we saved flag in local storage when the updating process was started, but it doesn't work if users clicks add to cart on the category page, because Magento doesn't trigger the event.
I found a more robust solution: when Magento started the update process, it deletes Magento cart from local storage.
So if we have bolt cart in local storage and do not have Magento cart it means the bolt cart is unactual and we shouldn't use it.
I reverted PR917 because new solution covers all cases.
Fixes: …

 M2P-233 Don't use bolt cart if we have no Magento cart

---

Model/ThirdPartyModuleFactory.php
Test/Unit/Model/ThirdPartyModuleFactoryTest.php

In legacy flow for support third party modules call **interface_exists** in necessary cases.
This fix makes module Aheadworks Store Credit work
We already have the same in new 3p support flow - https://github.com/BoltApp/bolt-magento2/blob/67c717b6a6aa7dd3e3ae1e073c6bb3bc9d194d1f/Model/EventsForThirdPartyModules.php#L332
Fixes: [M2P-219](https://boltpay.atlassian.net/browse/M2P-219)
#changelog M2P-219 Check if interface exists in legacy 3p support flow

M2P-219 Check if interface exists in legacy 3p support flow

---

Model/Api/UpdateCart.php
Model/Api/UpdateDiscountTrait.php

Final keyword is prohibited in Magento. It decreases extensibility and is not compatible with plugins and proxies.
And we need to remove final keyword from plugin to pass the check of marketplace.magento.com
#changelog Remove final keyword

Remove final keyword

---

Helper/Discount.php
Model/Api/UpdateCart.php
Model/Api/UpdateDiscountTrait.php
Model/EventsForThirdPartyModules.php
Test/Unit/Helper/DiscountTest.php
Test/Unit/Model/Api/UpdateDiscountTraitTest.php
Test/Unit/ThirdPartyModules/Amasty/GiftCardAccountTest.php
ThirdPartyModules/Amasty/GiftCardAccount.php
etc/di.xml

Resolves issues when applying both new and legacy Amasty Giftcards via discount/v2.
Adds support for failed payments for the new Amasty Giftcards by restoring gift card balance on failed payment.
Resolves issue with PPC and discount/v2 where Giftcards would get removed by the cloneAmastyGiftCards because of the same source and destination quote ID.
Fixes: [M2P-242](https://boltpay.atlassian.net/browse/M2P-242)
#changelog Discounts v2 fix - Unable to apply Amasty Gift Card via PPC

 M2P-242 - Discounts v2 fix - Unable to apply Amasty Gift Card via PPC

---

Helper/Cart.php
Helper/Discount.php
Model/Api/UpdateCart.php
Model/Api/UpdateDiscountTrait.php
Test/Unit/Helper/DiscountTest.php
Test/Unit/Model/Api/UpdateCartTest.php
Test/Unit/Model/Api/UpdateDiscountTraitTest.php
etc/di.xml
etc/frontend/di.xml

Currently the coupon can not be added via update-cart v2 api hook, something is broken. This PR is to fix it.
Fixes: https://boltpay.atlassian.net/browse/M2P-275
#changelog Bugfix: fail to add coupon via update-cart v2 api hook

M2P-275 Bugfix: fail to add coupon via update-cart v2 api hook

---

view/frontend/templates/js/replacejs.phtml

Under some condition possible that `setupReplacement()` run after bolt js script is initialized but before BoltState setup.
In version 2.14 this produces error
`Uncaught TypeError: Cannot read property 'isResolved' of null at callConfigure`
Solution: call setupReplacement() right after BoltState is initialized
#changelog Postpone setupReplacement() code until BoltState is initialized

Postpone setupReplacement() code until BoltState is initialized

---

Block/Form.php
Test/Unit/Block/FormTest.php
view/adminhtml/templates/boltpay/button.phtml

Add the additional attributes into the checkout button in the back-office
Fixes: https://boltpay.atlassian.net/browse/M2P-283
#changelog M2P-283 Add the additional attributes into the checkout button in the backoffice

M2P-283 Add the additional attributes into the checkout button in the backoffice

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

$quote->getAppliedRuleIds() would return all the available rules for the quote, and some of them (especially the no coupon type) actually does not match the conditions at that point and still have zero discount amount, so we need to exclude them from the cart data sent to Bolt
Fixes: https://boltpay.atlassian.net/browse/M2P-278
#changelog Exclude zero discount from the Bolt cart

M2P-278 Exclude zero discount from the Bolt cart

---

Model/Api/DiscountCodeValidation.php
Model/Api/UpdateCart.php
Model/Api/UpdateCartCommon.php
Test/Unit/Model/Api/UpdateCartCommonTest.php
Test/Unit/Model/Api/UpdateCartTest.php

Refactor validate quote so that it throws an exception instead of sending an error response to the client. 
I moved the sending of the error response to the api entry point (`UpdateCart::execute` and `DiscountCountValidation::validate`). 
This allows us to reuse the validateQuote function and not have to worry about the format of the error response (i.e. universalAPI will have a different error response format).
#changelog Refactor validate Quote

Refactor validate Quote

---

Model/EventsForThirdPartyModules.php
ThirdPartyModules/Amasty/Rewards.php

Amasty\Rewards\Helper\Data->getRewardsData(); does not get applied reward points of backoffice order, and Amasty\Rewards\Model\ResourceModel\Quote->getUsedRewards($quoteId) works for both backoffice order and front store oder, so we use it instead.
Fixes: https://boltpay.atlassian.net/browse/M2P-290
#changelog Bugfix: Amasty Reward points are not applied to the order in Back Office

M2P-290 Bugfix: Amasty Reward points are not applied to the order in Back Office

---

Block/Js.php
Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Test/Unit/Block/JsTest.php
etc/config.xml

The prefetch option doesn't work with new shipping flow, adds load for merchants servers and additional calls to paid services such as avalara.
We need to disable it by default, but still can use for merchants who need it via feature switches.
Fixes: [M2P-301](https://boltpay.atlassian.net/browse/M2P-301)
#changelog M2P-301 Disable prefetch shipping by default

M2P-301 Disable prefetch shipping by default

---

Model/EventsForThirdPartyModules.php
ThirdPartyModules/Amasty/Rewards.php
view/frontend/templates/js/replacejs.phtml

When users click on Amasty reward button "apply" or "remove" the module sends form data to the server, get 302 answer and reload cart page.
When the user clicks the button we know that the bolt cart will be unactual soon and we persist flag to update the bolt cart during the next page load.
We need to implement the same for all modules that reload cart page after discount applying. For 3p modules that works via jQuery AJAX we have another solution: https://github.com/BoltApp/bolt-magento2/pull/929
Fixes: [M2P-269](https://boltpay.atlassian.net/browse/M2P-269)
#changelog M2P-269 Update bolt cart when Amasty rewards applied or removed

M2P-269 Update bolt cart when Amasty rewards applied or removed

---

Api/Data/CartDataInterface.php
Api/Data/UpdateCartResultInterface.php

Currently, our Bolt module is breaking the Magento swagger UI. See here - https://prnt.sc/uuwdbm
This PR is to resolve the issue by changing the return type annotation from array to mixed[]
See the reference link here - https://github.com/mundipagg/magento2/issues/137
Fixes: 
https://boltpay.atlassian.net/browse/M2P-296
https://boltpay.atlassian.net/browse/EN-674
#changelog M2P-296 Change the return type annotation from array to mixed[] to fix the Swagger issue

M2P-296 Change the return type annotation from array to mixed[] to fix the Swagger issue

---

Helper/Discount.php
Test/Unit/Helper/DiscountTest.php

When collecting quote totals, by default it only reset the applied coupon rules once (https://github.com/magento/magento2/blob/2.4/app/code/Magento/SalesRule/Model/Validator.php#L248).
But in our plugin, especially when applying/removing the coupon code, we may collect quote totals for several times. And in current logic, the applied coupon rules are not updated properly after updating the coupon, as a result, the discount amount is wrong in some context and cause the discount/tax mismatch.
So we need to maunally reset the applied coupon rules every time set coupon code.
Fixes: https://boltpay.atlassian.net/browse/M2P-276
#changelog Bugfix: Tax amount mismatch after applying discount via v2 update-cart api hook …

M2P-276 Bugfix: Tax amount mismatch after applying discount via v2 update-cart api hook

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

In https://github.com/BoltApp/bolt-magento2/pull/942 we introduced code that split discounts in bolt modal in case when few discounts applied to cart.
PR942 saves intermediate results in checkout session, it doesn't work for backend orders.
Down the road we can find a solution for BO, but for now, I just fix the regression issue by applying PR942 to multistep orders only.
Fixes: [M2P-317](https://boltpay.atlassian.net/browse/M2P-317)
#changelog M2P-317 Fix issue with discounts in backend orders

M2P-317 Fix issue with discounts in backend orders

---

Helper/Cart.php
Plugin/SalesRuleActionDiscountPlugin.php
Plugin/SalesRuleQuoteDiscountPlugin.php
Test/Unit/Helper/CartTest.php
Test/Unit/Plugin/SalesRuleActionDiscountPluginTest.php
Test/Unit/Plugin/SalesRuleQuoteDiscountPluginTest.php

This bug is caused by the PR https://github.com/BoltApp/bolt-magento2/pull/997 , then the Bolt plugin can not distinguish between M2 discount rules and custom discount rule of 3rd-party plugins.
And after investigation, the root cause of the bug mentioned in the task https://boltpay.atlassian.net/browse/M2P-317 is that, for backoffice order, the default session type in SalesRuleActionDiscountPlugin and SalesRuleQuoteDiscountPlugin is Magento\\Backend\\Model\\Session, while the one in CartHelper is Magento\\Backend\\Model\\Session\\Quote, so the data of discount rules are not saved properly.
Solution: make all the sessions same type.
Fixes: https://boltpay.atlassian.net/browse/M2P-326
#changelog Fix issue with discounts of backoffice order
Please validate that you have tested your change …

M2P-326 Fix issue with discounts of backoffice order

---

Block/JsProductPage.php
Helper/Config.php
Test/Unit/Block/JsTest.php
Test/Unit/Helper/ConfigTest.php
etc/adminhtml/system.xml

Adds a configuration field to allow merchants to enable PPC only on products with the `bolt_ppc` attribute.
Fixes: [M2P-256](https://boltpay.atlassian.net/browse/M2P-256)
#changelog Add support to enable PPC only on specific products

M2P-256 Add support to enable PPC only on specific products

---

Helper/Order.php
Model/Payment.php
Test/Unit/Model/PaymentTest.php

If merchants try to refund paypal transaction but doesn't have enough funds in their account, bolt server creates refund transaction with **in_progress** status.
Once the merchant has enough funds, a refund will be processed and transaction status will be updated to **completed**.
By this PR we handle the case: update Magento order to closed status and add to order comment to explain that refund is in progress.
Before this PR we had exception when users try to create credit memo.
Fixes: [M2P-194](https://boltpay.atlassian.net/browse/M2P-194)
#changelog M2P-194 Add support for paypal "in progress" refund

M2P-194 Add support for paypal "in progress" refund

---

Helper/Order.php
Test/Unit/Helper/OrderTest.php

1. The customer clicked the Pay button in the Bolt modal and the order was created on both Bolt and Magento.
2. The first auth hook was sent to Magento and the exception “Unprocessable Entity: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock“ was thrown ( See here: https://prnt.sc/uz8olh). The deadlock exception is an edge case exception.
3. Since the first auth hook failed, Bolt re-sent the second auth hook to Magento to re-authorize the order. But the odd thing here is that it skipped because of this code http://prntscr.com/sb7lgg so it put order status to payment review
=> So I create the PR to allow the retry auth hook to authorize the order and update status to processing if it's status is payment review so the …

M2P-263 Allow the retry auth hook to authorize order if its status is payment review

---

Model/EventsForThirdPartyModules.php
ThirdPartyModules/Aheadworks/StoreCredit.php

Add support to remove Aheadworks StoreCredit by v2 update_cart api hook
Fixes: https://boltpay.atlassian.net/browse/M2P-313
#changelog Remove Aheadworks StoreCredit by API hooks

M2P-313 Remove Aheadworks StoreCredit by API hooks

---

Helper/Order.php
Test/Unit/Helper/OrderTest.php

When PPC order isn't paid and we try to delete it PHP throws an exception because of the wrong method name.
Fixes: [M2P-331](https://boltpay.atlassian.net/browse/M2P-331)
#changelog M2P-331Fix issue with deleting PPC orders

M2P-331 Fix issue with deleting PPC orders

---

view/frontend/templates/js/replacejs.phtml

Before this PR we missed Magento total update if we expect it.
For example, a user added something to the cart, we know that it means Magento total will be re-render soon. No action requires.
By this PR we compare Magento total (without shipping and tax) with bolt total even if we expect total rendering.
It works if we don't support some 3p module very well and haven't noticed that it changed cart (like added or removed discount).
Fixes: [M2P-269](https://boltpay.atlassian.net/browse/M2P-269)
#changelog M2P-269 Invalidate bolt cart if bolt total differs from Magento total

M2P-269 Invalidate bolt cart if bolt total differs from Magento total

---

view/frontend/templates/js/replacejs.phtml

Under some condition, it's possible that we observe Bolt cart at the moment when we already have a more fresh Magento cart.
Don't call configure because we will have a new bolt cart in the next second or so.
This continues the fix from https://github.com/BoltApp/bolt-magento2/pull/943
Fixes: [M2P-233](https://boltpay.atlassian.net/browse/M2P-233)
#changelog M2P-233 Don't call configure if we have more fresh Magento cart

M2P-233 Don't call configure if we have more fresh Magento cart

---

Model/EventsForThirdPartyModules.php
Observer/Adminhtml/ActionPredispatch.php
Test/Unit/Observer/Adminhtml/ActionPredispatchTest.php
Test/Unit/ThirdPartyModules/Aheadworks/Sarp2Test.php
ThirdPartyModules/Aheadworks/Sarp2.php
etc/adminhtml/events.xml

Backoffice key is dynamically loaded on Bolt order create [here](https://github.com/BoltApp/bolt-magento2/blob/a396f7342eff78e44aef056f4c866b506f603059/view/adminhtml/templates/boltpay/js/replacejs.phtml#L395). It is expected that, at the time of the order creation, an appropriate store is already chosen.
This was not the case for this client’s (Andrew Christian) store for the following reason: Magento 2, by default, performs some checks for each payment method before it can be rendered. These checks are defined [here](https://github.com/magento/magento2/blob/7ddd47e87e217ba20b883e9ee22e5e3ef618e6df/app/code/Magento/Sales/etc/di.xml#L154). Aheadworks_Sarp2 attempted to add a check for recurring payments, unfortunately they added it in the adminhtml area as opposed to global, where Magento …

M2P-262 - Resolve issue with Aheadworkds_Sarp2

---

Model/Api/CreateOrder.php
Model/EventsForThirdPartyModules.php
ThirdPartyModules/Mirasvit/Rewards.php

We need to send all the available points balance of Mirasvit Rewards to the Bolt server side when necessary, so Bolt can calculate the totals properly.
Fixes: https://boltpay.atlassian.net/browse/M2P-338
#changelog Bugfix: Tax mismatch if the available points balance of Mirasvit Rewards is larger than cart subtotal

M2P-338 Bugfix: Tax mismatch if the available points balance of Mirasvit Rewards is larger than cart subtotal

---

ThirdPartyModules/Aheadworks/Giftcard.php

In some contexts, if the cart has aheadworks Giftcard applied, there would be an error "The specified Gift Card code already in the quote" during order creation.
It is because when cloning quote data from the parent quote to the immutable quote, the immutable quote already has aheadworks Giftcard applied
Fixes: https://boltpay.atlassian.net/browse/M2P-339
#changelog Bugfix: the specified aheadworks Gift Card code already in the quote

M2P-339 Bugfix: the specified aheadworks Gift Card code already in the quote

---

Model/EventsForThirdPartyModules.php
ThirdPartyModules/Mirasvit/Rewards.php

When Mirasvit rewards points and Mirasvit store credits both are enabled, and the customer applies credits to the cart, then the Bolt plugin calculates Mirasvit rewards points instead of Mirasvit store credits for the order unexpecetly.
Fixes: https://boltpay.atlassian.net/browse/M2P-340
#changelog Bugfix: charge Mirasvit rewards points instead of Mirasvit store credits unexpecetly

M2P-340 Bugfix: charge Mirasvit rewards points instead of Mirasvit store credits unexpecetly

---

Model/EventsForThirdPartyModules.php

The root cause of this bug is that we send the discounts info to Bolt server in the order:
```
{"amount":2000,"code":null,"reference":null,"description":"Store Credit","details_url":null,"discount_category":"store_credit","type":"fixed_amount"},
{"amount":2000,"code":null,"reference":null,"description":"Reward Point(s)","details_url":null,"discount_category":"store_credit","type":"fixed_amount"}
```
Bolt first pick up "Store Credit" and apply the cart, after that it counts "Reward Point(s)" to the cart.
So we need to adjust the order of discounts info.
Fixes: https://boltpay.atlassian.net/browse/M2P-344
#changelog Bugfix: confuse mirasvit rewards points with mirasvit store credits

M2P-344 Bugfix: confuse mirasvit rewards points with mirasvit store credits

---

Model/EventsForThirdPartyModules.php
Plugin/Mirasvit/Rewards/Model/Total/Quote/DiscountPlugin.php
ThirdPartyModules/Mirasvit/Rewards.php
etc/di.xml

When the cart has Mirasvit rewards applied, if  subtotal < balance of Mirasvit rewards < subtotal +shipping cost , then the related quote has duplicate shipping discount from Mirasvit rewards, cause Bolt already count the Mirasvit rewards points in the totals.
Fixes: https://boltpay.atlassian.net/browse/M2P-343
#changelog Bugfix: duplicate shipping discount from Mirasvit rewards

M2P-343 Bugfix: duplicate shipping discount from Mirasvit rewards

---

view/frontend/templates/js/replacejs.phtml

Postpone magentoCartDataListener call to prevent case when if happens before boltCartDataListener is defined
#changelog Postpone magentoCartDataListener call

Postpone magentoCartDataListener call

---

Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Plugin/AbstractLoginPlugin.php
Test/Unit/Plugin/AbstractLoginPluginTest.php
Test/Unit/Plugin/LoginPostPluginTest.php

EN-1297 Add feature switch for disabling the redirect customers to the cart page after they log in
Fixes: https://boltpay.atlassian.net/browse/EN-1297
#changelog Add feature switch for disabling the redirect customers to the cart page after they log in

Add feature switch (default OFF) for disabling the redirect customers to the cart page after they log in

---

Helper/Cart.php

Currently, there are some rounding issues if the customer adds a product with a large qty. So this PR is to correct the total amount calculation logic when building Bolt cart
FYI, this is the same as the way that we handle on M1. See here: https://github.com/BoltApp/bolt-magento1/blob/master/app/code/community/Bolt/Boltpay/Model/BoltOrder.php#L150
Fixes: https://boltpay.atlassian.net/browse/ON-389
#changelog Correct the total amount calculation logic when building Bolt cart

M2P-359 Correct the total amount calculation logic when building Bolt cart

---

Block/Js.php
Model/EventsForThirdPartyModules.php
ThirdPartyModules/Mirasvit/Credit.php
view/frontend/templates/js/replacejs.phtml

This is not a 100% reproducible issue, but it does exist. After investigation, it turned out that, in some contexts, neither the **boltcart** nor **cart** in the local storage do not update after Mirasvit credits changes. So we need to force to invalidate the Bolt cart if the script detect credit.data_id >= boltCartDataID
Fixes: https://boltpay.atlassian.net/browse/M2P-354
#changelog Bugfix: Bolt cart does not update after Mirasvit credits changes

M2P-354 Bugfix: Bolt cart does not update after Mirasvit credits changes

---

Helper/Order.php
Model/Api/OrderManagement.php
Test/Unit/Helper/OrderTest.php
Test/Unit/Model/Api/OrderManagementTest.php

If users try to pay a second time after an unsuccessful attempt Magento plugin can return an error "Order is in pending payment. Waiting for the hook update.".It happens if Magento didn't receive failed payment hook yet.
It happens quite often (few times per day) because hooks work asynchronously, use the queue. We can't expect hook work instantly.
Order in pending payment status can mean another thing: the order was irreversibly rejected before auth (blacklist e.g.) but the hook wasn't sent yet.
In this case, we will delete the order as well. This is not the best behavior, but it's not an issue: eventually, the merchant will have an order with canceled status, the same as before this PR.
Down the road, we are going to change behavior on the server side and don't create orders in the cart …

M2P-331 Allow to create order on the second payment attempt

---

Block/Info.php
Test/Unit/Block/InfoTest.php

Now we show the last four cart digits for vantiv only.
But we have this info for adyen, alliance, braintree, nmi, and stripe as well.
After this fix, we show last4 for each case when we have it.
Fixes: [ON-429](https://boltpay.atlassian.net/browse/ON-429)
#changelog ON-429 Show cart type and last four digits for all payment processors

ON-429 Show cart type and last four digits for all payment processors

---

Helper/Order.php
Plugin/Magento/Framework/View/Element/UiComponent/DataProvider/DataProviderPlugin.php
Plugin/Magento/Ui/Component/Form/Element/SelectPlugin.php
Test/Unit/Plugin/Magento/Framework/View/Element/UiComponent/DataProvider/DataProviderPluginTest.php
Test/Unit/Plugin/Magento/Ui/Component/Form/Element/SelectPluginTest.php
etc/adminhtml/di.xml

Show payment type (such as Paypal) it in order grid as well, as done on order details page.
Fixes: https://boltpay.atlassian.net/browse/M2P-357
#changelog M2P-357 - Show alternative payment type in order grid

M2P-357 - Show alternative payment type in order grid

---

Model/Api/Shipping.php
Model/Api/ShippingTax.php
Model/Api/Tax.php
Test/Unit/Model/Api/ShippingTaxTest.php
Test/Unit/Model/Api/ShippingTest.php
Test/Unit/Model/Api/TaxTest.php

This is a bug of v2 shipping endpoint, when calling $this->shippingMethodManagement->estimateByAddress, the address of quote is still empty.
Fixes: https://boltpay.atlassian.net/browse/M2P-375
#changelog Bugfix: Missing shipping option blocking checkout

M2P-375 Bugfix: Missing shipping option blocking checkout

---

Helper/Order.php
Test/Unit/Helper/OrderTest.php

It's possible that Magento throws an exception during pre-auth call when order is already created.It's better for us to check if the order looks good and return a success answer to not block checkout for users
Fixes: https://boltpay.atlassian.net/browse/M2P-384
#changelog Pre auth double check if order was created

M2P-384 - Pre auth double check if order was created

---

Test/Unit/Helper/CartTest.php
Test/Unit/TestUtils.php

Use integration tests instead of unit tests for method getCartData in class Helper/Cart
Fixes: https://boltpay.atlassian.net/browse/M2P-333
#changelog M2P-333 Use integration tests instead of unit tests for method getCartData in class Helper/Cart

M2P-333 Use integration tests instead of unit tests for method getCartData in class Helper/Cart

---

Plugin/Magento/GiftCard/GenerateGiftCardAccountsOrderPlugin.php
Test/Unit/Plugin/Magento/GiftCard/GenerateGiftCardAccountsOrderPluginTest.php

Fix exception: Call to member function getMethod() on boolean
Fixes: https://boltpay.atlassian.net/browse/M2P-389
#changelog Fix exception: Call to member function getMethod() on boolean

M2P-389 Fix exception: Call to member function getMethod() on boolean

---

Helper/Discount.php
Model/Api/ShippingMethods.php

In some certain contexts, the shipping discounts amount could be some very small values like 0.00002, then the Bolt plugin collect it and covert it into [$0.00 discount], cause priceHelper->currency round 0.00002 into 0.00.
Actually in m2, if the number is less than 0.005, it can be treated as zero.
Fixes: https://boltpay.atlassian.net/browse/M2P-371
#changelog Remove zero discount text from shipping option label

M2P-371 Remove zero discount text from shipping option label

---

Model/FeatureSwitch.php
Model/FeatureSwitchRepository.php
Model/ResourceModel/FeatureSwitch/Collection.php
Setup/Recurring.php
Test/Unit/Model/FeatureSwitchRepositoryTest.php
Test/Unit/Model/FeatureSwitchTest.php

Now we run sql query like
`SELECT `bolt_feature_switches`.* FROM `bolt_feature_switches` WHERE (`bolt_feature_switches`.`switch_name`='M2_MERCHANT_METRICS')
` few dozens time per request.
After this fix we use magento collection to retrieve all feature data by one request and save it into cache
Fixes: [M2P-299](https://boltpay.atlassian.net/browse/M2P-299
)
#changelog M2P-299 Use Collection to cache feature switches data
-  x] New and existing unit tests pass locally with my changes.

M2P-299 Use Collection to cache feature switches data

---

Model/Api/ShippingMethods.php
Test/Unit/Model/Api/ShippingMethodsTest.php

I changed the error logging to more specifically reflect what changed in the cart instead of just saying "something" changed.
Fixes: https://boltpay.atlassian.net/browse/MA-414
#changelog MA-414: Improve error logging for shipping and tax call

MA-414: Improve error logging for shipping and tax call

---

Helper/Cart.php
Model/Api/UpdateCart.php
Model/ErrorResponse.php
Test/Unit/Model/Api/UpdateCartTest.php
Test/Unit/Model/ErrorResponseTest.php

The description of product is HTML content ( or even some other HTML content in the fields ) and may have new lines. 
In some contexts (eg. https://boltpay.atlassian.net/browse/EN-2762) it would break the response of Bolt v2 update-cart API and result in a timeout error. So we need to escape the new lines before sending.
Fixes: https://boltpay.atlassian.net/browse/M2P-402
#changelog Bugfix: New lines break the api response

M2P-402 Bugfix: New lines break the api response

---

Test/Unit/Helper/ConfigTest.php
Test/Unit/Observer/Adminhtml/Sales/CreatingInvoiceForRechargeOrderTest.php

1. @covers::methodname is wrong, the correct syntax is @covers ::methodname 
2. Fix the error `Bolt\Boltpay\Test\Unit\Observer\Adminhtml\Sales\CreateInvoiceForRechargedOrderTest::execute_withRechargeOrder
TypeError: Return value of Mock_InvoiceService_490102db::prepareInvoice() must implement interface Magento\Sales\Api\Data\InvoiceInterface, instance of Mock_InvoiceService_490102db returned`
Fixes: https://boltpay.atlassian.net/browse/M2P-409
#changelog Fix PHPUnit tests errors

M2P-409 Fix PHPUnit tests errors

---

Helper/Cart.php
Model/Api/DiscountCodeValidation.php
Model/Api/UpdateDiscountTrait.php
Test/Unit/Helper/CartTest.php
Test/Unit/Model/Api/DiscountCodeValidationTest.php

Re-adds parentheses to discount display when displaying the discount code.
Fixes: [M2P-259](https://boltpay.atlassian.net/browse/M2P-259?atlOrigin=eyJpIjoiYjlmNWFjZDQxNTZjNDVlNmJjY2I2N2Y0ZGU3NmI1NjEiLCJwIjoiaiJ9)
Discount description "Test description":
No description, discount code "NODES":
#changelog M2P-259 Re-add parentheses to discount display

M2P-259 Re-add parentheses to discount display

---

Helper/Config.php

From Magento 2.4.1, the const Magento\Downloadable\Observer\IsAllowedGuestCheckoutObserver::XML_PATH_DISABLE_GUEST_CHECKOUT become private (related PR https://github.com/magento/magento2/pull/23972), as a result, when the Bolt plugin try to access this variable (https://github.com/BoltApp/bolt-magento2/blob/master/Helper/Config.php#L1661), it causes an error `Cannot access private const Magento\Downloadable\Observer\IsAllowedGuestCheckoutObserver::XML_PATH_DISABLE_GUEST_CHECKOUT`.
So we define this const in the class instead.
Tested with M2 v2.3.6 and v2.4.1
Fixes: https://boltpay.atlassian.net/browse/M2P-410
#changelog Bugfix: Cannot access private const Magento\Downloadable\Observer\IsAllowedGuestCheckoutObserver::XML_PATH_DISABLE_GUEST_CHECKOUT …

M2P-410 Bugfix: Cannot access private const Magento\Downloadable\Observer\IsAllowedGuestCheckoutObserver::XML_PATH_DISABLE_GUEST_CHECKOUT

---

Helper/Config.php
Helper/Order.php
Plugin/Magento/Framework/View/Element/UiComponent/DataProvider/DataProviderPlugin.php
Plugin/Magento/Ui/Component/Form/Element/SelectPlugin.php
Test/Unit/Helper/ConfigTest.php
Test/Unit/Plugin/Magento/Framework/View/Element/UiComponent/DataProvider/DataProviderPluginTest.php
Test/Unit/Plugin/Magento/Ui/Component/Form/Element/SelectPluginTest.php
etc/adminhtml/system.xml
etc/config.xml

Right now we show cart type (Visa/MC/Amex) on order details but not in order grid.
Need to add plugin setting "Show cart type (Visa/MC/Amex) on the order grid" disabled by default.
If the setting enabled and we know cart type we show Bolt-Visa or Bolt-MC or Bolt-Amex in the order grid
This is a request from the merchant Cabinet and continue changes we started in https://boltpay.atlassian.net/browse/M2P-357
Fixes: https://boltpay.atlassian.net/browse/M2P-407
#changelog M2P-407 - Show cart type (Visa/MC/Amex) on the order grid

M2P-407 - Show cart type (Visa/MC/Amex) on the order grid

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

We create a fresh quote for Bolt PPC, then after the data of this quote updates, it should be saved via repository.
Fixes: https://boltpay.atlassian.net/browse/M2P-416
#changelog Bugfix: Bolt PPC error if Aheadworks GiftCard is enabled

M2P-416 Bugfix: Bolt PPC error if Aheadworks GiftCard is enabled

---

Plugin/Magento/Quote/Observer/Frontend/Quote/Address/AddressCollectTotalsObserverPlugin.php
Test/Unit/Plugin/Magento/Quote/Observer/Frontend/Quote/Address/AddressCollectTotalsObserverPluginTest.php
etc/di.xml

This issue turned out to be caused by incompatibility between Bolt and specific Magento VAT configuration. This means that it can be reproduced in a blank Magento instance.
Configurations attributing to this issue are:
• “Customers → Customer Configuration → Create New Account Options → Enable Automatic Assignment to Customer Group” set to “Yes”
• “Customers → Customer Configuration → Create New Account Options → Tax Calculation Based On” set to “Shipping Address”
After filling in the email address, selecting a shipping option will trigger totals re-collection. During totals re-collection (sales_customer_validate_vat_number event), a CollectTotalsObserver will overwrite quote customer with an empty customer object since it’s a guest checkout, effectively removing the email address.
To …

ON-438 - Resolve issue with VAT validation

---

Model/EventsForThirdPartyModules.php

The merchant upgraded their staging site from 2.14 to 2.17 and reported seeing error messages in the console log for Amasty_StoreCredit. The merchant does not use Amasty_StoreCredit and does not want to see these errors in the console window.
The errors should not be present after the update. It means that we did not do something right when refactoring the Amasty support as a Third party module. We need to remove those blocks if the 3rd party module is not present. However, we trigger the removal from the actual 3rd party support code, which does not run when the module is missing. 
Fixes: [M2P-423](https://boltpay.atlassian.net/browse/M2P-423)
#changelog Remove Amasty StoreCredit blocks from shopping cart page layout if th
Please validate that you have tested your change in at least one …

M2P-423 - Remove Amasty StoreCredit blocks from shopping cart page layout if the module is not enabled

---

Model/Api/DiscountCodeValidation.php
Model/Api/UpdateCart.php
Model/Api/UpdateCartCommon.php
Test/Unit/Model/Api/DiscountCodeValidationTest.php
Test/Unit/Model/Api/UpdateCartCommonTest.php
Test/Unit/Model/Api/UpdateCartTest.php

When handling the discounts.code.apply api request, currently we do not update checkout session after retrieving quote by id, as a result, the quote object associated with cart is null.
Fixes: https://boltpay.atlassian.net/browse/M2P-426
#changelog Bugfix: Update checkout session in the callback of discounts.code.apply api request

M2P-426 Bugfix: Update checkout session in the callback of discounts.code.apply api request

---

Model/Api/DiscountCodeValidation.php
Model/Api/UpdateCart.php
Test/Unit/Model/Api/DiscountCodeValidationTest.php
Test/Unit/Model/Api/UpdateCartTest.php

If the cart data is empty for some reason, it would cause an exception `Notice: Undefined index:`  (https://github.com/BoltApp/bolt-magento2/blob/2.17.0/Model/Api/DiscountCodeValidation.php#L291 and https://github.com/BoltApp/bolt-magento2/blob/2.17.0/Model/Api/UpdateCart.php#L277). 
We need to avoid this exception if cart data is empty.
Fixes: https://boltpay.atlassian.net/browse/M2P-427
#changelog M2P-427 Capture&handle exception if cart data is empty

M2P-427 Avoid Undefined index exception if cart data is empty

---

Helper/Cart.php

Reported by Trail Gear. Back office order note from the create order form does not get into the order. The reason is that this field often gets populated after the cart is sent to bolt, so not passed to / with the immutable quote, existing in the parent only. However, in our transfer data method an empty immutable quote order note field overwrites the parent quote one. The solution is to exclude this field from the transfer, keeping what's in the parent quote. This case exists in back-office flow only and does not collide with the frontend order note populated from the bolt modal.   
Fixes: [ON-438](https://boltpay.atlassian.net/browse/ON-438)
#changelog ON-438 - persist the back office order note from the form up to the final order DB record …

ON-438 - persist the back office order note from the form up to the final order DB record

---

Plugin/SalesRuleQuoteDiscountPlugin.php
Test/Unit/Model/Api/UpdateDiscountTraitTest.php
Test/Unit/Plugin/SalesRuleQuoteDiscountPluginTest.php

Currently each time when collecting address discount amount, the BoltCollectSaleRuleDiscounts session data would be reset, then the plugin SalesRuleActionDiscountPlugin stores the discount amount in the checkout session to make the discount data of quote up-to-date. But in some contexts, the shippingAssignment of billing address has no item, as a result, our plugin just clear the BoltCollectSaleRuleDiscounts session data, and does not collect discount data, so the callback of update_cart endpoint fails to apply coupon.
Solution: Reset BoltCollectSaleRuleDiscounts session data only if shippingAssignment has item
Fixes: https://boltpay.atlassian.net/browse/M2P-433
#changelog Reset BoltCollectSaleRuleDiscounts session data only if shippingAssignment has item
Please validate that you have …

M2P-433 Reset BoltCollectSaleRuleDiscounts session data only if shippingAssignment has item

---

CHANGELOG.md

Let me know what date to put (i see internally it's live, so maybe the 24th?) and I'll update it before we merge this. 
#changelog 2.18.0 release notes
added release notes

2.18.0 release notes

---

Helper/Cart.php
Helper/Order.php
Test/Unit/Helper/CartTest.php
Test/Unit/Helper/OrderTest.php

Reported by Trail Gear. Precondition: manual transaction capture.
There is Edit order action in Magento admin. The order being edited gets canceled and a creation of a new order started, as a copy of the canceled order. In the end the orders have a reference link to each other. 
Fixes: https://boltpay.atlassian.net/browse/ON-438
#changelog ON-438 - Edit order support

ON-438 - Edit order support

---

Model/Api/Shipping.php
Test/Unit/Model/Api/ShippingTest.php

Our method was using estimateByAddress function which does not take into account address city, and it causes result errors with some shipping modules. Now the estimateByExtendedAddress is used.
Fixes: https://boltpay.atlassian.net/browse/M2P-460
#changelog M2P-460 - Use extended addres in shipping options calculation

M2P-460 - Use extended addres in shipping options calculation

---

view/frontend/templates/js/replacejs.phtml

The parameter `data` of functon `boltCartDataListener` could only have data_id, while in the server side the function `getSectionData` is not triggered, so `boltCartDataListener` is triggered by some other events in client side, and cause this JS error.
So we need to check if data.hints exists before processing.
Fixes: https://boltpay.atlassian.net/browse/M2P-463
#changelog Bugfix: JS error: Cannot read property 'prefill' of undefined

M2P-463 Bugfix: JS error: Cannot read property 'prefill' of undefined

---

Api/Data/UniversalWebhookResultInterface.php
Api/UniversalApiInterface.php
Model/Api/Data/UniversalWebhookResult.php
Model/Api/UniversalWebhook.php
Test/Unit/Model/Api/UniversalWebhookTest.php
etc/di.xml
etc/webapi.xml

This PR goes along with https://github.com/BoltApp/bolt-magento2/pull/1085. This adds a webhook endpoint for V2 webhooks to be sent to and simply pulls the data needed to pass to the existing `OrderManagement::manage` method and returns either a success response or the error thrown by `OrderManagement::manage`
The inclusion of the result interface is a bit excessive for now as we are continuing to create and send the responses manually as opposed to returning the interface to the Magento REST handler. I'm including it here as in https://boltpay.atlassian.net/browse/MA-493 I hope to clean up the response handling to make better use of interfaces if we still cannot simply return interfaces to the Magento REST handler.
[Relevant slack …

MA-83 Universal Webhook Support

---

Model/EventsForThirdPartyModules.php
ThirdPartyModules/Magento/GiftCardAccount.php

Root cause: the boltcart still has old data when the cart page is reloaded after Magento Gift Card is applied (https://github.com/BoltApp/bolt-magento2/blob/2.18.1/view/frontend/templates/js/replacejs.phtml#L1097).
So we need to force to invalidate the bolt cart.
Fixes: https://boltpay.atlassian.net/browse/M2P-465
#changelog Bugfix: The Bolt cart does not update when the Magento Gift Card is applied

M2P-465 Bugfix: The Bolt cart does not update when the Magento Gift Card is applied

---

Controller/Adminhtml/Cart/Data.php
Helper/Cart.php
Helper/Order.php
Model/Response.php
Test/Unit/Controller/Adminhtml/Cart/DataTest.php
Test/Unit/Helper/CartTest.php
Test/Unit/Helper/OrderTest.php
etc/di.xml
view/adminhtml/templates/boltpay/js/replacejs.phtml

Trail Gear reported issues with customer creation during back office orders. Fixed, tested and approved in an extension made for them.The extension should be removed when this gets released and they update.
How we did it so far is always creating a back-office order as a guest user, and never taking care of really creating a customer account and putting it into appropriate customer group. It was kind of hard-coded in the module. That's not how Magento does it and it's very strange that we missed it and no merchant pointed that out until now.
Basically, in the back-office create order flow either an existing customer is selected or a new one needs to be created in the process (Create New Customer button). No guests in Magento back-office orders. And all our back-office order customers in …

EN-3825 - Assign customer an appropriate group id in backoffice order creation process

---

Model/Api/UpdateCart.php

Bug found in RC testing, discounts were not included in the Magento order. This adds the quote syncing that was left out of the special discount handler for the universal endpoint.
Note that these handlers will be refactored this sprint with https://boltpay.atlassian.net/browse/M2P-467
Fixes: https://boltpay.atlassian.net/browse/M2P-477
#changelog [M2P-477] Fixes quote not being updated with discounts added during bolt checkout

[M2P-477] Fixes quote not being updated with discounts added during bolt checkout

---

Helper/Cart.php
Model/Api/UpdateCartCommon.php
Test/Unit/Helper/CartTest.php
Test/Unit/Model/Api/UpdateCartCommonTest.php

Actually this issue exists for any type of product which has **Customizable Options**. These custom options have their own SKUs, and M2 would combine the SKU of custom option with SKU of its parent product for quote item, eg. The parent product has SKU 24-MB01, and the SKU of its custom option is C1, then for the quote item in the cart, the SKU becomes 24-MB01-C1. The problem is this SKU 24-MB01-C1 does not exist in the DB, so productRepository->get would raise NoSuchEntityException.
This PR is to fix this bug and also add custom options to the properties of Bolt cart.
@ethanwayda22 As we discuss in the slack, the update-cart endpoint can not process with any item that has customizable options, cause if we add same product with different custom options into cart, the product id of these …

ON-574 Bugfix: unable to create cart if any item has customizable options

---

etc/webapi.xml

Given the issues with `updateCart` and the V2 api, we've decided to not include the V2 support in the 2.19.0 release. This PR just removes the routes added for the V2 api. This PR might not be merged as it is just being extra cautious.
#changelog Remove universal API routes
Remove universal API routes

Remove universal API routes

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

Root cause: After cloning quote data from source to destination (https://github.com/BoltApp/bolt-magento2/blob/2.18.1/Helper/Cart.php#L1136), the items of destination quote address still have old data. 
So we need to reset the cached_items_all data.
Fixes: https://boltpay.atlassian.net/browse/M2P-478
#changelog Bugfix: Discount rule is not removed when the product was deleted via Bolt modal

M2P-478 Bugfix: Discount rule is not removed when the product was deleted via Bolt modal

---

etc/config.xml

QOL change really. We are creating divisions with this feature enabled by default but the plugin does not have this enabled by default. 
Fixes: https://boltpay.atlassian.net/browse/ON-547
#changelog [ON-547] set pre auth to enabled by default

[ON-547] set pre auth to enabled by default

---

Helper/Cart.php
Model/Api/ShippingMethods.php
Test/Unit/Model/Api/ShippingMethodsTest.php

If fixed discount applied on whole cart, and the shipping address is taxable, the Bolt cart would experience an error `Cart Tax mismatched`.
Solution: To calculate a right discount value before calculate totals, we need to reset Cart Fixed Rules in the quote. If not, the $quote->getCartFixedRules() returns old value, and cause invalid discounts (https://github.com/magento/magento2/blob/6e0c28c39f6308339ffedabb159aeff6c4d70b46/app/code/Magento/SalesRule/Model/Rule/Action/Discount/CartFixed.php#L95)
Fixes: https://boltpay.atlassian.net/browse/M2P-493
#changelog Bugfix: Cart tax mismatched if fixed discount applied on whole cart

M2P-493 Bugfix: Cart tax mismatched if fixed discount applied on whole cart

---

Test/Unit/Helper/CartTest.php

Use integration test instead of unit test for methods getHints,saveToCache,getCustomerByEmail in class Helper/CartTest
#changelog Use integration test instead of unit test for methods getHints,saveToCache,getCustomerByEmail in class Helper/CartTest

Use integration test instead of unit test for methods getHints,saveToCache,getCustomerByEmail in class Helper/CartTest

---

view/frontend/templates/boltaccount.phtml

We have a problem with custom themes such as Monin where on mobile their menu does not change/append another copy of the element which results in the tracking not opening. The idea is to add a retry before injecting regardless. Ideally if we had a reload function inside of account.js we would just call that to bind tracking to the buttons with a mutation observer but since we cannot I went with the retry solution.
Fixes: [MA-521](https://boltpay.atlassian.net/browse/MA-521)
#changelog [MA-521] Account.js Mobile Retry Limit
[MA-521]: https://boltpay.atlassian.net/browse/MA-521

[MA-521] Account.js Mobile Retry Limit

---

Model/Api/UpdateCart.php
Test/Unit/Model/Api/UpdateCartTest.php
etc/webapi.xml

Adds v2 routes back into `webapi.xml` and changes the discount handler to use the metadata from the request for `immutable_quote_id`
Fixes: https://boltpay.atlassian.net/browse/M2P-477
#changelog M2P-477 Fix discounts not showing in M2 orders when using V2 endpoints
Adds Universal Endpoint Support

M2P-477 Fix discounts not showing in M2 orders when using V2 endpoints

---

.circleci/config.yml
Test/scripts/ci-integration.sh

So https://github.com/BoltApp/bolt-magento2/pull/1133 broke our integration tests. This is because the sandbox merchant we use don't have preauth enabled. Originally I wanted to revert the PR but I decided to just set is_pre_auth to 0 in the script. Also change integration tests to run for every commit. A successful run only takes about 10 minutes, which is a not a long time.
#changelog Fix integration tests

[MA-572] Fix integration tests

---

Helper/Api.php
Helper/SSOHelper.php
Test/Unit/Helper/SSOHelperTest.php

Turns out exchangeToken wasn't really working. Changing it so it does.
#changelog Fix exchangeToken

Fix exchangeToken

---

view/frontend/templates/checkout/success.phtml

TooldToday:
_One issue that we noticed today, not sure if it’s something with Bolt or not, but when an order is being placed and you land on the order success page, the minicart still holds the items in the cart, but when you click on the mini-cart it shows empty cart… 
I would assume Bolt should clear the minicart…._
Fixes: https://boltpay.atlassian.net/browse/ON-588
#changelog ON-588 - order success page not refreshing minicart fix

ON-588 - order success page not refreshing minicart fix

---

Helper/Cart.php
Test/Unit/BoltTestCase.php
Test/Unit/Helper/CartTest.php

Wrong customer group assigned to the customer on backoffice order after group change and Bolt modal reopening 
Fixes: https://boltpay.atlassian.net/browse/M2P-470
#changelog M2P-470 backoffice customer group fix

M2P-470 backoffice customer group fix

---

Model/Api/UpdateDiscountTrait.php
Test/Unit/Model/Api/UpdateDiscountTraitTest.php
ThirdPartyModules/Aheadworks/Giftcard.php
ThirdPartyModules/Amasty/GiftCard.php
ThirdPartyModules/Amasty/GiftCardAccount.php
ThirdPartyModules/Magento/GiftCardAccount.php
ThirdPartyModules/Mageplaza/GiftCard.php

If the filter return false, it means we do not support this type of gift card, and if the exception object is returned, we need to report it to the Bolt server. 
Fixes: https://boltpay.atlassian.net/browse/M2P-474
#changelog Exception handling for filter filterApplyingGiftCardCode

M2P-474 Exception handling for filter filterApplyingGiftCardCode

---

Model/Api/UpdateDiscountTrait.php
Test/Unit/Model/Api/UpdateDiscountTraitTest.php
ThirdPartyModules/Aheadworks/Giftcard.php
ThirdPartyModules/Amasty/GiftCard.php
ThirdPartyModules/Amasty/GiftCardAccount.php
ThirdPartyModules/Magento/GiftCardAccount.php
ThirdPartyModules/Mageplaza/GiftCard.php

If the filter return false, it means we do not support this type of gift card, and if the exception object is returned, we need to report it to the Bolt server.
Fixes: https://boltpay.atlassian.net/browse/M2P-475
#changelog Exception handling for filter filterRemovingGiftCardCode

M2P-475 Exception handling for filter filterRemovingGiftCardCode

---

Model/Api/CreateOrder.php

Currently, there is an issue that causes every create_order hooks to always skip the shipping validation. 
This PR is to set the default returned value to false for filterSkipValidateShippingForProcessNewOrder to correct the pre-auth shipping validation logic.
#changelog Set default returned value to false for filterSkipValidateShippingForProcessNewOrder

Set default returned value to false for filterSkipValidateShippingForProcessNewOrder

---

Observer/TrackingSaveObserver.php
Test/Unit/Observer/TrackingSaveObserverTest.php

Fix formatting issue for when the tracksaveobserver recieves a dropdown style track number and/or carrier code object instead of a string from the observer event. This is causing hail errors due to the plugin passing improperly formatted data. We just return the value of the first field that was selected.
Fixes: (link Jira [ticket](https://boltpay.atlassian.net/browse/M2P-356))
#changelog M2 p 356 fix tracking number format

M2P-356 fix tracking number format

---

Model/Api/Data/DebugInfo.php
Model/Api/Debug.php
Test/Unit/BoltTestCase.php
Test/Unit/Helper/CartTest.php
Test/Unit/Model/Api/DebugTest.php

For getAutomatedTestingConfig, log the error instead of returning it. Also remove the last of skipTestInUnitTestsFlow.
#changelog Log instead of returning error

Log instead of returning error

---

Model/Api/Data/ShippingOptions.php
Model/Api/Data/ShippingTax.php

For the universal api the modal would fail to fetch shipping information when using joint shipping and tax. This was because the universal api formats its response using `json_encode` and the `ShippingOptions` object used by the joint shipping and tax method did not extend `\JsonSerializable`. Same is true of the `ShippingTax` class.
Fixes: no jira ticket
#changelog Fixes joint shipping and tax by adding json serialization

Fixes joint shipping and tax by adding json serialization

---

Test/Unit/Model/Api/CreateOrderTest.php
Test/Unit/TestUtils.php

Use integration test instead of unit test for all methods in class  Mode/Api/CreateOrderTest
#changelog Use integration test instead of unit test for all methods in class  Mode/Api/CreateOrderTest

Use integration test instead of unit test for all methods in class  Mode/Api/CreateOrderTest

---

Block/Checkout/Cart/ComponentSwitcherProcessor.php
Model/EventsForThirdPartyModules.php
Model/ThirdPartyEvents/FiltersCartTotalsLayout.php
Model/ThirdPartyEvents/FiltersMinicartAddonsLayout.php
Test/Unit/Block/Checkout/Cart/ComponentSwitcherProcessorTest.php
Test/Unit/ThirdPartyModules/Amasty/StoreCreditTest.php
Test/Unit/ThirdPartyModules/Magento/CustomerBalanceTest.php
Test/Unit/ThirdPartyModules/Magento/RewardTest.php
Test/Unit/ViewModel/MinicartAddonsTest.php
ThirdPartyModules/Amasty/StoreCredit.php
ThirdPartyModules/Magento/CustomerBalance.php
ThirdPartyModules/Magento/Reward.php
ViewModel/MinicartAddons.php
etc/adminhtml/system.xml
view/frontend/layout/checkout_cart_index.xml
view/frontend/templates/checkout/minicart_addons.phtml

To support store credit / reward points modules, we need to alter the shopping cart page layout by adding the user interface blocks for applying the credit / points to the order.
How it was done so far is by first adding them to `view/frontend/layout/checkout_cart_index.xml` and then checking and removing them in Layout Processor pipeline if not needed.
This solution optimizes the process by deferring the processing to ThirdPartyModule event handler so we only update the layout if the module is present and active.
Fixes: https://boltpay.atlassian.net/browse/M2P-503
#changelog store credit / reward points modules support - update shopping cart layout only when the module is active

M2P-503 - store credit / reward points modules support - update shopping cart layout only when the module is active

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

Fix the issue that Bolt cart does not collect free shipping coupon
Fixes: https://boltpay.atlassian.net/browse/M2P-502
#changelog Bugfix: Bolt cart does not collect free shipping coupon

M2P-502 Bugfix: Bolt cart does not collect free shipping coupon

---

Helper/Cart.php
Test/Unit/BoltTestCase.php
Test/Unit/Helper/CartTest.php
etc/frontend/sections.xml

If the cart persistence is allowed there are some edge cases where cart remains active after the customer browser session ends and if another customer logs in afterwards from the same browser it can “inherit” previous customer’s cart.
More context here https://docs.magento.com/user-guide/sales/cart-persistent-workflow.html
My suspicion is that something like this happened with RTA store. We patched it up but were not sure about the root cause.
The solution to address the above case is to add customer id to our cart cache identifier and to invalidate cart sections on customer log in. 
Fixes: https://boltpay.atlassian.net/browse/M2P-489
#changelog M2P-489 - Persistent cart support

M2P-489 - Persistent cart support

---

Observer/TrackingSaveObserver.php
Test/Unit/Observer/TrackingSaveObserverTest.php

We use some trick to know if the track just created or not.
If the track isn't just created we do not send it to the server, because it means we already sent it before.
But this trick works for Magento >=2.3.1 only
Before this comment, https://github.com/magento/magento2/commit/2307e16105e031c0826d218cf81ffe7949191a0b Magento in `Sales/Model/ResourceModel/Order/Shipment/Relation::processRelation` uses trackcollection to go over tracks when it saves shipment.
Trackcollection updates all tracks when it getIterator, so we have no way to know if the object from observer is new or not.
In this case, we can just send the track to bolt, it's not a very big deal, actually bolt server does nothing when it receives a duplicate track.
Fixes: [ON-425](https://boltpay.atlassian.net/browse/ON-425) …

ON-425 Do not check if track new for magento <2.3.1

---

Block/Js.php

An error occurred when trying to enable order tracking for The RTA Store's staging environment where $blockAlreadyShown could not be accessed. The issue here was that it couldn't access this variable in the private scope and it required the protected scope.
Fixes: (https://boltpay.atlassian.net/browse/M2P-515)
#changelog M2P-515 - Switch $blockAlreadyShown to protected scope
- Changed $blockAlreadyShown to have protected scope

M2P-515 - Switch $blockAlreadyShown to protected scope

---

Plugin/Zonos/DutyTax/Model/Carrier/ZonosPlugin.php
etc/di.xml

For each method of Zonos shipping, the Zonos plugin would add an unique identifier at the end of the service id in order to retrieve the correct quote, the generation of this unique identifier is based on the address data and the related quote id. Due to the logic in the Bolt checkout, the quote in shipping step is different from the one in order creation, so the identifier key of selected Zonos shipping method changes, and Magento throws out such an exception **The shipping method is missing.**.
To fix this issue, create a plugin function to replace the quote id with its Bolt parent quote id when generating unique identifier.
Fixes: https://boltpay.atlassian.net/browse/ON-683
#changelog Add support for Zonos custom shipping
Please validate that you have tested your change in at least one …

ON-683 Add support for Zonos custom shipping

---

view/frontend/templates/js/replacejs.phtml

Subscribing to billing address change and creating a new order token for the updated billing address. Also using cartBarrier instead of BoltState.boltcart for configure call to make sure we have the latest cart values.
Fixes: [M2P395](https://boltpay.atlassian.net/browse/M2P-395) - Billing address is invalid if it was created or changed on native checkout page
#changelog (WIP)[M2P395] Billing address is invalid if it was created or changed on native checkout page

[M2P395] Billing address is invalid if it was created or changed on native checkout page

---

view/frontend/templates/js/replacejs.phtml

More details in Jira Ticket. Summary is that we would like to reload the Magento 2 cart when the user exits the checkout modal without completing checkout. Currently this is achieved using a callback from the M2 Admin, but it would be preferable if the plugin handles this. This change adds a cart reload line to the non-success portion of the modal's close handler. This is triggered when the user exits using either the X-close-button or ESC.
Fixes: https://boltpay.atlassian.net/browse/M2P-497
#changelog Reload Magento Cart after checkout exit (M2P-497) 

Reload Magento Cart after checkout exit (M2P-497) 

---

Block/Js.php
Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Test/Unit/Block/JsProductPageTest.php
Test/Unit/Block/JsTest.php
view/frontend/templates/js/boltjs.phtml
view/frontend/templates/js/replacejs.phtml

Some merchant claim that bolt script affect their side speed.
So we implement the following logic under feature switch M2_LOAD_CONNECT_JS_ON_SPECIFIC_PAGE (disabled by default):
1. Fetch connect.js on page load only under the one of the following conditions:
1) On the cart page
2) On the product page and PPC is enabled
2. If on product page, PPC is disabled and mini cart support is enabled, then we dynamically load connect.js under the one of the following conditions:
1) The cart contains any item.
2) The cart is empty, and the customer add product to the cart.
Fixes: https://boltpay.atlassian.net/browse/M2P-518
#changelog Postpone connect.js load when possible

M2P-518 Postpone connect.js load when possible

---

Test/Unit/Model/Api/GetAccountTest.php

Use integration test instead of unit test for all methods in class Mode/Api/GetAccountTest
#changelog Use integration test instead of unit test for all methods in class Mode/Api/GetAccountTest

Use integration test instead of unit test for all methods in class Mode/Api/GetAccountTest

---

Api/DebugInterface.php
Helper/Config.php
Model/Api/Debug.php
Model/Api/UniversalApi.php
Test/Unit/Helper/ConfigTest.php
Test/Unit/Model/Api/UniversalApiTest.php
etc/adminhtml/system.xml
etc/config.xml

Add a universal debug endpoint which can be enabled/disabled by the merchant to be used later by a sync job.
Fixes: [MA-565](https://boltpay.atlassian.net/browse/MA-565)
#changelog [MA-565] Add an empty Debug to Universal API 
Add a debug event into the universal api endpoint which returns null until implemented

[MA-565] Add an empty Debug to Universal API 

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php
view/frontend/templates/button_product_page.phtml

Fix bug: Unable to purchase the downloadable product with mandatory options
Fixes: https://boltpay.atlassian.net/browse/M2P-528
#changelog M2P-528 Fix bug: Unable to purchase downloadable product with mandatory options

M2P-528 Fix bug: Unable to purchase downloadable product with mandatory options

---

view/frontend/templates/js/replacejs.phtml

When working for the task https://boltpay.atlassian.net/browse/M2P-254, I found that on the checkout page, especially the payment step, the page always stuck on the loading screen. After investigation, it is because each payment has its own billing fields, and with the specific theme and some payment gateways, the callback monitorAttributesChange (https://github.com/BoltApp/bolt-magento2/blob/2.20.0/view/frontend/templates/js/replacejs.phtml#L1389) is triggered repeatedly and result in infinite loop.
Solution: Only trigger the callback for specific elements related to Bolt.
Fixes: https://boltpay.atlassian.net/browse/M2P-536
#changelog Bugfix: Infinite loop on checkout page

M2P-536 Bugfix: Infinite loop on checkout page

---

Api/Data/ShipToStoreOptionInterface.php
Api/Data/ShippingDataInterface.php
Api/Data/StoreAddressInterface.php
Api/Data/TaxDataInterface.php
Model/Api/Data/ShipToStoreOption.php
Model/Api/Data/ShippingData.php
Model/Api/Data/StoreAddress.php
Model/Api/Data/TaxData.php
Test/Unit/Model/Api/Data/ShipToStoreOptionTest.php
Test/Unit/Model/Api/Data/ShippingDataTest.php
Test/Unit/Model/Api/Data/StoreAddressTest.php
Test/Unit/Model/Api/Data/TaxDataTest.php
etc/di.xml

As we decide to add support BOPIS Spilt shipping to M2, and In-store delivery method is supported with version 2.4.0 of Magento (https://devdocs.magento.com/guides/v2.4/inventory/release-notes.html#v120) , this PR is for adding support for this feature.
Step 1 : Create/Update related api data interfaces and classes.
Fixes: https://boltpay.atlassian.net/browse/M2P-537
#changelog Add support for Magento native In-Store Pickup step 1

M2P-537 Add support for Magento native In-Store Pickup step 1

---

Model/Api/Shipping.php
Model/Api/ShippingTax.php
Model/Api/ShippingTaxContext.php
Model/Api/Tax.php
Model/EventsForThirdPartyModules.php
Test/Unit/Model/Api/ShippingTaxContextTest.php
Test/Unit/Model/Api/ShippingTest.php
Test/Unit/Model/Api/TaxTest.php
ThirdPartyModules/Magento/InStorePickupShipping.php

As we decide to add support BOPIS Spilt shipping to M2, and In-store delivery method is supported with version 2.4.0 of Magento (https://devdocs.magento.com/guides/v2.4/inventory/release-notes.html#v120) , this PR is for adding support for this feature.
Step 2 : Add in-store pickup options to split shipping endpoint if they are available.
Fixes: https://boltpay.atlassian.net/browse/M2P-537
#changelog Add support for Magento native In-Store Pickup step 2

M2P-537 Add support for Magento native In-Store Pickup step 2

---

Model/Api/Tax.php

This is because for virtual cart, the split tax api hook does not send any shipping_option or ship_to_store_option, for this case, we should not call setShippingOption or setShipToStoreOption for setting shipping info to the response, instead the response just returns "shipping_option":null,"ship_to_store_option":null
Tested with Magento v2.4.1-p1/v2.3.5/v2.2.2
Fixes: https://boltpay.atlassian.net/browse/M2P-549
#changelog Bugfix: Tax endpoint error when the cart is  virtual

M2P-549 Bugfix: Tax endpoint error when the cart is  virtual

---

Test/Unit/Model/Api/ShippingTaxContextTest.php

Use integration test instead of unit test for all methods in class Mode/Api/ShippingTaxContextTest.php
Fixes: https://boltpay.atlassian.net/browse/M2P-542
#changelog M2P-542 Use integration test instead of unit test for all methods in class Mode/Api/ShippingTaxContextTest.php

M2P-542 Use integration test instead of unit test for all methods in class Mode/Api/ShippingTaxContextTest.php

---

Model/Api/ShippingMethods.php

Refer to the task https://boltpay.atlassian.net/browse/EN-4217 for contexts, and for v1 shipping&tax endpoint, we load immutable quote into checkout session and get shipping and tax options, but usually the immutable quote in not active, if any other plugins try to call
`$this->quoteRepository->getActive($this->checkoutSession->getQuoteId());`
it would cause an error No such entity with cartId = xxx
Solution: Load parent quote instead of immutable quote into the checkout session, as same as we do for split shipping tax endpoint.
Fixes: https://boltpay.atlassian.net/browse/M2P-541
#changelog Bugfix: No such entity with cartId

M2P-541 Bugfix: No such entity with cartId

---

Test/Unit/Model/Api/UniversalWebhookTest.php

Use integration test instead of unit test for all methods in class Model/Api/UniversalWebhookTest
Fixes: https://boltpay.atlassian.net/browse/M2P-552
#changelog M2P-552 Use integration test instead of unit test for all methods in class Model/Api/UniversalWebhookTest

M2P-552 Use integration test instead of unit test for all methods in class Model/Api/UniversalWebhookTest

---

Test/Unit/Cron/DeleteOldWebHookLogsTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Cron\DeleteOldWebHookLogsTest
Fixes: https://boltpay.atlassian.net/browse/M2P-557
#changelog ON-386 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Cron\DeleteOldWebHookLogsTest

M2P-557 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Cron\DeleteOldWebHookLogsTest

---

Helper/Config.php
Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Helper/Order.php
Test/Unit/Helper/CartTest.php
Test/Unit/Helper/ConfigTest.php
Test/Unit/Helper/OrderTest.php
Test/Unit/ViewModel/OrderCommentTest.php
ViewModel/OrderComment.php
etc/adminhtml/system.xml
view/adminhtml/layout/sales_order_view.xml
view/adminhtml/templates/order/comment.phtml

Passing the order note to whatever field is configured. Defaults to customer_note.
Adding a Order Comment section to the admin order view.
Fixes: https://boltpay.atlassian.net/browse/M2P-388
#changelog Custom Order Note field support

Custom Order Note field support

---

Helper/AutomatedTesting.php
Test/Unit/Helper/AutomatedTestingTest.php

fix tax for cart (make it a priceproperty object instead of a string) i need it to properly merge json with storeconfig for integration tests
https://boltpay.atlassian.net/browse/MA-709
#changelog MA-709: fix the M2 config generation type name mismatch
- [] Bug fix (change which fixes an issue)

MA-709: fix the M2 config generation type name mismatch

---

Plugin/SalesRuleActionDiscountPlugin.php
Plugin/SalesRuleModelUtilityPlugin.php
Test/Unit/Plugin/SalesRuleActionDiscountPluginTest.php
Test/Unit/Plugin/SalesRuleModelUtilityPluginTest.php
etc/di.xml

If the unit price of cart item is zero, the discount amount of this item is zero too. In the Magento core, after calculating sale rule on the item, it would do some extra fixes on the discount data, such as eventFix, deltaRoundingFix and minFix (refer to https://github.com/magento/magento2/blob/7c6b6365a3c099509d6f6e6c306cb1821910aab0/app/code/Magento/SalesRule/Model/RulesApplier.php#L238), so the solution to fix this issue is saving discount info after minFix.
Fixes: https://boltpay.atlassian.net/browse/EN-4540
#changelog Bugfix: Fixed amount discount errors

Bugfix: Fixed amount discount errors

---

view/frontend/templates/js/replacejs.phtml

When the customer adds the item to the product page, the Bolt checkout button on the minicart is loaded for the first time and it triggers the onElementReady event to initiate BoltCheckout properly(https://github.com/BoltApp/bolt-magento2/blob/2.21.0/view/frontend/templates/js/replacejs.phtml#L1183).
Now we only add the selector of v1 button to bolt_button_selector (https://github.com/BoltApp/bolt-magento2/blob/2.21.0/view/frontend/templates/js/replacejs.phtml#L449), that's why v2 button does not load. To fix it, we just need to add the selector [data-tid="instant-bolt-checkout-button"] of v2 button.
Fixes: https://boltpay.atlassian.net/browse/M2P-571
#changelog Bugfix: Bolt checkout button v2 doesnot work on minicart …

M2P-571 Bugfix: Bolt checkout button v2 doesnot work on minicart

---

Test/Unit/Model/ResourceModel/CustomerCreditCardTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\ResourceModel\CustomerCreditCardTest
Fixes: https://boltpay.atlassian.net/browse/M2P-565
#changelog M2P-565 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\ResourceModel\CustomerCreditCardTest

M2P-565 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\ResourceModel\CustomerCreditCardTest

---

Test/Unit/Model/ResourceModel/FeatureSwitchTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\ResourceModel\FeatureSwitchTest
Fixes: https://boltpay.atlassian.net/browse/M2P-567
#changelog M2P-566 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\ResourceModel\FeatureSwitchTest

M2P-567 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\ResourceModel\FeatureSwitchTest

---

Helper/Api.php
Helper/Cart.php
Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Observer/OrderSaveObserver.php
Test/Unit/Helper/CartTest.php
Test/Unit/Observer/OrderSaveObserverTest.php
Test/Unit/TestUtils.php
etc/events.xml

* We'd like for order/cart information to be in sync between M2 and Bolt, even post-purchase. See [this spec](https://docs.google.com/document/d/1BcV_yGw2Itk0Q_T4xaiTbG_ppliC_cZ87kP_PlIyvXI/edit#heading=h.cunzcjjb9kz).
* We listen to the `sales_order_save_after` to invoke this functionality. This event triggers, for example, when refunds are issued. There are also paid plugins that allow order items to be added or edited.
* The functionality is gated behind a feature switch.
#changelog Update orders in Bolt when orders are saved

[Orders] Update orders on Bolt when orders are edited on the plugin side

---

Test/Unit/Model/ResourceModel/ExternalCustomerEntityTest.php

M2P-566 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\ResourceModel\ExternalCustomerEntityTest
Fixes: https://boltpay.atlassian.net/browse/M2P-566
#changelog M2P-566 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\ResourceModel\ExternalCustomerEntityTest

M2P-566 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\ResourceModel\ExternalCustomerEntityTest

---

Plugin/OrderPlugin.php
Test/Unit/Plugin/OrderPluginTest.php

In some contexts, when the create_order hook (thread 1) takes a lot of time to execute and returns a timeout, the authorize/payment hook (thread 2) is sent to Magento. It updates the order prior to the create_order hook (thread 1) process and change order status to processing. Then the create_order hook (thread 1) could change the order status back to pending payment which is unexpected behavior.
This PR is to compare previous status with new status and prevent such a behavior.
Fixes: https://boltpay.atlassian.net/browse/M2P-544
#changelog Bugfix: order status moves from processing back to pending payment

M2P-544 Bugfix: order status moves from processing back to pending payment

---

Test/Unit/Plugin/OrderPluginTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Plugin\OrderPluginTest
Fixes: https://boltpay.atlassian.net/browse/M2P-574
#changelog M2P-574 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Plugin\OrderPluginTest

M2P-574 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Plugin\OrderPluginTest

---

Test/Unit/Model/ResourceModel/WebhookLogTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\ResourceModel\WebhookLogTest
Fixes: https://boltpay.atlassian.net/browse/M2P-569
#changelog M2P-569 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\ResourceModel\WebhookLogTest

M2P-569 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\ResourceModel\WebhookLogTest

---

Api/OAuthRedirectInterface.php
Model/Api/OAuthRedirect.php
Test/Unit/Model/Api/OAuthRedirectTest.php

We pass the order reference to the plugin when doing an OAuth login for Bolt SSO,
which should be used as a quote ID. Use this to fetch and update the customer
attributes for the order. In case the OAuth login happens during checkout but
before the order is placed, we look up the quote and update the attributes on
both the parent quote and any descendent immutable quotes so that when the order
is created, it is created on behalf of the newly logged-in customer.
#changelog Associate both orders and quotes with logged-in customer
Please validate that you have tested your change in at least one of the following …

Associate both orders and quotes with logged-in customer

---

Helper/CustomFieldsHandler.php
Test/Unit/Helper/CustomFieldsHandlerTest.php

Flips `in_array` args.
Test case added for unit tests. Fails when I flipped the arguments back around.
Fixes: https://boltpay.atlassian.net/browse/M2P-587
#changelog WIP [M2P-587] Flips in_array args to be correct

[M2P-587] Flips in_array args to be correct

---

Test/Unit/Plugin/SalesRuleQuoteDiscountPluginTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Plugin\SalesRuleQuoteDiscountPluginTest
Fixes: https://boltpay.atlassian.net/browse/M2P-584
#changelog M2P-584 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Plugin\SalesRuleQuoteDiscountPluginTest

M2P-584 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Plugin\SalesRuleQuoteDiscountPluginTest

---

Model/Api/Tax.php
Test/Unit/Model/Api/TaxTest.php

For split shipping and tax, we do not calculate the shipping discount if the coupon has **Apply to Shipping Amount** enabled, as a result, the order creation fails due to the total mismatch error.
Solution: In the tax endpoint, we have selected shipping option, then we can calculate shipping discount and return updated shipping cost.
Fixes: https://boltpay.atlassian.net/browse/M2P-583
#changelog Bugfix: shipping coupon not applying

M2P-583 Bugfix: shipping coupon not applying

---

Test/scripts/ci-integration.sh

Integration tests use newer m2 images with smaller DB dumb after https://github.com/BoltApp/integration-tests/pull/2859.
If this PR doesn't fix m2 ci tests @njfaries please close it and merge https://github.com/BoltApp/integration-tests/pull/2900 which recovers original SQL dump
#changelog Use newer db dump for tests

Integration tests - Update sql db for tests

---

Block/Js.php
view/adminhtml/templates/boltpay/js/replacejs.phtml

Root cause : from magento 2.4.x, some behaviors of creating backoffice order changes: 
1. In the step "select a customer", there is already a quote created and its billing&shipping address are both created as well, all the fields of shipping address are null expect "same_as_billing" and its value is true by default. 
2. Therefore, the js variable shippingAsBilling is set to true (link to related code [order.disableShippingAddress(true);](https://github.com/magento/magento2/blob/2.4.0/app/code/Magento/Sales/view/adminhtml/templates/order/create/form/address.phtml#L139)and [disableShippingAddress: function](https://github.com/magento/magento2/blob/2.4.0/app/code/Magento/Sales/view/adminhtml/web/order/create/scripts.js#L379))
3. On the other hand, when processing to order creation form, the …

M2P-596 Bugfix: shipping address of backoffice order is overridden by billing address

---

Model/EventsForThirdPartyModules.php
ThirdPartyModules/SomethingDigital/InStorePickupBoltIntegration.php

Implement separate "buy online" and "pick up in stores" options for Muji 
See the demo screenshot: https://prnt.sc/138ew1f 
Fixes: https://boltpay.atlassian.net/browse/M2P-548
#changelog Adds support for SomethingDigital_InStorePickupBoltIntegration and Magedelight_Storepickup

M2P-548 Adds support for SomethingDigital_InStorePickupBoltIntegration and Magedelight_Storepickup

---

Test/Unit/Block/Checkout/ComponentSwitcherProcessorTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Block\Checkout\ComponentSwitcherProcessorTest
#changelog Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Block\Checkout\ComponentSwitcherProcessorTest

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Block\Checkout\ComponentSwitcherProcessorTest

---

Helper/CustomFieldsHandler.php
Test/Unit/Helper/CustomFieldsHandlerTest.php

Farm & Home supply reported that custom fields where `subscribe to newsletter` feature was enabled did not trigger newsletter subscription logic in M2. Upon investigation, we found that we look for `subscribe_to_platform_newsletter` in custom fields payload. This is incorrect we should be looking for `subscribe_to_newsletter` instead.
The [spec](https://docs.google.com/document/d/1SrxeAf5ISwhEsWx7-Je_JJJp7GXjqCMR1fA54dfk5Fs/edit#) is here.
#changelog Custom Fields: Fix newsletter feature flag name

Custom Fields: Fix newsletter feature flag name

---

Block/Js.php
Helper/Config.php
Test/Unit/Block/JsTest.php
Test/Unit/Helper/ConfigTest.php
etc/adminhtml/system.xml
etc/config.xml
view/frontend/templates/js/boltglobaljs.phtml

Currently the additionalJS field only injects on pages where BoltCheckout can appear. This will let us globally inject JS to deal with things like errant buttons or fields.
Fixes: https://boltpay.atlassian.net/browse/M2P-575
#changelog Create global JS field for injecting JS on all Magento pages

M2P-575 Create global JS field for injecting JS on all Magento pages

---

ThirdPartyModules/Magento/InStorePickupShipping.php

When converting pickup location data and quote shipping address to Pickup Location Quote Address, it does not include phone info, so we need to add this field separately.
Fixes: https://boltpay.atlassian.net/browse/M2P-612
#changelog Bugfix: unable to checkout for BOPIS using Bolt PPC

M2P-612 Bugfix: unable to checkout for BOPIS using Bolt PPC

---

Helper/Cart.php
Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Model/Api/CreateOrder.php
Test/Unit/Helper/CartTest.php

Some (custom) themes, and the theme this merchant is using is heavily customized, as well as the whole store, don't verify the item integrity and allow showing of the checkout button on the shopping cart page even if not all options are selected for some of the products. In conjunction with (presumed) pre-auth timeout (Bolt acts like it had succeeded), this may result in crating the order on Bolt end but failing hooks and no (orphaned) order created in Magento.
This PR adds pre-check in plugin before order request is sent to Bolt and prevents the request if some mandatory options are not chosen. The feature switch is added and set to on by default.
Fixes: https://boltpay.atlassian.net/browse/M2P-570
#changelog M2P-570 - Don't create carts for quotes with error
Please validate that you …

M2P-570 - Don't create carts for quotes with error

---

Test/Unit/Model/FeatureSwitchTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\FeatureSwitchTest.
Fixes: https://boltpay.atlassian.net/browse/M2P-621
#changelog M2P-621 Use integration test instead of unit test for  all methods in class Bolt\Boltpay\Test\Unit\Model\FeatureSwitchTest

M2P-621 Use integration test instead of unit test for  all methods in class Bolt\Boltpay\Test\Unit\Model\FeatureSwitchTest

---

Test/Unit/Model/ExternalCustomerEntityTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\ExternalCustomerEntityTest
Fixes: https://boltpay.atlassian.net/browse/M2P-623
#changelog M2P-623 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\ExternalCustomerEntityTest

M2P-623 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\ExternalCustomerEntityTest

---

Model/Api/CreateOrder.php

When multi currencies are enabled in M2 store, the function getPrice just returns price of base currency while getCalculationPrice returns actual price of current currency. So we need to use getCalculationPrice instead
Fixes: https://boltpay.atlassian.net/browse/FP-746
#changelog Bugfix: item price mismatch error when checkout with non-usd currency

FP-746 Bugfix: item price mismatch error when checkout with non-usd currency

---

Helper/Order.php
Test/Unit/Helper/OrderTest.php

Create a new filed `token_type` in the AdditionalInformation of payment, so the merchant can read it to determine what APM the order went through. For its value, the plugin retrieves $transaction->from_credit_card->token_type by default, and if $transaction->from_credit_card->token_type does not exist, we use $transaction->processor instead.
Fixes: https://boltpay.atlassian.net/browse/FP-751
#changelog FP-751 Add token_type to payment data

FP-751 Add token_type to payment data

---

Controller/ReceivedUrlTrait.php
Helper/Cart.php
Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Helper/Order.php
Test/Unit/Controller/Order/ReceivedUrlTest.php
Test/Unit/Controller/ReceivedUrlTraitTest.php

With pre-auth, the payment info is passed back to Magento and order updated in a hook that happens after the checkout.
In this PR we do it in the checkout redirect process.
Fixes: https://boltpay.atlassian.net/browse/EN-4862
#changelog EN-4862 - Get the Last 4 card digits in the checkout success event

EN-4862 - Get the Last 4 card digits in the checkout success event

---

Plugin/ClassyLlama/AvaTax/Plugin/Model/ResourceModel/ExtensionAttributesPersistencePluginPlugin.php
Test/Unit/Plugin/ClassyLlama/AvaTax/Plugin/Model/ResourceModel/ExtensionAttributesPersistencePluginPluginTest.php
etc/di.xml

**What happens?**
After an order was placed, during order management webhook when we attempt to load the newly created order, the loaded collection receives two identical orders from the database instead of one, which shouldn’t be possible so the whole process fails.
**Why it happens?**
Avatax adds an extension attribute, https://github.com/avadev/Avalara-AvaTax-for-Magento2/blob/master/etc/extension_attributes.xml#L41 for Orders called avatax_response that is stored inside avatax_sales_order table. This extension attribute gets loaded automatically when loading Orders by adding a JOIN SQL directive that references the external table. During that process we discover that there are two entries related to the same Order ID in that external table, causing the query to return two rows instead …

Fix issues with avatax_sales_order table

---

Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Helper/Order.php
Model/Api/ShippingMethods.php
Test/Unit/Helper/OrderTest.php

M2P-609 - Save customer_firstname, customer_lastname in sales_order table
For the logged in customer it is done automatically by Magento by copying the data from customer billing address.
This PR does it for guests.
Fixes: https://boltpay.atlassian.net/browse/M2P-609
#changelog M2P-609 - Save customer_firstname, customer_lastname in sales_order table

M2P-609 - Save customer_firstname, customer_lastname in sales_order table

---

Test/Unit/Plugin/MageVision/FreeShippingAdmin/MethodPluginTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Plugin\MageVision\FreeShippingAdmin\MethodPluginTest
Fixes: https://boltpay.atlassian.net/browse/M2P-629
#changelog M2P-629 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Plugin\MageVision\FreeShippingAdmin\MethodPluginTest

M2P-629 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Plugin\MageVision\FreeShippingAdmin\MethodPluginTest

---

Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Helper/Order.php
Test/Unit/Helper/OrderTest.php

Create feature switch for saving the customer credit card when the pending hook is sent to Magento
#changelog Create feature switch for saving the customer credit card when the pending hook is sent to Magento

Create feature switch for saving the customer credit card when the pending hook is sent to Magento

---

Model/Api/Tax.php
Model/EventsForThirdPartyModules.php
ThirdPartyModules/MageWorld/RewardPoints.php

Fix mismatch total amount issue if customers redeem their maximum reward points when enabling split shipping and tax
Fixes: https://boltpay.atlassian.net/browse/EN-4706
#changelog EN-4706 Fix mismatch total amount issue if customers redeem their maximum reward points when enabling split shipping and tax

EN-4706 MW_RewardPoints: Fix mismatch total amount issue if customers redeem their maximum reward points when enabling split shipping and tax

---

Helper/Cart.php
Model/Api/CreateOrder.php
Model/Api/ShippingMethods.php
Model/Api/ShippingTax.php
Test/Unit/Helper/CartTest.php

1. Add validation on the stock status of cart items for legacy shipping&tax api endpoint and separate shipping&tax api endpoint.
2. Add validation on the stock status of quote items before order creation, so the plugin can respond with proper error code if any specific exception related to stock status.
Fixes: https://boltpay.atlassian.net/browse/MA-688
#changelog Improve error message for out of stock item

MA-688 Improve error message for out of stock item

---

Block/Js.php
Helper/Config.php
Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Test/Unit/Block/JsTest.php
view/frontend/templates/js/boltjs.phtml
view/frontend/templates/js/replacejs.phtml

add track.js to each page of the site
add feature switch M2_DISABLE_TRACK_ON_HOME_PAGE (disabled by default) that remove track.js from main page of the site
add feature switch M2_DISABLE_TRACK_ON_NON_BOLT_PAGES (disabled by default). With this feature switch, we include track.js only on pages where we have connect.js (actually the same as we have now)
Fixes: https://boltpay.atlassian.net/browse/M2P-636
#changelog Conditionally load trackjs

M2P-636 Conditionally load trackjs

---

Test/Unit/Block/Checkout/Cart/ComponentSwitcherProcessorTest.php

M2P-590 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Block\Checkout\Cart\ComponentSwitcherProcessorTest
Fixes: https://boltpay.atlassian.net/browse/M2P-590
#changelog M2P-590 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Block\Checkout\Cart\ComponentSwitcherProcessorTest

M2P-590 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Block\Checkout\Cart\ComponentSwitcherProcessorTest

---

Test/Unit/Model/CustomerCreditCardTest.php
Test/Unit/TestUtils.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\CustomerCreditCardTest
Fixes: https://boltpay.atlassian.net/browse/M2P-621
#changelog M2P-621 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\CustomerCreditCardTest

M2P-621 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\CustomerCreditCardTest

---

Test/Unit/Cron/DeactivateQuoteTest.php

M2P-556 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Cron\DeactivateQuoteTest
Fixes: https://boltpay.atlassian.net/browse/M2P-556
#changelog M2P-556 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Cron\DeactivateQuoteTest

M2P-556 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Cron\DeactivateQuoteTest

---

Test/scripts/ci-integration.sh

#changelog CI - fix nodejs version for integration tests
Fix nodejs error for `integration-php72-magento23`. node 10 -> 14

CI - fix nodejs version for integration tests

---

Model/Api/DiscountCodeValidation.php
Model/Api/UpdateCart.php
Model/Api/UpdateCartCommon.php
Test/Unit/Model/Api/DiscountCodeValidationTest.php
Test/Unit/Model/Api/UpdateCartCommonTest.php

Root cause: we do not set billing address for virtual quote while virtual cart item is handled as physical
Fixes: https://boltpay.atlassian.net/browse/M2P-661
#changelog Bugfix: Discount not applied to virtual quote when the feature switch M2_HANDLE_VIRTUAL_PRODUCTS_AS_PHYSICAL is enabled

M2P-661 Bugfix: Discount not applied to virtual quote when the feature switch M2_HANDLE_VIRTUAL_PRODUCTS_AS_PHYSICAL is enabled

---

Helper/Cart.php
Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Plugin/WebapiRest/Magento/Quote/Model/QuotePlugin.php
Test/Unit/Plugin/WebapiRest/Magento/Quote/Model/QuotePluginTest.php
etc/webapi_rest/di.xml

Merchant requires customer IP but we are only sending AWS IPs in our requests.
Merchant is reporting that as of 29/01/2020 they haven't received the customer IP in their DB when orders are created via Bolt.
This is a generic, although not so common, case - some 3party modules may trigger totals collection in pre-auth processing and get and store the IP from the session. This PR prevents that in our calls, leaving the initial, customer session IP in place.
Fixes: https://boltpay.atlassian.net/browse/EN-5023
#changelog Prevent overwriting quote customer IP with Bolt (AWS) one in pre-auth call

Prevent overwriting quote customer IP with Bolt (AWS) one in pre-auth call

---

Plugin/SalesRuleModelUtilityPlugin.php
Test/Unit/Plugin/SalesRuleModelUtilityPluginTest.php

If the merchant create a cart price rule that:
1. Zero discount amount
2. No free shipping
For such a rule, M2 native cart does not calculate it in.
But when the customer apply another coupon to cart, the Bolt plugin would take the "useless" rule and apply a discount to the cart by mistake.
We need to fix this bug.
Fixes: https://boltpay.atlassian.net/browse/EN-5280
#changelog Exclude "useless" cart price rule from Bolt cart

EN-5280 Exclude "useless" cart price rule from Bolt cart

---

Helper/ArrayHelper.php
Helper/Cart.php
Helper/Session.php
Model/Api/ShippingMethods.php
Test/Unit/Helper/CartTest.php
Test/Unit/Helper/SessionTest.php
Test/Unit/TestHelper.php
ThirdPartyModules/MageWorld/Affiliate.php
ThirdPartyModules/Mageside/CustomShippingPrice.php

Externally reported issue
https://github.com/BoltApp/bolt-magento2/issues/1371
Hi,
We are upgrading our site from Magento 2.4.2-p1 to Magento 2.4.3. We are facing the issue while running the site and we got the below error.
Class Zend\Serializer\Adapter\PhpSerialize does not exist
Fixes: https://boltpay.atlassian.net/browse/M2P-666
#changelog Magento 2.4.3 support - replace Zend PhpSerialize with Magento Serializer Interface

Magento 2.4.3 support - replace Zend PhpSerialize with Magento Serialize

---

Test/Unit/Block/JsProductPageTest.php
Test/Unit/TestUtils.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Block\JsProductPageTest
Fixes: https://boltpay.atlassian.net/browse/M2P-683
#changelog M2P-683 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Block\JsProductPageTest

M2P-683 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Block\JsProductPageTest

---

Test/Unit/Helper/OrderTest.php

Use integration test instead of unit test for some methods in class Bolt\Boltpay\Test\Unit\Helper\OrderTest
Fixes: https://boltpay.atlassian.net/browse/M2P-669
#changelog Use integration test instead of unit test for some methods in class Bolt\Boltpay\Test\Unit\Helper\OrderTest

M2P-669 Use integration test instead of unit test for some methods in class Bolt\Boltpay\Test\Unit\Helper\OrderTest

---

Controller/Adminhtml/Cart/Data.php
Helper/Cart.php
Test/Unit/Controller/Adminhtml/Cart/DataTest.php
Test/Unit/Helper/CartTest.php

Actually this is a bug of M2 and it had been fixed from M2 v2.3.5 ([Related commit in M2 core](https://github.com/magento/magento2/commit/edfc05b0634f253c2cf12687d288ae8b1e62190c)).
To fix this bug in Bolt plugin, we need to register rule_data before saving quote or calculating quote totals.
This PR has been tested with M2 v2.2.9 v2.2.11 v2.3.3 v2.3.6 v2.4.2-p1
Fixes: https://boltpay.atlassian.net/browse/EN-5429
#changelog Bugfix: catalog price rule is not calculated for backoffice order

EN-5429 Bugfix: catalog price rule is not calculated for backoffice order

---

Controller/Adminhtml/Order/ReceivedUrl.php
Test/Unit/Controller/Adminhtml/Order/ReceivedUrlTest.php

If the M2 configuration field "Add Store Code to Urls" is set to Yes, a store code of default website would be added to the Url of success page which leads to a 404 page.  So if "Add Store Code to Urls" is enabled in configuration, we do not need to set scope entity for retrieving redirect Url.
Fixes: https://boltpay.atlassian.net/browse/M2P-687
#changelog Bugfix: the success page of backoffice order redirects to a 404 page

M2P-687 Bugfix: the success page of backoffice order redirects to a 404 page

---

Block/Js.php
Helper/Config.php
Test/Unit/Block/JsTest.php
Test/Unit/Helper/ConfigTest.php
etc/adminhtml/system.xml
etc/config.xml
view/frontend/templates/button.phtml
view/frontend/templates/js/replacejs.phtml

To create setting to show/hide Bolt checkout button on cart page.
The Bolt connect.js and track.js would be still loaded on the cart page with/without Bolt checkout button.
Fixes: https://boltpay.atlassian.net/browse/M2P-691
#changelog Create setting to show/hide Bolt checkout button on cart page

M2P-691 Create setting to show/hide Bolt checkout button on cart page

---

view/frontend/templates/js/boltglobaljs.phtml

This happens because HTML parser as defined by W3C is totally separated from the JavaScript parser. After the <script> tag it looks for the closing </script>, regardless that it's inside comments or strings, it treats JS code as normal text, as a result, the JS comment before the closing </script> breaks JS code when minified.
Fixes: https://boltpay.atlassian.net/browse/M2P-703
#changelog Bugfix: Js syntax error when Minify Html is enabled in production mode

M2P-703 Bugfix: Js syntax error when Minify Html is enabled in production mode

---

Helper/Cart.php

To support various types of fee/gift wrapping, we add them as cart item, but those items are not actual products in store. There is no need to validate stock state for them.
Fixes: https://boltpay.atlassian.net/browse/M2P-690
#changelog Bypass stock validation for custom cart item

M2P-690 Bypass stock validation for custom cart item

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

Currently, there is an error when placing the same single cart order twice in a row in the product page checkout. 
So this PR resolves the issue by not using cart cache if the cart’s order reference is associated with an existing order
See here: https://prnt.sc/1rpwy8b
Fixes: https://boltpay.atlassian.net/browse/M2P-688
#changelog

M2P-688 Not using the cart cache if order reference is associated with an existing order

---

Controller/Adminhtml/Cart/Data.php
Model/EventsForThirdPartyModules.php
Test/Unit/Controller/Adminhtml/Cart/DataTest.php
ThirdPartyModules/MageWorx/ShippingRules.php

When creating backoffice order, the MageWorx Shipping Rules is not applied to shipping rate and result in a shipping total mismatch error.
Root cause : Before applying the valid rules, MageWorx_ShippingRules would fetch customer group id, if param collect_shipping_rates exists in the request, it gets customer group id from quote, if not, it gets customer group id from customer session instead. For Bolt backoffice order, only the quote has proper customer group id, so we need to set param collect_shipping_rates exists.
Fixes: https://boltpay.atlassian.net/browse/M2P-694
#changelog Add support for MageWorx_ShippingRules

M2P-694 Add support for MageWorx_ShippingRules

---

Helper/Cart.php

The M2 class Magento\CatalogInventory\Model\Quote\Item\QuantityValidator\QuoteItemQtyList processes product qty from quote items and is used only in singleton mode. When its function getQty is called for item quantity validation, it would add qty to existing quote item.
For Bolt PPC, the function QuoteItemQtyList->getQty  is called twice and result in this bug if the product only has 1 in stock
1. When adding product to the empty cart created for PPC in the method Bolt\Boltpay\Helper\Cart->createCart, the item qty stored in QuoteItemQtyList  is 1.
2. When getting parent quote by the method getQuoteById in the method Bolt\Boltpay\Helper\Cart->getCartData, the item qty stored in QuoteItemQtyList becomes 2.
Actually the parent quote and immutable quote are identical in Bolt PPC, so there is …

Bugfix: Bolt PPC does not work properly with items that have a quantity of 1

---

Model/Api/UpdateCartCommon.php
Test/Unit/Model/Api/UpdateCartCommonTest.php

For the cart.update and discounts.code.apply api request, if there is shipment info in the payload, we save the address data into shipping address of quote and calculate shipping rate then. After investigation, the shipping rate calculation is unnecessary and causes this bug. So the solution is to remove the related code.
Fixes: https://app.asana.com/0/1201104538767801/1201308276077754/f
#changelog Bugfix: Discount error with specific condition of Table Rates shipping method

Bugfix: Discount error with specific condition of Table Rates shipping method

---

Helper/Order.php
Model/EventsForThirdPartyModules.php
ThirdPartyModules/Amasty/GiftCardAccount.php

From Amasty gift card 2.5.0 , their team introduces a new feature to restrict the usage of gift card by transaction and the plugin completes the transaction in the observer of event checkout_submit_all_after when the order is created successfully. But in our plugin, we do not trigger this event right after order creation, instead, we trigger it when save&update order by api hooks. At that time, the ExtensionAttributes of order does not contain any gift card info, as a result, the transaction of gift card can not be completed.
Fixes: https://app.asana.com/0/1201104538767801/1201218874560405/f
#changelog Add support for Amasty gift card 2.5.x

Add support for Amasty gift card 2.5.x

---

Plugin/ClearQuote.php

The code
`$subject->setLoadInactive(false);
$subject->replaceQuote($subject->getQuote()->save());`
in the plugin method afterClearQuote is to fix issue for specific Magento versions and causes bug with reorder functionality in M2 v2.4.0+. 
So we add conditional statement to fix this bug.
Fixes: [(link Jira ticket)](https://app.asana.com/0/951157735838091/1201324830035954/f)
#changelog Bugfix: subtotal calculation issue with reorder functionality

Bugfix: subtotal calculation issue with reorder functionality

---

Test/Unit/TestUtils.php

If we create quotes without addresses it does nothing during total calculation so total, as well as item price, will be empty.
We didn't face this before because we worked with immutable quotes. When we create an immutable quote we add addresses.
#changelog Fx empty quote creation for integration tests

Fix empty quote creation

---

Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Helper/Order.php
Test/Unit/Helper/OrderTest.php

Currently, we can't refund if an order is adjusted price mismatch. 
See the detail in this task: https://app.asana.com/0/564264490825835/1201256841759895
=> The root cause is that the grand total isn't correct in the admin new credit memo creation page. This PR is to correct the credit memo grand total by including the mismatch amount into the tax amount when adjusting price mismatch.
FYI, this logic is the same as M1 logic. See here: https://github.com/BoltApp/bolt-magento1/blob/master/app/code/community/Bolt/Boltpay/Model/Order.php#L518
Fixes: https://boltpay.atlassian.net/browse/EN-6094
#changelog EN-6094 Fix bug: Can not refund if an order is adjusted price mismatch

EN-6094 Fix bug: Can not refund if an order is adjusted price mismatch

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

The automatic discount description is shown as part of a discount tag on the Bolt modal. That discount description isn't a required field. When it's empty, the discount tag will be very indescriptive and confuse the customers.
This PR resolves the issue by using the required discount name as part of the discount tag. 
Fixes: https://app.asana.com/0/0/1201256841759895/1201384293294758/f
#changelog Use discount name instead of discount description for automatic coupons

Use discount name instead of discount description for automatic coupons

---

Helper/Cart.php
Model/Api/CreateOrder.php
Model/Api/Tax.php

Currently, customers can't place an order if they apply a coupon of 'Fixed amount discount for whole cart' and 'Apply to shipping amount'. This is because that the mismatch shipping issue. This PR fixes the issue by correcting the shipping amount calculation in the Bolt modal. 
Fixes: https://app.asana.com/0/564264490825835/1201367629380173
#changelog Bugfix: Mismatch shipping issue if the quote has a cart rule of 'Fixed amount discount for whole cart' and 'Apply to shipping amount'

Bugfix: Mismatch shipping issue if the quote has a cart rule of 'Fixed amount discount for whole cart' and 'Apply to shipping amount'

---

Helper/Cart.php
Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Test/Unit/Helper/CartTest.php

- introduce feature switch M2_ENABLE_API_DRIVEN_INTEGRAION
- Under feature switch update **getCartData** function to create bolt order without immutable quote creation.
Eventually we will delete code for immutable quote so I prefer to have few <IF> statement for now rather than separate function.
#changelog Do not create immutable quote for API driven integration

Do not create immutable quote for API driven integration

---

Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Plugin/OrderPlugin.php

The order state is for Magento to understand and process the order in a defined workflow. Whereas, the order status is for store owners to understand and process the order in a workflow. The merchant may create any number of custom order statuses to manege the exact order flow, but currently the plugin method Bolt\Boltpay\Plugin\OrderPlugin::beforeSetStatus() has logic to ensure that the order in processing/complete/closed status won't be updated back to pending_review and override the default "pending" order status with the "pending_payment", that causes conflict issue. 
To fix this issue, we add a new feature switch M2_DISALLOW_ORDER_STATUS_OVERRIDE to enable/disable the logic.
Fixes: [(link Jira ticket)](https://app.asana.com/0/951157735838091/1201290052673025/f)
#changelog Add feature …

Add feature switch for order status update

---

Helper/Cart.php
Model/Api/UpdateDiscountTrait.php
Plugin/SalesRuleActionDiscountPlugin.php
Plugin/SalesRuleModelUtilityPlugin.php
Plugin/SalesRuleQuoteDiscountPlugin.php
Test/Unit/Helper/CartTest.php
Test/Unit/Model/Api/UpdateDiscountTraitTest.php
Test/Unit/Plugin/SalesRuleActionDiscountPluginTest.php
Test/Unit/Plugin/SalesRuleModelUtilityPluginTest.php
Test/Unit/Plugin/SalesRuleQuoteDiscountPluginTest.php
ThirdPartyModules/Mexbs/Tieredcoupon.php

From Magento 2 v2.3.4, we can get details of applied sale rules from $address->getExtensionAttributes()->getDiscounts() and there is no need to calculate discount amount of each sale rule via plugin methods separately (That may cause potential bug and we need to maintain the calculation as long as M2 updates).
Then we still keep the approach to collect discounts via plugin methods for the merchant which still use old versions of Magento 2. 
Tested with Magento 2 v2.3.0, v2.3.4, v2.4.0, v2.4.3-p1
#changelog Code refactoring for collecting discounts

Code refactoring for collecting discounts

---

Model/Api/CreateOrder.php

**Issue**: 
Currently, Bolt validates tax before shipping. When the mismatched shipping issue causes the mismatched tax issue (shipping is taxable), Bugsnag just logs the mismatched tax issue. This would cause the developers to have a hard time figuring out the root cause.
**Improvement**:
Moving the shipping validation prior to the tax validation. This is the same as Magento flow because Magento calculates shipping before tax. 
See here: 
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Tax/Model/Sales/Total/Quote/Tax.php#L126
#changelog Improvement: Move shipping validation prior to tax validation

Improvement: Move shipping validation prior to tax validation

---

Controller/ReceivedUrlTrait.php
Test/Unit/Controller/Order/ReceivedUrlTest.php

In M2 API driven flow we still need the intermediate redirect page to assign new order to user session on it.
Two differences with the previous flow:
- we send order id, not incremental order id
- we do not need dispatch PostCheckoutEvents because they were already dispatched
#changelog Fix Controller/ReceivedUrlTrait.php for M2 API driven

Fix Controller/ReceivedUrlTrait.php for M2 API driven

---

Helper/Config.php
Model/EventsForThirdPartyModules.php
ThirdPartyModules/Aheadworks/StoreCredit.php
etc/adminhtml/system.xml
etc/config.xml

Add Aheadworks Store Credit to layout to be rendered below the cart
#changelog Add Aheadworks Store Credit to layout to be rendered below the cart

Add Aheadworks Store Credit to layout to be rendered below the cart

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php
Test/Unit/Helper/OrderTest.php
Test/Unit/TestUtils.php

When getting order items for Bolt cart, we do not check if the related product is already deleted, as a result, there is fatal error with collecting item info.
Solution: check if the product exists before processing.
Fixes: [(link Jira ticket)](https://app.asana.com/0/951157735838091/1201391676862045/f)
#changelog Exclude deleted product from Bolt cart

Exclude deleted product from Bolt cart

---

Block/Js.php
Helper/Cart.php
Test/Unit/Block/JsTest.php
view/frontend/templates/js/replacejs.phtml

When we disable or enable new api driven flow we should try not to affect the users in the middle of checkout process.
Before this PR users on cart page are blocked until they update cart.
With this PR users on the cart page just need to reload the page to be unblocked.
Just in case we do cart invalidation only once per cart page reloading.
#changelog invalidate cart if plugin mode changed

Reload cart if integration mode changed

---

Helper/Order.php
Model/EventsForThirdPartyModules.php
ThirdPartyModules/MageWorld/Affiliate.php

The merchant updates MageWorld Affiliate from 1.4.0 to 1.4.2 and experiences an issue that the commission is not applied to the affiliate's acct. This PR is to fix this compatibility issue.
Tested with both MageWorld Affiliate 1.4.0 and 1.4.2
Fixes: [(link Jira ticket)](https://app.asana.com/0/951157735838091/1201423349470785/f)
#changelog Add support for MageWorld Affiliate 1.4.2

Add support for MageWorld Affiliate 1.4.2

---

Model/Api/Tax.php

When the ship-to-store option is selected, the shipping_option in payload of tax api request is null and it causes an error `Trying to access array offset on value of type null` in this line https://github.com/BoltApp/bolt-magento2/blob/396cbb3662fc0a4652bd3d85e9b40e9e3829ee2c/Model/Api/Tax.php#L264
So we need to check $shipping_option before processing.
#changelog Bugfix: tax calculation error if ship-to-store option selected

Bugfix: tax calculation error if ship-to-store option selected

---

Block/Js.php
view/frontend/templates/js/replacejs.phtml

The PR [1413](https://github.com/BoltApp/bolt-magento2/pull/1413) only fix issue for M2 community edition, and there is still similar js error in M2 enterprise edition (It is because the in M2 enterprise edition, the Magento_Checkout/js/model/quote is extended, and the require-specific errbacks of RequireJS can not catch the error)
To fix this error, we use loader plugin of RequireJS to handle such case, log the error in the console and eliminate the exception.
#changelog Bugfix: JS error on cart page if quote is empty (M2E)

Bugfix: JS error on cart page if quote is empty (M2E)

---

Helper/Cart.php

We cache many bolt orders per the same [parent] quote id, so if user, for example, adds discount and then removed it we can find a bolt order without a discount in the cache.
This approach work with API driven as well, there is no known issue, but it looks error-prone to me.
Let's take bolt order from cache only if quote was not changed from the last call.
Down the road, we will change cache key: it makes sense to have quote_id as cache rather than hash of cart content.
#changelog Clear outdated cart cache for API driven approach

Clear outdated cart cache for API driven approach

---

Model/Api/UpdateCartCommon.php
Plugin/Magento/Fedex/Model/CacheFedexResultPlugin.php
etc/di.xml

For some merchants, they use Fedex as shipping carrier. But when making remote request to Fedex from merchant server, the response takes too long and causes timeout error with Bolt api request.
Solution: The response cache is a feature of M2 core (https://github.com/magento/magento2/blob/f34651e7794d0186dce2f242ebed14f2a6cae11d/app/code/Magento/Fedex/Model/Carrier.php#L515), we make use of it and use plugin method to cache Fedex API response when needed, if the content of request does not change, it can directly use the response from cache. 
Fixes: https://app.asana.com/0/951157735838091/1201488099526448/f
#changelog Add support for caching Fedex API response

Add support for caching Fedex API response

---

etc/webapi.xml

carts/mine/payment-information is magento endpoint which works for applying payment method to quote and create order.
This is a way how to create order for logged-in magento user.
This PR allows to use payment-information endpoint by admin integration users
#changelog Allow using carts/mine/payment-information for admin users

Allow using carts/mine/payment-information for admin users

---

Plugin/Magento/Fedex/Model/CacheFedexResultPlugin.php

The Fedex Api request could fail for some reasons, and it may be a temporary failure. If we still cache such invalid response, there is no chance for M2 core to correct the result. Also the invalid result from cache could cause an error "Trying to get property 'Message' of non-object" in M2 core (https://github.com/magento/magento2/blob/2.4.3-p1/app/code/Magento/Fedex/Model/Carrier.php#L581)
Solution: Only cache valid Fedex Api response.
#changelog Only cache valid Fedex Api response

Only cache valid Fedex Api response

---

Helper/Cart.php

For API-driven approach we need to set bolt checkout type in quote to backoffice.
It allows us to do proper redirect from admin page.
In the legacy approach we set this field for immutable quote in createImmutableQuote() method.
#changelog Magento API: fix redirect for backoiffice orders

Magento API: fix redirect for backoiffice orders

---

Helper/Cart.php
Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Test/Unit/Helper/CartTest.php

Reverting https://github.com/BoltApp/bolt-magento2/pull/1461/ and use rule name as coupon description only under feature switch.
This fix affects merchants who use automated discounts with empty discount descriptions.
Before this fix we showed to shoppers **rule name** and after fix - word "`Discount`"
The reason under the fix: some merchants save internal information in the discount name field.
#changelog Use rule name as coupon description only under feature switch

Use rule name as coupon description only under feature switch

---

Api/Data/DefaultOrderStatusInterface.php
Api/GetDefaultOrderStatusesInterface.php
Model/Api/Data/DefaultOrderStatus.php
Model/Api/GetDefaultOrderStatuses.php
etc/di.xml
etc/webapi.xml

Magento doesn't have API for get default order status per order state but we need to set status during webhook handling.
So need to have this simple GET endpoint.
#changelog Implement get order status endpoint

Implement get order status endpoint

---

view/frontend/templates/button_product_page.phtml
view/frontend/templates/js/boltglobaljs.phtml
view/frontend/templates/js/replacejs.phtml

Added multiple callbacks ability to window.whenDefined js method for fixing conflicts between replacejs.phtml and button_product_page.phtml. Both files are using the same property for whenDefined method and override each other.
Fixes: https://app.asana.com/0/1200879031426307/1201869413677057/f
#changelog Fix js whendefined callback conflicts

Fix js whendefined callback conflicts

---

Block/Adminhtml/System/Config/Form/Version.php

Now the main branch of Bolt M2 plugin does not pass all the circleci checks, the job integration-php72-magento23 experiences an error
`Class Magento\Framework\View\Helper\SecureHtmlRenderer does not exist `
After investigation, this error was introduced with [PR 1511](https://github.com/BoltApp/bolt-magento2/pull/1511), it is because M2 2.3.x does not have such a class Magento\Framework\View\Helper\SecureHtmlRenderer
Actually the parameter SecureHtmlRenderer is unnecessary for the constructor of Bolt\Boltpay\Block\Adminhtml\System\Config\Form\Version, so it is safe to remove this parameter and the compatibility issue is solved. 
Fixes: https://app.asana.com/0/1200879031426307/1202003016284406/f
#changelog Remove non-existent M2 class
Please validate that you have tested your change in at …

Remove non-existent M2 class

---

Helper/Cart.php
Model/Api/CreateOrder.php
Test/Unit/Helper/CartTest.php

To fix this bug
1 . Call setCollectShippingRates before collecting quote totals.
2.  Collect shipping discounts when creating Bolt order.
Fixes: https://app.asana.com/0/inbox/632578947811319/1201978015327776/1202036018623393/f
#changelog Bugfix: Unable to checkout with fixed amount shipping discount - BO

Bugfix: Unable to checkout with fixed amount shipping discount - BO

---

Helper/Cart.php

Magento 2 has a bug with cart rule "Fixed amount discount for whole cart" and fixed in v2.3.6 ([PR 26419](https://github.com/magento/magento2/pull/26419)) . So in M2 v2.3.4-p2, the code $address->getCartFixedRules() returns an array 
```
[
"ruleid" => 0.00
]
```
even there is no discount applied to shipping. And it causes double discount error in Bolt plugin.
Solution: validate the discount amount before calculation.
Fixes:  https://app.asana.com/0/1200879031426307/1202082673763428/f
#changelog Bugfix: Discount amount getting doubled

Bugfix: Discount amount getting doubled

---

.github/pull_request_template.md

1. Replace JIRA with neutral "ticket". We don't use JIRA anymore and we may move away from Asana down the road, so better to use neutral "ticket". 
2. Even out the spacing.
#changelog Minor modifications to PR template

Minor modifications to PR template

---

Block/Js.php
Block/JsProductPage.php
Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Test/Unit/Block/JsTest.php
view/frontend/templates/js/boltjs.phtml
view/frontend/templates/js/replacejs.phtml

Inject Openreplay into M2 behind a feature switch! This is for merchants who do not want the script in their HTML at all due to bloat. 
[COMING SOON: division feature to stop openreplay.js from sending info to us if the merchant wants to opt out but is okay with leaving the script in the html]
#changelog Inject Openreplay into M2 + feature switch

Inject Openreplay into M2 + feature switch

---

Model/Api/CreateOrder.php
Test/Unit/Model/Api/CreateOrderTest.php

Currently we always get error code from the field "code" of the first element in the ErrorInfos of quote item, but in this case, all the fields of first ErrorInfo element have null value (it seems that it is added by other 3p plugin) when the related cart item is out of stock, and actually the second ErrorInfo element has proper info, therefore, $boltErrorCode does not have appropriated code for out-of-stock, and the Bolt modal just displays a general error message.
To solve such an issue, we need to find the valid error info (code, message and origin) as far as possible. Also from M2 v2.4.3, the ErrorInfo of quote item for inventory error does not have any message value (https://github.com/magento/magento2/commit/7f127923ba83be5dba9caef78ce6f584e0ec16e9), so we have to get the message …

Bugfix: unappropriated error message when cart item is out of stock

---

Helper/Order.php
Test/Unit/Helper/OrderTest.php

When issuing a Credit Memo, the merchant can choose to refund the full amount of an invoice and a portion of the quantity for one line item (such as three of the five shirts in an order.), then this order can still be shipped and its status should be processing instead of closed.
So in our plugin we need to check order shipment availability when mapping internal Bolt transaction state representation to Magento order state.
Fixes: https://app.asana.com/0/inbox/632578947811319/1202132733661537/1202133535306761/f
#changelog Bugfix: incorrect order status if order can be shipped after full refund
---
- …

Bugfix: incorrect order status if order can be shipped after full refund

---

Plugin/Magento/Framework/View/Element/UiComponent/DataProvider/RegularFilterPlugin.php

The APM info is saved in the additional_information field of sales_order_payment table, so we need to filter the payment method with that field.
Fixes: https://app.asana.com/0/1124368832381302/1202128894520486/f
#changelog Bugfix: Magento dashboard filter does not capture Bolt APM orders

Bugfix: Magento dashboard filter does not capture Bolt APM orders

---

Block/JsProductPage.php
Test/Unit/Block/JsProductPageTest.php

Currently, the Bolt button displays even if the bolt_ppc flag is disabled.
So this PR fixes the issue by correcting the condition in the isBoltProductPage method in the JSProductPage block
Fixes: https://app.asana.com/0/564264490825835/1202163249205445
#changelog Fix bug: Bolt button displays even if the bolt_ppc flag is disabled

Fix bug: Bolt button displays even if the bolt_ppc flag is disabled

---

Block/Js.php
Helper/Config.php
Test/Unit/Helper/ConfigTest.php

Currently the custom api, cdn and merchant dash urls for local development are saved in the core_config_data data table, if we do not have SSH access, there is no way to update these values. 
To make it easier for developer to change the settings, this PR uses additional configuration to setup values instead.
Fixes: https://app.asana.com/0/1124368832381302/1202155503854984/f
#changelog Set dev mode for local development by additional configuration

Set dev mode for local development by additional configuration

---

Model/Api/OrderManagement.php

Steps to replicate the issue:
- Create new order status (pending_ogone) and assign it to the pending_payment state and set it as default
- Place an order with invalid card info and get a failed payment
- After that, Bolt calls the delete order endpoint and throws the exception: Unexpected order status
See the Datadog link here:
https://app.datadoghq.com/logs?query=%40merchant_name%3A%22John%20McCombs%20Testing%22%20-service%3Aasyncjobs&event=AQAAAYBxEsjmid-36QAAAABBWUJ4RXVnaEFBQ0xvNjN5NWxfSjZBQUU&index=&from_ts=1648573874478&to_ts=1651165874478&live=true
**Actual result** :
Magento order isn't deleted
**Expected result** :
No exception and Magento order should be deleted
So this PR resolves the issue by correcting the condition logic (**use the order state instead of the order status**) …

Bugfix: Unexpected order status in the delete order endpoint

---

Plugin/Magento/Framework/View/Element/UiComponent/DataProvider/RegularFilterPlugin.php

Any 3p plugin could join table sales_order_payment to collection select for specific purpose, usually it also selects some columns from table sales_order_payment. As a result, there could be conflict with the columns we select in Bolt plugin
```
['additional_information' => 'LOWER(additional_information)', 'cc_type' => 'LOWER(cc_type)']
```
To solve this issue, just use an empty array for the list of columns, cause we do not need any columns from this joined table as query result.
Fixes: https://app.asana.com/0/1124368832381302/1202182258989837/f
#changelog Bugfix: SQL error if joining same table to collection select multiple times

Bugfix: SQL error if joining same table to collection select multiple times

---

Controller/ReceivedUrlTrait.php

Partially revert PR https://github.com/BoltApp/bolt-magento2/pull/1468 because we update the server part to return Incremental ID instead of order ID.
asana:
https://app.asana.com/0/1124368832381302/1202229182315897/f
#changelog Redirect to success page: search for orders by incrementID

Redirect to success page: search for orders by incrementID

---

Plugin/Magento/Framework/View/Element/UiComponent/DataProvider/DataProviderPlugin.php
Plugin/Magento/Framework/View/Element/UiComponent/DataProvider/RegularFilterPlugin.php

When checkout with Magento 2 APIs, the payment data saved in sales_order_payment table is different from Bolt APIs. So we need to update related plugin methods for displaying alternative payment type in order grid, as well as the payment method filter of order grid.
Fixes: https://app.asana.com/0/1124368832381302/1202229182315905/f
#changelog Bugfix: [API-driven] Payment methods field is empty

Bugfix: [API-driven] Payment methods field is empty

---

view/frontend/templates/js/boltjs.phtml
view/frontend/templates/js/replacejs.phtml

Make Track.js load as a `defer` script. 
#changelog Change load method of Track.js script to defer

Change load method of Track.js script to defer

---

Helper/Cart.php
Helper/Discount.php
Model/Api/DiscountCodeValidation.php
Test/Unit/Helper/CartTest.php
Test/Unit/Helper/DiscountTest.php
Test/Unit/ThirdPartyModules/Aheadworks/RewardPointsTest.php
Test/Unit/ThirdPartyModules/Amasty/GiftCardAccountTest.php
Test/Unit/ThirdPartyModules/Amasty/StoreCreditTest.php
ThirdPartyModules/Aheadworks/Giftcard.php
ThirdPartyModules/Aheadworks/RewardPoints.php
ThirdPartyModules/Aheadworks/StoreCredit.php
ThirdPartyModules/Amasty/GiftCard.php
ThirdPartyModules/Amasty/GiftCardAccount.php
ThirdPartyModules/Amasty/Rewards.php
ThirdPartyModules/Amasty/StoreCredit.php
ThirdPartyModules/BagRiders/StoreCredit.php
ThirdPartyModules/Bss/StoreCredit.php
ThirdPartyModules/ImaginationMedia/TmwGiftCard.php
ThirdPartyModules/J2t/Rewardpoints.php
ThirdPartyModules/MageWorld/RewardPoints.php
ThirdPartyModules/MageWorx/RewardPoints.php
ThirdPartyModules/Magento/GiftCardAccount.php
ThirdPartyModules/Mageplaza/GiftCard.php
ThirdPartyModules/Mirasvit/Credit.php
ThirdPartyModules/Mirasvit/Rewards.php
ThirdPartyModules/Teamwork/StoreCredit.php
ThirdPartyModules/Teamwork/Token.php

Discount type refactoring:
- introduce constants for discount type
- use the constant rather than $this->discountHelper->getBoltDiscountType('by_fixed') call
The purpose of the refactoring: change getBoltDiscountType in the next PR to support free shipping type in magento
https://app.asana.com/0/1201931884901947/1201594901813539/f
#changelog Discount type refactoring

Discount type refactoring

---

Plugin/Magento/Sales/Model/InvoiceOrderPlugin.php
etc/di.xml

Aheadworks Store Credit extension doesn't apply points if invoice created via API call
It happens because the module expected to see direct save call $invoice->save() but API
saves invoice via resource model
So in this plugin we trigger direct invoice saving after API call
This PR should be reverted once the issue is fixed on Aheadworks Store Credit side.
https://app.asana.com/0/0/1202418007292947/f
#changelog Fix for Aheadworks Store Plugin to support API invoice creation

Fix for Aheadworks Store Plugin to support API invoice creation

---

Helper/Cart.php
Helper/Discount.php
Model/EventsForThirdPartyModules.php
ThirdPartyModules/Mexbs/Tieredcoupon.php

To fix the bug that the customer is unable to add/remove Tieredcoupon through Bolt modal
Fixes: https://app.asana.com/0/951157735838091/1201513791312930/f
#changelog Bugfix: Unable to add/remove Tieredcoupon through Bolt modal

Bugfix: Unable to add/remove Tieredcoupon through Bolt modal

---

Controller/Adminhtml/Order/ReceivedUrl.php
Controller/Order/ReceivedUrl.php
Controller/ReceivedUrlInterface.php
Controller/ReceivedUrlTrait.php
Plugin/Magento/Checkout/Model/Session/SuccessValidatorPlugin.php
Test/Unit/Controller/Adminhtml/Order/ReceivedUrlTest.php
Test/Unit/Controller/Order/ReceivedUrlTest.php
Test/Unit/Controller/ReceivedUrlTraitTest.php
etc/frontend/di.xml

Root cause: the variables (such as LastQuoteId, LastSuccessQuoteId and etc.) saved in the checkout session lost for some reasons, therefore, the redirection can not pass validation (https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Checkout/Model/Session/SuccessValidator.php#L34) and stay on the empty cart page.
Solution: use Magento cache to store these variables instead.
Fixes: https://app.asana.com/0/474713171217346/1201502391293711/f
#changelog Bugfix: Sporadic issues with shoppers not being redirected to the confirmation page

Bugfix: Sporadic issues with shoppers not being redirected to the confirmation page

---

view/frontend/templates/button_product_page.phtml
view/frontend/templates/js/boltglobaljs.phtml
view/frontend/templates/js/custom_sso_buttons.phtml
view/frontend/templates/js/replacejs.phtml
view/frontend/web/js/utils/when-defined.js

When Bolt is disabled on minicart a dependency we use for SSO is not loaded. The dependency is now transformed to a proper requirejs module and required wherever needed.
The issue was reported in github:
https://github.com/BoltApp/bolt-magento2/issues/1575
Because window.whenDefined is declared in view/frontend/templates/js/boltglobaljs.phtml, which exits early in the following conditional:
//check if we need Bolt on this page
if (!$block->isOnPageFromWhiteList() && !$block->isMinicartEnabled() && !$block->isBoltProductPage()) { return;
}
And because view/frontend/templates/js/custom_sso_buttons.phtml was introduced in commit 75b2b248419fae09d0244d36f42274882f3b9e7c and does not include the same conditional (particularly, $block->isBoltProductPage()) yet depends on window.whenDefined, the …

Resolve reported issue with javascript dependencies - load whenDefined via requireJs

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

For Bolt PPC, the plugin does not setup proper currency when creating empty quote and the cart still uses default currency.
Solution: We have correct currency in the api request, and just apply it before creating empty quote.
Fixes: https://app.asana.com/0/951157735838091/1202452720391991/f
#changelog Bugfix: Incorrect amounts displayed at Bolt PPC for currency chosen

Bugfix: Incorrect amounts displayed at Bolt PPC for currency chosen

---

Helper/Cart.php

For direct API, the quote does not have the property `parent quote id` anymore, as a result, some logic depending on parent quote (eg. support for Mirasvit Reward Points) does not work as expected.
Solution: Assign the property `parent quote id` with its own quote id.
Fixes: https://app.asana.com/0/0/1202504882047670/f
#changelog Bugfix: missing parent quote for direct API

Bugfix: missing parent quote for direct API

---

Helper/Cart.php
view/frontend/templates/button_product_page.phtml

We have a bug in our PPC in the plugin where if a multiselect field is used to select product options we only send one of the values and the total only accounts for a single value as well.
What we need to do is modify the total to account for all values and also send all selected options. We are using this also for Native API flow and in native api flow we are expecting a string which contains comma separated values like: "1,2,3,4" to represent each option selected. 
Fixes: https://app.asana.com/0/1200879031426307/1202497849167312/f
#changelog Bugfix: multiselect field is not supported for PPC

Bugfix: multiselect field is not supported for PPC

---

Helper/Order.php

When creating a credit memo from M2 admin dashboard, the normal process would be
1. process a refund through payment gateway
2. create a credit memo
3. save order 
(please refer to https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/Model/Service/CreditmemoService.php#L164)
So the event `sales_order_save_after` should be dispatched after creditmemo is created.
But for Bolt, the process is a bit different. 
1. process a refund through payment gateway
2. in the Bolt plugin, refund the amount through API (https://github.com/BoltApp/bolt-magento2/blob/refs/tags/2.25.2/Model/Payment.php#L478)
3. in the Bolt plugin, then update order payment / transaction data (https://github.com/BoltApp/bolt-magento2/blob/refs/tags/2.25.2/Helper/Order.php#L2068)
4. in the Bolt plugin, …

Bugfix: the event sales_order_save_after is dispatched before creating creditmemo

---

Plugin/Magento/Config/Model/ConfigPlugin.php

Fix catalog ingestion plugin for store configuration, removed not required type of second argument in Bolt\Boltpay\Plugin\Magento\Config\Model\ConfigPlugin, to prevent possible empty result for 3-th party modules
Fixes: [(link ticket)](https://app.asana.com/0/951157735838091/1202652441204573/f)
#changelog Catalog ingestion: store configuration plugin fix

Catalog ingestion: store configuration plugin fix

---

.circleci/config.yml

We are being blocked on our PR's because memory running out during integration tests. 
Example workflow where this occurs:
https://app.circleci.com/pipelines/github/BoltApp/bolt-magento2/15607/workflows/61a7bb93-3bdc-499e-b1ea-4e40c0356940/jobs/50389
#changelog Bump up memory for Integration tests

Bump up memory for Integration tests

---

Helper/Cart.php
Model/Api/ShippingMethods.php
Test/Unit/Helper/CartTest.php

Currently, if a customer use gift wrapping on item level, the gift wrapping image doesn't show in the Bolt modal
So the PR is to fix the issue by correcting the gift wrapping integration logic
Fixes: 
#changelog Bugfix: Gift wrapping image for item level doesn't show in the Bolt modal

Bugfix: Gift wrapping image for item level doesn't show in the Bolt modal

---

Helper/Cart.php

If the cart contains any bundle product, the Bolt plugin is unable to get discount details for bundle product. This is related to a bug in M2 core (https://support.magento.com/hc/en-us/articles/4412563019661-MDVA-40435-Discount-on-bundle-product-is-not-applied-correctly-via-GraphQL) and it has been fixed in M2 v2.4.4
And if the merchant still has M2 version older than 2.4.4 installed in the store, we have to use plugin method to collect discount details for cart including bundle product.
Fixes: https://app.asana.com/0/1200879031426307/1202621165399576/f
#changelog Bugfix: unable to get discount details for bundle product

Bugfix: unable to get discount details for bundle product

---

ThirdPartyModules/Amasty/Extrafee.php

For native API, the property $this->_extrafeeCollectionFactory is null when trying to add extra fee in the filter method.
Fixes: https://app.asana.com/0/1201931884901947/1202731054395069/f
#changelog [API-driven] Add support for Amasty Extrafee extension

[API-driven] Add support for Amasty Extrafee extension

---

ThirdPartyModules/Amasty/Extrafee.php

Use default placeholder image instead of Route fee icon for Amasty extra fee
#changelog Use default placeholder image for Amasty extra fee

Use default placeholder image for Amasty extra fee

---

Plugin/Magento/Framework/View/Element/UiComponent/DataProvider/RegularFilterPlugin.php

By default, the Payment Method is a single-select field for filtering orders in M2 backend, but it could be changed to multiple select field by some 3p modules.
Currently in the plugin method Bolt\Boltpay\Plugin\Magento\Framework\View\Element\UiComponent\DataProvider\RegularFilterPlugin::aroundApply, it only expects $filter->getValue() to return string value, and if the multiple select field returns array value, it raises a PHP error "strpos0 expects parameter 1 to be string, array given".
To fix this issue, just convert array to string for parameter 1 of strpos0 when needed.
Fixes: https://app.asana.com/0/1200879031426307/1202779261404551/f
#changelog Support multiple-select options for filtering orders
Please validate that you have tested your change in at least one of the following …

Support multiple-select options for filtering orders

---

Helper/Cart.php

Due to a bug in Magento core (https://github.com/magento/magento2/commit/c5563f254f3e28d9c1b6cc4ae04bcad4fd7faf56), if we add a configurable product to cart and there is a "Fixed amount discount for whole cart" sale rule being automatically applied to cart, both child item and parent item get discounted, but Magento cart only collect discounts of child item. Then the total mismatch happens. 
Solution : save quote via repository once Bolt cart is created.
Fixes: https://app.asana.com/0/1201669303758312/1202880033146584/f
#changelog [API-driven] Bugfix: Total mismatch between Bolt cart and Magento cart

[API-driven] Bugfix: Total mismatch between Bolt cart and Magento cart

---

Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Helper/ModuleRetriever.php
Test/Unit/Helper/ModuleRetrieverTest.php

The Magento Bolt\Boltpay\Helper\ModuleRetriever::getInstalledModules()
is not returning all available magento modules, because if a module uses only db_schema.xml and doesn't have upgrade scripts (the latest version of Amasty_Giftcard, Magento_GiftCards for example) a module doesn't have any record in magento "setup_module" table. In this case we have mismatch with backend "merchant_division_platform_plugin_third_party_plugins" table and some features is not working as expected. By this fix we are using the Magento Core Functionality for fetching available modules. 
Fixes: https://app.asana.com/0/1201931884901947/1202947319621682/f
#changelog Module Retriever Update

Module Retriever Update

---

Helper/Order.php
Test/Unit/Helper/OrderTest.php

This PR is to the public the setAddress method in the order helper class so we can use the method easier to do the integration
Here are examples:
https://github.com/BoltApp/bolt-magento2/blob/2.24.1.rossignol.bopis/ThirdPartyModules/Rossignol/Synolia/Store.php#L223
https://github.com/BoltApp/bolt-magento2/blob/2.26.1.metroplex/ThirdPartyModules/Grabagun/InStorePickup.php#L564
#changelog Public setAddress method in order helper class

Public setAddress method in order helper class

---

ThirdPartyModules/Amasty/Extrafee.php

In PR https://github.com/BoltApp/bolt-magento2/pull/1632 we fixed placeholder image URL but only in one place, for an add-on.
In this PR we fix the same URL in the other place, for a cart item.
https://app.asana.com/0/1200879031426307/1202780668772807/f
#changelog Amasty extra fee support: use default placeholder image

Amasty extra fee support: use default placeholder image

---

Helper/Cart.php
Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php

We face cases that the discount total is different between Bolt cart and M2 cart when the native API is enabled, it could be caused by various reasons. For now we just add a new feature switch M2_SKIP_CART_DISCOUNT_TOTAL_MISMATCH to skip such mismatch when needed.
Fixes: https://app.asana.com/0/1201931884901947/1202975415590108/f
#changelog Skip cart discount total mismatch when needed

Skip cart discount total mismatch when needed

---

Controller/Adminhtml/System/ProcessIntegrationToken.php

From Magento 2.4.4, the integration tokens can no longer be used for API Bearer token authentication. Previously, an integration token could be used as a standalone key for token-based authentication. However, this behavior has been disabled by default due to the security implications of a never-expiring access token. 
Then to restore this behavior for API-driven, we have to update the related setting (Stores > Configuration > Services > OAuth > Consumer Settings > Allow OAuth Access Tokens to be used as standalone Bearer tokens option to Yes.) when sending API keys to Bolt.
Fixes: https://app.asana.com/0/1200879031426307/1202585550729365/f
#changelog [API-driven] Enable token-based authentication

[API-driven] Enable token-based authentication

---

Helper/Config.php
Model/Api/GetProduct.php

Removed Magento_Bundle module dependency for "/V1/bolt/boltpay/product" API endpoint
Fixes: https://app.asana.com/0/1201931884901947/1203189967357439/f
#changelog M2 Bolt API GetProduct removed bundle dependency

M2 Bolt API GetProduct removed bundle dependency

---

ThirdPartyModules/Route/Route.php

When we first time added the product into the cart and the quote created total calculation is done before Route set its data to checkout session.
So we need to recalculate totals one more time.
This is not an issue for the legacy approach because we create a child quote and calculate totals for it.
https://app.asana.com/0/1201931884901947/1203273057259994/f
#changelog M2 API: collect totals if route is enabled

M2 API: collect totals if route is enabled

---

Block/Checkout/Success.php
ThirdPartyModules/Rossignol/Synolia/Store.php

Remove the hard-coded country ID "US" and set the country code of the pickup store depending on the current customer's address.
We don't have the country_id of the selected store for pick up at this point, but since we already have a customization to show only stores that match the country_id of customer's shipping address, we can use it here.
Fixes: BOPIS cannot be used to check out at the Canada store. 
#changelog Set the country code of the pickup store depending on the current customer's address

Set the country code of the pickup store depending on the current customer's address

---

etc/integration/api.xml

Add parent scopes to have a proper list of scopes in Magento admin.
Before PR:
After PR:
https://app.asana.com/0/1201931884901947/1203242144329499/f
#changelog Add integration scopes parent for Magento_Backend::store

Add integration scopes parent for Magento_Backend::store

---

Model/Api/UpdateCartCommon.php

Under some condition it's possible that we are unable to find product via SKU in update_cart call.
In this case we'd rather want to continue with product found by ID then throw an error.
See details:
https://app.asana.com/0/1200879031426307/1202975571339919/f
#changelog Get product by ID if exception thrown when we unable to find it via SKU

Get product by ID if exception thrown when we unable to find it via SKU

---

Helper/Order.php
Test/Unit/Plugin/Magento/Ui/Component/Form/Element/SelectPluginTest.php

Show Amazon pay processor for payment method in order grid
#changelog Show Amazon pay processor for payment method in order grid

Show Amazon pay processor for payment method in order, invoice, credit memo, shipment grid

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

Some international addresses does not require state/province to be set. We have region field set as required in bolt. 
Removed 'region' from required address fields in order to fix bolt checkout for addresses without region
Fixes: [(link ticket)](https://app.asana.com/0/1201931884901947/1203373200842526)
#changelog Removed 'region' from required address fields in order to fix bolt checkout for addresses without region

Removed 'region' from required address fields in order to fix bolt checkout for addresses without region

---

Model/CatalogIngestion/Request/Product/DataProcessor.php

We did a typo "values" instead of "Values" which lead to payload like
```
"Values": [],
"values": [
{
"DisplayValue": "Standard Chair Cart - Black",
"SortOrder": "0",
"Value": 1177
},
{
"DisplayValue": "Heavy Duty Chair Cart - Tan",
"SortOrder": "1",
"Value": 1178
},
{
"DisplayValue": "Chair Cart Cover",
"SortOrder": "2",
"Value": 1179
}
```
Another issue with type of Product.Options.Values.Value. It should be string, not int
Asana:
https://app.asana.com/0/1201307079775363/1203413404142283/f
UPD: This PR is almost empty because issue is already resolved in https://github.com/BoltApp/bolt-magento2/pull/1703/files
#changelog Catalog ingestion: Fix issues with Product.Options

Catalog ingestion: Fix issues with Product.Options

---

Helper/Order.php
Test/Unit/Helper/OrderTest.php
ThirdPartyModules/Amasty/Extrafee.php
etc/config.xml
view/frontend/layout/catalog_product_view.xml
view/frontend/templates/subscription_freq_selector_product_page.phtml

This PR contains all the necessary changes to add a subscription frequency selector to the product details page.
[Template file task](https://app.asana.com/0/1202967843415720/1203093658712998)
[Magento admin setting task](https://app.asana.com/0/1202967843415720/1203093658713000)
This is a core functionality for our Subscription team's MVP in January for First-part Physical Subscription offerings.
**This PR contains 3 sections:**
Whether to display the product details page frequency selector. This is the flag that our beta merchants will manually enable to see the rest of the changes, and consequently see the frequency selector on their subscribable product detail pages.
Changes: 
- Define and added the config in system.xml
- `getPDPFrequencySelectorFlag()` in Config.php that checks for …

[subscriptions] Implement new template file for subscription PDP frequency selector

---

Model/CatalogIngestion/ProductEventManager.php

Catalog ingestion: added removing "product event" from database after successfully sending instant product event
Fixes: https://app.asana.com/0/1201931884901947/1203475759864888/f
#changelog catalog ingestion: instant product event added removing database "bolt event" after successfully sending process.

Catalog ingestion: remove product event after instant sent call

---

Model/Api/ShippingMethods.php

Fix error which block checkout when applied rule ids are null
Issue is reproducable if prefetch shipping is enabled (payment/boltpay/prefetch_shipping) & user trying to checkout without any discounts applied.
Fixes: [(link ticket)](https://app.asana.com/0/1201931884901947/1203339630490034)
#changelog Fix error when applied rule ids is null

Fix error when applied rule ids is null

---

view/frontend/templates/button_product_page.phtml

Fixed product page for magento 2.4.5-p1
Magento 2.4.5-p1 doesn't have jquery/jquery.cookie and it is blocking bolt script loading process. It is enought to have only 'mage/cookies'
Fixes: https://app.asana.com/0/1201931884901947/1203499616221175/f
#changelog Fix product page checkout for magento 2.4.5

Fix product page checkout for magento 2.4.5

---

Api/GetProductImageUrlInterface.php
Model/Api/GetProductImageUrl.php
etc/di.xml
etc/webapi.xml

Implemented new endpoint  which is retrurning cachable url of image like:
https://m2.ygarmash.dev.bolt.me/media/catalog/product/cache/78f8cf97d02c8723e0bc8c00b62c4cd3/s/m/small_image.jpg
This request have additional param `imageId` which is the type of product image in magento terms like:
- product_page_image_small
- product_page_image_medium
- product_page_image_large
- .....
The request with parameter looks like: 
https://m2.ygarmash.dev.bolt.me/rest/default/V1/bolt/boltpay/product/1/image-url?imageId=product_page_image_large
if we are using this endpoint without imageId parameter the default parameter is: `product_page_image_small`
Return value is `string` type
```
<route url="/V1/bolt/boltpay/product/:productId/image-url" method="GET">
<service …
```

Fetch Cart: product image endpoint implementation

---

Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Model/CatalogIngestion/ProductEventManager.php
Model/CatalogIngestion/ProductEventProcessor.php
Plugin/Magento/Inventory/Model/SourceItem/Command/SourceItemSavePlugin.php

Fixed catalog ingestion wrong inventory level data during running instant flow. Caused by transaction in core magento legacy stock item save plugin.
Fixes: https://app.asana.com/0/1201931884901947/1203554804830150/f
#changelog catalog ingestion magento 2.4.4 wrong inventory level during instant run process

Catalog ingestion: fix transaction issue with legacy stock item

---

Model/Api/OAuthRedirect.php

Fixed 2 issues related to SSO
- safari: unable to add products to card(session expired) after log-in by "Bolt Shopper Assistant":
When we are logged-in by SSO without page redirect (by using Bolt Shopper Assistant for example) in this case Magento removing cookie by backend [here](https://github.com/magento/magento2/blob/5844ade68b2f9632e3888c81c946068eba6328bb/app/code/Magento/PageCache/Observer/FlushFormKey.php). But on safari without redirect the cookie is removed from browser (you can't see cookie on the devtool) but not in window.document object(we can see the cookie "form_key" there by checking object in browser console: "document.cookie") therefore all future requests is being called without "form_key" which is the reason of  "session expire" issue.
By normal flow Magento updates …

SSO: fix safari log-in by Bolt Assistant

---

view/frontend/layout/catalog_product_view.xml
view/frontend/layout/catalog_product_view_type_configurable.xml

Our initial plugin change to add the subscription frequency selector component just put it together with the product page checkout button. This PR aims to reposition the component to be above the "add to cart" button, which is more in line with the design we're going for:
[Figma link](https://www.figma.com/file/214BFW3oTs7bAhxcDFNCGi/22-Q3-FP-%E2%80%A2-Bolt-Subscriptions-%E2%80%94-Storefront-%26-Shopper-Experience-%E2%80%A2-P0?node-id=792%3A12617&t=vcrPkA6j3Z0AtHS8-1)
It doesn't look perfect in the screenshot, but Oat is handling the styling adjustments.
We are adding 2 new reference blocks:
```
<referenceBlock name="product.info.options.wrapper.bottom">
<block class="Bolt\Boltpay\Block\JsProductPage" name="bolt.frequencySelector.additional" …
```

[subscriptions] Reposition PDP frequency selector to be before add to cart

---

view/frontend/templates/subscription_freq_selector_product_page.phtml

We want to eventually support subscription offers at the product variant level. For example, we want to support offering a subscription for a red jacket, but not a yellow jacket variant. We need a way to listen for when the shopper changes the product color swatch. I found this code that adds a listener for the `updatePrice` event in the `button_product_page.phtml` file. I would like confirmation as to whether `updatePrice` is the correct event to listen on, and if it is, if there's any documentation for it.
#changelog [subscriptions] Call setupProductPage when configurable product swatch options are changed

[subscriptions] Call setupProductPage when configurable product swatch options are changed

---

Helper/Order.php
Model/Payment.php

If the merchant refund online an Amazon pay order in Magento but for some reason (await the response from processor)
Bolt server creates refund transaction with created status.
Once the processor approves, a refund will be processed and the transaction status will be updated to refund.
By this PR, we handle the case: update Magento order to closed status and add to order comment to explain that refund is in progress.
Before this PR, we had exception "If the invoice was created offline, try creating an offline credit memo."  when users try to create credit memo online
FYI, this PR applies the same logic as https://github.com/BoltApp/bolt-magento2/pull/1003
Fixes: [(link ticket)](https://app.asana.com/0/1201495896048972/1203556781378701)
#changelog Add support for AmazonPay 'in progress' …

Add support for AmazonPay 'in progress' refund

---

Helper/Api.php
Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Plugin/Magento/Checkout/CustomerData/Cart.php

Pre-Fetch cart implementated:
- added new feature switcher `M2_PRE_FETCH_CART_VIA_API` 
- now we are sending request to bolt API `/v1/order/pre_fetch_cart` when magento card is requested by JS customer-data (it happens in cases when card updated/created). The current customer-data is stored in magento cache by tag `PRE_FETCH_CART_CUSTOMER_DATA_CACHE_TAG` with lifetime 1h with hash  identity md5 of serialized customer-data array. If customer-data has diff hash value it means customer-data contains diff data and we must send pre-fetch request to bolt api.
Fixes: https://app.asana.com/0/1201931884901947/1203149984455025/f
#changelog Pre-Fetch cart implementation

Pre-Fetch cart implementation

---

view/frontend/templates/js/replacejs.phtml
view/frontend/web/js/bolt-api-driven-checkout.js

- Replaced  `onSuccess` callback argument `data` whith `transaction` data without renaming of argument name to save possible backward functionality.(if one of merchants is checking existing `data` argument)
- Did the same for "fetch cart project" js file.
Fixes: https://app.asana.com/0/951157735838091/1203434860273469/f
#changelog fixed onSuccess callback argument data

On success callback: added transaction data as argument

---

view/frontend/templates/button_product_page.phtml

- Fixed unexpected "product page checkout" button rendering for out of stock products.
We include our ppc template in magento addtocart.phtml [here](https://github.com/magento/magento2/blob/647b34eb3d8bc13c02adca1262aaab389dec1324/app/code/Magento/Catalog/view/frontend/templates/product/view/addtocart.phtml#L37) you can see that this default magento template have product saleable check conditition [here](https://github.com/magento/magento2/blob/647b34eb3d8bc13c02adca1262aaab389dec1324/app/code/Magento/Catalog/view/frontend/templates/product/view/addtocart.phtml#L11). If merchant use default template the ppc bolt button won't rendered. But if merchant have some diff structure which calls `<?= $block->getChildHtml('', true) ?>` not under saleable check condition bolt button will be …

PPC out of stock products

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php
ThirdPartyModules/Amasty/Promo.php

Amasty promo rule bolt modal coupon code duplication fix
Magento Legacy Mode:
- With "amasty/promo": "2.13.0", Magento 2.4.5-p1, Bolt 2.26.5 all types of amasty promo rules is applied on general discount collection step and not require additional 3th party module collect process.
Fixes: https://app.asana.com/0/951157735838091/1203645260964776/f
#changelog Amasty promo rule bolt modal coupon code duplication fix

Amasty promo rule coupon code duplication fix

---

Model/Api/DiscountCodeValidation.php
Model/Api/UpdateDiscountTrait.php
Test/Unit/Model/Api/UpdateDiscountTraitTest.php

- Remove applyingGiftCardCode which we do not use
- Rename applyingGiftCardCode to applyGiftCardCode to fix issue with static type checker
Class Model/Api/DiscountCodeValidation has its own applyingGiftCardCode method with 4 arguments, so when we include the trait into this class with a function with the same name but the different number of arguments it shows an error.
Asana:
https://app.asana.com/0/1201931884901947/1204028793252855/f
#changelog UpdateDiscountTrait refactoring

UpdateDiscountTrait refactoring

---

Block/Info.php
Helper/Order.php
Test/Unit/Plugin/Magento/Ui/Component/Form/Element/SelectPluginTest.php

Store credova_public_id and credova_application_id in the payment info object and show it in admin order
See screenshot: https://prnt.sc/v883yEXjADzm
This is from Metroplex's requirement
Fixes: https://app.asana.com/0/1201495896048972/1202938624902004
#changelog Store credova_public_id and credova_application_id in payment and order info object

Store credova_public_id and credova_application_id in payment and order info object

---

view/frontend/web/js/utils/when-defined.js
view/frontend/web/js/utils/when-defined.test.js

We have a bug in [whenDefined](https://github.com/BoltApp/bolt-magento2/blob/master/view/frontend/web/js/utils/when-defined.js). When called multiple times it can return false positive result. The issue manifested on Headlights Depot PPC [page](https://shop.headlightsdepot.com/tail-light-smoked-factory-style-left-driver-fits-2016-2019-toyota-tacoma.html).
Fixes: ([link ticket](https://app.asana.com/0/0/1204134908074103/f))
#changelog Resolve issues with multiple calls to whenDefined

Resolve issues with multiple calls to whenDefined

---

Block/Js.php
Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
view/frontend/templates/js/replacejs.phtml

- added new feature switcher: `M2_AJAX_ADD_TO_CART_SUCCESS_DISABLE_TIME_OUT`
- If the switcher above is enabled we are not using zero timeout for bolt configure call after `ajax:addToCart` js event.
Fixes: [(link ticket)](https://app.asana.com/0/1200879031426307/1204090292056675/f)
#changelog feature switcher to disable timeout on ajax:addToCart event bolt configure call

Ajax add to cart success event timeout feature switcher

---

view/adminhtml/templates/boltpay/button.phtml

Currently, the Error popup triggers multi times in the admin. 
See the video for replicating the issue here: https://drive.google.com/file/d/18weqoQykbegXPcKWBJzeqLbRec54_AIZ
The cause is that sometimes, the on-change event call multi-times. And in order to fix this, we add an e.stopImmediatePropagation() into the function.
#changelog Fix bug: Error popup trigger multi times in admin

Fix bug: Error popup trigger multi times in admin

---

view/frontend/templates/js/replacejs.phtml
view/frontend/web/js/bolt-api-driven-checkout.js

Our frontend integration relies on Magento cart section data persisting and updating in local storage.
This works fine, but if the env is broken for some third-party integration Magento cart may not be retrieved and the bolt button doesn't work.
See an example in asana.
In this PR we catch this situation and requested magento cart from backend manually.
Asana:
https://app.asana.com/0/1200879031426307/1204081354756081/f
#changelog Request magento cart from backend if it's not present

Request magento cart from backend if it's not present

---

view/adminhtml/templates/boltpay/button.phtml

Currently, the Boltpay order is still created with Magento submit order button in admin.
Before we had the PR https://github.com/BoltApp/bolt-magento2/pull/416 to force admin users to use the Bolt checkout button instead of the Magento submit order button by adding a required field with a hidden type. However, In some cases, this won't work since the input field is missing the name. So this PR is to add name for the input field
See screenshot: https://prnt.sc/rjB1rXCHIAY2
#changelog Fix bug: Boltpay order is created with Magento submit order button in admin

Fix bug: Boltpay order is created with Magento submit order button in admin

---

Helper/Cart.php

Currently, customers still can place a Bolt order without filling billing address in the admin.  
See the screenshot here: https://prnt.sc/gBfBAfVUKVEx
So this PR fix issue by alerting popup to force the administrator fill billing address in the admin order creation page 
See screenshot here: https://prnt.sc/DkkFovSrrPkT
Fixes: 
#changelog Alert popup to force administrator fill billing address in the admin order creation form

Alert popup to force administrator fill billing address in the admin order creation page

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

Currently, Bolt displays a general error message "Bolt order was not created successfully." if customer forgets filling require fields (Ex: shipping address, shipping method, etc) in the admin sale order creation form and clicks the Bolt button. This confuses customers since they do not know which steps they're missing  So this PR is to display the detailed error message.
See screenshot here: https://prnt.sc/KnfyxSAuYdD4
#changelog Show detail error message if customer cannot place order in admin

Show detail error message if customer cannot place order in admin

---

.circleci/phpstan/phpstan.neon
Helper/Api.php
Helper/Geolocation.php
Helper/GraphQL/Client.php
Helper/IntegrationManagement.php
Model/HttpClientAdapter.php
Test/Unit/Helper/ApiTest.php
Test/Unit/Helper/GeolocationTest.php
Test/Unit/Helper/GraphQL/ClientTest.php

M 2.4.6 support:
- replaced deprecated zend http client to laminas http client, by creating custom bolt client adapter class which incapsulated both itself.
Fixes: https://app.asana.com/0/1200879031426307/1204271392550023/f
#changelog Magento 2.2.6 support: replaced zend http client to laminas http client

Magento 2.4.6 support: replaced zend http client to laminas http client

---

view/adminhtml/templates/boltpay/button.phtml

Do not allow create order by clicking Magento submit order button if the publishable back-office key is not filled
See screenshot: https://prnt.sc/PJei_ENs6btC
#changelog Not allowing creating order by clicking Magento submit order button if the publishable back-office key is not filled

Do not allow create order by clicking Magento submit order button if the publishable back-office key is not filled

---

Helper/Cart.php
Plugin/LoginPlugin.php

M 2.4.6 support:
- replaced deprecated zend framework method calls to laminas.
Fixes: https://app.asana.com/0/1200879031426307/1204271392550023/f
#changelog Magento 2.2.6 support: replaced zend to laminas

Magento 2.4.6 support: zend calls replacing

---

Helper/Order.php

Fixed partial capture process. During partial capture creation critical order data overwritten by email sender [here](https://github.com/magento/magento2/blob/fd5b8d002a1bc62e0bd3c76c67432d9e104cdf47/app/code/Magento/Sales/Model/Order/Email/Sender/InvoiceSender.php#L125), which makes future refund webhooks calls incorrect, because during magento creditmemo totals calculation the overwritten(missed) data required.
Fixes: https://app.asana.com/0/1201931884901947/1204329729409242/f
#changelog fixed partial capture

Partial capture wrong order data fix

---

Plugin/WebapiRest/Magento/Quote/Model/QuotePlugin.php
Test/Unit/Plugin/WebapiRest/Magento/Quote/Model/QuotePluginTest.php

Orders which was created by m2 API has incorrect remote_ip value. We have "M2_PREVENT_SETTING_BOLT_IPS_AS_CUSTOMER_IP_ON_QUOTE" feature switcher for this, but it is true only for specific webhooks and looks like it was created for legacy mode. I've updated the condiition to run for all web api calls. Unfortunately magento doesn't return "remote_ip" field data during GET cart API call, so we can't fetch quote ip on backend side without adding additional endpoint to plugin.
Fixes: https://app.asana.com/0/951157735838091/1204198418877969/f
#changelog fix remote_ip quote data during magento api calls

API calls update remote_ip value

---

Plugin/LoginPlugin.php

Fixed incorrect return type of laminas json decode method.
#changelog m2 2.4.6 support fix login post plugin

M 2.4.6 support: fixed incorrect response type of laminas json decode

---

Model/Api/UpdateCart.php
Test/Unit/Model/Api/UpdateCartTest.php

When we add addon and then request again shipping methods addon is removed from the cart. In order to solve it, we applying addons to immutable quote as well
Fixes: [(link ticket)](https://app.asana.com/0/1201931884901947/1203586216479563)
#changelog Added addItemToQuote func call to apply addons to immutable quote

Added addItemToQuote func call to apply addons to immutable quote

---

Helper/Api.php
Test/Unit/Helper/ApiTest.php

In this PR we are removing logging bugsnag `BOLT API REQUEST` meta-data, because it [contains](https://app.bugsnag.com/bolt/magento-2/errors/644a57a50f876600085d7ac2?filters[event.since]=2023-05-22T19%3A43%3A00.000Z&filters[app.release_stage]=production&filters[error.status]=for_review&filters[search]=https%3A%2F%2Fwww.burtsbeesbaby.com%2F) sensitive data like "api key".
Fixes: https://app.asana.com/0/1201688509544833/1204661131427338/f
#changelog Bugsnag: remove sensitive data bugsnag logging

Bugsnag: remove sensitive data logging

---

Block/Checkout/Success.php
view/frontend/templates/checkout/success.phtml

Currently, the undefined bug js throws in the console tab on the checkout success page. And this causes google tag manager issue for Metroplex
See screenshot: https://prnt.sc/mn0rsDwB2km9
In order to fix this, we need to add initStorage before reloading the cart. FYI, the error just throws if Magento version >= 2.4.0. This is because Adobe moves storage logic into the initStorage method in the file customer-data.js
See here: https://github.com/magento/magento2/commit/5983e1733d56b1b2f15fb4f0e64094a3a4f3145d in Magento 2.4.0
#changelog Fix undefined bug js in success page

Fix undefined bug js in success page

---

Helper/Cart.php
Model/EventsForThirdPartyModules.php
Test/Unit/Helper/CartTest.php
ThirdPartyModules/Magento/CustomerBalance.php

Currently, the customer is unable to remove Magento store credit in the Bolt modal. https://prnt.sc/PMUStz7ZARJd
I created this PR to fix the issue. 
#changelog Add support to remove store credit in Bolt modal

Add support to remove store credit in Bolt modal

---

Helper/Order.php
Test/Unit/Helper/OrderTest.php

Credit Memo button on admin dashboard is not rendered. No webhook errors for affected orders. Legacy approach. 
During investigations figured out that invoice creation in legacy approach works differently from default magento, total_paid value is missing in legacy approach. 
Link to m2 default function which is responsible for validation of Credit Memo button rendering - https://github.com/magento/magento2/blob/adc4105fcfbeee29d534482d8c6d9c5c1a193a0c/app/code/Magento/Sales/Model/Order.php#L727 
Fixes: [(link ticket)](https://app.asana.com/0/1201931884901947/1204718084460094)
#changelog Added setter for total_paid value for order during capture transaction invoice creation

Added setter for total_paid value for order during capture transaction invoice creation

---

view/frontend/web/js/bolt-api-driven-checkout.js

Fix bug: authentication popup is shown incorrectly if the fetch cart is enabled. Same issue as this PR https://github.com/BoltApp/bolt-magento2/pull/1827
Investigation: 
customer().isLoggedIn  always returns undefined value even if customer logged in (see here: https://prnt.sc/CjMeFzQBepmE). So we need to correct that logic by using the condition logic customer().firstname 
Fixes: [(link ticket)](https://app.asana.com/0/1204419514580775/1205046399335814)
#changelog Fix bug: authentication popup is shown incorrectly if fetch cart is enabled

Fix bug: authentication popup is shown incorrectly if fetch cart is enabled

---

view/frontend/templates/button_product_page.phtml

Steps for replicating the issue:
- Ensure guest checkout is disabled in Magento site, Bolt and SSO, product page checkout is enabled
- Go to product detail page, and clicks Bolt checkout button
Actual result: Magento authentication popup display 
Expected result: Bolt SSO popup should be displayed
So this PR is to show Bolt SSO popup instead of Magento authentication popup on product detail page  if SSO is enabled 
Fixes: https://app.asana.com/0/1204419514580775/1205241392267730 
#changelog Product page checkout: Show Bolt SSO popup instead of Magento authentication popup if SSO is enabled

Product page checkout: Show Bolt SSO popup instead of Magento authentication popup if SSO is enabled

---

Plugin/ClearQuote.php
Test/Unit/Plugin/ClearQuoteTest.php

**Issue:**
The ClearQuote plugin causes an Infinite loop for RTA Store because of the conflict with their module Magecomm\Shipping\Model\Data.  Their DevOps engineer dug into and found that the code line $subject->getQuote()->getId();  in method beforeClearQuote is causing an Infinite loop.
Before, we created this plugin to handle the logic for product page checkout. See PR here: https://github.com/BoltApp/bolt-magento2/pull/543/files
So a simple solution here is to bypass clearQuote plugin if the product page checkout is disabled  so it will resolve the Infinite loop for RTA Store. FYI, the merchant doesn't use the product page checkout feature. 
Fixes: https://app.asana.com/0/1200879031426307/1205798880294122
#changelog Not execute clearQuote plugin if product page checkout is disabled …

Bypass clearQuote plugin if the product page checkout is disabled

---

view/frontend/templates/button_product_page.phtml

Seeing an issue on https://vintageking.com product page checkout pages on first load in a new incognito window where the `customer()` call returns a null object and then we try to access `.firstname` on that null value, throwing an error. Added a check to make sure `customer()` is non null before evaluating `customer().firstname`
https://app.asana.com/0/951157735838091/1206026904004435
#changelog Handle null customer in check callback

Handle null customer in check callback

---

Plugin/WebapiRest/Magento/Framework/Webapi/ErrorProcessorPlugin.php
etc/webapi_rest/di.xml

Currently we call magento API and it is in production mode it doesn't include details error information into 500 answer, just "An error has happened during application run. See exception log for details."
See screenshot: https://prnt.sc/Gimlmh7RXnlh
So this PR is to add plugin to shares detailed error information with bolt even in production mode
See screenshot for testing: https://prnt.sc/lJRoX-0SY3Yg
Fixes: https://app.asana.com/0/1200879031426307/1206178861644311
#changelog Include details error information into 500 answer when Bolt call Magento API to site on production mode

Include details error information into 500 answer when Bolt call Magento API to site even in production mode

---

Observer/ClearBoltShippingTaxCacheObserver.php

In the legacy plugin approach, we store cache tag in this endpoint [store_url]/rest/V1/bolt/boltpay/shipping/methods and reuse it when needed. We also build this ClearBoltShippingTaxCacheObserver obsever to clear the bolt shipping and tax cache if the tax (Magento,Taxjar) setting is changed 
See more info in this PR https://github.com/BoltApp/bolt-magento2/pull/915
However, in the M2 API approach, we use Magento native API and don't use endpoint [store_url]/rest/V1/bolt/boltpay/shipping/methods anymore. So we don't need clear cache anymore and this obsever ClearBoltShippingTaxCacheObserver isn't needed. 
#changelog Not execute ClearBoltShippingTaxCacheObserver if M2 Api approach is enabled …

Bypass ClearBoltShippingTaxCacheObserver if M2 Api approach is enabled

---

Controller/ReceivedUrlTrait.php

#changelog Fix bug sometimes order payment info isnt set on success page

Fix bug sometimes order payment info isnt set on success page

---

Helper/Cart.php

Issue: The "First name" and "Last name" fields aren't autocompleted for Logged user on the Bolt pop up 
See more detail: https://app.asana.com/0/1204419514580775/1206470335185423
#changelog Auto prefill customer first name and last name in Bolt modal if customer is logged in Magento

Auto prefill customer first name and last name in Bolt modal if customer is logged in Magento

---

Model/BoltAdditionalRequestParamsReader.php
Plugin/Magento/Framework/HTTP/PhpEnvironment/RemoteAddressPlugin.php
etc/di.xml

This PR introduces a mechanism to the Magento Bolt plugin for reading additional data from the Bolt request by custom header = `X-Bolt-Additional-Params`. For more details, see [PR #1888](https://github.com/BoltApp/bolt-magento2/pull/1888). 
If the request contains a `client_ip`, the PR replaces by magento plugin the default calls in the Magento method [here](https://github.com/magento/magento2/blob/c6bc8300e771e5e96ce9ac6c116746fe3de80544/lib/internal/Magento/Framework/HTTP/PhpEnvironment/RemoteAddress.php#L140) with this client ip value.
Fixes:  https://app.asana.com/0/1201748965125532/1207322672212344
#changelog mechanism for reading additional request params from bolt

Additional request param: client ip
