BoltApp/bolt-magento2

Helper/Cart.php
Model/Api/OrderManagement.php
Model/Api/ShippingMethods.php
composer.json
etc/module.xml
view/frontend/templates/js/replacejs.phtml

Discounts improvements. 
Order creation triggered on live page event - grand total change, when discounts are added / removed on checkout page.

1.0.2 release

---

Helper/Config.php
Test/Unit/Helper/ConfigTest.php

I finished the covering the class Bolt\Boltpay\Helper\Config

PhpUnit tests.

---

Controller/Cart/Data.php
Controller/Order/Save.php
Helper/Bugsnag.php
Helper/Cart.php
Helper/Hook.php
Model/Api/OrderManagement.php
Model/Api/ShippingMethods.php
view/frontend/templates/js/replacejs.phtml

- create order controller: remove redundant class
- order save controller: fix result format and error code
- bugsnag: remove unhandled exceptions reporting
- cart helper: refactor hints prefill, cart creation from API call, fix product image url
- hook helper: change http error type
- hooks: improve error responses
- shipping and tax hook: fix checkCartItems SKU bug, save quote address, clear selected shiping method
- replace.js: do not prefetch shipping with payment only checkout

latest development fixes and improvements

---

Helper/Hook.php
Helper/Order.php

rejected reversible -> on hold
rejected irreversible -> canceled

update transaction status map

---

Helper/Order.php
Model/Api/OrderManagement.php
Model/Api/ShippingMethods.php
view/frontend/templates/js/replacejs.phtml

Annotate orders so we can know whether order was created via AJAX call or hook
Add bugsnag error reporting if amount mismatch between quote and bolt order

additional order existence check before quote submit

---

Helper/Cart.php

This is a bug fix that should be propagated to master ASAP.
**Merge into develop before merging develop to master**.

cart billing email check fix

---

Helper/Cart.php

This is hotfix with no assana task so no PR subtask either.

old customer quotes not cleared preventing creating new order fix

---

Helper/Order.php

Try running deactivateParentQuote and deleteRedundantQuotes on every hook call not just on order create. In case something went wrong and the quotes were not cleared first time, parent quote can remain attached to the session and that might cause issues with the logged in user.

move cleaning quotes up one level

---

view/frontend/templates/js/replacejs.phtml

https://github.com/BoltApp/bolt-magento2/pull/67 split into 2

Refactor guest checkout allowed check

---

Helper/Config.php
Helper/Order.php
Model/Api/ShippingMethods.php
etc/adminhtml/system.xml
etc/config.xml

Take discount on shipping into account when calculating shipping and tax

Shipping discount

---

Helper/Cart.php

Extracted from discount code validation branch into separate PR. Allows cart recreation / update for already cloned quote. Also prevents a potential bug when cart data is generated for bugsnag report.

 get cart data fix

---

Api/DiscountCodeValidationInterface.php
Model/Api/DiscountCodeValidation.php
Model/ThirdPartyModuleFactory.php
etc/di.xml
etc/module.xml

- Moved a coupon applying process to the separate method
- Added the gift card applying process, also placed in a separate method.
- Fixed the returning statements for the errors.
- Fixed a message returning an error to the Bugsnag in exception

Updated the DiscountCodeValidation model.

---

Test/Unit/Block/JsTest.php

FIxed the error: "Error: Call to a member function getValue()on null."
Regarding travisCI job - https://travis-ci.org/BoltApp/bolt-magento2/jobs/419751258

Fixed the PHPUnit error

---

Controller/Adminhtml/Order/Save.php
Helper/Order.php

Regarding the issue https://app.asana.com/0/436430054069245/796899986783266/f
As i see the BackOffice and the default Frontend should work in the same way for this method.

Updated the saveUpdateOrder for BackOffice.

---

Model/Api/DiscountCodeValidation.php
Model/Api/ShippingMethods.php
Model/ErrorResponse.php

https://app.asana.com/0/436430054069245/752233217526404/f

Update response format for hook and ShippingAndTax

---

Block/Js.php
view/frontend/layout/default.xml
view/frontend/templates/js/replacejs.phtml
view/frontend/templates/popup.phtml

Task https://app.asana.com/0/436430054069245/800395419256951/f

Added new modal popup.

---

Block/Js.php
Helper/Config.php
Test/Unit/Block/JsTest.php
etc/adminhtml/system.xml
etc/config.xml
view/frontend/templates/js/replacejs.phtml
view/frontend/web/js/view/payment/method-renderer/boltpay.js
view/frontend/web/template/payment/boltpay.html

https://app.asana.com/0/436430054069245/806908348117542/f

Add additional button class option

---

Helper/Order.php

https://app.asana.com/0/436430054069245/802179372011120/f

Added user_note to the order comment section

---

Helper/Order.php

Notice: Undefined property: stdClass::$user_note
app/code/Bolt/Boltpay/Helper/Order.php on line 581

HotFix: Notice: Undefined property: stdClass::$user_note

---

Block/Js.php
Helper/Config.php
etc/adminhtml/system.xml
etc/config.xml
view/frontend/templates/js/replacejs.phtml

@rbres please let me know if need to add google track code from admin.
I can add additional fields to the setting.

Map out 3 step checkout tag lines for Google Analytics

---

Block/Js.php
Helper/Config.php
etc/adminhtml/system.xml
etc/config.xml
view/frontend/templates/js/replacejs.phtml

Reverts BoltApp/bolt-magento2#100

Revert "Revert "Map out 3 step checkout tag lines for Google Analytics""

---

Block/Js.php
Helper/Config.php
etc/adminhtml/system.xml
etc/config.xml
view/frontend/templates/js/replacejs.phtml

Removed a Google Track Enable option and some improvement.

Removed a Google Track Enable option and some improvement.

---

Controller/Cart/Data.php
Controller/Order/Save.php
Helper/Api.php
etc/config.xml
view/frontend/layout/checkout_cart_index.xml
view/frontend/layout/default.xml
view/frontend/templates/button.phtml
view/frontend/templates/js/replacejs.phtml

- moved popup div from head to body
- pass order create api errors to frontend
- showBoltErrorMessage moved to the isolated scope, where jQuery is available
- insert button on shopping cart page via layout/template

Insert button on shopping cart page via layout/template

---

Helper/Order.php

Task - https://app.asana.com/0/0/832044533657439/f

Prevent second email.

---

view/frontend/templates/js/replacejs.phtml

https://app.asana.com/0/436430054069245/939559464675166/f
Splitting the previous PR into separate ones

prevent order ceation API call with an empty cart

---

Helper/Order.php

Splitting the previous PR into separate ones
https://app.asana.com/0/436430054069245/939433511127701/f
https://app.asana.com/0/436430054069245/938538787123161/f

webhook fixes: invalid capture amount, payment review status

---

Observer/Adminhtml/Sales/OrderCreateProcessDataObserver.php
etc/adminhtml/events.xml

Fixed Magento's admin order creation issue (Magento core from 2.1.0 to 2.1.3 version).

(Admin) Fixed an order creation issue (2.1.0-2.1.3)

---

.circleci/config.yml
CHANGELOG.md
Helper/Cart.php
Helper/Config.php
Helper/Discount.php
Helper/Order.php
Model/Api/DiscountCodeValidation.php
Model/ThirdPartyModuleFactory.php
Observer/Adminhtml/Sales/OrderCreateProcessDataObserver.php
Plugin/AmastyGiftCardRemovePlugin.php
Test/Unit/phpunit.xml
composer.json
etc/adminhtml/events.xml
etc/di.xml
etc/frontend/di.xml
etc/module.xml
view/frontend/templates/js/replacejs.phtml

- Amasty Gift Card support
- No status after unhold fix

Release 1.1.7

---

Model/Api/ShippingMethods.php

Task: https://app.asana.com/0/941920570700290/962234572439827/f

Allow empty email in api (ApplePay)

---

Block/Js.php
Helper/Config.php
etc/adminhtml/system.xml
etc/config.xml
view/frontend/layout/default.xml
view/frontend/templates/button.phtml
view/frontend/templates/css/boltcss.phtml
view/frontend/templates/js/boltjs.phtml
view/frontend/templates/js/replacejs.phtml
view/frontend/templates/popup.phtml

https://app.asana.com/0/941920570700290/984112314972366/f
As an addition I have implemented additional (hidden) configuration whitelist / blacklist page filters so we can have more granular (full) control over which pages can load bolt js and show the checkout button.

minicart support & page whitelist / blacklist configuration

---

Model/Api/ShippingMethods.php
Test/Unit/Model/Api/ShippingMethodsTest.php

Task - "Unit test for Apple Pay shipping&tax"
https://app.asana.com/0/941920570700290/962234572439827/f

Unit test for getShippingMethods() method

---

.gitignore
CHANGELOG.md
composer.json
etc/module.xml

v119 update

---

Test/scripts/install_magento.sh

For some reason CI started failing without sudo :/

CI - sudo composer self-update

---

Helper/Cart.php

Context: asana task https://app.asana.com/0/941920570700290/978845442097717/f

Add support for item properties

---

Test/Unit/Helper/CartTest.php

Recreated from develop branch.

Add PHPUnit tests for Helper/Cart 

---

Helper/Order.php

There is no pending hook for orders created from the back office

Back office hook

---

view/frontend/templates/js/replacejs.phtml

https://app.asana.com/0/899238157173033/1110206061222383/f

checkout initialization fix

---

CHANGELOG.md
Helper/Cart.php
Model/Api/ShippingMethods.php
Test/Unit/Model/Api/ShippingMethodsTest.php
Test/scripts/ci.sh
Test/scripts/install_magento.sh
composer.json
view/frontend/templates/js/replacejs.phtml

Several fixes cherry-picked into 1.1.8 based release.
Capillus has issues with 1.1.9+.

1.1.8.x update

---

Controller/Cart/Data.php

Error: Warning: Creating default object from empty value in /home/staging/bolt-magento2-0/vendor/boltpay/bolt-magento2/Controller/Cart/Data.php on line 123
at Object.<anonymous> (hero-hoodie.html:776)
at fire (jquery.js:3232)
at Object.fireWith [as resolveWith] (jquery.js:3362)
at done (jquery.js:9840)
at XMLHttpRequest.callback (jquery.js:10311)

Fixed a currency error.

---

Helper/Cart.php
view/adminhtml/templates/boltpay/js/replacejs.phtml

Admin javascript refactored to fix outstanding email and address issues.

Back office order creation fix

---

Helper/Order.php

Task: https://app.asana.com/0/0/1107924392740868/f

Create invoice if we have zero amount.

---

Helper/Order.php

Asana task: https://app.asana.com/0/564264490825835/1113207840437480

Allow Admin to update order manually

---

Block/Checkout/Cart/ComponentSwitcherProcessor.php
Block/Form.php
Block/Js.php
Controller/Adminhtml/Cart/Data.php
Helper/Cart.php
Helper/Config.php
Test/Unit/Block/JsTest.php
Test/Unit/Helper/ConfigTest.php
etc/adminhtml/di.xml
view/adminhtml/layout/sales_order_create_index.xml
view/adminhtml/layout/sales_order_create_load_block_data.xml
view/adminhtml/templates/boltpay/button.phtml
view/adminhtml/templates/boltpay/js/replacejs.phtml
view/frontend/templates/js/replacejs.phtml

Task - https://app.asana.com/0/0/1113210174697856/f

Add multistore support

---

Block/Js.php
Controller/Order/Save.php
view/frontend/templates/js/replacejs.phtml

asana task : https://app.asana.com/0/928715412732532/1108544043000739/f

Update ajax order creation error message

---

Controller/Cart/Data.php
Helper/Cart.php

asana task https://app.asana.com/0/941920570700290/1115277704594367/f

Set hints.virtual_terminal_mode=true for admin order

---

Api/Data/ShippingOptionsInterface.php
Helper/Config.php
Model/Api/Data/ShippingOptions.php
Model/Api/DiscountCodeValidation.php
Model/Api/ShippingMethods.php
Test/Unit/Model/Api/ShippingMethodsTest.php

Asana task: https://app.asana.com/0/564264490825835/1116347704823454

Add discount back to shipping amount when address doesn't allow discount

---

Plugin/RequireJs.php
etc/di.xml

check the asana task for context, https://app.asana.com/0/941920570700290/864273388399379/f

conditionally override page-cache.js only for store versions prior to 2.2.0

---

Helper/Order.php
Model/Api/OrderManagement.php

Asana task: https://app.asana.com/0/564264490825835/1115713860206741

Partial void implementation

---

CHANGELOG.md
composer.json
etc/module.xml

Bump version to 1.1.13

---

Helper/Order.php
Plugin/OrderSenderPlugin.php
etc/di.xml

Prevent sending order confirmation email until the order payment is approved

Confirmation email postpone

---

Model/Api/DiscountCodeValidation.php
Test/Unit/Model/Api/DiscountCodeValidationTest.php

asana task https://app.asana.com/0/941920570700290/1118193263476543/f

Fix bug - fail to apply coupon if it is only applicable to specific shipping method

---

Helper/Cart.php
Model/Api/ShippingMethods.php

asana task https://app.asana.com/0/941920570700290/1118197468249385/f

Fix bug - Shipping discount entered in cart page is not picked up

---

Helper/Api.php
Helper/Order.php
Model/Payment.php
Test/Unit/Model/PaymentTest.php

Asana task: https://app.asana.com/0/564264490825835/945931188955500

Feature implement review api

---

Helper/Cart.php
Helper/Discount.php
Plugin/MirasvitCreditQuotePaymentImportDataBeforePlugin.php
etc/adminhtml/di.xml
etc/di.xml

Asana task: https://app.asana.com/0/564264490825835/1124038059584813

Support Mirasvit Store Credit

---

Helper/Cart.php
Helper/Discount.php
Helper/Order.php
Helper/Session.php
Model/Api/DiscountCodeValidation.php
Test/Unit/Model/Api/DiscountCodeValidationTest.php
etc/di.xml

Asana task: https://app.asana.com/0/564264490825835/1121586614366893

Support Mageplaza gift card

---

Helper/Hook.php
Model/Api/DiscountCodeValidation.php
Test/Unit/Model/Api/DiscountCodeValidationTest.php

- added multi-website support and corrected responses for errors.
- a bit refactoring
- fixed unit tests
Task: https://app.asana.com/0/941920570700290/1125041703113783/f

Multi-website support: Fix DiscountCodeValidation api call

---

Model/Api/CreateOrder.php

multi-website support for create_order, refactoring quoteItem validation.
After research i found that when we load quote items collection, calls an event, where the Magento updates stock info for every quoteItem. So, after Magento was validated, we have error messages if something happened with quote Item.
Example response for Bolt:
``` 
body:[{"status":"failure","error":[{"code":2001001,"data":[{"reason":"(cataloginventory): We don't have as many \"Configurable Product 121 - option 1\" as you requested."}]}]}]
```

PreAuth multi-website: check quoteItem errors.

---

Block/Js.php
Controller/Adminhtml/Order/ReceivedUrl.php
Controller/Order/ReceivedUrl.php
Controller/ReceivedUrl.php
Controller/ReceivedUrlTrait.php
Helper/ArrayHelper.php
Helper/Config.php
Helper/Order.php
Model/Api/CreateOrder.php
Test/Unit/Block/JsTest.php
Test/Unit/Helper/ArrayHelperTest.php
view/adminhtml/layout/sales_order_create_load_block_data.xml
view/adminhtml/templates/boltpay/js/replacejs.phtml
view/frontend/templates/js/replacejs.phtml

Also included code from PR https://github.com/BoltApp/bolt-magento2/pull/301

PreAuth: fixed success-redirect process on multi-website.

---

Helper/Discount.php

When applying multiple Unirgy Gift Cert codes from the shopping cart page bolt order creation results in an error.

Unirgy multiple codes

---

CHANGELOG.md
composer.json
etc/module.xml

Bump version to 2.0.0

---

Helper/Order.php

Turns out this was causing problems. Ran some quick tests with the oldest and the newest Magento version we support.

removed redundant area code emulation

---

Helper/Order.php
Model/Api/CreateOrder.php

https://app.asana.com/0/941920570700290/1130810862387296/f

Do not allow checkout after Declined Payment card

---

Helper/Cart.php

"Notice: Undefined index: email in /home/dev/public_html/vendor/boltpay/bolt-magento2/Helper/Cart.php on line 735" when testing the latest code with another fix for restaurant supply

hints prefill undefined index fix

---

Controller/Adminhtml/Cart/Data.php
Helper/Cart.php

https://app.asana.com/0/0/1131971886094727/f
In order to load connect.js and show bolt button the earliest possible
return store id and publishable key as soon as available
Fixes: (link Asana Tank)

Back office button load fix

---

Helper/Cart.php

https://app.asana.com/0/0/1131971886094733/f
store credit does not sync for back-office orders, it's reported as $0 total
Fixes: (link Asana Tank)

Aheadworks store credit back office fix

---

view/frontend/templates/js/boltjs.phtml

Optimize load procedure for connect.js by loading it asynchronously.  
Fixes: (link Asana Tank)
https://app.asana.com/0/941920570700290/1131813017023401/f

Async attribute added to the bolt-connect script

---

.circleci/config.yml
Test/scripts/install_magento.sh
operations/docker/php70/Dockerfile
operations/docker/php70/auth-sample.json
operations/docker/php71/Dockerfile
operations/docker/php71/auth-sample.json
operations/docker/php72/Dockerfile
operations/docker/php72/auth-sample.json

Improving build speed for docker containers by having them come pre-installed with magento. Shaves an additional 2 minutes off of the build. Resulting in the run speed of the container being about a minutes

Installed docker builds

---

Test/Unit/Model/PaymentTest.php

This PR adds two tests around void: successful void and getting API error from Bolt.

Add unit test for void

---

.circleci/config.yml

CI shouldn't be red. While we work on fix, let's disable test.

Disable integration test

---

Test/Unit/Model/PaymentTest.php

Add unit test for capture

---

Test/Unit/Model/PaymentTest.php

Add test for refunds

---

Model/Payment.php
Test/Unit/Model/PaymentTest.php

Add unit test for force-approval and confirm-rejection

---

Model/Payment.php
Test/Unit/Model/PaymentTest.php

Add unit test for fetchTransaction. Now all interesting methods in Payment.php is covered by unit test :)

Add unit test for fetchTransaction

---

.circleci/config.yml
Test/scripts/ci-unit.sh

Fix caching and codecov for magento 2

Fix circle cache keys

---

Helper/Cart.php
Model/Api/ShippingMethods.php
Test/Unit/Helper/CartTest.php
Test/Unit/Model/Api/DiscountCodeValidationTest.php

The customization for the merchant has already been done for 1.x version but not in a preferable way. Now it's done via plugins, without overriding classes. In order to do so I needed to refactor 2 methods and extract some of their logic into a separate methods.
https://app.asana.com/0/0/1135091400919922/f

Refactor for extending

---

Model/Api/ShippingMethods.php
Test/Unit/Model/Api/ShippingMethodsTest.php

Only collect total for the quote twice if the discount applies to shipping
Fixes: https://app.asana.com/0/564264490825835/1126529642624345

Only collect total for the quote twice if the discount applies to shipping

---

Helper/Order.php

Small update that enables us to easily customize the order statuses via plugins. See the Asana task below. The plugin for the particular request is deployed separately (copied to app/code) and its main class looks like this:
```php
<?php
namespace Bolt\Bolt\Plugin;
class Order
{
/**
* @param \Bolt\Boltpay\Helper\Order $subject
* @param callable $proceed
* @param string $transactionState
* @return string
*/
public function aroundTransactionToOrderState(
\Bolt\Boltpay\Helper\Order $subject,
callable $proceed,
string $transactionState
) {
if ($transactionState == $subject::TS_ZERO_AMOUNT) {
return \Magento\Sales\Model\Order::STATE_HOLDED;
}
return $proceed($transactionState);
}
}
```
Fixes:
https://app.asana.com/0/1125081140214268/1134394080472577/f …

Transaction state to order status mapping method

---

Block/Js.php
Block/JsProductPage.php
Helper/Config.php
view/frontend/layout/catalog_product_view.xml
view/frontend/templates/button_product_page.phtml
view/frontend/templates/js/boltjs.phtml
view/frontend/templates/js/replacejs.phtml

Reference https://app.asana.com/0/0/1103912883581240/f

Add frontend code for calling configureProductCheckout

---

CHANGELOG.md
composer.json
etc/module.xml

Version bump PR for v2.0.1 release. Includes update to CHANGELOG.md

v2.0.1 version number bump and changelog update

---

.circleci/config.yml
Test/scripts/ci-integration.sh

Added integration test back into PR's after fixing the flacky test and did some code cleanup.

re-enable test

---

Model/Api/CreateOrder.php

validateItemPrice fix for the case with multiple items with same SKU and different prices, (multivariant product)
Fixes:
https://app.asana.com/0/474713171217346/1139465075665305/f

validateItemPrice fix - multiple items with the same SKU and different prices, (multivariant product)

---

Test/scripts/ci-integration.sh

Updated discounts to tests to update new ones

updated discount tests

---

Test/scripts/ci-integration.sh

updated discount tests (#379)

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

There was redundant complexity in loading item product that led to this error. Please check the Asana task for the context
Fixes:
https://app.asana.com/0/474713171217346/1141424540626593/f

load item product fix

---

Plugin/OrderPlugin.php

check payment on order state and status override

---

.github/CODEOWNERS

Add Nathaniel to codeowners

---

Helper/Order.php

bugsnag order cancel exception

---

Api/FeatureSwitchesInterface.php
Model/Api/FeatureSwitches.php
etc/di.xml
etc/webapi.xml

This PR adds the framework for the feature switch webhook. Future PRs will actually add logic. This PR simply adds the framework for a webhook.
Fixes: https://app.asana.com/0/1141250355664307/1144555698023475

[PFS] Api Hook for feature switch change notification

---

Api/Data/FeatureSwitchInterface.php
Api/FeatureSwitchRepositoryInterface.php
Model/FeatureSwitch.php
Model/FeatureSwitchRepository.php
Model/ResourceModel/FeatureSwitch.php
Test/Unit/Model/FeatureSwitchRepositoryTest.php
etc/di.xml

This PR introduces the feature switch repository. Nothing uses this repo yet. This repo has the capability to save, read from and delete from the table. Most of the code is boilerplate code. look at feature switch repository which has the only bit of logic.
If trying to run this locally, please make sure to compile again.
Note: Magento2 strictly requires class names to be in full and not imported using `use` when dealing with repositories in order to generate the factories. This is non negotiable, and hence the code might not look exactly how we want it to. 
Fixes: Part of https://app.asana.com/0/1141250355664307/1144434411596969
Please …

[PFS][Part 1] Introduce feature switch repository

---

Api/FeatureSwitchRepositoryInterface.php
Model/FeatureSwitchRepository.php
Test/Unit/Model/FeatureSwitchRepositoryTest.php

Fixes: Part of https://app.asana.com/0/1141250355664307/1144434411596969

[PFS][Part2] Add upsert method

---

Helper/GraphQL/Client.php
Setup/UpgradeData.php

This PR makes the module fetch the latest feature switches on upgrade.
#changelog Fetch Bolt feature switches on module upgrade.
Fixes: https://app.asana.com/0/1141250355664307/1145091162039559

[PFS] Fetch feature switches on upgrade

---

Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Helper/FeatureSwitch/Manager.php
Test/Unit/Helper/FeatureSwitch/ManagerTest.php

Add lib to get feature switches.
Fixes: Part of https://app.asana.com/0/1141250355664307/1145091162039545

[PFS] Lib to get feature switches

---

Test/Unit/Model/Api/OrderManagementTest.php

Write Api/OrderManagement.php tests
Fixes: https://app.asana.com/0/1131034199022718/1137538625478178/f

Order management unit tests

---

Test/Unit/Model/PaymentTest.php

Model/Payment.php unti tests up to 100% coverage
Fixes: https://app.asana.com/0/1131034199022718/1137538625478175/f
\#changelog

Model payment unit tests

---

Test/Unit/Helper/CartTest.php
Test/Unit/Helper/OrderTest.php
Test/Unit/Model/Api/CreateOrderTest.php
Test/Unit/Model/Api/DiscountCodeValidationTest.php
Test/Unit/Model/Api/OrderManagementTest.php
Test/Unit/Model/Api/ShippingMethodsTest.php

Api/CreateOrder.php unit tests
Fixes: https://app.asana.com/0/1131034199022718/1137538625478176/f

Create order unit tests

---

CHANGELOG.md
composer.json
etc/module.xml

Bringing in https://github.com/BoltApp/bolt-magento2/commit/b463347cbabfc10a8f3926be1e6f6fc77f4be827

Bump version 2.0.3

---

Test/Unit/Controller/Cart/EmailTest.php

Added tests for ../Cart/Email.php. 
Part of https://app.asana.com/0/1131034199022718/1137538625478186/f

added tests for /Cart/Email.php

---

Test/Unit/Model/Api/DiscountCodeValidationTest.php
phpcs.xml

Api/DiscountCodeValidation.php unit test coverage
Fixes: https://app.asana.com/0/1131034199022718/1137538625478177/f
\#changelog

Discount code validation unit tests

---

Test/Unit/Controller/Cart/DataTest.php
Test/Unit/Controller/Cart/EmailTest.php

Added unit tests for /Cart/Data.php. 
There are three lines not quite covered that I will be getting coverage for later as my lack of familiarity with m2 means I'm not sure how to get it covered. Given the delays in this project already though 93% is good enough to merge and tackle other tests.
Fixes: https://app.asana.com/0/1131034199022718/1137538625478186/f

Adding unit tests for /Cart/Data.php

---

Helper/Cart.php
Helper/Discount.php
Test/Unit/Helper/CartTest.php
etc/di.xml

Support BSS store credit
Fixes: https://app.asana.com/0/564264490825835/1147949599186353

Support BSS store credit 

---

Test/Load/README.md
Test/Load/config.js
Test/Load/inputs/address.js
Test/Load/inputs/amount.js
Test/Load/inputs/jacket_item.js
Test/Load/inputs/preauth_cart.js
Test/Load/inputs/preauth_payload.js
Test/Load/inputs/shipment.js
Test/Load/inputs/shippingtax_cart.js
Test/Load/inputs/shippingtax_payload.js
Test/Load/rpcs/cartdata.js
Test/Load/rpcs/create_order.js
Test/Load/rpcs/shippingtax.js
Test/Load/user_flow.js

Load tests that will test how the M2 plugin handles high loads. 
These load tests will test the user flow through checkout: 
- Getting to the cart page (which creates the order token and order reference)
- Calling the shipping and tax web hook set up on the merchant's site
- Calling the Pre-auth web hook set up on the merchant's site 
The purpose behind these load tests is to see whether our plugin is the actual problem when a merchant has a significant number of users accessing their store. 
Fixes: https://app.asana.com/0/941920570700290/1149771740816851/f
\#changelog
- [ x ] New feature (change which adds functionality)
Please validate that you have tested your change in at least one of the following …

Load Test M2 Plugin 

---

Test/Load/README.md
Test/Load/config.js
Test/Load/inputs/address.js
Test/Load/inputs/amount.js
Test/Load/inputs/jacket_item.js
Test/Load/inputs/preauth_cart.js
Test/Load/inputs/preauth_payload.js
Test/Load/inputs/shipment.js
Test/Load/inputs/shippingtax_cart.js
Test/Load/inputs/shippingtax_payload.js
Test/Load/rpcs/cartdata.js
Test/Load/rpcs/create_order.js
Test/Load/rpcs/shippingtax.js
Test/Load/setup-files/LoadTestCartData.php
Test/Load/setup-files/LoadTestCartDataInterface.php
Test/Load/setup-files/README.md
Test/Load/setup-files/setup.sh
Test/Load/user_flow.js

This PR describes how to expose an endpoint that allows us to trigger the part of the code that is run when a user goes to the cart page (or is on any page that has a mini-cart). This endpoint adds given items to a cart, creates a bolt order, and then return the order token and order reference.
This is going to be used to Load Test the plugin. Since this endpoint is only for LoadTesting, I put all the relevant files in the Test Directory and made a README file that describes how to setup the endpoint. 
Fixes: https://app.asana.com/0/941920570700290/1149771740816849/f
\#changelog
- [ x ] New feature (change which adds functionality) …

Expose endpoint for Load Testing

---

CHANGELOG.md
composer.json
etc/module.xml

Version bump for v2.1.0
Fixes: https://app.asana.com/0/941920570700290/1150509342495990/f

Bump version 2.1.0

---

Test/Unit/Controller/Adminhtml/Cart/DataTest.php
Test/Unit/Controller/Shipping/PrefetchTest.php

This PR includes unit tests for Shipping/Prefetch.php and Adminhtml/Cart/Data.php. Work on these got mixed up in commits, apologies for giant pull request.
\#changelog

Add unit tests for Shipping/Prefetch.php and Adminhtml/Cart/Data.php

---

Model/CustomerCreditCard.php
Model/ResourceModel/CustomerCreditCard.php
Model/ResourceModel/CustomerCreditCard/Collection.php
Test/Unit/Model/CustomerCreditCardTest.php
Test/Unit/Model/ResourceModel/CustomerCreditCard/CollectionTest.php
Test/Unit/Model/ResourceModel/CustomerCreditCardTest.php

Create model, resource model and resource model collection for the credit card entity 
Fixes: https://app.asana.com/0/564264490825835/1150842025023779

Create model, resource model and collection for the credit card entity

---

Model/CustomerCreditCard.php
Model/ResourceModel/CustomerCreditCard.php
Model/ResourceModel/CustomerCreditCard/Collection.php
Setup/UpgradeSchema.php
Test/Unit/Model/CustomerCreditCardTest.php
Test/Unit/Model/ResourceModel/CustomerCreditCard/CollectionTest.php
Test/Unit/Model/ResourceModel/CustomerCreditCardTest.php
Test/Unit/Setup/UpgradeSchemaTest.php
etc/module.xml

Create schemas for generating a new table for saving the customer credit card information 
Fixes: https://app.asana.com/0/564264490825835/1150842025023778

Create schemas for generating the bolt customer credit cards table

---

view/frontend/templates/js/boltjs.phtml

connect.js already has logic to check shopping cart based on this field and used for logging etc, this PR add the "magento2" value to this field.

Add data-shopping-cart-id attribute to script tag

---

Helper/Order.php
Model/Api/OrderManagement.php
Test/Unit/Helper/OrderTest.php
Test/Unit/Model/Api/OrderManagementTest.php

Create new credit card for the customer when the pending hook is sent to Magento
Fixes: https://app.asana.com/0/564264490825835/1150842025023780

Create new credit card for the customer when the pending hook is sent to Magento

---

Helper/Order.php
Model/ResourceModel/CustomerCreditCard/Collection.php
Test/Unit/Helper/OrderTest.php

Ignore the credit card creation logic if the card exists
Fixes: https://app.asana.com/0/564264490825835/1150842025023781

Ignore the credit card creation logic if the card exists

---

view/adminhtml/templates/boltpay/button.phtml

Toggle Bolt checkout button if the administrator chooses to use a new or an existing credit card
Fixes: https://app.asana.com/0/564264490825835/1151771809488786

Toggle Bolt checkout button if the administrator chooses to use a new or an existing credit card

---

Test/Unit/Block/JsTest.php
Test/Unit/Controller/Adminhtml/Cart/DataTest.php
Test/Unit/Controller/Cart/DataTest.php
Test/Unit/Controller/Cart/EmailTest.php
Test/Unit/Controller/Shipping/PrefetchTest.php
Test/Unit/Helper/CartTest.php
Test/Unit/Helper/ConfigTest.php
Test/Unit/Helper/FeatureSwitch/DeciderTest.php
Test/Unit/Helper/FeatureSwitch/ManagerTest.php
Test/Unit/Helper/GraphQL/ClientTest.php
Test/Unit/Helper/MetricsClientTest.php
Test/Unit/Helper/Shared/ApiUtilsTest.php
Test/Unit/Model/Api/FeatureSwitchesHookTest.php
Test/Unit/Model/Api/ShippingMethodsTest.php
Test/Unit/Model/FeatureSwitchRepositoryTest.php
Test/Unit/Model/PaymentTest.php

Refactor all test methods to use @test annotation and remove test prefixes
verified we have same number of running tests after my change

Refactor all test methods to use @test annotation

---

.circleci/config.yml

This PR introduces commands to Bolt Magento 2 CI. This will make setting up mx-greenkeeper easier.
Towards Fixing: https://app.asana.com/0/home/1120201793092518/1151422723872713
\#changelog

[CircleCI] Commands

---

.circleci/config.yml

Send notification to #mx-greenkeeper if build fails on master

[Greenkeeper] Notify on build fail in master

---

Controller/Order/ReceivedUrl.php
Controller/Order/Save.php
Test/Unit/Controller/Order/SaveTest.php

Added tests for `Controller/Order/Save.php`. Some methods were changed from `private` to `protected` to make testing easier. Also added some coverage ignore decorators to methods in `ReceivedUrl.php` that were performing no logic, just retrieving things.
Fixes: https://app.asana.com/0/1131034199022718/1137538625478187/f

Add tests for Controller/Order/Save

---

Controller/Adminhtml/Order/Save.php
Test/Unit/Controller/Adminhtml/Order/SaveTest.php

Added tests for Adminhtml/Order folder, which is just Save.php.
Fixes: https://app.asana.com/0/1131034199022718/1137538625478187/f

Add tests for Adminhtml/Order

---

Test/Unit/Controller/Order/ReceivedUrlTest.php

Added one test for ReceivedUrl execute method, which is contained in ReceivedUrlTrait.php. This test is only for the successful case and includes the initial structure and variable set-up that will be needed for all the test covering exception cases. As this is already a large pull request (200+ lines) I've decided to break it up and add the rest of the tests in future PR(s).
Some of the constants are "good for now" and will potentially be updated as I progress through the rest of the tests. Input on better values welcome.
Fixes: https://app.asana.com/0/1131034199022718/1153867691786721/f
\#changelog

Add happy path test for Order/ReceivedUrl.php

---

Controller/Order/ReceivedUrl.php
Test/Unit/Controller/Order/ReceivedUrlTest.php

Added test for an error case, also removed the attributes flagging methods in ReceivedUrl to be ignored by code coverage. In adding the error case I did some refactoring of how mocks were being created and managed.
Fixes: https://app.asana.com/0/1131034199022718/1153867691786721/f
\#changelog

Add tests for receivedUrlTrait error cases

---

Controller/Order/ReceivedUrl.php
Test/Unit/Controller/Order/ReceivedUrlTest.php

Add test for NoSuchEntityException catching flow. Refactored test class to streamline creation of some mock objects. 
Fixes: https://app.asana.com/0/1131034199022718/1153867691786721/f
\#changelog

Add test for NoSuchEntityException catch, minor refactoring of test class.

---

Helper/Cart.php
Helper/Order.php
Model/Api/ShippingMethods.php
Test/Unit/Helper/CartTest.php

Set proper currency code everywhere except `getRoundAmount` in Cart.php, which I'll refactor in next PR

Remove most of hardcoded USD

---

Controller/Order/ReceivedUrl.php
Test/Unit/Controller/Order/ReceivedUrlTest.php

Localized exception error case coverage
Fixes: https://app.asana.com/0/1131034199022718/1153867691786721/f
\#changelog

Add coverage of localized exception

---

Model/Api/ShippingMethods.php
Test/Unit/Model/Api/ShippingMethodsTest.php

Fix typo in ShippingMethods.php

---

Helper/Api.php
Model/CustomerCreditCard.php
Observer/Adminhtml/Sales/RechargeCustomer.php
Test/Unit/Model/CustomerCreditCardTest.php
Test/Unit/Observer/Adminhtml/Sales/RechargeCustomerTest.php
etc/adminhtml/events.xml

Recharge the customer if the administrator uses an existing credit card then submits the order
Fixes: https://app.asana.com/0/564264490825835/1151771809488787

Recharge the customer if the administrator uses an existing credit card then submits the order

---

Model/Api/CreateOrder.php
Model/Api/DiscountCodeValidation.php
Test/Unit/Model/Api/CreateOrderTest.php
Test/Unit/Model/Api/DiscountCodeValidationTest.php

Set proper currency code in discount hook and preauth hook so amount is properly calculated

Set currency in discount hook and create order hook

---

Test/Load/README.md
Test/Load/config.js
Test/Load/inputs/preauth_payload.js
Test/Load/user_flow.js

- Add SLEEP environment variable in load test scripts so that we simulate tests that will test loads of less than a user per second (i.e 1 user every 5 seconds)
- Add BLACKFIRE_HEADER environment variable so that we can create a profile of the execution path of the requests using BlackFire
Fixes: https://app.asana.com/0/941920570700290/1154668228212537
\#changelog

Add env vars to load tests

---

Block/Adminhtml/Customer/CreditCard/Tab/CreditCard.php
Block/Adminhtml/Customer/CreditCard/Tab/View/CardNumber.php
Block/Adminhtml/Customer/CreditCard/Tab/View/CardType.php
Block/Adminhtml/Customer/CreditCard/Tab/View/CreditCard.php
Controller/Adminhtml/Customer/CreditCard.php
Model/CustomerCreditCard.php
Test/Unit/Block/Adminhtml/Customer/CreditCard/Tab/CreditCardTest.php
Test/Unit/Block/Adminhtml/Customer/CreditCard/Tab/View/CardNumberTest.php
Test/Unit/Block/Adminhtml/Customer/CreditCard/Tab/View/CardTypeTest.php
Test/Unit/Block/Adminhtml/Customer/CreditCard/Tab/View/CreditCardTest.php
Test/Unit/Controller/Adminhtml/Customer/CreditCardTest.php
Test/Unit/Model/CustomerCreditCardTest.php
etc/module.xml
view/adminhtml/layout/boltpay_customer_creditcard.xml
view/adminhtml/layout/customer_index_edit.xml

List all credit cards in the admin customer detail page
See the demo screenshot: https://www.screencast.com/t/y9tn5BXLW
Fixes: https://app.asana.com/0/564264490825835/1152758055340089

List all credit cards in the admin customer detail page

---

Block/Form.php
Model/ResourceModel/CustomerCreditCard/Collection.php
Test/Unit/Block/FormTest.php
Test/Unit/Model/ResourceModel/CustomerCreditCard/CollectionTest.php
view/adminhtml/templates/boltpay/button.phtml

Render the credit card list in a select box when the administrator chooses Bolt as the payment
Here are the demo screenshots:
https://screencast.com/t/9vDs7mnHRK
https://www.screencast.com/t/LWvUxKEe
Fixes: https://app.asana.com/0/564264490825835/1151771809488785

Render the credit card list in a select box when the administrator chooses Bolt as the payment

---

Helper/Order.php
Model/CustomerCreditCard.php
Test/Unit/Helper/OrderTest.php
Test/Unit/Model/CustomerCreditCardTest.php

Refactor PR https://github.com/BoltApp/bolt-magento2/pull/441 based on Yevhen’s requests
Fixes: https://app.asana.com/0/564264490825835/1150842025023781

Refactore the PR 441

---

Model/ResourceModel/CustomerCreditCard/Collection.php
Test/Unit/Block/FormTest.php
Test/Unit/Model/ResourceModel/CustomerCreditCard/CollectionTest.php
view/adminhtml/templates/boltpay/button.phtml

Refactor PR https://github.com/BoltApp/bolt-magento2/pull/443/
Fixes: https://app.asana.com/0/564264490825835/1151771809488785

Refactor PR 443

---

Helper/Session.php
Test/Unit/Helper/OrderTest.php
Test/Unit/Helper/SessionTest.php
Test/Unit/Helper/TestHelper.php

Unit Test: Bolt\Boltpay\Helper\Session
Fixes: https://app.asana.com/0/564264490825835/1155509005367105

Unit Test: Bolt\Boltpay\Helper\Session

---

Helper/Config.php
Test/Unit/Block/JsTest.php
Test/Unit/Helper/ConfigTest.php
etc/adminhtml/system.xml
etc/config.xml

If custom api, cdn and merchant dash urls are set, this allows magento2 module to work with a developer's local development setup. This basically links M2 to all of local dev.
Bonus: We can now have magento stores for staging, and during storm CD
\#changelog

[Dev] Dev mode for local development

---

Api/OrderManagementInterface.php
Helper/Cart.php
Model/Api/OrderManagement.php
Test/Unit/Helper/CartTest.php
Test/Unit/Model/Api/OrderManagementTest.php

Handle cart.create API call. We need it for Product page checkout
Fixes: https://app.asana.com/0/0/1155249819640873/f
Restrictions
- for guest users only
- doesn't work for multistore

Handle cart.create API call

---

Test/Unit/Helper/MetricsClientTest.php

Complete Helper\MetricsClient coverage
Fixes: https://app.asana.com/0/1131034199022718/1155069140173378/f
\#changelog

Complete Helper\MetricsClient coverage

---

Helper/Config.php
Test/Unit/Helper/ConfigTest.php
etc/adminhtml/system.xml
etc/config.xml

Fixes: https://app.asana.com/0/0/1103912883581239/f

Add plugin option to enable/disable product page checkout

---

Test/Unit/Helper/ArrayHelperTest.php

Complete Helper\ArrayHelper coverage
Fixes: https://app.asana.com/0/1131034199022718/1155031608239089/f
\#changelog

Complete Helper\ArrayHelper coverage

---

Helper/Cart.php
Helper/Order.php
Model/Api/ShippingMethods.php
Test/Unit/Helper/CartTest.php
Test/Unit/Model/Api/ShippingMethodsTest.php

We need to do a few changes in order creating process to handle Product page checkout
Fixes: https://app.asana.com/0/0/1155249819640877/f

Product page checkout: changes for shipping&tax and create_order

---

Block/Js.php
Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Test/Unit/Block/JsTest.php

This PR will allow slow roll out of bolt, controlling it via a feature switch.
#changelog Allows slow roll out of Bolt

Feature switch to manage slow roll out

---

Block/JsProductPage.php
Test/Unit/Block/JsProductPageTest.php

I had a merge which broke master without a conflict. This fixes that.
\#changelog

Fix master

---

Block/Js.php
Controller/Cart/Hints.php
Helper/Cart.php
Helper/Config.php
Test/Unit/Block/JsTest.php
Test/Unit/Controller/Cart/HintsTest.php
view/frontend/templates/button_product_page.phtml

Add hints support for product page checkout
Fixes: https://app.asana.com/0/0/1119824466711711/f

Add hints support for product page checkout

---

Helper/Config.php
Test/Unit/Helper/ConfigTest.php

Complete Helper\Config coverage
Fixes: https://app.asana.com/0/1131034199022718/1155031608239091/f
\#changelog

Complete Helper\Config coverage

---

.github/CODEOWNERS

Update codeowners - removing Ethan

---

Test/Unit/Helper/OrderTest.php

Fixes: https://app.asana.com/0/0/1156165568164481/f

Add test for prepareQuote() for Product page checkout

---

Test/Unit/Model/ResourceModel/FeatureSwitchTest.php

Unit Test: Bolt\Boltpay\Model\ResourceModel\FeatureSwitch
Fixes: https://app.asana.com/0/564264490825835/1156458420303801

Unit Test: Bolt\Boltpay\Model\ResourceModel\FeatureSwitch

---

Test/Unit/Model/Api/Data/ShippingOptionTest.php

Unit Test: Bolt\Boltpay\Model\Api\Data\ShippingOption
Fixes: https://app.asana.com/0/564264490825835/1156274257891465

Unit Test: Bolt\Boltpay\Model\Api\Data\ShippingOption

---

Test/Unit/Model/Api/Data/ShippingOptionsTest.php

Unit Test: Bolt\Boltpay\Model\Api\Data\ShippingOptions
Fixes: https://app.asana.com/0/564264490825835/1156289651972137

Unit Test: Bolt\Boltpay\Model\Api\Data\ShippingOptions

---

Test/Unit/Model/Api/Data/ShippingTaxTest.php

Unit Test: Bolt\Boltpay\Model\Api\Data\ShippingTaxFixes: 
Fixes: https://app.asana.com/0/564264490825835/1156282132911963

Unit Test: Bolt\Boltpay\Model\Api\Data\ShippingTax

---

Test/Unit/Helper/MetricTest.php

Unit Test: Bolt\Boltpay\Helper\Metric
Fixes: https://app.asana.com/0/564264490825835/1155856547564851

Unit Test: Bolt\Boltpay\Helper\Metric

---

Helper/Log.php
Test/Unit/Helper/LogTest.php

Unit Test: Bolt\Boltpay\Helper\Log 
Fixes: https://app.asana.com/0/564264490825835/1155443326571665
\#changelog

Unit Test: Bolt\Boltpay\Helper\Log

---

Block/Adminhtml/Customer/CreditCard/Tab/View/CreditCard.php
Block/Adminhtml/Customer/CreditCard/Tab/View/DeleteAction.php
Controller/Adminhtml/Customer/DeleteCreditCard.php
Test/Unit/Block/Adminhtml/Customer/CreditCard/Tab/View/CreditCardTest.php
Test/Unit/Block/Adminhtml/Customer/CreditCard/Tab/View/DeleteActionTest.php
Test/Unit/Controller/Adminhtml/Customer/DeleteCreditCardTest.php

Remove credit card in the admin customer detail page
Fixes: https://app.asana.com/0/564264490825835/1152758055340090

Remove credit card in the admin customer detail page

---

Block/Customer/CreditCard.php
Controller/Customer/DeleteCreditCard.php
Test/Unit/Block/Customer/CreditCardTest.php
Test/Unit/Controller/Customer/DeleteCreditCardTest.php
view/frontend/templates/customer/creditcard.phtml

Delete credit card in the customer detail page
See the demo screenshot: https://www.screencast.com/t/hux5DIuEqPA
Fixes: https://app.asana.com/0/564264490825835/1155418911999809

Delete credit card in the customer detail page

---

Block/Customer/CreditCard.php
Controller/Customer/CreditCard.php
Controller/Customer/DeleteCreditCard.php
Test/Unit/Block/Customer/CreditCardTest.php
Test/Unit/Controller/Customer/DeleteCreditCardTest.php
view/frontend/layout/boltpay_customer_creditcard.xml
view/frontend/layout/customer_account.xml
view/frontend/templates/customer/creditcard.phtml

List all credit cards in the customer detail page
See the screenshot demo: https://www.screencast.com/t/6nqdhvYoTY
Fixes: https://app.asana.com/0/564264490825835/1155415097095293

List all credit cards in the customer detail page

---

Setup/RecurringData.php

Changes `UpgradeData` -> `RecurringData`. This lets us get the version number of the upgrade just applied, so we can pass this back to Bolt to track merchant's current Bolt module version.
Fixes: https://app.asana.com/0/941920570700290/1157054368227945/f

Change UpgradeData -> RecurringData

---

view/adminhtml/templates/boltpay/js/replacejs.phtml
view/frontend/templates/button_product_page.phtml
view/frontend/templates/js/replacejs.phtml

Remove ajaxPost and use jQuert $.post in phtml templates (javascript).
Fixes: https://app.asana.com/0/941920570700290/1155745644813038/f
\#changelog

Use jquery ajax in templates

---

view/frontend/templates/button_product_page.phtml

Line "customerData.init();" triggers JS error on same environments. Hopefully, we can just delete it.
Fixes: https://app.asana.com/0/941920570700290/1158207181659897/f

Fix product page checkout JS code

---

view/frontend/templates/button_product_page.phtml

logged in customer fix

---

Block/Js.php
Helper/Cart.php
view/frontend/templates/button_product_page.phtml

ppc multistore and session quote fix

---

Controller/ReceivedUrlTrait.php
Helper/Order.php
Model/Api/DiscountCodeValidation.php
Test/Unit/Controller/Order/ReceivedUrlTest.php
Test/Unit/Helper/OrderTest.php
Test/Unit/Model/Api/DiscountCodeValidationTest.php

fix failed hooks and discount validation

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

There's a collision bug with Magento\PageBuilder (EE only) module. Details in Asana task below.
Fixes: https://app.asana.com/0/941920570700290/1159330950508011/f
\#changelog Fix collision issue with Magento\PageBuilder in 2.3.4 EE

fix collision bug with EE PageBuilder module

---

Block/Checkout/Success.php

After a successful payment and redirect to success page the items remain in minicart. When refreshing the page or opening the (empty) shopping cart page again they are gone.
Fixes: https://app.asana.com/0/941920570700290/1159551121447084/f
\#changelog

cart not cleared after purchase in M2.3.4 bug fix

---

CHANGELOG.md
composer.json
etc/module.xml

Version bump v2.2.0
Fixes: https://app.asana.com/0/436430054069245/1154357850270438/f
\#changelog

Bump version 2.2.0

---

.circleci/config.yml

Bump composer memory limit to 3G during circle unit test runs.
\#changelog

Bump composer memory limit to 3G

---

Cron/DeactivateQuote.php
Test/Unit/Cron/DeactivateQuoteTest.php
etc/cron_groups.xml
etc/crontab.xml

Create a Cron job to deactivate quotes which belong to created orders
Fixes: https://app.asana.com/0/564264490825835/1157946616328017

Create a Cron job to deactivate quotes which belong to created orders

---

view/frontend/templates/js/replacejs.phtml

Undefined cart error is a result of click on bolt checkout button before plugin JavaScript calls BoltCheckout.configure.
With this change we will be able to solve the error by passing custom button class, CSS and JavaScript via Magento admin plugin configuration. As discussed, **we won't be using "disabled"** **button in the** **plugin core**. Moreover, all hardcoded **Bolt checkout and button related CSS will be removed from the plugin**, "disabled" included. However, we will have the option to set it up it via config, if we need, as following:
**Additional Checkout Button Class**: (in addition to with-cards, flexible etc)
```
disabled
```
**Global CSS**:
```css
.bolt-multi-step-checkout.disabled {
opacity: 0.5;
cursor: default;
pointer-events: none;
}
```
**Additional Javascript**: …

execute additional javascript, passed via config, from plugin isolated scope

---

view/frontend/templates/js/replacejs.phtml

Fix for the case when connect.js executes after plugin javascript.
\#changelog

Do not createOrder / configure checkout until BoltCheckout is defined

---

Block/Checkout/Cart/ComponentSwitcherProcessor.php
Test/Unit/Block/Checkout/Cart/ComponentSwitcherProcessorTest.php

Store credit / reward points component processor switcher fix.
Caused paypal issue described in the task below.
Fixes: https://app.asana.com/0/1125081140214268/1150344420444785/f
\#changelog

store credit / reward points component processor switcher fix

---

Block/JsProductPage.php
Helper/Cart.php
Helper/Config.php
Test/Unit/Block/JsProductPageTest.php
Test/Unit/Helper/CartTest.php
view/frontend/templates/button_product_page.phtml

Fixes: https://app.asana.com/0/0/1119824466711710/f
\#changelog Add support for PPC Configurable Products

Product page checkout: add support for configurable products

---

Helper/Order.php
Test/Unit/Helper/OrderTest.php

Bug in pre-auth flow - dispatchPostCheckoutEvents is called twice, once with parent and another time with immutable quote in hook. This leads to some processing done twice, eg. deducting Amasty reward points.
Expected: Always use the parent quote, thus called once per order
Fixes: https://app.asana.com/0/941920570700290/1162518950067671/f
\#changelog

use parent quote in after order creation processing

---

Helper/Cart.php
Model/Api/OrderManagement.php
Model/ErrorResponse.php
Test/Unit/Model/Api/OrderManagementTest.php

Fixes: https://app.asana.com/0/0/1156147394609521/f

Product page checkout: add special codes for inventory errors

---

Helper/Order.php
Test/Unit/Helper/OrderTest.php

Fixes: https://app.asana.com/0/0/1161039988578263/f

PPC: temporary set quote active to true for third party plugins

---

Plugin/ClearQuote.php

Fixes: https://app.asana.com/0/0/1155249819640874/f

Don't empty cart after PPC checkout

---

Helper/CheckboxesHandler.php
Helper/Order.php
Model/Api/OrderManagement.php
Test/Unit/Helper/CheckboxesHandlerTest.php
Test/Unit/Helper/OrderTest.php
Test/Unit/Model/Api/OrderManagementTest.php

Fixes: https://app.asana.com/0/941920570700290/1155656238889067/f
\#changelog [Beta] Add support for custom checkboxes.

Add support for custom checkboxes

---

.github/stale.yml

[Stale] Add github stale bot

---

view/frontend/templates/button_product_page.phtml

Fixes: https://app.asana.com/0/941920570700290/1162975014277289/f

Do not show bolt product page checkout button if option is disabled

---

CHANGELOG.md
composer.json
etc/module.xml

Version bump. Do not merge until rc is approved for release.

2.3.0 version bump commit

---

Helper/Order.php

In PR https://github.com/BoltApp/bolt-magento2/pull/544/ I didn't use camelCase variable name, want to fix it now
Fixes: https://app.asana.com/0/941920570700290/1163893469797555/f

Change variable name to camelCase

---

.github/pull_request_template.md

Update PR template!
#changelog Update PR template

Update PR template for new changelog procedures

---

CHANGELOG.md
composer.json
etc/module.xml

Version bump
#changelog Version bump

Version bump to 2.4.0

---

view/frontend/templates/button_product_page.phtml

Simple products can have custom options. They were not covered in our plugin so far.
Fixes: https://app.asana.com/0/941920570700290/1166699277306729/f
#changelog custom options support for simple products in product page checkout

PPC simple product custom options support

---

view/frontend/templates/js/replacejs.phtml

M2 2.4.0 and M2 2.3.0 doesn't open Bolt Checkout in IE
Fixes: https://app.asana.com/0/436430054069245/1167024055895587/f
#changelog fix promise return value in barrier

fix promise return value in barrier

---

.circleci/config.yml
.circleci/scripts/rc-tag.sh

Create an autotagger to tag an rc candidate every 3 weeks.
Fixes: [ENG-221]
#changelog Create an autotagger to tag an rc candidate every 3 weeks
[ENG-221]: https://boltpay.atlassian.net/browse/ENG-221

Create an autotagger to tag an rc candidate every 3 weeks

---

Test/Unit/Block/Checkout/ComponentSwitcherProcessorTest.php

Unit test: Bolt\Boltpay\Block\Checkout\ComponentSwitcherProcessor
Fixes: https://app.asana.com/0/564264490825835/1167428405040633
#changelog Unit test: Bolt\Boltpay\Block\Checkout\ComponentSwitcherProcessor

Unit test: Bolt\Boltpay\Block\Checkout\ComponentSwitcherProcessor

---

view/adminhtml/templates/boltpay/button.phtml

Escape HTML in view/adminhtml/templates/boltpay/button.phtml
Fixes: https://app.asana.com/0/564264490825835/1167309587978324
#changelog Escape HTML in view/adminhtml/templates/boltpay/button.phtml

Escape HTML in view/adminhtml/templates/boltpay/button.phtml

---

Controller/Customer/DeleteCreditCard.php
Test/Unit/Controller/Customer/DeleteCreditCardTest.php

Validate customer session prior to deleting credit card
Fixes: https://app.asana.com/0/564264490825835/1167212907267857
#changelog Validate customer session prior to deleting credit card

Validate customer session prior to deleting credit card

---

Test/Unit/Model/Service/InvoiceServiceTest.php

Unit Test: Bolt\Boltpay\Model\Service\InvoiceService
Fixes: https://app.asana.com/0/564264490825835/1166437205608665
#changelog Unit Test: Bolt\Boltpay\Model\Service\InvoiceService

Unit Test: Bolt\Boltpay\Model\Service\InvoiceService

---

Test/Unit/Model/ErrorResponseTest.php

Unit test: Bolt\Boltpay\Model\ErrorResponse
Fixes: https://app.asana.com/0/564264490825835/1166300305743761
#changelog Unit test: Bolt\Boltpay\Model\ErrorResponse

Unit test: Bolt\Boltpay\Model\ErrorResponse

---

etc/config.xml
view/frontend/templates/css/boltcss.phtml

Initial commit for removing css classes from boltcss.phtml. Some of these are used by custom integrations for some m2 merchants, so there will need to be work done to get them put into the global css field on the config page until we can make a more permanent fix by moving options elsewhere. 
#changelog Removes classes from boltcss.phtml

ENG-122 Removed css classes from boltcss.phtml file

---

Model/Api/CreateOrder.php
Test/Unit/Model/Api/CreateOrderTest.php

#Description
Create_order request:
https://app.datadoghq.com/logs?cols=core_host%2Ccore_service&event=AQAAAXC_e5AYrc927wAAAABBWENfZkNqb3cydFVuNnRSYTRBQQ&from_ts=1583592107155&index=&live=true&messageDisplay=inline&query=%40trace_id%3AG22ovP6WdEuTgDBr1rg%3D%3D&stream_sort=desc&to_ts=1583764907155
Report api\/614499078467
"Fatal Error: 'Uncaught Error: Call to a member function render() on string in \/chroot\/home\/a30cdfff\/dermadoctor.com\/magento\/vendor\/boltpay\/bolt-magento2\/Model\/Api\/CreateOrder.php:532\nStack trace:\n#0 \/chroot\/home\/a30cdfff\/dermadoctor.com\/magento\/vendor\/boltpay\/bolt-magento2\/Model\/Api\/CreateOrder.php(511): Bolt\\Boltpay\\Model\\Api\\CreateOrder->hasItemErrors(Object(Magento\\Quote\\Model\\Quote\\Item\\Interceptor))\n#1 …

Fix bug "Fatal Error: Uncaught Error: Call to a member function render() on string" - https://prnt.sc/re1ysy

---

Block/Form.php
Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Test/Unit/Block/FormTest.php
view/adminhtml/templates/boltpay/button.phtml

Add feature swtich with default off for the feature/admin reorder for logged in customer 
Fixes: https://app.asana.com/0/564264490825835/1164870981236849
#changelog Add feature swtich with default off for the feature/admin reorder for logged in customer

Add feature swtich with default off for the feature/admin reorder for logged in customer

---

.github/CODEOWNERS

Remove Yevhen
#changelog Update CODEOWNERS remove Yevhen

Update CODEOWNERS remove Yevhen

---

Test/Unit/Controller/Adminhtml/Order/ReceivedUrlTest.php

Unit Test: Bolt\Boltpay\Controller\Adminhtml\Order\ReceivedUrl
Fixes: https://app.asana.com/0/564264490825835/1167590715220267
#changelog Unit Test: Bolt\Boltpay\Controller\Adminhtml\Order\ReceivedUrl

Unit Test: Bolt\Boltpay\Controller\Adminhtml\Order\ReceivedUrl

---

Block/Js.php
Helper/Config.php
Test/Unit/Block/JsTest.php
Test/Unit/Helper/ConfigTest.php
etc/adminhtml/system.xml
etc/config.xml
view/adminhtml/layout/adminhtml_system_config_edit.xml
view/adminhtml/web/js/validation.js
view/frontend/templates/button.phtml
view/frontend/templates/button_product_page.phtml
view/frontend/templates/js/replacejs.phtml

Add support for boltPrimaryActionColor
Fixes: [ENG-123]
#changelog Add plugin option to configure checkout button color
[ENG-123]: https://boltpay.atlassian.net/browse/ENG-123

ENG-123: Support boltPrimaryActionColor

---

Test/Unit/Model/ThirdPartyModuleFactoryTest.php

Unit Test: Bolt\Boltpay\Model\ThirdPartyModuleFactory
Fixes: https://app.asana.com/0/564264490825835/1166266009370491
#changelog  Unit Test: Bolt\Boltpay\Model\ThirdPartyModuleFactory

 Unit Test: Bolt\Boltpay\Model\ThirdPartyModuleFactory

---

Block/Adminhtml/Order/View/Tab/Info.php
Test/Unit/Block/Adminhtml/Order/View/Tab/InfoTest.php
view/adminhtml/layout/sales_order_view.xml
view/adminhtml/templates/order/view/tab/info/payment.phtml

Show CC TYpe, CC Last 4 in the admin order detail page
See demo screenshot: https://screencast.com/t/RSJ3VN9e 
Fixes: https://app.asana.com/0/564264490825835/1165438792994569
#changelog Show CC TYpe, CC Last 4 in the admin order detail page

Show CC Type, CC Last 4 in the admin order detail page

---

Test/Unit/Setup/RecurringDataTest.php

Unit Test: Bolt\Boltpay\Setup\RecurringData 
Fixes: (https://app.asana.com/0/564264490825835/1168435359917049
#changelog Unit Test: Bolt\Boltpay\Setup\RecurringData

Unit Test: Bolt\Boltpay\Setup\RecurringData

---

CHANGELOG.md
composer.json
etc/module.xml

#changelog Version bump
- [x ] I have commented my code, particularly in hard-to-understand areas.

2.5.0 version bump

---

Api/DebugInterface.php
Model/Api/Data/BoltConfigSetting.php
Model/Api/Data/DebugInfo.php
Model/Api/Data/PluginVersion.php
Model/Api/Debug.php
Test/Unit/Model/Api/DebugTest.php

This PR changes the debug endpoint response to universal endpoint format.
Fixes: [ENG-553]
#changelog [Debug Endpoint] [ENG-553] change debug endpoint to universal endpoint format
[ENG-553]: https://boltpay.atlassian.net/browse/ENG-553

[Debug Endpoint] [ENG-553] change debug endpoint to universal endpoint format

---

Model/Api/Data/DebugInfo.php
Test/Unit/Model/Api/DebugTest.php

This PR updates JSON field names in debug endpoint response to snake cases to make it consistent with other merchant APIs.
Fixes: [ENG-571]
#changelog [Debug Endpoint] ENG-571: Update JSON field names to snake case
[ENG-571]: https://boltpay.atlassian.net/browse/ENG-571

[Debug Endpoint] ENG-571: Update JSON field names to snake case

---

Helper/Api.php
Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Helper/TrackingSaveObserver.php
Observer/TrackingSaveObserver.php
Test/Unit/Observer/TrackingSaveObserverTest.php
etc/events.xml

#changelog [WIP] Add tracking observer to M2
**Project summary:**
Frontend changes:
add &lt;div class="bolt-track-order"&gt;&lt;/div&gt;
include core script account.js
As a result "account" button is shown
2. When a user clicks on the "account" button, they see iFrame with a prompt to enter an email.
3. Bolt server calls the new plugin endpoint to know if there is magento2 user with this email.
If yes, a user is redirected to M2 login page
If no, a user fills in the phone number, enters SMS code, and sees a page with all orders from this store.
4. When merchant staff add track number into order plugin, send it to …

ENG-535 Add tracking observer to M2

---

Test/Unit/Plugin/LoginPostPluginTest.php

Unit test: Bolt\Boltpay\Plugin\LoginPostPlugin
Fixes: https://app.asana.com/0/564264490825835/1170133973612753
#changelog Unit test: Bolt\Boltpay\Plugin\LoginPostPlugin

Unit test: Bolt\Boltpay\Plugin\LoginPostPlugin

---

Test/Unit/Plugin/MirasvitCreditQuotePaymentImportDataBeforePluginTest.php

Unit Test: Bolt\Boltpay\Plugin\MirasvitCreditQuotePaymentImportDataBeforePlugin
#changelog Unit Test: Bolt\Boltpay\Plugin\MirasvitCreditQuotePaymentImportDataBeforePlugin

Unit Test: Bolt\Boltpay\Plugin\MirasvitCreditQuotePaymentImportDataBeforePlugin

---

Test/Unit/Plugin/QuotePluginTest.php

Unit Test: Bolt\Boltpay\Plugin\QuotePlugin
Fixes: https://app.asana.com/0/564264490825835/1170432066325193
#changelog Unit Test: Bolt\Boltpay\Plugin\QuotePlugin

Unit Test: Bolt\Boltpay\Plugin\QuotePlugin

---

Helper/Order.php
Model/Api/CreateOrder.php
Model/Api/OrderManagement.php
Test/Unit/Model/Api/CreateOrderTest.php
Test/Unit/Model/Api/OrderManagementTest.php

Update webhook response message to include order data for debugging
See the demo screenshot: https://prnt.sc/rvhr7x
Fixes: https://app.asana.com/0/436430054069245/1170621169479145
#changelog Update webhook response message to include order data for debugging

Update webhook response message to include order data for debugging

---

Test/Unit/Plugin/CheckSettingsUpdateTest.php
Test/Unit/Plugin/OrderSenderPluginTest.php

Correct namespace in the CheckSettingsUpdateTest class and 
Unit Test: Bolt\Boltpay\Plugin\OrderSenderPlugin
Fixes: https://app.asana.com/0/564264490825835/1170804745347073
#changelog Correct namespace in the CheckSettingsUpdateTest class and Unit Test: Bolt\Boltpay\Plugin\OrderSenderPlugin

Correct the namespace in the CheckSettingsUpdateTest class and Unit Test: Bolt\Boltpay\Plugin\OrderSenderPlugin

---

Test/Unit/Plugin/RequireJsTest.php

Unit test: Bolt\Boltpay\Plugin\RequireJs
Fixes: https://app.asana.com/0/564264490825835/1170861239316281
#changelog Unit test: Bolt\Boltpay\Plugin\RequireJs

Unit test: Bolt\Boltpay\Plugin\RequireJs

---

Controller/Cart/Hints.php
Test/Unit/Controller/Cart/HintsTest.php

Correct the exception class in the catch block. 
See here: https://www.screencast.com/t/xDlSrog0
Fixes: https://app.asana.com/0/564264490825835/1170092286517577
#changelog Correct the exception class in the catch block

Correct the exception class in the catch block

---

Helper/Shared/CurrencyUtils.php
Test/Unit/Helper/Shared/CurrencyUtilsTest.php

PHP exception "A non well formed numeric value encountered" in Helper/Shared/CurrencyUtils.php
Fixes: https://boltpay.atlassian.net/browse/SUP-86
#changelog Type amount variable to float in Helper/Shared/CurrencyUtils.php
- [ *] Bug fix (change which fixes an issue)
- [ *] Successfully tested locally (or docker image)
- [ *] My code follows the style guidelines of this project.
- [ *] I have performed a self-review of my own code.
- [* ] New and existing unit tests pass locally with my changes.
- [* ] I have created or modified unit tests to sufficiently cover my changes.
- [ *] I have added my Asana task link and provided a changelog message if applicable.

type amount variable to float in Helper/Shared/CurrencyUtils.php

---

Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php

Just adding flag for future use
#changelog Add new feature switch for pay-by-link feature

Add new feature switch for pay-by-link feature

---

Helper/Cart.php

This code is causing additional rounding problems for a merchant 
Fixes: 
https://app.asana.com/0/1125081140214268/1168686308499785
https://app.asana.com/0/1125081140214268/1164552839717137
#changelog Remove the outdated rounding code

Remove the outdated rounding code

---

Observer/TrackingSaveObserver.php

We need to update merchant/track_shipment API format, make it more extendable for the case if down the road we will need an additional identifier for the order  line.
#changelog Fix merchant/track_shipment API format

Fix merchant/track_shipment API format

---

Block/Form.php
Block/Js.php
Controller/Adminhtml/Order/ReceivedUrl.php
Controller/Order/ReceivedUrl.php
Controller/ReceivedUrlTrait.php
Model/Api/CreateOrder.php
Test/Unit/Block/JsTest.php
Test/Unit/Controller/Order/ReceivedUrlTest.php
Test/Unit/Model/Api/CreateOrderTest.php
view/adminhtml/templates/boltpay/button.phtml
view/adminhtml/templates/boltpay/js/replacejs.phtml

This PR implements pay-by-link feature. This feature allows magento admin to generate an order link that can be sent to customer with pre-populated cart items, user's address and shipping option. When customer opens the link, they can fill card information and complete the order. 
Demo:
This PR:
1. Modify `replace.js.phtml` to show additional UI for pay-by-link if payment only publishable key is present
2. Modify how we handle order received URL. Previously we checked if quote is admin or not and decide which URL to land user. Now pay-by-link is quote created by admin and paid by consumer we can no longer use it. This PR implements an logic to check referrer, and if quote is admin AND user place order from admin page, we redirect user to admin confirmation page.
Fixes: …

Pay-by-link feature from magento admin

---

etc/adminhtml/system.xml

Exception #0 (Magento\Framework\Exception\LocalizedException): The XML in file "app/code/Bolt/Boltpay/etc/adminhtml/system.xml" is invalid:
Element 'group', attribute 'path': The attribute 'path' is not allowed. Line: 33
See here: https://prnt.sc/s03016
Fixes: https://app.asana.com/0/564264490825835/1171489309080097
#changelog Fix the exception: 'XML in file system.xml is invalid'

Fix the exception: 'XML in file system.xml is invalid'

---

Test/Unit/Plugin/OrderPluginTest.php

Unit Test: Bolt\Boltpay\Plugin\OrderPlugin
Fixes: https://app.asana.com/0/564264490825835/1171470268094089
#changelog Unit Test: Bolt\Boltpay\Plugin\OrderPlugin

Unit Test: Bolt\Boltpay\Plugin\OrderPlugin

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

Deactivate session quote that associates with an existing order
Fixes: 
https://boltpay.atlassian.net/browse/SUP-106
https://app.asana.com/0/564264490825835/1171819550693705
#changelog Deactivate session quote that associates with an existing order

Deactivate session quote that associates with an existing order

---

Plugin/RestoreQuotePlugin.php
Test/Unit/Plugin/RestoreQuotePluginTest.php
etc/di.xml

Ingore restoring quote if payment method is Boltpay
Fixes: https://app.asana.com/0/564264490825835/1172172320261745
#changelog Ignore restoring quote if payment method is Boltpay

Ignore restoring quote if payment method is Boltpay

---

Helper/Bugsnag.php
Test/Unit/Helper/BugsnagTest.php

Complete code coverage for Bolt\Boltpay\Helper\Bugsnag class
Fixes: https://app.asana.com/0/1131034199022718/1155788465060187
#changelog Unit Test: Bolt\Boltpay\Helper\Bugsnag

Unit Test: Bolt\Boltpay\Helper\Bugsnag

---

Test/Unit/Helper/CartTest.php

Cart constructor changed in between merge, resulting in a test missing a parameter.  This fixes the test
Fixes: https://boltpay.slack.com/archives/CRGUZABC6/p1587733923008200
#changelog Fix Helper/Cart Unit Test For Missing Parameter

Fix Helper/Cart Unit Test For Missing Parameter

---

Test/Unit/Model/Api/Data/DebugInfoTest.php

Unit test: Bolt\Boltpay\Test\Unit\Model\Api\DebugInfo
Fixes: https://app.asana.com/0/564264490825835/1172764603467961
#changelog Unit test: Bolt\Boltpay\Test\Unit\Model\Api\DebugInfo

Unit test: Bolt\Boltpay\Test\Unit\Model\Api\DebugInfo

---

Test/Unit/Model/Api/Data/AccountInfoTest.php
Test/Unit/Model/Api/Data/ShippingOptionTest.php
Test/Unit/Model/Api/Data/ShippingOptionsTest.php

Correct the namespace and add Unit Test: \Bolt\Boltpay\Model\Api\Data\AccountInfo
Fixes: https://app.asana.com/0/564264490825835/1172449941539393
#changelog Correct the namespace and add Unit Test: \Bolt\Boltpay\Model\Api\Data\AccountInfo

Correct the namespace and add Unit Test: \Bolt\Boltpay\Model\Api\Data\AccountInfo

---

Test/Unit/Model/Api/Data/PluginVersionTest.php

Unit Test: Bolt\Boltpay\Model\Api\Data\PluginVersion
Fixes: https://app.asana.com/0/564264490825835/1172537152154765
#changelog Unit Test: Bolt\Boltpay\Model\Api\Data\PluginVersion

Unit Test: Bolt\Boltpay\Model\Api\Data\PluginVersion

---

Test/Unit/Model/Api/Data/BoltConfigSettingTest.php

Unit Test: Bolt\Boltpay\Model\Api\Data\BoltConfigSetting
Fixes: https://app.asana.com/0/564264490825835/1172537152154761
#changelog Unit Test: Bolt\Boltpay\Model\Api\Data\BoltConfigSetting

Unit Test: Bolt\Boltpay\Model\Api\Data\BoltConfigSetting

---

Test/Unit/Plugin/Mirasvit/Rewards/Model/PurchasePluginTest.php

Unit Test: Bolt\Boltpay\Plugin\PurchasePlugin
Fixes: https://app.asana.com/0/564264490825835/1172442715973673
#changelog Unit Test: Bolt\Boltpay\Plugin\PurchasePlugin

Unit Test: Bolt\Boltpay\Plugin\PurchasePlugin

---

.circleci/config.yml

#changelog Try to fix autotagger not tagging second person

Try to fix autotagger not tagging second person

---

view/frontend/templates/button_product_page.phtml

Unable to complete checkout with PPC for product with attributes - unknown error occurs
Fixes: https://boltpay.atlassian.net/browse/M2P-52?atlOrigin=eyJpIjoiNmE1ZmUwODZiZjE2NDllOGE3Y2M0YTM5ODIwMjgyNzYiLCJwIjoiaiJ9
#changelog PPC for product with attributes - unable to complete checkout fix

PPC for product with attributes - unable to complete checkout fix

---

CHANGELOG.md
composer.json
etc/module.xml

Version bump
#changelog version bump and added changelog items

version bump and added changelog items

---

Observer/TrackingSaveObserver.php

When we send variable products in track_shipment call we need to include product options as well as we do when creating bolt cart.
Otherwise, hail can't match products and generate an error:
https://app.datadoghq.com/logs?agg_m=count&agg_q=&agg_t=count&analyticsOptions=%5B%22bars%22%5D&cols=service%2C%40job_name&event=AQAAAXHrK6fYpc6qEAAAAABBWEhyTEM5LUREMFN5NWt3QXdBQQ&from_ts=1588763575317&index=main&live=true&messageDisplay=inline&query=status%3Aerror+%40env%3Aproduction+%40request_path%3A%22%2Fv1%2Fmerchant%2Ftrack_shipment%22&stream_sort=desc&to_ts=1588777975317&top_n=10&viz=timeseries
Fixes: [M2P-56]
#changelog M2P-56 Add product options into merchant/track_shipment call

M2P-56 Add product options into merchant/track_shipment call

---

.github/pull_request_template.md

Minor change to PR template. Changed wording to refer to Jira.
#changelog changed references to Asana to refer to Jira

Updated template to refer to Jira instead of asana

---

Helper/Bugsnag.php
Helper/Config.php
Test/Unit/Helper/BugsnagTest.php

Fixes: [M2P-30]
#changelog Don't bugsnag from CI instances.

M2P-30 Don't bugsnag from CI

---

CHANGELOG.md
composer.json
etc/module.xml

2.7.0 version bump
#changelog 2.7.0 version bump

version bump

---

.circleci/config.yml
Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Helper/MetricsClient.php
Test/Unit/Helper/MetricsClientTest.php
Test/scripts/ci-integration.sh
etc/di.xml

Feature switch for merchant metrics. Flagged just the `processMetric` function as it's the major entry point. Left `getCurrentTime` unflagged since it's fairly benign.
Fixes: [MX-287]
#changelog Feature switches for merchant metrics.
[MX-287]: https://boltpay.atlassian.net/browse/MX-287

MX-287 - Feature switch for merchant metrics

---

Helper/Cart.php
Helper/Order.php
Model/Api/DiscountCodeValidation.php
Plugin/QuotePlugin.php
Setup/UpgradeSchema.php
Test/Unit/Helper/CartTest.php
Test/Unit/Helper/OrderTest.php
Test/Unit/Model/Api/DiscountCodeValidationTest.php
Test/Unit/Plugin/QuotePluginTest.php
etc/di.xml
etc/webapi.xml

Split M2 Shipping and Tax endpoints
NOTE: Shipping and Tax split feature is divided into 4 PRs after it was finished. The split is done by dev workflow, position in the code base, execution logic and interference with the previous code (put in the last PR). However, the PRs are not independent of each other, that is visible in failed unit tests. The unit tests will pass when all 4 PRs get merged, as they do in the integral version at https://github.com/BoltApp/bolt-magento2/pull/641. That's why an intermediate branch is created, feature/shipping-and-tax-spli, instead of merging them directly into master.
Fixes: https://boltpay.atlassian.net/browse/M2P-51
https://github.com/BoltApp/bolt-magento2/pull/641
#changelog Required plugin updates
Please validate that you have tested your change in …

PR4 Required plugin updates

---

Helper/Config.php
Test/Unit/Helper/ConfigTest.php
etc/adminhtml/system.xml
view/adminhtml/web/js/validation.js

Add custom url validation
Fixes: https://app.asana.com/0/932047656377869/1174920017329137
#changelog Add custom url validation

Add custom url validation

---

Test/Unit/Model/FeatureSwitchTest.php

Unit test: Bolt\Boltpay\Model\FeatureSwitch
Fixes: https://app.asana.com/0/564264490825835/1174950612747345
#changelog Unit test: Bolt\Boltpay\Model\FeatureSwitch

Unit test: Bolt\Boltpay\Model\FeatureSwitch

---

Test/Unit/Plugin/ClearQuoteTest.php

Unit test: Bolt\Boltpay\Plugin\ClearQuote
Fixes: https://app.asana.com/0/564264490825835/1175181324952969
#changelog Unit test: Bolt\Boltpay\Plugin\ClearQuote

Unit test: Bolt\Boltpay\Plugin\ClearQuote

---

Test/Unit/Exception/BoltExceptionTest.php

Unit test: Bolt\Boltpay\Exception\BoltException
Fixes: https://app.asana.com/0/564264490825835/1175386400822737
#changelog Unit test: Bolt\Boltpay\Exception\BoltException

Unit test: Bolt\Boltpay\Exception\BoltException

---

etc/adminhtml/system.xml

Add config path for store pickup configurations
Fixes: https://app.asana.com/0/564264490825835/1175181324952973
#changelog Add config path for store pickup configurations

Add config path for store pickup configurations

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

Covers Unit test for Bolt\Boltpay\Helper\Cart
Fixes: https://boltpay.atlassian.net/browse/M2P-59
#changelog Unit Test: Bolt\Boltpay\Helper\Cart - [M2P-59]

Unit Test: Bolt\Boltpay\Helper\Cart - [M2P-59]

---

Test/Unit/Observer/Adminhtml/Sales/OrderCreateProcessDataObserverTest.php
Test/Unit/Observer/Adminhtml/Sales/RechargeCustomerTest.php

Unit test: Bolt\Boltpay\Observer\Adminhtml\Sales\OrderCreateProcessDataObserver
Fixes: https://app.asana.com/0/564264490825835/1175625637036457
#changelog Unit test: Bolt\Boltpay\Observer\Adminhtml\Sales\OrderCreateProcessDataObserver

Unit test: Bolt\Boltpay\Observer\Adminhtml\Sales\OrderCreateProcessDataObserver

---

Test/Unit/Controller/Customer/CreditCardTest.php

Unit test: Bolt\Boltpay\Controller\Customer\CreditCard
Fixes: https://app.asana.com/0/564264490825835/1176158950230457
#changelog Unit test: Bolt\Boltpay\Controller\Customer\CreditCard

Unit test: Bolt\Boltpay\Controller\Customer\CreditCard

---

view/frontend/templates/button_product_page.phtml

#changelog Remove PPC Ajax hints call (for burts bees baby only)

Remove PPC Ajax hints call (for burts bees baby only)

---

Api/Data/ShippingDataInterface.php
Api/Data/ShippingTaxDataInterface.php
Api/Data/TaxDataInterface.php
Api/Data/TaxResultInterface.php
Api/ShippingInterface.php
Api/TaxInterface.php

Split M2 Shipping and Tax endpoints
NOTE: Shipping and Tax split feature is divided into 4 PRs after it was finished. The split is done by dev workflow, position in the code base, execution logic and interference with the previous code (put in the last PR). However, the PRs are not independent of each other, that is visible in failed unit tests. The unit tests will pass when all 4 PRs get merged, as they do in the integral version at https://github.com/BoltApp/bolt-magento2/pull/641. That's why an intermediate branch is created, feature/shipping-and-tax-spli, instead of merging them directly into master.
Fixes: https://boltpay.atlassian.net/browse/M2P-51
https://github.com/BoltApp/bolt-magento2/pull/641
#changelog API interfaces definition
Please validate that you have tested your change …

PR1 API interfaces definition

---

Model/Api/CreateOrder.php
Model/Api/Shipping.php
Model/Api/ShippingTax.php
Model/Api/ShippingTaxContext.php
Model/Api/Tax.php
Test/Unit/Model/Api/ShippingTaxContextTest.php
Test/Unit/Model/Api/ShippingTaxTest.php
Test/Unit/Model/Api/ShippingTest.php
Test/Unit/Model/Api/TaxTest.php

Split M2 Shipping and Tax endpoints
NOTE: Shipping and Tax split feature is divided into 4 PRs after it was finished. The split is done by dev workflow, position in the code base, execution logic and interference with the previous code (put in the last PR). However, the PRs are not independent of each other, that is visible in failed unit tests. The unit tests will pass when all 4 PRs get merged, as they do in the integral version at https://github.com/BoltApp/bolt-magento2/pull/641. That's why an intermediate branch is created, feature/shipping-and-tax-spli, instead of merging them directly into master.
Fixes: https://boltpay.atlassian.net/browse/M2P-51
https://github.com/BoltApp/bolt-magento2/pull/641
#changelog PR3  Api classes implementation …

PR3  Api classes implementation

---

.circleci/config.yml
.circleci/scripts/tag-rc-if-necessary.sh

#changelog Update autotagger schedule

[MX-1105] Update autotagger schedule

---

Test/Unit/Helper/GeolocationTest.php

Unit Test: Bolt\Boltpay\Helper\Geolocation
Fixes: 
#changelog Unit Test: Bolt\Boltpay\Helper\Geolocation

Unit Test: Bolt\Boltpay\Helper\Geolocation

---

view/adminhtml/templates/boltpay/js/replacejs.phtml
view/frontend/templates/js/replacejs.phtml

Fixes: [M2P-74]
#changelog Fix issue with magento session caching

[M2P-74] Fix issue with magento session caching

---

Observer/TrackingSaveObserver.php
Test/Unit/Observer/TrackingSaveObserverTest.php

Fixes: [M2P-67]
#changelog M2P-67 Order management: Fix bug with configurable products

M2P-67 Order management: Fix bug with configurable products

---

Helper/Cart.php
Helper/Order.php
Test/Unit/Helper/CartTest.php
Test/Unit/Helper/OrderTest.php

Add logic to check if order exist by the parent quote
Fixes: https://boltpay.atlassian.net/browse/M2P-76
#changelog Add logic to check if order exist by the parent quote

Add logic to check if order exist by the parent quote

---

Block/JsProductPage.php
Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Section/CustomerData/BoltHints.php
Test/Unit/Block/JsProductPageTest.php
Test/Unit/Section/CustomerData/BoltHintsTest.php
etc/frontend/di.xml
etc/frontend/sections.xml
view/frontend/templates/button_product_page.phtml
view/frontend/templates/js/replacejs.phtml

Fixes: [M2P-61] 
#changelog Improve performance for Product page checkout

M2P-61 Save hints for PPC in magento sections

---

Helper/Config.php
Test/Unit/Helper/ConfigTest.php
view/adminhtml/web/js/validation.js

Use regex to validate custom url
Fixes: https://boltpay.atlassian.net/browse/M2P-79 
#changelog Use regex to validate custom url

Use regex to validate custom url

---

CHANGELOG.md
composer.json
etc/module.xml

Version bump and changelog update
#changelog 2.8.0versionbump

2.8.0versionbump

---

Helper/Cart.php
Helper/Config.php
Test/Unit/Helper/ConfigTest.php

Fix regex bug
#changelog Fix broken regex for custom API url
Fix broken regex for custom API url

Fix broken regex for custom API url

---

etc/di.xml
etc/frontend/di.xml
view/adminhtml/requirejs-config.js
view/adminhtml/templates/boltpay/js/replacejs.phtml
view/adminhtml/web/js/shims/es6-collections-shim.js

This PR resolves the issue that prevented Bolt Pay button from showing up in admin. 
It was caused by a conflict between polyfills for `Map` class from Magento core and Bolt connect. Bolt connect seems to wrap the `Map` class constructor which causes [a check](https://github.com/magento/magento2/blob/8d90d12c2e0573a5ff898d6695cf730cd5a5792c/lib/web/es6-collections.js#L89) in Magento core polyfill to fail, enter an infinite loop and exhaust call stack.
Polyfill used in Magento core is [deprecated](https://github.com/WebReflection/es6-collections#deprecated) and has a [pending PR]([url](https://github.com/WebReflection/es6-collections/pull/45)) which would resolve this issue.
As we can (should) not interfere with Magento core scripts, we detect if `Map` had been polyfilled and then make the …

Resolve Bolt Pay button missing in backoffice in IE

---

Helper/Api.php
Test/Unit/Helper/ApiTest.php

Updates coverage to help reach overall code coverage of 100%
Fixes: https://app.asana.com/0/1131034199022718/1176872523096461
#changelog Unit test: Bolt\Boltpay\Helper\Api

Unit test: Bolt\Boltpay\Helper\Api

---

.github/pull_request_template.md

Update to PR template
Fixes: https://boltpay.atlassian.net/browse/MX-1182
#changelog N/A

MX-1182 Update PR template to call out minimization of mocks

---

.github/CODEOWNERS

Fixes: https://app.asana.com/0/0/1175598486792452/f
#changelog Add Vitaliy as code owner

Add Vitaliy as code owner

---

view/frontend/templates/button_product_page.phtml

PPC frontend error on Magento2.3.5.
`data` object is null on the first `updatePrice` call.
Fixes: https://boltpay.atlassian.net/browse/M2P-90
#changelog PPC javascript error on Magento2.3.5 fix

PPC javascript error on Magento2.3.5 fix

---

CHANGELOG.md
composer.json
etc/module.xml

Version bump for hotfix
Fixes: 
#changelog Version bump for 2.8.1 hotfix

Version bump for 2.8.1 hotfix

---

Plugin/MageVision/FreeShippingAdmin/MethodPlugin.php
etc/di.xml

Fixes: [MX-1169]
#changelog MX-1169 Add support for module MageVision\FreeShippingAdmin
[MX-1169]: https://boltpay.atlassian.net/browse/MX-1169

MX-1169 Add support for module MageVision\FreeShippingAdmin

---

Controller/Cart/Data.php
Helper/Cart.php
Test/Unit/Controller/Cart/DataTest.php
Test/Unit/Helper/CartTest.php

Move method for handle boltpay/cart/data API call to cart helper
We will reuse this code to work with magento sections
#changelog Plugin refactoring

M2P-82 Move boltpay/cart/data code to helper

---

Section/CustomerData/BoltCart.php
etc/frontend/di.xml
etc/frontend/sections.xml

M2P-82 Add new magento section to save bolt cart and hints

---

view/frontend/templates/js/replacejs.phtml

In the next PR we save old code for onestep case and do some refactoring for multistep case
#changelog Plugin refactoring

M2P-82 Read bolt cart from sections instead of AJAX call

---

view/frontend/templates/js/replacejs.phtml

In this PR:
- Remove legacy code we added for support multistep&paymentonly on the same page (we don't use this option for years)
- Mark code that we need only for payment only (wrap up this code into if statement). I intentionally don't format indents for PR readability. Will format in separate PR
- Remove unnecessary DOM listener - we no need to listen to "sum" changes anymore.
#changelog M2P-82 Further JS refactoring

M2P-82 Further JS refactoring

---

Block/Js.php
Helper/Config.php
etc/adminhtml/system.xml
view/frontend/templates/js/replacejs.phtml

Fixes: [MX-1169]
#changelog MX-1169 Espresso parts: show native M2 checkout button under some condition
[MX-1169]: https://boltpay.atlassian.net/browse/MX-1169

MX-1169 Show native M2 checkout button under some condition

---

Api/CreateOrderInterface.php
Api/DiscountCodeValidationInterface.php
Block/Adminhtml/Customer/CreditCard/Tab/CreditCard.php
Block/Adminhtml/Customer/CreditCard/Tab/View/CardNumber.php
Block/Adminhtml/Customer/CreditCard/Tab/View/CardType.php
Block/Adminhtml/Customer/CreditCard/Tab/View/CreditCard.php
Block/Adminhtml/Customer/CreditCard/Tab/View/DeleteAction.php
Block/BlockTrait.php
Block/Checkout/Cart/ComponentSwitcherProcessor.php
Block/Checkout/ComponentSwitcherProcessor.php
Block/Checkout/Success.php
Block/Customer/CreditCard.php
Block/Form.php
Block/Js.php
Controller/Adminhtml/Cart/Data.php
Controller/Adminhtml/Customer/CreditCard.php
Controller/Adminhtml/Order/ReceivedUrl.php
Controller/Adminhtml/Order/Save.php
Controller/Cart/CheckoutConfig.php
Controller/Cart/Data.php
Controller/Cart/Email.php
Controller/Cart/Hints.php
Controller/Customer/CreditCard.php
Controller/Order/ReceivedUrl.php
Controller/Order/Save.php
Controller/ReceivedUrlTrait.php
Controller/Shipping/Prefetch.php
Cron/DeleteOldWebHookLogs.php
Exception/BoltException.php

Fixing manual Magento2 coding standard issues. Covers:
```
Api/
Block/
Controller/
Cron/
Exception/
```
Fixes: [M2P-68]
#changelog M2P-68 Part 1 manual phpcs fixes
#mergeWhenGreen

M2P-68 Part 1 manual phpcs fixes

---

Observer/TrackingSaveObserver.php
Test/Unit/Observer/NonBoltOrderObserverTest.php
Test/Unit/Observer/TrackingSaveObserverTest.php

#changelog Send non-Bolt tracking information to Bolt backend
Send non-Bolt tracking information to Bolt backend

Send non-Bolt tracking information to Bolt backend

---

Plugin/OrderPlugin.php
Test/Unit/Plugin/OrderPluginTest.php

M2P-94 https://boltpay.atlassian.net/browse/M2P-94
https://github.com/BoltApp/bolt-magento2/pull/731
Fixes: [M2P-94]
#changelog Postpone order place

M2P-94 Postpone order place

---

Block/Js.php
Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Test/Unit/Block/JsTest.php
view/frontend/templates/js/replacejs.phtml

We did a quite big refactoring and I propose to save legacy JS code for 1 or 2 release to have opportunity change feature switch and use old code.
#changelog M2P-82 Add feature switches to disable saving cart in magento section

M2P-82 Add feature switches to disable saving cart in magento section

---

CHANGELOG.md
composer.json
etc/module.xml

Version bump for 2.9.0 and changelog update
#changelog 2.9.0 version bump

2.9.0 Version bump

---

view/frontend/templates/button_product_page.phtml
view/frontend/templates/js/replacejs.phtml

I added a bug in version 2.8.0.
I call customerData.invalidate with string argument instead of array.
This is the same call with argument ["b","o","l" ... ]
As result, magento tries to get a new value for section "b". Backend returns error and no sections updated.
**Who potentially affected:**
* Merchant on 2.8.0 or 2.8.1
* User did the purchase
* Use tries to pay with new cart
* User still has the old cookies at this moment  (cookies save for one day)
* User doesn't only add the product to cart but apply a discount or something similar (when user add a product to cart all magento sections are invalidated and magento doesn't look to list for invalidation, so this is a change to get correct bolt cart)
**Result**
The plugin doesn't receive a  correct bolt cart and call configure with cart …

M2P-105 Fix issue with magento sections

---

Helper/Discount.php
Test/Unit/Helper/DiscountTest.php
Test/Unit/Model/Api/DiscountCodeValidationTest.php
Test/Unit/TestHelper.php

Completion of code coverage for Discount helper
Fixes: https://app.asana.com/0/1131034199022718/1166467787916019
#changelog Update coverage on Discount

Update coverage on Discount

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

Now when we clone quote data from source to destination,  we use the method `merge` of Quote model to clone the the items and some other data. In this `merge` method, it mainly does three things :
1. Clone the items
2. Init shipping and billing address if quote is new
3. Set coupon code if exists
After investigation, I found that:
1. Clone the items
The method `merge` of Quote model would compare quote items with the product id and options, if these property data are same then it just merge the two items. But we face cases that the cart could be created by ERP, and the items of cart could have exactly same product id and options, only the unit price are different, M2 still treats them as different quote items and have unique quote item ids.  When we replicate quote data, what we need to …

M2P-118 Clone items of source quote to destination quote properly

---

.circleci/README.md
.circleci/config.yml
.circleci/scripts/auto-rebase-branches.txt
.circleci/scripts/auto-rebase.sh

This PR adds a new circle ci workflow to auto-rebase configured branch to master whenever there is a new push to master. To make a branch auto-rebasing, we can add it to **_.circleci/scripts/auto-rebase-branches.txt_** 
The job will try to auto-rebase all the specified branches one by one and if there is a failure (eg: there is a conflict) during auto-rebasing one branch, it will continue to try the rest branches. In the end, it would generate a report and exits with 1 if any of the configured branches failed to rebase.
This [google doc](https://docs.google.com/document/d/1QwS79LgkXUCbc9_ud9-cH8uSTqlysHDErnuYc1kaxa0/edit#) talks about different scenarios in more details.
Fixes: [MX-1316]
#changelog [MX-1316] Add support to auto-rebase configured branches to master
Please validate that you …

[MX-1316] Add support to auto-rebase configured branches to master

---

Model/Payment.php
Test/Unit/Model/PaymentTest.php

Currently, there is an exception being thrown when creating an invoice online that has the amount of less than 0.01 on Magento. This is because of https://github.com/BoltApp/bolt-magento2/blob/master/Model/Payment.php#L385
This PR ensures that we don’t make a call to Bolt if the capture amount is less than 0.01 and returns $this so the Magento invoice can be created.
Fixes: https://boltpay.atlassian.net/browse/M2P-123
#changelog Do not make a call to Bolt if capture amount is less than 0.0.1

M2P-123 Do not make a call to Bolt if capture amount is less than 0.0.1

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php
etc/frontend/sections.xml

Magento Gift Message Integration
See demo screenshot: https://prnt.sc/t69jff
Fixes: 
https://boltpay.atlassian.net/browse/M2P-117
https://app.asana.com/0/1142111051828235/1179558902503967
#changelog M2P-117 Magento Gift Message Integration

M2P-117 Magento Gift Message Integration

---

view/frontend/templates/js/replacejs.phtml

Need to revert the fix because it affects on integration tests.
https://boltpay.atlassian.net/browse/M2P-124
This reverts commit ebf19e16fc5f1f8270b9b82e5c1bd2690db33108.
#changelog Revert "Bugfix: Call configure after we render new bolt button (#769)"

Revert "Bugfix: Call configure after we render new bolt button (#769)"

---

Block/Js.php
Helper/Config.php
etc/adminhtml/system.xml
view/frontend/templates/js/replacejs.phtml

Revert commit 9c62b92e9288dfee688060396cdcee4396302bfe because we decided to implement this in a separate merchant branch.
Will be implemented in task https://boltpay.atlassian.net/browse/MX-1320
#changelog Revert "MX-1169 Show native M2 checkout button under some condition (#745)"

Revert "MX-1169 Show native M2 checkout button under some condition (#745)"

---

Observer/NonBoltOrderObserver.php

I copied how the additional information is set here: https://github.com/BoltApp/bolt-magento2/blob/cfb50285f069990719bee7e450523924883f2bbb/Helper/Order.php#L1969-L1971
Fixes: https://boltpay.atlassian.net/browse/EN-364
#changelog Set additional information on payment correctly
Fix broken payment additional information
Bug fix (change which fixes an issue)

Set additional information on payment correctly

---

Block/Checkout/Success.php
Test/Unit/Block/Checkout/SuccessTest.php
view/frontend/templates/checkout/success.phtml
view/frontend/templates/js/replacejs.phtml

**Steps to reproduce:**
1. Version is 2.3.0
2. Empty the cart
3. Go to a product page
4. Add the product to cart
5. Reload the page (F5)
6. Finish checkout from minicart
**Actual behavior:**
Magento shows an icon that the cart isn't empty. Actually, cart became empty only if we reload the page
**Expected behavior**
Cart is empty
**What happened**
In v 2.3.0 Magento reload all sections data when new page is loaded if we made any POST request on the previous page: in backend magento updates cookie private_content_version and in frontend it checks if cookie updated.
https://github.com/magento/magento2/blob/f4c1d7526f05bdfb1327b0701cc345f94aadcaed/app/code/Magento/Customer/view/frontend/web/js/customer-data.js#L219
https://github.com/magento/magento2/blob/f4c1d7526f05bdfb1327b0701cc345f94aadca …

M2P-132 Invalidate bolt and magento carts in success event

---

CHANGELOG.md
composer.json
etc/module.xml

Version bump
#changelog 2.10.0 version bump
#mergewhengreen

2.10.0 version bump

---

.circleci/scripts/auto-rebase-branches.txt

Add yogibo and nmwa (2 real merchant branches) to be the pilots of auto-rebasing
#changelog update auto-rebase configuration

update auto-rebase configuration

---

.circleci/config.yml
.circleci/scripts/auto-rebase-branches.txt
.circleci/scripts/test-merchant-branches.sh

Only the first auto-rebase branch from the config will be rebased on and tested for now. In subsequent PR, we will add support to do this for all the configured auto-rebase branches in parallel
Fixes: [MX-1318]
#changelog [MX-1318] Circle CI will rebase and run tests for all auto-rebase branches on every PR
[MX-1318]: https://boltpay.atlassian.net/browse/MX-1318

[MX-1318] Circle CI will rebase and run tests for all auto-rebase branches on every PR 

---

Test/Unit/Plugin/MageVision/FreeShippingAdmin/MethodPluginTest.php

Fixes: https://boltpay.atlassian.net/browse/M2P-150
#changelog M2P-150 Unit test: Bolt\Boltpay\Plugin\MageVision\FreeShippingAdmin\MethodPlugin

M2P-150 Unit test: Bolt\Boltpay\Plugin\MageVision\FreeShippingAdmin\MethodPlugin

---

Test/Unit/Plugin/AbstractLoginPluginTest.php

Unit test: Bolt\Boltpay\Plugin\AbstractLoginPlugin
Fixes: https://boltpay.atlassian.net/browse/M2P-158
#changelog M2P-158 Unit test: Bolt\Boltpay\Plugin\AbstractLoginPlugin

M2P-158 Unit test: Bolt\Boltpay\Plugin\AbstractLoginPlugin

---

.circleci/scripts/test-merchant-branches.sh

Add git config in test-merchant-branches
#changelog init git config in test-merchant-branches

init git config in test-merchant-branches.sh

---

.circleci/config.yml
.circleci/scripts/tag-rc-if-necessary.sh
.gitignore

Moving autotagger to every 2 weeks.
Fixes: No ticket :(
#changelog Autotag release every 2 weeks

Update rc tagger for every 2 weeks

---

Controller/ReceivedUrlTrait.php
Test/Unit/Controller/ReceivedUrlTraitTest.php

Unit Test: Bolt\Boltpay\Controller\ReceivedUrlTrait
Fixes: https://boltpay.atlassian.net/browse/M2P-162
#changelog M2P-162 Unit Test: Bolt\Boltpay\Controller\ReceivedUrlTrait

M2P-162 Unit Test: Bolt\Boltpay\Controller\ReceivedUrlTrait

---

.circleci/config.yml

#Description 
Don't know if slack will tag correctly if we use `pavel` instead of `Pavel`, but seems like this bot can't tag with capitalized names. Worth a shot?
#changelog Try with lower case names
#mergewhengreen

Try with lower case names

---

.circleci/config.yml

As described above.
#changelog Fix broken circle config
#mergeWhenGreen

Fix missing then

---

CHANGELOG.md
composer.json
etc/module.xml

#changelog 2.11.0 version bump

2.11.0 version bump

---

Block/Js.php
Block/MinifiedJs.php
view/frontend/layout/default.xml
view/frontend/templates/js/boltglobaljs.phtml
view/frontend/templates/js/replacejs.phtml

Delegate Js minification logic from template to the block
Fixes: https://boltpay.atlassian.net/browse/M2P-174
#changelog Delegate Js minification logic from template to the block

M2P-174 Delegate Js minification logic from template to the block

---

Test/Unit/Block/BlockTraitTest.php

Unit test: Bolt\Boltpay\Block\BlockTrait
Fixes: https://boltpay.atlassian.net/browse/M2P-164
#changelog M2P-164 Unit test: Bolt\Boltpay\Block\BlockTrait

M2P-164 Unit test: Bolt\Boltpay\Block\BlockTrait

---

view/frontend/templates/js/replacejs.phtml

Yesterday we started using feature from ECMAScript 2015 and it broke IE. Removing now.
#changelog M2P-180 Remove code incompatible with IE

M2P-180 Remove code incompatible with IE

---

Block/Js.php
Block/MinifiedJs.php
view/adminhtml/templates/boltpay/button.phtml
view/adminhtml/templates/boltpay/js/replacejs.phtml
view/frontend/layout/default.xml
view/frontend/templates/boltaccount.phtml
view/frontend/templates/button.phtml
view/frontend/templates/button_product_page.phtml
view/frontend/templates/checkout/minicart_addons.phtml
view/frontend/templates/css/boltcss.phtml
view/frontend/templates/customer/creditcard.phtml
view/frontend/templates/info/default.phtml
view/frontend/templates/js/boltglobaljs.phtml
view/frontend/templates/js/boltjs.phtml
view/frontend/templates/js/replacejs.phtml

This PR fixes most of the warning issues reported by the Magento coding standard tool except for the **addcslashes** and **ob_start** issue which will be fixed in later PRs.
See the reported issues in the following link: https://gist.github.com/johnmccombs1/12e3e68b7b228d99dffe39a580623fd0
Fixes: https://boltpay.atlassian.net/browse/M2P-172
#changelog Fix warning issues reported by the Magento coding standard tool in the view folder

M2P-172 Fix warning issues reported by the Magento coding standard tool in the view folder

---

Test/Unit/Helper/CartTest.php
Test/Unit/Helper/OrderTest.php
Test/Unit/Model/Api/DiscountCodeValidationTest.php
Test/Unit/Model/Api/ShippingMethodsTest.php
Test/Unit/Observer/Adminhtml/Sales/RechargeCustomerTest.php
Test/Unit/TestHelper.php
Test/Unit/UnirgyMock.php

This PR fixes the error issues reported by the Magento coding standard tool
The following command to run:
**vendor/bin/phpcs --standard=Magento2 app/code/Bolt/Boltpay/Test -n**
See the reported issues in the following link: https://gist.github.com/johnmccombs1/b4b8289209cac5b3d3457df818cf7322
Fixes: https://boltpay.atlassian.net/browse/M2P-166
#changelog Fix error issues reported by the Magento coding standard tool in the test folder

M2P-166 Fix error issues reported by the Magento coding standard tool in the test folder

---

Test/Unit/Helper/OrderTest.php

Update code coverage for /Test/Unit/Helper/OrderTest
Fixes: https://boltpay.atlassian.net/browse/M2P-188
#changelog Update code coverage for /Test/Unit/Helper/OrderTest

Update code coverage for /Test/Unit/Helper/OrderTest

---

Helper/Hook.php
Test/Unit/Helper/HookTest.php

This PR updates coverage of the Hook helper 
Fixes: https://boltpay.atlassian.net/browse/M2P-187
#changelog Unit Test: Bolt\Boltpay\Helper\Hook

Unit Test: Bolt\Boltpay\Helper\Hook

---

Block/Checkout/LayoutProcessor.php
Controller/Adminhtml/Cart/Data.php
Controller/Adminhtml/Order/Save.php
Controller/Cart/Data.php
Controller/Cart/Email.php
Controller/Cart/Hints.php
Controller/Order/Save.php
Controller/Shipping/Prefetch.php
Helper/Config.php
Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Manager.php
Helper/Geolocation.php
Helper/GraphQL/Client.php
Helper/Log.php
Helper/Session.php
Test/Unit/Block/Checkout/LayoutProcessorTest.php
Test/Unit/Controller/Adminhtml/Cart/DataTest.php
Test/Unit/Controller/Adminhtml/Order/SaveTest.php
Test/Unit/Controller/Cart/DataTest.php
Test/Unit/Controller/Cart/EmailTest.php
Test/Unit/Controller/Cart/HintsTest.php
Test/Unit/Controller/Order/SaveTest.php
Test/Unit/Controller/Shipping/PrefetchTest.php
Test/Unit/Helper/ConfigTest.php
Test/Unit/Helper/FeatureSwitch/DeciderTest.php
Test/Unit/Helper/FeatureSwitch/ManagerTest.php
Test/Unit/Helper/GeolocationTest.php
Test/Unit/Helper/GraphQL/ClientTest.php
Test/Unit/Helper/LogTest.php
Test/Unit/Helper/SessionTest.php

This PR removes all @codeCoverageIgnore tags and implement tests for it
Fixes: https://boltpay.atlassian.net/browse/M2P-186
#changelog Remove codeCoverageIgnore and Implement tests

Remove codeCoverageIgnore and Implement tests

---

Block/Js.php
Test/Unit/Block/JsTest.php
Test/Unit/TestHelper.php

This pull request update coverage to 100% on Js block
Fixes: https://app.asana.com/0/1114048648211853/1176870330266809/f
#changelog Update coverage for Js block

Update coverage for Js block

---

Helper/Order.php

adding affirm

---

Test/Unit/Section/CustomerData/BoltCartTest.php

Unit test: Bolt\Boltpay\Section\CustomerData\BoltCart
Fixes: https://boltpay.atlassian.net/browse/M2P-165
#changelog Unit test: Bolt\Boltpay\Section\CustomerData\BoltCart

M2P-165 Unit test: Bolt\Boltpay\Section\CustomerData\BoltCart

---

Setup/UpgradeSchema.php
Test/Unit/Setup/UpgradeSchemaTest.php

Update Test For Bolt\Boltpay\Setup\UpgradeSchema
Fixes: https://boltpay.atlassian.net/browse/M2P-195
#changelog Update Test For Bolt\Boltpay\Setup\UpgradeSchema

Update Test For Bolt\Boltpay\Setup\UpgradeSchema

---

Test/Unit/Model/Api/OrderManagementTest.php

Update Unit Test for \Bolt\Boltpay\Model\Api\OrderManagement
Fixes: https://boltpay.atlassian.net/browse/M2P-193
#changelog Update Unit Test for \Bolt\Boltpay\Model\Api\OrderManagement

Update Unit Test for \Bolt\Boltpay\Model\Api\OrderManagement

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

This reverts commit 0793d40a798faa0f7e9f73f362dbb6ab38477f9f.
Reverting PR - breaks sandbox.
#changelog Revert 845.

Revert "Correct logic to get product images for the Bolt cart (#845)"

---

.circleci/config.yml
.circleci/scripts/auto-rebase-branches.txt
.circleci/scripts/rebase-and-unit-test.sh
.circleci/scripts/test-merchant-branches.sh

#changelog Update circleci config for rebase tests
Update circleci config file from 'vincent/circleci/test-multiple-branches-pr', in orer to test the rebase and unit test workflow

Update circleci config for rebase tests

---

CHANGELOG.md
composer.json
etc/module.xml

#changelog 2.12.0 version bump

2.12.0 version bump

---

Block/Js.php
Helper/Config.php
Test/Unit/Block/JsTest.php
Test/Unit/Helper/ConfigTest.php
view/frontend/templates/button.phtml
view/frontend/templates/js/replacejs.phtml

There are several non-advertised "Secret Checkout Button Options" that can be applied to the Bolt checkout button.  One example is in changing the buttons text as follows:
`<div class="bolt-checkout-button" data-btn-txt="Pay now"></div>`
While we wish to provide an easy to use means to accomplish this, we also do not wish to advertise this to merchants.
https://www.notion.so/boltteam/Secret-Checkout-Button-Options-f732422101474a84a4922af3f1e0b904
To accomplish this, we can utilize our existing "Additional Configuration" field, 
https://github.com/BoltApp/bolt-magento2/blob/master/etc/adminhtml/system.xml#L220
This field holds arbitrary JSON and for custom button attributes, we will use the following format:
```
{
"checkoutButtonAttributes": {
"<attribute1_name>": "<attribute1_value>", …
```

Custom Button Attributes

---

.circleci/config.yml
.circleci/scripts/auto-rebase-branches.txt
.circleci/scripts/rebase-and-unit-test.sh
.circleci/scripts/test-merchant-branches.sh

#changelog [MX-1488] Run auto rebase tests on multiple branches for PRs 
Added a workflow for running auto rebase and unit tests
Run this new workflow on all merchant branches for each PR

[MX-1488] Run auto rebase tests on multiple branches for PRs 

---

.circleci/scripts/test-merchant-branches.sh

#changelog [Fix Error Code] Run Rebase and Unit Test on each PR
fix exit code

[Fix Error Code] Run Rebase and Unit Test on each PR

---

Helper/Discount.php
Model/Api/DiscountCodeValidation.php
Test/Unit/Helper/DiscountTest.php
Test/Unit/Model/Api/DiscountCodeValidationTest.php

Move the supports for Magento Coupon from Model/Api/DiscountCodeValidation.php to Helper/Discount.php for common reuse.
Related task https://boltpay.atlassian.net/browse/M2P-64
#changelog Implementation of Update Cart endpoint - Pre-step 1-2

Implementation of Update Cart endpoint - Pre-step 1-2

---

Helper/FeatureSwitch/Definitions.php

#changelog Remove duplicated feature switch definition

Remove duplicated feature switch definition

---

CHANGELOG.md

#changelog Add Magento Commerce 2.4 to changelog

Add Magento Commerce 2.4 to changelog

---

Helper/Session.php
Test/Unit/Helper/SessionTest.php
etc/di.xml

Fixes: [MA-36](https://boltpay.atlassian.net/browse/MA-36)
#changelog MA-36 Add support for plugin Mageplaza Shipping Restriction

MA-36 Add support for plugin Mageplaza Shipping Restriction

---

.circleci/config.yml
.circleci/scripts/auto-rebase-branches.txt
.circleci/scripts/rebase-and-unit-test.sh
.circleci/scripts/test-merchant-branches.sh

#changelog [MP-1591] Display status of merchant branch rebase and tests on PR
Show the status of rebasing and unit tests on merchant branches in the current PR

[MP-1591] Display status of merchant branch rebase and tests on PR

---

Test/Unit/Block/MinifiedJsTest.php

Unit Test: Bolt\Boltpay\Block\MinifiedJs
Fixes: https://boltpay.atlassian.net/browse/M2P-196
#changelog M2P-196 Unit Test: Bolt\Boltpay\Block\MinifiedJs

M2P-196 Unit Test: Bolt\Boltpay\Block\MinifiedJs

---

Block/Js.php
Helper/Config.php
Test/Unit/Block/JsTest.php
Test/Unit/Helper/ConfigTest.php
etc/adminhtml/system.xml

Fixes: [M2P-212](https://boltpay.atlassian.net/browse/M2P-212)
#changelog M2P-212 Change URL for account.js to https://account.bolt.com/account.js

M2P-212 Change URL for account.js to https://account.bolt.com/account.js

---

CHANGELOG.md
composer.json
etc/module.xml

Release notes for 2.13.0
#changelog 2.13.0 version bump

2.13.0 version bump

---

Block/Js.php
Helper/Cart.php
Test/Unit/Block/JsTest.php
view/frontend/templates/js/replacejs.phtml

We need to revert two commits due to IE 11 issue: we use promises in IE11 before they are initialized by polyfill.
#changelog Revert commit due to IE 11 issue

Revert commit due to IE 11 issue

---

view/frontend/templates/js/replacejs.phtml

**The same PR as https://github.com/BoltApp/bolt-magento2/pull/882 with two additional bugfix commits:**
**- IE 11 fix**
**- fix minicart issue when user has an empty cart, add something to cart and click bolt button on minicart.**
Magento2 plugin needs to know Magento settings before answer on check() callback.
But this info loaded asynchronously and isn't available during 1-2 seconds after we show bolt button.
So right now if user clicks on bolt button very fast, we return false in check() callback.
It's not ideal and by this PR we return promise in check(). Storm PR that allows this is under review. I've tested the workflow on my local dev site.
By this PR we allow plugin to return promise in check() callback. Solution was discussed with @pschutz93 by slack.
Fixes: …

M2P-179 Return promise in check() callback

---

.circleci/config.yml
Test/Unit/BoltTestCase.php
Test/Unit/Helper/CartTest.php
Test/Unit/Helper/DiscountTest.php
Test/Unit/Model/Api/DiscountCodeValidationTest.php
Test/Unit/README.md
Test/Unit/TestCase.php
Test/Unit/TestUtils.php
Test/Unit/integration_phpunit.xml
Test/scripts/ci-magento-integration.sh
Test/scripts/install_magento.sh

- Add into circle CI task to run all tests in magento integration flow
- Skip integration tests in unit tests flow
- Add the first magento integration test
- Add some helpers for integration tests creating
- Add instruction how to run integration tests locally.
Fixes: [MA-42](https://boltpay.atlassian.net/browse/MA-42) 
#changelog [WIP] Use magento integration test framework

MA-42 Use magento integration test framework

---

Test/Unit/README.md

#changelog Format Test/Unit/README.md

Format Test/Unit/README.md

---

Model/Api/DiscountCodeValidation.php
Model/Api/Shipping.php
Model/Api/ShippingMethods.php
Model/Api/ShippingTax.php
Model/Api/Tax.php
Model/Payment.php
Test/Unit/Model/Api/ShippingMethodsTest.php

This PR fixes the error issues reported by the Magento coding standard tool
The following command to run:
vendor/bin/phpcs --standard=Magento2 app/code/Bolt/Boltpay/Model -n
See the reported issues in the following link: https://gist.github.com/johnmccombs1/020cbd9361364493a2a2ec341a08d1b9
Fixes: https://boltpay.atlassian.net/browse/M2P-191
#changelog M2P-191 Fix error issues reported by the Magento coding standard tool in the model folder

M2P-191 Fix error issues reported by the Magento coding standard tool in the model folder

---

Helper/Order.php

Tiny little typo fix in a comment
Fixes: typo
#changelog fixed typo

fixed typo

---

Helper/Api.php
Helper/Bugsnag.php
Helper/Cart.php
Helper/Config.php
Helper/Discount.php
Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Manager.php
Helper/Geolocation.php
Helper/GraphQL/Client.php
Helper/LogRetriever.php
Helper/Order.php
Helper/Session.php
Observer/Adminhtml/Sales/RechargeCustomer.php
Test/Unit/Helper/CartTest.php
Test/Unit/Helper/LogRetrieverTest.php
Test/Unit/Helper/SessionTest.php

Before we had the PRs for fixing error issues in the Model, Test, view directories reported by the Magento coding standard tool
So this PR is to fix the error issues in the remaining directories
The following command to run:
vendor/bin/phpcs --standard=Magento2 app/code/Bolt/Boltpay/ -n
See the reported issues in the following link: https://gist.github.com/johnmccombs1/37053b5d5d0a3ebca44b4041230dbdcf
Fixes: https://boltpay.atlassian.net/browse/M2P-167
#changelog Fix error issues reported by the Magento coding standard tool in the remaining directories

M2P-167 Fix error issues reported by the Magento coding standard tool in the remaining directories

---

Helper/Cart.php
Helper/Order.php
Model/Api/DiscountCodeValidation.php
Model/EventsForThirdPartyModules.php
Test/Unit/Helper/CartTest.php
Test/Unit/Helper/OrderTest.php
Test/Unit/Model/Api/DiscountCodeValidationTest.php
Test/Unit/Model/EventsForThirdPartyModulesMock.php
Test/Unit/Model/EventsForThirdPartyModulesTest.php
Test/Unit/Model/ListenerMock.php
ThirdPartyModules/Aheadworks/Giftcard.php

- Add new entity - filters - into class EventsForThirdPartyModules.php
- Add support for module Aheadworks/Giftcart:
Refactor code from https://github.com/BoltApp/bolt-magento2/pull/883 with the approach proposed in https://github.com/BoltApp/bolt-magento2/pull/900
Fixes: [M2P-92](https://boltpay.atlassian.net/browse/M2P-92)
#changelog M2P-92 Add support for module Aheadworks/Giftcart

M2P-92 Add support for module Aheadworks/Giftcart

---

CHANGELOG.md
composer.json
etc/module.xml

Release Notes for 2.14.0 
#changelog release notes for 2.14.0

release notes for 2.14.0

---

Helper/Cart.php
Model/Api/DiscountCodeValidation.php
Test/Unit/Model/Api/DiscountCodeValidationTest.php

Fixes: https://boltpay.atlassian.net/browse/M2P-228
#changelog M2P-228 Fix v1/discount validation after increment order id refactoring

M2P-228 Fix v1/discount validation after increment order id refactoring

---

Model/Api/ShippingMethods.php
Observer/ClearBoltShippingTaxCacheObserver.php
Test/Unit/Observer/ClearBoltShippingTaxCacheObserverTest.php
etc/events.xml

1. The customer adds a product to the cart, enters the shipping address, and clicks on the Continue button. The total amount is $100, the tax rate is 10%, so the tax amount is $10 in the Bolt modal.
2. The administration changes the tax rate to 11%.
3. The customer reloads the page, enters the same address, and clicks on the Continue button again. The tax is still $10 while it should be $11. The issue occurs because the shipping and tax are cached. See here - https://prnt.sc/ub41my
=> So this PR adds the ability to clear the Bolt shipping tax cache if the tax setting is changed.
Fixes: https://boltpay.atlassian.net/browse/M2P-227
#changelog M2P-227 Clear the bolt shipping and tax cache if the tax setting is changed
Please validate that you have tested …

M2P-227 Clear the bolt shipping and tax cache if the tax (Magento,Taxjar) setting is changed

---

etc/adminhtml/events.xml

1. The customer adds a product to the cart, enters the shipping address, and clicks on the Continue button. The total amount is $100, the tax rate is 10%, so the tax amount is $10 in the Bolt modal.
2. The administration changes the tax rate to 11%.
3. The customer reloads the page, enters the same address, and clicks on the Continue button again. 
The tax is still $10 while it should be $11. The issue occurs because the shipping and tax are cached. 
See here - https://prnt.sc/ub41my
=> So this PR adds the ability to clear the Bolt shipping tax cache if the shipping method setting is changed.
Fixes: https://boltpay.atlassian.net/browse/M2P-227
#changelog Clear the bolt shipping and tax cache if the shipping method setting is changed
Please validate …

M2P-227 Clear the bolt shipping and tax cache if the shipping method setting is changed

---

Model/Api/DiscountCodeValidation.php
Model/EventsForThirdPartyModules.php
Test/Unit/Model/Api/DiscountCodeValidationTest.php
Test/Unit/ThirdPartyModules/IDme/GroupVerificationTest.php
ThirdPartyModules/IDme/GroupVerification.php

Apply the id.me data to customer session to correct the discount
Fixes: https://boltpay.atlassian.net/browse/EN-834
#changelog EN-834 Apply the id.me data to customer session to correct the discount

EN-834 Apply the id.me data to customer session to correct the discount

---

Helper/Cart.php
Helper/Discount.php
Model/EventsForThirdPartyModules.php
Test/Unit/Helper/CartTest.php
Test/Unit/Helper/DiscountTest.php
ThirdPartyModules/Aheadworks/Giftcard.php
ThirdPartyModules/Bss/StoreCredit.php
ThirdPartyModules/Mirasvit/Credit.php
etc/di.xml

Code refactoring for 3rd-party module Bss StoreCredit
Fixes: https://boltpay.atlassian.net/browse/M2P-249
#changelog Code refactoring for 3rd-party module Bss StoreCredit

M2P-249 Code refactoring for 3rd-party module Bss StoreCredit

---

Block/Js.php
Block/JsProductPage.php
Model/Api/CreateOrder.php
Model/EventsForThirdPartyModules.php
Test/Unit/Block/JsProductPageTest.php
Test/Unit/Block/JsTest.php
Test/Unit/Model/Api/CreateOrderTest.php
ThirdPartyModules/MageWorld/RewardPoints.php

Add support for module MageWorld RewardPoints
Fixes: https://boltpay.atlassian.net/browse/M2P-211
#changelog Add support for module MageWorld RewardPoints

M2P-211 Add support for module MageWorld RewardPoints

---

Helper/Order.php
Model/Api/OrderManagement.php
Test/Unit/Model/Api/OrderManagementTest.php

#changelog Use helper to get immutableQuoteId from transaction

Use helper to get immutableQuoteId from transaction

---

Model/EventsForThirdPartyModules.php
ThirdPartyModules/Amasty/Rewards.php

Amasty Reward Points - General plugin support
Fixes: https://boltpay.atlassian.net/browse/M2P-240
#changelog Add support for module Amasty Reward Points

M2P-240 Add support for module Amasty Reward Points

---

.circleci/config.yml

#changelog Move integration tests to scheduled job

Move integration tests to scheduled job

---

Helper/Discount.php
Model/Api/DiscountCodeValidation.php
Model/Api/UpdateCart.php
Model/Api/UpdateCartCommon.php
Model/Api/UpdateCartContext.php
Model/Api/UpdateDiscountTrait.php
Test/Unit/Helper/DiscountTest.php
Test/Unit/Model/Api/DiscountCodeValidationTest.php
Test/Unit/Model/Api/UpdateCartCommonTest.php
Test/Unit/Model/Api/UpdateCartContextTest.php
Test/Unit/Model/Api/UpdateCartTest.php
Test/Unit/Model/Api/UpdateDiscountTraitTest.php
etc/di.xml

Refactor v1 Discount Code Validation code to reduce duplicate code
Fixes: https://boltpay.atlassian.net/browse/M2P-252
#changelog Refactor v1 Discount Code Validation code to reduce duplicate code

M2P-252 Refactor v1 Discount Code Validation code to reduce duplicate code

---

CHANGELOG.md
composer.json
etc/module.xml

#changelog release notes for 2.15.0

release notes for 2.15.0

---

Setup/Recurring.php
Setup/UpgradeSchema.php
Test/Unit/Setup/RecurringTest.php
Test/Unit/Setup/UpgradeSchemaTest.php

The following case is
1. Remove the table bolt_feature_switches from the database
2. Run the command "php bin/magento setup:upgrade"
3. The recurringData class adds data to the table bolt_feature_switches https://github.com/BoltApp/bolt-magento2/blob/master/Setup/RecurringData.php#L71 whenever running setup:upgrade and the exception **"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento24.bolt_feature_switches' doesn't exist**" is thrown because it is removed by #1
So this PR is to create a Recurring class to create the table bolt_feature_switches if it doesn't exist because we always need the bolt_feature_switches table to sync the feature switch from Bolt to Magento
Fixes: https://boltpay.atlassian.net/browse/M2P-206
#changelog M2P-206 Move the bolt_feature_switches table …

M2P-206 Move the bolt_feature_switches table creation from UpgradeSchema to Recurring class

---

Test/Unit/Model/Api/UpdateCartTest.php

The unit tests of main repo fail after merging https://github.com/BoltApp/bolt-magento2/pull/954
#changelog Fix unit tests

Fix unit tests

---

Model/Api/DiscountCodeValidation.php
Model/Api/UpdateCart.php
Model/Api/UpdateCartCommon.php
Model/Api/UpdateDiscountTrait.php
Test/Unit/Model/Api/DiscountCodeValidationTest.php
Test/Unit/Model/Api/UpdateCartTest.php
Test/Unit/Model/Api/UpdateDiscountTraitTest.php

Currently not all the exceptions of discount api v1/v2 are added to Bugsnag, this PR is to fix it.
Fixes: https://boltpay.atlassian.net/browse/M2P-245
#changelog Report exception of discount api v1/v2 to Bugsnag

M2P-245 Report exception of discount api v1/v2 to Bugsnag

---

Helper/Cart.php
Model/EventsForThirdPartyModules.php
Test/Unit/Helper/CartTest.php
ThirdPartyModules/Aheadworks/Giftcard.php

Support to add/remove Aheadworks GiftCard via V2 update-cart api hook
Fixes: https://boltpay.atlassian.net/browse/M2P-266
#changelog Add/Remove Aheadworks GiftCard by API hooks

M2P-266 Add/Remove Aheadworks GiftCard by API hooks

---

.circleci/config.yml

#changelog [MP-1547] Display Branch Name on MX-Greenkeeper Slack Notification
display branch name on mx-greenkeeper slack notification 

[MP-1547] Display Branch Name on MX-Greenkeeper Slack Notification

---

Block/Js.php
Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Model/EventsForThirdPartyModules.php
ThirdPartyModules/Listrak/Remarketing.php
view/frontend/templates/js/boltglobaljs.phtml

Listrak Intergration
Fixes: https://boltpay.atlassian.net/browse/M2P-247
#changelog M2P-247 Listrak Intergration

M2P-247 Listrak Intergration

---

Helper/Session.php
etc/di.xml

Remove the declaration for Mageplaza_ShippingRestricton module in file di.xml because it's not used anywhere
Fixes: https://boltpay.atlassian.net/browse/M2P-281
#changelog Remove the declaration for Mageplaza_ShippingRestricton module in file di.xml

Remove the declaration for Mageplaza_ShippingRestricton module in file di.xml

---

view/frontend/templates/button_product_page.phtml

Add the additional attributes into the checkout button in the product detail page
Fixes: https://boltpay.atlassian.net/browse/M2P-273
#changelog Add the additional attributes into the checkout button in the product detail page

Add the additional attributes into the checkout button in the product detail page

---

Helper/Cart.php

We have a lot of cases that the discount code is empty when collecting cart data from quote, and this PR is to report this exception to Bugsnag for further investigation.
Fixes: https://boltpay.atlassian.net/browse/M2P-245
#changelog Report to Bugsnag if the discount code is empty when building cart data from quote

M2P-245 Report to Bugsnag if the discount code is empty when building cart data from quote

---

Model/Api/UpdateDiscountTrait.php
Model/ErrorResponse.php
Test/Unit/Model/Api/UpdateDiscountTraitTest.php

Fixes: [M2P-274](https://boltpay.atlassian.net/browse/M2P-274)
#changelog M2P-274 Implement discount code error for  "Code requires login"

M2P-274 Implement discount code error for  "Code requires login"

---

Observer/TrackingSaveObserver.php
Test/Unit/Observer/TrackingSaveObserverTest.php

Although native Magento code does not update track object (only create new ones and delete), if any 3p module update track we can have redundant API calls to hail.
By this PR:
- if track object was updated don't make API call with the same track_id
- add track entity ID to payload, it helps to investigate issues with 3p modules
Fixes: [MA-170](https://boltpay.atlassian.net/browse/MA-170)
#changelog MA-170 Tracking observer: if track object was updated don't make API call with the same track_id

MA-170 Tracking observer: if track object was updated don't make API call with the same track_id

---

Helper/Cart.php
Helper/Discount.php
Model/EventsForThirdPartyModules.php
Test/Unit/Helper/CartTest.php
Test/Unit/Helper/DiscountTest.php
ThirdPartyModules/Aheadworks/StoreCredit.php
etc/di.xml

Code refactoring for 3rd-party module Aheadworks StoreCredit
Fixes: https://boltpay.atlassian.net/browse/M2P-280
#changelog M2P-280 Code refactoring for 3rd-party module Aheadworks StoreCredit

M2P-280 Code refactoring for 3rd-party module Aheadworks StoreCredit

---

Helper/Bugsnag.php
Helper/Cart.php
Helper/MetricsClient.php
Helper/Session.php
Model/Api/ShippingMethods.php
Model/Api/UpdateCartItemTrait.php
Test/Unit/Block/JsTest.php
Test/Unit/Helper/CartTest.php
Test/Unit/Helper/OrderTest.php
Test/Unit/Helper/SessionTest.php
Test/Unit/Model/Api/ShippingMethodsTest.php
Test/Unit/TestHelper.php

M2P-268 Fix the error issues reported by the Magento coding standard
Fixes: https://boltpay.atlassian.net/browse/M2P-268
#changelog M2P-268 Fix the error issues reported by the Magento coding standard

M2P-268 Fix the error issues reported by the Magento coding standard

---

CHANGELOG.md
composer.json
etc/module.xml

2.16.0 release notes 
#changelog 2.16.0 release notes

2.16.0 release notes

---

Observer/TrackingSaveObserver.php
Test/Unit/Observer/TrackingSaveObserverTest.php

Correct the exception in the catch block
See here: https://prnt.sc/uxtvey
Fixes: https://boltpay.atlassian.net/browse/M2P-315
#changelog Add the path for the exception

Correct the exception in the catch block

---

Test/scripts/ci-integration.sh

#changelog CI - More threads for ci-integration

CI - More threads for ci-integration

---

view/adminhtml/templates/boltpay/js/replacejs.phtml

Show validation message and prevent using the pay by link if the token is invalid
Fixes: https://boltpay.atlassian.net/browse/EN-1106
#changelog  M2P-320 Show validation message and prevent using the pay by link if the token is invalid

 M2P-320 Show validation message and prevent using the pay by link if the token is invalid

---

CHANGELOG.md

Fix readme

---

create_release.sh

#changelog Add script for creating release for magento.com

Add script for creating release for magento.com

---

etc/csp_whitelist.xml

Lots of red items in dev console regarding CSP, bolt and bugsnag related
Fixes: [M2P-330](https://boltpay.atlassian.net/browse/M2P-330)
#changelog Remove reported Content Security Policy warnings

M2P-330 - Remove reported Content Security Policy warnings

---

Model/EventsForThirdPartyModules.php
ThirdPartyModules/Amasty/Rewards.php

Add support to remove Amasty Rewards from Bolt modal by API hooks
Fixes: https://boltpay.atlassian.net/browse/M2P-314
#changelog Remove Amasty Rewards by API hooks

M2P-314 Remove Amasty Rewards by API hooks

---

Test/Unit/Model/Api/Data/CartDataTest.php
Test/Unit/Model/Api/Data/UpdateCartResultTest.php

Unit test for PR https://github.com/BoltApp/bolt-magento2/pull/983
Fixes: https://boltpay.atlassian.net/browse/M2P-296
#changelog M2P-296 Unit test for PR 983

M2P-296 Unit test for PR 983

---

Model/EventsForThirdPartyModules.php
ThirdPartyModules/IDme/GroupVerification.php

Apply the id.me data to the customer session to correct the discount
Fixes: https://boltpay.atlassian.net/browse/M2P-305
#changelog M2P-305 Apply the id.me data to the customer session to correct the discount

M2P-305 Apply the id.me data to the customer session to correct the discount

---

Helper/FeatureSwitch/Definitions.php

The feature switch is already enabled in hail, need to update source code for better readability
#changelog Enable M2_PAY_BY_LINK feature switch

Enable M2_PAY_BY_LINK feature switch

---

CHANGELOG.md
composer.json
etc/module.xml

Release Notes for 2.17.0

---

Model/EventsForThirdPartyModules.php
ThirdPartyModules/Mirasvit/Credit.php

Add support to remove Mirasvit credit by v2 update_cart api hook
Fixes: https://boltpay.atlassian.net/browse/M2P-346
#changelog Remove Mirasvit credit by API hooks

M2P-346 Remove Mirasvit credit by API hooks

---

README.md

#changelog Change Magento version in readme to 2.3

Change Magento version in readme to 2.3

---

view/adminhtml/templates/boltpay/button.phtml

Support translation for text
Fixes: https://boltpay.atlassian.net/browse/M2P-341
#changelog M2P-341 Support translation for text

M2P-341 Support translation for text

---

README.md

Add create order url in README.md
Fixes: https://boltpay.atlassian.net/browse/M2P-364
#changelog M2P-364 Add create order url in README.md

M2P-364 Add create order url in README.md

---

Model/Api/UpdateDiscountTrait.php

Additional location that was needed for the discount code PR https://github.com/BoltApp/bolt-magento2/pull/996
Fixes: M2P-264
#changelog Additional discount code change to unify everything

Additional discount code change to unify everything

---

README.md

Update README.md
Fixes: https://boltpay.atlassian.net/browse/M2P-369
#changelog M2P-369 Update README.md

M2P-369 Update README.md

---

Helper/Order.php
Test/Unit/Helper/OrderTest.php
Test/Unit/README.md
Test/Unit/TestUtils.php

Integration test for PR 1012
Fixes: https://boltpay.atlassian.net/browse/M2P-337
#changelog Integration test for PR 1012

M2P-337 Integration test for PR 1012

---

Helper/Cart.php
view/frontend/templates/js/replacejs.phtml

Restory payment only checkout flow
Fixes: [M2P-205](https://boltpay.atlassian.net/browse/M2P-205)
#changelog M2P-205 Restore payment only checkout flow

M2P-205 Restore payment only checkout flow

---

Helper/Cart.php

Root cause:
The original discount amount of sale rule is not rounded yet when the Bolt plugin collects discounts, and it is 77.675, then the Bolt plugin convert it to 7768, and calculates the diff between 7767.5 (non-rounding result) and 7768, there is 0.5 diff. After that, Bolt plugin rounds this diff amount to 1 and add it to item unit price, it eventually causes the mismatch error when fetching shipping options.
Solution:
I have checked the M2 core code, and actually it rounds the discount amount as the same way as we do, So there is no need to calculate the diff anymore.
TODO:
Investigate the calculated diff for other gift card&rewards&store credits
Fixes: https://boltpay.atlassian.net/browse/M2P-376
#changelog M2P-376 Remove diff for M2 native discounts
Please validate that you have …

M2P-376 Remove diff for M2 native discounts

---

view/frontend/templates/js/replacejs.phtml

See discussion here https://boltpay.atlassian.net/browse/M2P-377?focusedCommentId=44614
#changelog Move subscribe call for better readability

Move subscribe call for better readability

---

Block/Js.php
Helper/Cart.php
Model/Api/UpdateCart.php
Model/Api/UpdateCartCommon.php
Test/Unit/Block/JsTest.php
Test/Unit/Helper/CartTest.php
Test/Unit/Model/Api/UpdateCartTest.php
view/frontend/templates/button_product_page.phtml

PPC - implement quote caching
Fixes: https://boltpay.atlassian.net/browse/M2P-11
#changelog M2P-11 - PPC quote caching

M2P-11 - PPC quote caching

---

Test/Unit/Helper/CartTest.php

Use integration tests instead of unit test for method collectDiscounts in class Helper/Cart
Fixes: https://boltpay.atlassian.net/browse/M2P-333
#changelog M2P-333 Use integration tests instead of unit test for method collectDiscounts in class Helper/Cart

M2P-333 Use integration tests instead of unit test for method collectDiscounts in class Helper/Cart

---

view/frontend/templates/js/replacejs.phtml

Use encodeURIComponent to correct the email when posting Ajax request
Fixes: https://boltpay.atlassian.net/browse/M2P-367
#changelog M2P-367 Use encodeURIComponent to correct the email when posting Ajax request

M2P-367 Use encodeURIComponent to correct the email when posting Ajax request

---

Plugin/Mirasvit/RewardsCheckout/Controller/Checkout/ApplyPointsPostPlugin.php
ThirdPartyModules/Mirasvit/Rewards.php
etc/di.xml

On the cart page, the customer can enter any number of points which they would like to spend or choose "Use maximum". 
But in the Bolt plugin, we always try to apply full balance to the cart whatever the customer enter .
Then we need to update the functions to implement the logic as same as Mirasvit rewards plugin does.
So only if the customer choose "Use maximum" we send full balance to the Bolt.
or we just apply specific points as much as the customer enter
Fixes: https://boltpay.atlassian.net/browse/M2P-399
#changelog Apply Mirasvit rewards points to the Bolt cart per the customer choose to spend

M2P-399 Apply Mirasvit rewards points to the Bolt cart per the customer choose to spend

---

Test/Unit/Controller/Adminhtml/Order/SaveTest.php
Test/Unit/Helper/ApiTest.php
Test/Unit/Helper/CartTest.php
Test/Unit/Helper/SessionTest.php
Test/Unit/Model/Api/DiscountCodeValidationTest.php
Test/Unit/Model/Api/ShippingMethodsTest.php

Fix some other PHPUnit tests errors
Fixes: https://boltpay.atlassian.net/browse/M2P-409
#changelog Fix PHPUnit tests errors

M2P-409 Fix PHPUnit tests errors

---

.circleci/config.yml
Test/scripts/install_magento.sh
operations/docker/php74/Dockerfile
operations/docker/php74/auth-sample.json

#changelog [MA-375] Add circle image for php7.4 m2.4 unit test

[MA-375] Add circle image for php7.4 m2.4 unit test

---

Controller/Order/ReceivedUrl.php
Test/Unit/Controller/Order/ReceivedUrlTest.php

In the success redirect logic, frontend or backend, we rely on the HTTP_ REFERER header.
However, according to the browser Referrer-Policy strict-origin-when-cross-origin, the whole referrer URL may not be sent, having just the origin (base url, domain) and our check would fail. So for admin orders, instead for checking for the full admin order page referrer, we reverse the logic and check if the order is made through pay-by-link (no referrer or Bolt referrer) otherwise we consider it an admin order and do the redirection.
https://developers.google.com/web/updates/2020/07/referrer-policy-new-chrome-default
Fixes: [ON-438](https://boltpay.atlassian.net/browse/ON-438)
#changelog Redirect to admin: multistore and referrer policy strict-origin-when-cross-origin fix
Please validate that you …

ON-438 - Redirect to admin: multistore and referrer policy strict-origin-when-cross-origin fix

---

Model/Api/UpdateDiscountTrait.php
Test/Unit/Model/Api/UpdateDiscountTraitTest.php

1. Detect inactive coupon
2. Detect if quote does not meet rule's conditions
Fixes: https://boltpay.atlassian.net/browse/M2P-422
#changelog Improve the process of applying coupon

M2P-422 Improve the process of applying coupon

---

composer.json
etc/module.xml

Release notes TBD
#changelog Bump plugin version

Bump plugin version

---

Test/Unit/Model/Api/UniversalApiTest.php

[This test run](https://app.circleci.com/pipelines/github/BoltApp/bolt-magento2/7894/workflows/0eb0bc20-135e-4a35-8b96-460aae3c9952/jobs/30963) failed in circleci after merging https://github.com/BoltApp/bolt-magento2/pull/1085. This should fix it.
~Additionally, should check adding php74-2.4.0 to the pre-merge checks~ **EDIT**: Looks like it's been added now. It didn't run on 1085 so I assumed it hadn't been added yet
Fixes: 
#changelog Fix failing circle test run

Fix failing circle test run

---

Test/Unit/Helper/CartTest.php
Test/Unit/Helper/OrderTest.php
Test/Unit/Model/Api/OrderManagementTest.php
Test/Unit/TestUtils.php

Create integration style tests for class OrderManagement
Fixes: https://boltpay.atlassian.net/browse/M2P-420
#changelog Create integration style tests for class OrderManagement

M2P-420 Create integration style tests for class OrderManagement

---

Test/Unit/Model/Api/OrderManagementTest.php
Test/Unit/TestUtils.php

Refactor OrderManagementTest code
Fixes: https://boltpay.atlassian.net/browse/M2P-451
#changelog Refactor OrderManagementTest code

M2P-451 Refactor OrderManagementTest code

---

CHANGELOG.md
composer.json
etc/module.xml

#changelog 2.18.1 hotfix release notes

2.18.1 hotfix release notes

---

Model/ThirdPartyEvents/CollectsSessionData.php
Model/ThirdPartyEvents/RestoresSessionData.php
Test/Unit/Helper/ConfigTest.php
Test/Unit/ThirdPartyModules/IDme/GroupVerificationTest.php

Additional unit tests for https://github.com/BoltApp/bolt-magento2/pull/1091
Fixes: https://boltpay.atlassian.net/browse/M2P-418
#changelog M2P-418 - additional unit tests for proper-session-emulation-via-metadata

M2P-418 - additional unit tests for proper-session-emulation-via-metadata

---

Model/Api/UpdateCartItemTrait.php

If the customer tries to remove an item from the cart, there is no need to check its valid quantity in the store.
Fixes: https://boltpay.atlassian.net/browse/M2P-466
#changelog Bugfix: Unable to remove items from Cart with Update Cart Endpoint

M2P-466 Bugfix: Unable to remove items from Cart with Update Cart Endpoint

---

Helper/Discount.php
ThirdPartyModules/Amasty/GiftCard.php

Fix undefined method error
#changelog Fix undefined method error

Fix undefined method error

---

Setup/UpgradeSchema.php

#changelog [MA-526] Add new table for SSO

[MA-526] Add new table for SSO

---

Model/Api/Data/AutomatedTesting/Cart.php
Model/Api/Data/AutomatedTesting/CartItem.php
Model/Api/Data/AutomatedTesting/Config.php
Model/Api/Data/AutomatedTesting/PriceProperty.php
Model/Api/Data/AutomatedTesting/StoreItem.php
Model/Api/Data/DebugInfo.php
Model/Api/Debug.php
Setup/Recurring.php
Setup/RecurringData.php
Setup/UpgradeSchema.php

#changelog Format some files I recently touched

Format some files I recently touched

---

Api/OAuthRedirectInterface.php
Helper/AutomatedTesting.php
Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Helper/FeatureSwitch/Manager.php
Model/Api/Debug.php
Model/Api/OAuthRedirect.php
Setup/Recurring.php
Setup/RecurringData.php
Setup/UpgradeSchema.php
Test/Unit/Setup/UpgradeSchemaTest.php
etc/di.xml
etc/webapi.xml

#changelog [MA-528] Add feature switch for Bolt SSO and a skeleton of the new endpoint that just returns a 500
[MA-528]: https://boltpay.atlassian.net/browse/MA-528

[M2P-486] Add feature switch for Bolt SSO and a skeleton of the new endpoint that just returns a 500

---

CHANGELOG.md

Updated Release Notes  for 2.19.0

release notes 2.19.0

---

Helper/SSOHelper.php
Test/Unit/Helper/AutomatedTestingTest.php
Test/Unit/Helper/SSOHelperTest.php

#changelog [M2P-485] Add method to parse and validate jwt token

[M2P-485] Add method to parse and validate jwt token

---

Api/Data/ExternalCustomerEntityInterface.php
Api/ExternalCustomerEntityRepositoryInterface.php
Model/ExternalCustomerEntity.php
Model/ExternalCustomerEntityRepository.php
Model/ResourceModel/ExternalCustomerEntity.php
Model/ResourceModel/ExternalCustomerEntity/Collection.php
Test/Unit/Model/ExternalCustomerEntityRepositoryTest.php
Test/Unit/Model/ExternalCustomerEntityTest.php
Test/Unit/Model/ResourceModel/ExternalCustomerEntity/CollectionTest.php
Test/Unit/Model/ResourceModel/ExternalCustomerEntityTest.php
etc/di.xml

#changelog [M2P-487] Add external customer entity repository and related files

[M2P-487] Add external customer entity repository and related files

---

Helper/Config.php
Test/Unit/Helper/ConfigTest.php
etc/adminhtml/system.xml
etc/config.xml

Just like custom_api, this will not be visible in admin. This is only for easier testing during development.
#changelog Add a custom setting for public key for testing

Add a custom setting for public key for testing

---

Test/Unit/Model/Api/DebugTest.php

Use integration test instead of unit test for all methods in class Mode/Api/DebugTest
#changelog  Use integration test instead of unit test for all methods in class Mode/Api/DebugTest

 Use integration test instead of unit test for all methods in class Mode/Api/DebugTest

---

ThirdPartyModules/Amasty/GiftCard.php

$this->bugsnag is undefined and should be replaced with $this->bugsnagHelper
https://github.com/BoltApp/bolt-magento2/blob/master/ThirdPartyModules/Amasty/GiftCard.php#L396
#changelog Fix undefined variable

Fix undefined variable

---

Api/GetAccountInterface.php
Helper/Hook.php
Model/Api/GetAccount.php
Test/Unit/Helper/HookTest.php
Test/Unit/Model/Api/GetAccountTest.php
etc/di.xml
etc/webapi.xml

#changelog [M2P-492] Add endpoint to check if user with email exists

[M2P-492] Add endpoint to check if user with email exists

---

Model/Api/UpdateDiscountTrait.php
Test/Unit/Model/Api/UpdateDiscountTraitTest.php
ThirdPartyModules/Aheadworks/Giftcard.php
ThirdPartyModules/Amasty/GiftCard.php
ThirdPartyModules/Amasty/GiftCardAccount.php
ThirdPartyModules/Magento/GiftCardAccount.php
ThirdPartyModules/Mageplaza/GiftCard.php

If the filter return null, it means no valid gift card loaded , and if the exception object is returned, we need to report it to the Bolt server.
Fixes: https://boltpay.atlassian.net/browse/M2P-476
#changelog Exception handling for filter loadGiftcard

M2P-476 Exception handling for filter loadGiftcard

---

Helper/Cart.php
Helper/Order.php
Model/EventsForThirdPartyModules.php
ThirdPartyModules/Zonos/DutyTax.php

Add support for Zonos_DutyTax
Fixes: https://boltpay.atlassian.net/browse/ON-587
#changelog Add support for Zonos_DutyTax

Add support for Zonos_DutyTax

---

composer.json
etc/module.xml

Bump version

---

Test/scripts/ci-magento-integration.sh

Fix codecov

---

Model/Api/OAuthRedirect.php
Test/Unit/Model/Api/OAuthRedirectTest.php
etc/webapi.xml

This is so that the OAuth redirect endpoint is compliant with the OAuth spec.
#changelog Use GET for OAuth redirect endpoint and add logger

Use GET for OAuth redirect endpoint and add logger

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

When transfer data from parent quote to the immutable quote ([code link](https://github.com/BoltApp/bolt-magento2/blob/2.18.1/Helper/Cart.php#L1105)), our plugin directly set the 'items' property with the data of parent quote ([code link](https://github.com/magento/magento2/blob/fbfac3e51730abe2b79c6072544bc9742fcf7606/app/code/Magento/Quote/Model/Quote.php#L560)), as a result, when calling $immutableQuote->getItems();, actually it returns the items in parent quote instead of immutable quote, and eventually causes the exception __('The %1 Cart doesn\'t contain the %2 item.', $cartId, $itemId)([code link](https://github.com/magento/magento2/blob/fbfac3e51730abe2b79c6072544bc9742fcf7606/app/code/Magento/Quote/Model/Quote/Item/CartItemPersister.php#L70))
Solution: Refer to M2 core code …

ON-648 Bugfix: The Cart doesn't contain the xxxx item

---

Helper/JWT/BeforeValidException.php
Helper/JWT/ExpiredException.php
Helper/JWT/JWK.php
Helper/JWT/JWT.php
Helper/JWT/LICENSE
Helper/JWT/SignatureInvalidException.php

#changelog Add firebase php jwt library into our codebase directly

Add firebase php jwt library into our codebase directly

---

Helper/Api.php
Helper/FeatureSwitch/Definitions.php
Helper/GraphQL/Client.php
Helper/SSOHelper.php
Helper/Shared/ApiUtils.php
Model/Api/OAuthRedirect.php
Test/Unit/Helper/ApiTest.php
Test/Unit/Helper/SSOHelperTest.php
Test/Unit/Helper/Shared/ApiUtilsTest.php
Test/Unit/Model/Api/OAuthRedirectTest.php

And make several other fixes based on the OAuth API:
- Use form-urlencoded as the ContentType
- Use the correct encoding for the POST data
- Format the RSA public key correctly
#changelog Update OAuth endpoint to use 3rd party library for JWT validation
- [] I have added my Jira ticket link and provided a changelog message.

Update OAuth endpoint to use 3rd party library for JWT validation

---

Model/Api/UpdateDiscountTrait.php
Test/Unit/Model/Api/UpdateDiscountTraitTest.php
ThirdPartyModules/Aheadworks/Giftcard.php
ThirdPartyModules/Amasty/GiftCard.php
ThirdPartyModules/Amasty/GiftCardAccount.php
ThirdPartyModules/Magento/GiftCardAccount.php
ThirdPartyModules/Mageplaza/GiftCard.php

Fixes: [M2P-507](https://boltpay.atlassian.net/browse/M2P-507)
#changelog M2P-507 Revert refactoring around 3p modules error handling.

M2P-507 Revert refactoring around 3p modules error handling.

---

Test/scripts/ci-magento-integration.sh

Some files weren't showing up in codecov. This is because there are some other files with the same name so codecov doesn't know what to do. I just delete everything else and only keep magento/app/code/Bolt/Boltpay.
#changelog Fix codecov again

Fix codecov again

---

CHANGELOG.md

Release notes for 2.20.0
#changelog release notes for 2.20.0

release notes for 2.20.0

---

Model/Api/LegacyApi.php

Had the wrong name of the variable in the constructor.
#changelog Fix incorrect constructor

Fix incorrect constructor

---

Api/OAuthRedirectInterface.php
Model/Api/OAuthRedirect.php
Test/Unit/Model/Api/OAuthRedirectTest.php

#changelog [M2P-504] Link order with newly created customer during sso login

[M2P-504] Link order with newly created customer during sso login

---

Helper/Session.php
Model/EventsForThirdPartyModules.php
Test/Unit/Helper/SessionTest.php
ThirdPartyModules/Mageside/CustomShippingPrice.php

Add support for the module Mageside Custom Shipping Price (https://marketplace.magento.com/mageside-module-custom-shipping-price.html)
Fixes: https://boltpay.atlassian.net/browse/M2P-516
#changelog Add support for Mageside Custom Shipping Price

M2P-516 Add support for Mageside Custom Shipping Price

---

view/frontend/templates/js/replacejs.phtml

Minor whitespace cleanup.
#changelog Minor whitespace cleanup.

Minor whitespace cleanup.

---

Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Model/Api/UpdateDiscountTrait.php
Test/Unit/Model/Api/UpdateDiscountTraitTest.php
Test/Unit/ThirdPartyModules/Amasty/GiftCardAccountTest.php
ThirdPartyModules/Aheadworks/Giftcard.php
ThirdPartyModules/Amasty/GiftCard.php
ThirdPartyModules/Amasty/GiftCardAccount.php
ThirdPartyModules/Magento/GiftCardAccount.php
ThirdPartyModules/Mageplaza/GiftCard.php

Contexts: https://boltpay.atlassian.net/browse/M2P-507
So instead of returning the exception directly
- log all unexpected exceptions into bugsnag when they are thrown
- add feature switch disabled by default to return error if there is any exception
In this case we can enable feature switch for the specific merchant if needed.
After few months we can enable this feature switch by default or even remove it
Fixes: https://boltpay.atlassian.net/browse/M2P-510
#changelog Exception handling for filter loadGiftcard

M2P-510 Exception handling for filter loadGiftcard

---

Helper/Cart.php
Helper/Order.php
Model/EventsForThirdPartyModules.php
ThirdPartyModules/MageWorld/Affiliate.php

Add support for MageWorld Affiliate
Fixes: https://boltpay.atlassian.net/browse/M2P-520
#changelog Add support for MageWorld Affiliate

M2P-520 Add support for MageWorld Affiliate

---

Test/Unit/Model/Api/ShippingTaxTest.php

Use integration test instead of unit test for all methods in class Mode/Api/ShippingTaxTest
#changelog Use integration test instead of unit test for all methods in class Mode/Api/ShippingTaxTest

Use integration test instead of unit test for all methods in class Mode/Api/ShippingTaxTest

---

Test/Unit/Model/Api/ShippingTest.php

Use integration test instead of unit test for all methods in class Mode/Api/ShippingTest
#changelog  Use integration test instead of unit test for all methods in class Mode/Api/ShippingTest

 Use integration test instead of unit test for all methods in class Mode/Api/ShippingTest

---

Test/Unit/Model/Api/TaxTest.php

Use integration test instead of unit test for all methods in class Mode/Api/TaxTest
#changelog Use integration test instead of unit test for all methods in class Mode/Api/TaxTest

Use integration test instead of unit test for all methods in class Mode/Api/TaxTest

---

Test/Unit/Model/Api/ShippingMethodsTest.php

Use integration test instead of unit test for all methods in class Mode/Api/ShippingMethodTest
#changelog Use integration test instead of unit test for all methods in class Mode/Api/ShippingMethodTest

Use integration test instead of unit test for all methods in class Mode/Api/ShippingMethodTest

---

Test/Unit/Model/Api/UniversalApiTest.php

Use integration test instead of unit test for all methods in class Mode/Api/UniversalApiTest
#changelog Use integration test instead of unit test for all methods in class Mode/Api/UniversalApiTest

Use integration test instead of unit test for all methods in class Mode/Api/UniversalApiTest

---

Helper/Order.php
Helper/Session.php
Model/Api/DiscountCodeValidation.php
Model/Api/ShippingMethods.php
Model/Api/ShippingTax.php
Model/Api/UpdateCartCommon.php

Fix loadSession error when metadata is explicit null
Fixes: https://boltpay.atlassian.net/browse/M2P-543
#changelog M2P-543 - Fix loadSession error when metadata is explicit null

M2P-543 - Fix loadSession error when metadata is explicit null

---

Test/Unit/Model/Api/UpdateSettingsTest.php

Use integration test instead of unit test for all methods in class Mode/Api/UpdateSettingTest
#changelog Use integration test instead of unit test for all methods in class Mode/Api/UpdateSettingTest

M2P-540 Use integration test instead of unit test for all methods in class Mode/Api/UpdateSettingTest

---

Helper/Config.php
Test/Unit/Helper/ConfigTest.php

We hardcode the key for now, but plan to expose an endpoint for fetching it
in the future. It is not a security risk to hardcode this publicly since
this is a public key.
#changelog Add production public key for Bolt SSO via OAuth

Add production public key for Bolt SSO via OAuth

---

Helper/JWT/JWT.php

#changelog Allow 1 second of leeway when validating the timestamp for the JWT

Allow 1 second of leeway when validating the timestamp for the JWT

---

Setup/Uninstall.php

Add uninstall script to clean up all Bolt created tables, columns and configurations when the Bolt plugin is uninstalled by a merchant.
Fixes: [MA-648](https://boltpay.atlassian.net/browse/MA-648)
#changelog [MA-648] Add uninstall script for Module

[MA-648] Add uninstall script for Module

---

Test/Unit/Model/Api/UpdateCartItemTraitTest.php

Use integration test instead of unit test for all methods in class Model /Api/UpdateCartItemTraitTest
Fixes: https://boltpay.atlassian.net/browse/M2P-550
#changelog M2P-550 Use integration test instead of unit test for all methods in class Model /Api/UpdateCartItemTraitTest

M2P-550 Use integration test instead of unit test for all methods in class Model /Api/UpdateCartItemTraitTest

---

Test/Unit/Model/Api/OAuthRedirectTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\Api\OAuthRedirectTest
Fixes: https://boltpay.atlassian.net/browse/M2P-555
#changelog M2P-555 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\Api\OAuthRedirectTest

M2P-555 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\Api\OAuthRedirectTest

---

Helper/Cart.php
Model/Api/CreateOrder.php
Model/Api/ShippingMethods.php
Model/EventsForThirdPartyModules.php
Model/ThirdPartyEvents/FiltersCartBeforeLegacyShippingAndTax.php
Model/ThirdPartyEvents/FiltersCartItems.php
Model/ThirdPartyEvents/FiltersTransactionBeforeValidation.php
Test/Unit/ThirdPartyModules/Magecomp/ExtrafeeTest.php
ThirdPartyModules/Magecomp/Extrafee.php

Move Larson Jewelers custom code to source
- Magecomp_Extrafee support
Fixes: https://boltpay.atlassian.net/browse/M2P-511
#changelog Magecomp_Extrafee support

M2P-511 - Move Larson Jewelers Extrafee code to source #1 Magecomp_Extrafee support

---

Helper/Order.php
Model/EventsForThirdPartyModules.php
Plugin/Webkul/Odoomagentoconnect/Model/ResourceModel/OrderPlugin.php
Test/Unit/Plugin/Webkul/Odoomagentoconnect/Model/ResourceModel/OrderPluginTest.php
Test/Unit/ThirdPartyModules/Webkul/OdoomagentoconnectTest.php
ThirdPartyModules/Webkul/Odoomagentoconnect.php
etc/di.xml

Move Larson Jewelers custom code to source
This PR is the support for Webkul Odoomagentoconnect module
Fixes: https://boltpay.atlassian.net/browse/M2P-511
#changelog Webkul_Odoomagentoconnect support

M2P-511 - Move Larson Jewelers Extrafee code to source #2 Webkul_Odoomagentoconnect support

---

Test/Unit/Model/WebhookLogTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\WebhookLogTest
Fixes: https://boltpay.atlassian.net/browse/M2P-558
#changelog M2P-558 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\WebhookLogTest

M2P-558 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\WebhookLogTest

---

Api/Data/GetProductDataInterface.php
Api/GetProductInterface.php
Model/Api/Data/GetProductData.php
Model/Api/GetAccount.php
Model/Api/GetProduct.php
etc/di.xml
etc/webapi.xml

Adding an endpoint to fetch Product Inventory. The expected behavior is to have it perform similarly to https://devdocs.magento.com/redoc/2.2/#operation/catalogProductRepositoryV1GetGet
The new testing framework is not working properly. Spoke with @njfaries, added TODO for unit tests later
#changelog Adding endpoint to fetch Product Info from a given site. 

Fetch Product Info V0

---

Test/Unit/Observer/ClearBoltShippingTaxCacheObserverTest.php

M2P-560 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Observer\ClearBoltShippingTaxCacheObserver
Fixes: https://boltpay.atlassian.net/browse/M2P-560
#changelog M2P-560 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Observer\ClearBoltShippingTaxCacheObserver

M2P-560 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Observer\ClearBoltShippingTaxCacheObserver

---

Test/Unit/Model/Api/FeatureSwitchesHookTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\Api\FeatureSwitchesHookTest
Fixes: https://boltpay.atlassian.net/browse/M2P-559
#changelog M2P-559 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\Api\FeatureSwitchesHookTest

M2P-559 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\Api\FeatureSwitchesHookTest

---

Api/Data/GetProductDataInterface.php
Api/Data/ProductInventoryInfoInterface.php
Api/GetProductInterface.php
Model/Api/Data/GetProductData.php
Model/Api/Data/ProductInventoryInfo.php
Model/Api/GetProduct.php
etc/di.xml

Follow up to https://github.com/BoltApp/bolt-magento2/pull/1223
-Add parent/children lookup for configurable items
-Add stock to each of those products fetched
- remove hmac validation from get request
#changelog WIP: fetch inventory v1

Fetch Product Info V1

---

Test/Unit/Model/ResourceModel/WebhookLog/CollectionTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\ResourceModel\WebhookLog\CollectionTest
Fixes: https://boltpay.atlassian.net/browse/M2P-562
#changelog Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\ResourceModel\WebhookLog\CollectionTest

M2P-562 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\ResourceModel\WebhookLog\CollectionTest

---

Api/Data/GetProductDataInterface.php
Model/Api/Data/GetProductData.php
Model/Api/GetProduct.php

Added list of configurable product's attribute options to the getProduct endpoint. Thsi is so that attributes can be understood throughout the product structure. 
#changelog WIP: Added list of configurable product's attribute options to the getProduct endpoint.

Add list of super attribute options to product endpoint

---

Api/Data/GetProductDataInterface.php
Model/Api/Data/GetProductData.php
Model/Api/GetProduct.php

Add base image url to product endpoint so we can fully understand image paths
#changelog Add base image url for product images

Add base image url for product images

---

Model/Api/OAuthRedirect.php

#changelog Update logic for linking order

Update logic for linking order

---

etc/csp_whitelist.xml

This prevents warnings in the browser console in report mode and allows
fetching and running the scripts in restrict mode.
#changelog Add account.bolt.com to the CSP Allowlist

Add account.bolt.com to the CSP Allowlist

---

Model/Api/GetProduct.php

#changelog Add performance improvements and DRY-out the code

Add performance improvements and DRY-out the code

---

README.md
Test/scripts/ci-magento-integration.sh
Test/scripts/ci-unit.sh

Remove codecov uploader
ref: https://github.com/BoltApp/bolt-magento1/pull/473/files
#changelog Remove codecov uploader

Remove codecov uploader

---

Test/Unit/Controller/Cart/EmailTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Controller\Cart\EmailTest
Fixes: https://boltpay.atlassian.net/browse/M2P-581
#changelog M2P-581 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Controller\Cart\EmailTest

M2P-581 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Controller\Cart\EmailTest

---

Api/Data/GetProductDataInterface.php
Model/Api/Data/GetProductData.php
Model/Api/GetProduct.php

Add Store ID to product Inventory Call. This is needed to add the product to a cart. 
#changelog Add Store ID to product Inventory Call

Add Store ID to product Inventory Call

---

Model/Api/Data/AutomatedTesting/Address.php
Model/Api/Data/AutomatedTesting/Order.php
Model/Api/Data/AutomatedTesting/OrderItem.php

add some new classes to represent past orders.
https://boltpay.atlassian.net/browse/MA-843
#changelog MA-843 scaffold data model for past orders

MA-843 scaffold data model for past orders

---

CHANGELOG.md
composer.json
etc/module.xml

2.21.1 version bump
#changelog 2.21.1 bump and changelog. Fixed link to previous version tag as well

2.21.1 bump 

---

Helper/Cart.php
Model/Api/UpdateCartCommon.php
Test/Unit/Helper/CartTest.php
Test/Unit/Model/Api/UpdateCartCommonTest.php

With MageWorx Advanced Product Options Suite, the merchant can associate existing product as custom option, then the format of sku could combine with MAGENTO SKU DELIMITER.
eg. the sku of parent product is 24-MG01 and the skus of associated product options are 25-MG02 and 26-MG03, then the sku of cart item become 24-MG01-25-MG02-26-MG03 
as a result, the current logic to retrieve sku of parent product does not work anymore.
This PR mainly fix two issues:
1. Get the skus of associated product options properly.
2. Using str_replace(self::MAGENTO_SKU_DELIMITER.$customizableOption['sku'], '', $sku); to remove the custom option skus, cause that's the rule to build the sku of cart item which has custom options in Magento 2.
Fixes: https://boltpay.atlassian.net/browse/M2P-553
#changelog M2P-553 …

M2P-553 Add support for MageWorx Advanced Product Options Suite

---

Model/Api/GetProduct.php

Merging a change made by @danac-gs a week or so ago. Tested it locally and it is working wonderfully! These changes make getting item properties much more efficient and simpler. 
#changelog Add performance improvements and DRY-out the code (#1262)

Add performance improvements and DRY-out the code (#1262)

---

Block/Info.php
Test/Unit/Block/InfoTest.php
view/adminhtml/templates/info/pdf/default.phtml

Add processor / card info to the invoice printout. (Verify the appropriate info is displayed system-wide)
Fixes: https://boltpay.atlassian.net/browse/M2P-525
#changelog Add processor to admin invoice print

M2P-525 - Add processor to admin invoice print

---

CHANGELOG.md
composer.json
etc/module.xml

Bump for 2.21.2
#changelog 2.21.2 bump

2.21.2 bump

---

Plugin/Shineretrofits/ShippingMethod/Model/Carrier/CustomshippingPlugin.php
etc/di.xml

Add support for Shineretrofits custom shipping, that's a custom shipping module built by the merchant Shineretrofits
Fixes: https://boltpay.atlassian.net/browse/EN-4605
#changelog Add support for Shineretrofits custom shipping

EN-4605 Add support for Shineretrofits custom shipping

---

Model/EventsForThirdPartyModules.php
ThirdPartyModules/BagRiders/StoreCredit.php

This merchant has a custom Store Credit module, and our team decide to support it in main repo of Bolt plugin.
Fixes: https://boltpay.atlassian.net/browse/M2P-589
#changelog Adds support for Bag Riders Store Credit

Adds support for Bag Riders Store Credit

---

Model/Api/ShippingMethods.php
Model/EventsForThirdPartyModules.php
ThirdPartyModules/MageWorld/RewardPoints.php

1. In the admin, go to Store -> Configuration -> Mageworld -> Reward Points Pro -> General.
Set Allow redeemed points to apply to tax to No.
Set Allow redeemed points to apply to shipping to Yes.
2. Add product to the cart.
3. On the cart page, choose to Maximize my discount with points, see here - https://prnt.sc/12j4c55
4. Open Bolt modal, estimate shipping and click on the Pay button. The error occurs because of the mismatch total amount issue. See the Bugsnag link here: https://app.bugsnag.com/bolt/magento-2/errors/6089c87aa91b6f000845c98b?filters%5Bevent.since%5D%5B%5D%5Btype%5D=eq&filters%5Bevent.since%5D%5B%5D%5Bvalue%5D=30d&filters%5Bsearch%5D%5B%5D%5Btype%5D=eq&filters%5Bsearch%5D%5B%5D%5Bvalue%5D=%22funandfunction.com%22&event_id=608e6fd60079c …

EN-4706 MW_RewardPoints - Fix the mismatch total amount issue if the customers redeem their maximum reward points

---

ThirdPartyModules/MageWorld/RewardPoints.php

1. Add product to the cart.
2. On the cart page, apply a gift card or coupon code and choose to Maximize my discount with points, see here - https://prnt.sc/12j4c55
3. Open Bolt modal, neither the shipping nor tax totals are reduced
See the following videos for replicating the issue:
When using a gift card + rewards points: 
https://drive.google.com/file/d/1T-Ss0hk8m4_VjyJQO8DqXI19nIjvADxI/view 
When using a promo code + rewards points: 
https://drive.google.com/file/d/1K9U6Rb_WLdNkNyCWFhBu-YcdW1koOYkl/view
=> This PR resolves the issue by applying the reward point balance for those cases.
Fixes: https://boltpay.atlassian.net/browse/EN-4706
#changelog EN-4706 MW_RewardPoints - Fix bug that neither the shipping nor tax totals are reduced if reward …

EN-4706 MW_RewardPoints - Fix bug that neither the shipping nor tax totals are reduced if reward points are combined with a gift card or coupon code

---

CHANGELOG.md
composer.json
etc/module.xml

version bump for tag. Changelog will be reviewed/modified by LB when back from vacation.
#mergewhengreen 
#changelog 2.22.0 bump

2.22.0 bump

---

Test/Unit/Block/Checkout/SuccessTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Block\Checkout\SuccessTest
Fixes: https://boltpay.atlassian.net/browse/M2P-595
#changelog Use integration test instead of unit test for all methods in class Bo…

M2P-595 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Block\Checkout\SuccessTest

---

Model/EventsForThirdPartyModules.php
ThirdPartyModules/Teamwork/StoreCredit.php

M2P-600 Adds support for Teamwork_Storecredit
Fixes: https://boltpay.atlassian.net/browse/M2P-600
#changelog M2P-600 Adds support for Teamwork_Storecredit

M2P-600 Adds support for Teamwork_Storecredit

---

Model/EventsForThirdPartyModules.php
ThirdPartyModules/Teamwork/Token.php

Adds support for Teamworks_Token
Fixes: https://boltpay.atlassian.net/browse/M2P-598
#changelog M2P-598 Adds support for Teamworks_Token

M2P-598 Adds support for Teamworks_Token

---

Helper/Order.php
Model/EventsForThirdPartyModules.php
Test/Unit/Helper/OrderTest.php
ThirdPartyModules/Magento/InStorePickupShipping.php

To support BOPIS with Bolt payment-only.
Fixes: https://boltpay.atlassian.net/browse/M2P-601
#changelog Bugfix: Unable to complete payment for BOPIS using Bolt payment-only

M2P-601 Bugfix: Unable to complete payment for BOPIS using Bolt payment-only

---

Test/Unit/Model/Api/Data/AutomatedTesting/CartTest.php
Test/Unit/Model/Api/Data/BoltConfigSettingTest.php

Integration test: Bolt\Boltpay\Test\Unit\Model\Api\Data\AutomatedTesting\CartTest
Fixes: https://boltpay.atlassian.net/browse/M2P-611
#changelog M2P-611 Integration test: Bolt\Boltpay\Test\Unit\Model\Api\Data\AutomatedTesting\CartTest

M2P-611 Integration test: Bolt\Boltpay\Test\Unit\Model\Api\Data\AutomatedTesting\CartTest

---

Test/Unit/Model/Api/Data/AutomatedTesting/StoreItemTest.php

Integration test: Bolt\Boltpay\Test\Unit\Model\Api\Data\AutomatedTesting\StoreItemTest
Fixes: https://boltpay.atlassian.net/browse/M2P-610
#changelog M2P-610 Integration test: Bolt\Boltpay\Test\Unit\Model\Api\Data\AutomatedTesting\StoreItemTest

M2P-610 Integration test: Bolt\Boltpay\Test\Unit\Model\Api\Data\AutomatedTesting\StoreItemTest

---

Test/Unit/Model/Api/Data/AutomatedTesting/ConfigTest.php

Integration test: Bolt\Boltpay\Test\Unit\Model\Api\Data\AutomatedTesting\ConfigTest
Fixes: https://boltpay.atlassian.net/browse/M2P-613
#changelog M2P-613 Integration test: Bolt\Boltpay\Test\Unit\Model\Api\Data\AutomatedTesting\ConfigTest

M2P-613 Integration test: Bolt\Boltpay\Test\Unit\Model\Api\Data\AutomatedTesting\ConfigTest

---

Test/Unit/Model/Api/Data/AutomatedTesting/PricePropertyTest.php

Fixes: https://boltpay.atlassian.net/browse/M2P-608
#changelog M2P-608 Integration test: Bolt\Boltpay\Test\Unit\Model\Api\Data\AutomatedTesting\PricePropertyTest

M2P-608 Integration test: Bolt\Boltpay\Test\Unit\Model\Api\Data\AutomatedTesting\PricePropertyTest

---

Test/Unit/Model/Api/Data/AutomatedTesting/CartItemTest.php

Integration test: Bolt\Boltpay\Test\Unit\Model\Api\Data\AutomatedTesting\CartItemTest
Fixes: https://boltpay.atlassian.net/browse/M2P-607
#changelog M2P-607 Integration test: Bolt\Boltpay\Test\Unit\Model\Api\Data\AutomatedTesting\CartItemTest

M2P-607 Integration test: Bolt\Boltpay\Test\Unit\Model\Api\Data\AutomatedTesting\CartItemTest

---

Test/Unit/Model/Api/Data/AutomatedTesting/AddressTest.php

Fixes: https://boltpay.atlassian.net/browse/M2P-606
#changelog M2P-606 Integration test: Bolt\Boltpay\Test\Unit\Model\Api\Data\AutomatedTesting\AddressTest

M2P-606 Integration test: Bolt\Boltpay\Test\Unit\Model\Api\Data\AutomatedTesting\AddressTest

---

Test/Unit/Block/Checkout/LayoutProcessorTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Block\Checkout\LayoutProcessor
Fixes: https://boltpay.atlassian.net/browse/M2P-593
#changelog M2P-593 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Block\Checkout\LayoutProcessor

M2P-593 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Block\Checkout\LayoutProcessor

---

Model/EventsForThirdPartyModules.php
ThirdPartyModules/ImaginationMedia/TmwGiftCard.php

M2P-614 Adds support for ImaginationMedia_TmwGiftCard
Fixes: https://boltpay.atlassian.net/browse/M2P-614
#changelog M2P-614 Adds support for ImaginationMedia_TmwGiftCard

M2P-614 Adds support for ImaginationMedia_TmwGiftCard

---

Test/Unit/Model/Api/Data/AutomatedTesting/OrderItemTest.php

Integration test: Bolt\Boltpay\Test\Unit\Model\Api\Data\AutomatedTesting\OrderItemTest
Fixes: https://boltpay.atlassian.net/browse/M2P-615
#changelog M2P-615 Integration test: Bolt\Boltpay\Test\Unit\Model\Api\Data\AutomatedTesting\OrderItemTest

M2P-615 Integration test: Bolt\Boltpay\Test\Unit\Model\Api\Data\AutomatedTesting\OrderItemTest

---

Test/Unit/Model/Api/Data/AutomatedTesting/OrderTest.php

Integration test: Bolt\Boltpay\Test\Unit\Model\Api\Data\AutomatedTesting\OrderTest
Fixes: https://boltpay.atlassian.net/browse/M2P-616
#changelog M2P-616 Integration test: Bolt\Boltpay\Test\Unit\Model\Api\Data\AutomatedTesting\OrderTest

M2P-616 Integration test: Bolt\Boltpay\Test\Unit\Model\Api\Data\AutomatedTesting\OrderTest

---

Test/Unit/Model/Authorization/HookContextTest.php

Integration Test: Bolt\Boltpay\Test\Unit\Model\Authorization\HookContextTest
Fixes: https://boltpay.atlassian.net/browse/M2P-617
#changelog M2P-617 Integration Test: Bolt\Boltpay\Test\Unit\Model\Authorization\HookContextTest

M2P-617 Integration Test: Bolt\Boltpay\Test\Unit\Model\Authorization\HookContextTest

---

Helper/Cart.php
Model/EventsForThirdPartyModules.php
ThirdPartyModules/Route/Route.php

Add Route to Bolt cart in M2
Fixes: https://boltpay.atlassian.net/browse/MA-869
#changelog Add Route to Bolt cart in M2

MA-869 Add Route to Bolt cart in M2

---

Test/Unit/Model/ThirdPartyModuleFactoryTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\ThirdPartyModuleFactoryTest
Fixes: https://boltpay.atlassian.net/browse/M2P-624
#changelog M2P-624 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\ThirdPartyModuleFactoryTest

M2P-624 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Model\ThirdPartyModuleFactoryTest

---

Test/Unit/Helper/ModuleRetrieverTest.php

#changelog Use integration test instead of unit test for all methods in class Test/Unit/Helper/ModuleRetrieverTest.php 

Use integration test instead of unit test for all methods in class Test/Unit/Helper/ModuleRetrieverTest.php 

---

Test/scripts/ci-integration.sh

#changelog CI - fix php72 Magento 2.3.0 Integration
Recovered old DB dump 
https://github.com/BoltApp/integration-tests/pull/2989

CI - fix php72 Magento 2.3.0 Integration

---

Test/Unit/Helper/SessionTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Helper\SessionTest
Fixes: https://boltpay.atlassian.net/browse/M2P-625
#changelog M2P-625 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Helper\SessionTest

M2P-625 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Helper\SessionTest

---

Model/Api/GetProduct.php

_External publishers will need to ensure that they are showing product attributes in the correct order. Ideally, we can update our product endpoint to specify what order certain attributes should be shown for a product._ 
Fixes: https://boltpay.atlassian.net/browse/M2P-618
#changelog Add position to configurable product options

Add position to configurable product options

---

Test/Unit/Plugin/Webkul/Odoomagentoconnect/Model/ResourceModel/OrderPluginTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Plugin\MageVision\FreeShippingAdmin\MethodPluginTest
Fixes: https://boltpay.atlassian.net/browse/M2P-631
#changelog M2P-631 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Plugin\MageVision\FreeShippingAdmin\MethodPluginTest

M2P-631 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Plugin\MageVision\FreeShippingAdmin\MethodPluginTest

---

Test/Unit/ViewModel/MinicartAddonsTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Plugin\Webkul\Odoomagentoconnect\Model\ResourceModel\OrderPluginTest\MinicartAddonsTest
Fixes: https://boltpay.atlassian.net/browse/M2P-632
#changelog M2P-632 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Plugin\Webkul\Odoomagentoconnect\Model\ResourceModel\OrderPluginTest\MinicartAddonsTest

M2P-632 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\ViewModel\MinicartAddonsTest.php 

---

Test/Unit/ViewModel/OrderCommentTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\ViewModel\OrderCommentTest
Fixes: https://boltpay.atlassian.net/browse/M2P-637
#changelog M2P-637 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\ViewModel\OrderCommentTest

M2P-637 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\ViewModel\OrderCommentTest

---

Test/Unit/Section/CustomerData/BoltHintsTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Section\CustomerData\BoltHintsTest
Fixes: https://boltpay.atlassian.net/browse/M2P-638
#changelog M2P-638 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Section\CustomerData\BoltHintsTest

M2P-638 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Section\CustomerData\BoltHintsTest

---

Test/Unit/ThirdPartyModules/Magento/CustomerBalanceTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\ThirdPartyModules\Magento\CustomerBalanceTest
Fixes:  https://boltpay.atlassian.net/browse/M2P-639
#changelog M2P-639 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\ThirdPartyModules\Magento\CustomerBalanceTest

M2P-639 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\ThirdPartyModules\Magento\CustomerBalanceTest

---

Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Helper/Order.php
Test/Unit/Helper/OrderTest.php
Test/Unit/Model/Api/OrderManagementTest.php

This PR resolves the following test case.
1. Order and invoice are created on both Bolt and Magento with a total of $200
2. The admin goes to the Magento admin and edits the total to $100.
3. The admin refunds $100 on Bolt to match the Magento total.
4. The following exception is thrown https://app.bugsnag.com/bolt/magento-2/errors/5fb6fa4832dadc00186f772b?filters[event.since][][type]=eq&filters[event.since][][value]=30d&filters[search][][type]=eq&filters[search][][value]="thertastore.com'"&event_id=604a32ff0073cd71f35d0000
Fixes: https://boltpay.atlassian.net/browse/M2P-509
#changelog Ignore the total validation when the credit hook is sent to Magento if the order is edited in Magento admin

M2P-509 Ignore the total validation when the credit hook is sent to Magento if the order is edited in Magento admin

---

Plugin/Magento/Framework/Session/ValidatorPlugin.php
Test/Unit/Plugin/Magento/Framework/Session/ValidatorPluginTest.php
etc/di.xml

Currently, if the configuration Web/Session Validations Setting/ Validate Remote_Addr is set to Yes, there is an exception thrown when the request is from Bolt.
See the Bugsnag link here:
https://app.bugsnag.com/bolt/magento-2/errors/60d077879804e900079859c7?filters%5Bevent.since%5D%5B%5D%5Btype%5D=eq&filters%5Bevent.since%5D%5B%5D%5Bvalue%5D=30d&filters%5Bsearch%5D%5B%5D%5Btype%5D=eq&filters%5Bsearch%5D%5B%5D%5Bvalue%5D=%22m231.bolt.devzn.com%22&event_id=60d0a5d3007f644f28f50000
This PR resolves the issue by ignoring the session validation if the request is from Bolt
Fixes:  https://boltpay.atlassian.net/browse/EN-5009
#changelog EN-5009 Ignore the session validation if the request is from Bolt

EN-5009 Ignore the session validation if the request is from Bolt

---

Helper/Cart.php
Model/EventsForThirdPartyModules.php
ThirdPartyModules/Amasty/Preorder.php

Add support for Amasty Preorder
Fixes: https://boltpay.atlassian.net/browse/EN-4951
#changelog Add support for Amasty Preorder

EN-4951 Add support for Amasty Preorder

---

Model/Api/DiscountCodeValidation.php
Test/Unit/Model/Api/DiscountCodeValidationTest.php

Add logic for store labels in discount description
Fixes: https://boltpay.atlassian.net/browse/M2P-363
#changelog Extend discount description logic

[WIP] M2P-363 - Extend discount description logic

---

Test/Unit/Helper/ConfigTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Helper\ConfigTest
Fixes: https://boltpay.atlassian.net/browse/M2P-643
#changelog Use integration test instead of unit test for all methods in class Bo…

M2P-643 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Helper\ConfigTest

---

CHANGELOG.md

Pulls webkul from changelog
#changelog Removes webkul from changelog

Removes webkul from changelog

---

etc/di.xml

Fix Uncaught Error: Call to undefined method Magento\Framework\Session\SessionManagerInterface\Proxy::getBoltFeatureSwitchId()
Fixes: https://boltpay.atlassian.net/browse/EN-507
#changelog EN-507 Fix Uncaught Error: Call to undefined method Magento\Framework\Session\SessionManagerInterface\Proxy::getBoltFeatureSwitchId()

EN-507 Fix Uncaught Error: Call to undefined method Magento\Framework\Session\SessionManagerInterface\Proxy::getBoltFeatureSwitchId()

---

Block/Js.php
Helper/Config.php
Model/EventsForThirdPartyModules.php
Plugin/MageWorx/RewardPoints/Controller/Checkout/ApplyPlugin.php
Test/Unit/Block/JsTest.php
Test/Unit/Helper/ConfigTest.php
ThirdPartyModules/MageWorx/RewardPoints.php
etc/adminhtml/system.xml
etc/config.xml
etc/di.xml
view/frontend/templates/js/replacejs.phtml
view/frontend/web/template/third-party-modules/mageworx/reward-points/cart/rewardpoints.html
view/frontend/web/template/third-party-modules/mageworx/reward-points/cart/rewardpoints_custom_amount.html

Add support for Mageworx rewards
Fixes: https://boltpay.atlassian.net/browse/M2P-640
#changelog Add support for Mageworx rewards

M2P-640 Add support for Mageworx rewards

---

Test/Unit/ViewModel/CartDiscountsTest.php

Integration test: Test/Unit/ViewModel/CartDiscountsTest.php
Fixes: https://boltpay.atlassian.net/browse/M2P-644
#changelog M2P-644 Integration test: Test/Unit/ViewModel/CartDiscountsTest.php

M2P-644 Integration test: Test/Unit/ViewModel/CartDiscountsTest.php

---

Test/Unit/Helper/OrderTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Helper\OrderTest
#changelog Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Helper\OrderTest

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Helper\OrderTest

---

.circleci/config.yml

#changelog CI - integr tests browsers update
- chrome 80 -> chrome latest
- store test results after the build

CI - integr tests browsers update

---

Test/scripts/ci-integration.sh

#changelog CI - upd int tests
- NODE_VERSION from https://app.circleci.com/settings/project/github/BoltApp/bolt-magento2/environment-variables
- sudo fix

CI - upd int tests

---

Test/Unit/Helper/OrderTest.php

Use integration test instead of unit test for some methods in class Bolt\Boltpay\Test\Unit\Helper\OrderTest
#changelog Use integration test instead of unit test for some methods in class Bolt\Boltpay\Test\Unit\Helper\OrderTest

Use integration test instead of unit test for some methods in class Bolt\Boltpay\Test\Unit\Helper\OrderTest

---

Helper/FeatureSwitch/Decider.php

Fix Uncaught Error: Call to undefined method Magento\Framework\Session\SessionManagerInterface\Proxy::getBoltFeatureSwitchId()
Currently, if the feature switch M2_ORDER_UPDATE's rollout percentage it isn't 0 and 100 (it's from 1 to 99), the exception "Call to undefined method Magento\Framework\Session\SessionManagerInterface\Proxy::getBoltFeatureSwitchId()" is thrown whenever the create_order hook is sent to Magento
See the Datadog link here: 
https://app.datadoghq.com/logs?query=env%3A%22production%22%20%40merchant_name%3A%22Divers%20Supply%22%20%22Server%20internal%20error.%22%20%22create_order%22&cols=core_host%2Ccore_service&event=AQAAAXqv-sck47rNsQAAAABBWHF2LTZyVkFBQzRhYXk5TDlhSWpnQUE&index=&messageDisplay=inline&stream_sort=desc&from_ts=1624205607254&to_ts=1626797607254&live=true
So …

M2P-650 Fix Uncaught Error: Call to undefined method Magento\Framework\Session\SessionManagerInterface\Proxy::getBoltFeatureSwitchId()

---

Helper/Config.php
Observer/RemoveBlocksObserver.php
Test/Unit/Observer/RemoveBlocksObserverTest.php
view/frontend/layout/customer_account_create.xml
view/frontend/layout/customer_account_login.xml
view/frontend/templates/authorization.phtml
view/frontend/templates/customer/login.phtml
view/frontend/templates/customer/register.phtml

Fixes: https://boltpay.atlassian.net/browse/M2P-653
#changelog SSO Login Page Replacement

M2P-653 SSO Login Page Replacement

---

Model/EventsForThirdPartyModules.php
ThirdPartyModules/Aheadworks/Giftcard.php

Fixes: https://boltpay.atlassian.net/browse/M2P-662
#changelog Replicate Aheadworks Giftcards data properly

M2P-662 Replicate Aheadworks Giftcards data properly

---

CHANGELOG.md
composer.json
etc/module.xml

2.23.0 bump

---

Helper/SSOHelper.php
Test/Unit/Helper/SSOHelperTest.php

We are migrating issuer from bolt.com to api.bolt.com so we would have to accept both issuers in the interim.
This code was introduced in 2.20.0-rc but SSO was released as part of 2.21.0-rc5 to select merchants
#changelog [SSO] Add api.bolt.com as a valid issuer

[SSO] Add api.bolt.com as a valid issuer

---

Helper/Order.php
Test/Unit/Helper/OrderTest.php

Improve error reporting with multiple capture failure.
Fixes: https://boltpay.atlassian.net/browse/ON-1059
#changelog ON-1059 - More verbose capture amount validation

ON-1059 - More verbose capture amount validation

---

Helper/Cart.php
Model/Api/CreateOrder.php
Model/Api/ShippingTax.php
Model/Api/UpdateCart.php
Model/EventsForThirdPartyModules.php
Model/ThirdPartyEvents/FiltersCartBeforeCreateOrder.php
Model/ThirdPartyEvents/FiltersCartBeforeSplitShippingAndTax.php
Model/ThirdPartyEvents/FiltersCartItems.php
Model/ThirdPartyEvents/FiltersItemsForUpdateCartApi.php
Test/Unit/Model/Api/UpdateCartTest.php
Test/Unit/ThirdPartyModules/Magecomp/ExtrafeeTest.php
ThirdPartyModules/Magecomp/Extrafee.php
ThirdPartyModules/Route/Route.php

Add/Remove Route fee via Updatecart api endpoint
Fixes: https://boltpay.atlassian.net/browse/MA-870
#changelog Add/Remove Route fee via Updatecart api endpoint

MA-870 Add/Remove Route fee via Updatecart api endpoint

---

Api/Data/UniversalWebhookResultInterface.php
Api/UniversalWebhookInterface.php
Model/Api/Data/UniversalWebhookResult.php

Fixes: https://boltpay.atlassian.net/browse/EN-5349
#changelog Bugfix: incorrect param/return datatype in interface

EN-5349 Bugfix: incorrect param/return datatype in interface

---

Plugin/ImaginationMedia/TmwGiftCard/ForceInvoicePlugin.php
etc/di.xml

This PR resolve the following case:
1. The customer placed a Bolt order that has a virtual gift card. The order was created on both Magento and Bolt.
2. The pending hook was sent to Magento and Magento threw the exception “Transaction is not in authorized state.”, 
See the Bugsnag link here:
https://app.bugsnag.com/bolt/magento-2/errors/6102e1040639e600079da9e9?filters%5Bevent.since%5D%5B0%5D%5Btype%5D=eq&filters%5Bevent.since%5D%5B0%5D%5Bvalue%5D=30d&filters%5Bsearch%5D%5B0%5D%5Btype%5D=eq&filters%5Bsearch%5D%5B0%5D%5Bvalue%5D=%22m2dev.shopakira.com%22
This PR resolves the issue by ignoring the invoice creation for Bolt order that has virtual gift card when the hook is sent to Magento
Fixes: https://boltpay.atlassian.net/browse/ON-792
#changelog ON-792 ImaginationMedia_TmwGiftCard: …

ON-792 ImaginationMedia_TmwGiftCard: Ignore invoice creation for Bolt order that has a virtual gift card when the hook is sent to Magento

---

Helper/Cart.php
Model/EventsForThirdPartyModules.php
ThirdPartyModules/Route/Route.php

Support Route for Bolt PPC
Fixes: https://boltpay.atlassian.net/browse/M2P-668
#changelog Support Route for Bolt PPC

M2P-668 Support Route for Bolt PPC

---

Test/Unit/Block/FormTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Block\FormTest
Fixes: https://boltpay.atlassian.net/browse/M2P-681
#changelog M2P-681 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Block\FormTest

M2P-681 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Block\FormTest

---

Test/Unit/Block/Adminhtml/Customer/CreditCard/Tab/CreditCardTest.php

Use integration test instead of unit test for all methods in class Test/Unit/Block/Adminhtml/Customer/CreditCard/Tab/CreditCardTest.php
Fixes: https://boltpay.atlassian.net/browse/M2P-678
#changelog M2P-678 Use integration test instead of unit test for all methods in class Test/Unit/Block/Adminhtml/Customer/CreditCard/Tab/CreditCardTest.php

M2P-678 Use integration test instead of unit test for all methods in class Test/Unit/Block/Adminhtml/Customer/CreditCard/Tab/CreditCardTest.php

---

CHANGELOG.md

#changelog Add changelog for version 2.23.0

Add changelog for version 2.23.0

---

Observer/TrackingSaveObserver.php
Test/Unit/Observer/TrackingSaveObserverTest.php

Currently, we can’t send shipment tracking info to Bolt if it has a configurable item. 
See the Datadog link [here.](https://app.bugsnag.com/bolt/magento-2/errors/60db5ab28fb47b000705797b?filters[event.since][][type]=eq&filters[event.since][][value]=30d&filters[search][][type]=eq&filters[search][][value]=%22m231.bolt.devzn.com%22&event_id=612f95bc007f958d05100000)
See the Bugsnag link [here.](https://app.datadoghq.com/logs?query=%40merchant_name%3A%22John%20McCombs%20Testing%22%20status%3Aerror%20%40trace_id%3A5AnbKwMkGhhr48tOPDDfXg%3D%3D&cols=host%2Cservice%2C%40trace_id&index=&messageDisplay=inline&stream_sort=desc&from_ts=1628331831109&to_ts=1630923831109&live=true)
This PR corrects the tracking API logic to bypass the configurable item data from sending to Bolt, only its simple item …

M2P-686 Bugfix: cannot send shipment tracking information to Bolt if it has a configurable item

---

Test/Unit/Block/Customer/CreditCardTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Block\Customer\CreditCardTest
Fixes: https://boltpay.atlassian.net/browse/M2P-695
#changelog M2P-695 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Block\Customer\CreditCardTest

M2P-695 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Block\Customer\CreditCardTest

---

Test/Unit/Plugin/AbstractLoginPluginTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Plugin\AbstractLoginPluginTest
Fixes: https://boltpay.atlassian.net/browse/M2P-696
#changelog M2P-696 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Plugin\AbstractLoginPluginTest

M2P-696 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Plugin\AbstractLoginPluginTest

---

Test/Unit/Plugin/OrderSenderPluginTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Plugin\OrderSenderPlugin
Fixes: https://boltpay.atlassian.net/browse/M2P-697
#changelog M2P-697 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Plugin\OrderSenderPlugin

M2P-697 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Plugin\OrderSenderPlugin

---

Test/Unit/Plugin/QuotePluginTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Plugin\QuotePluginTest
Fixes:https://boltpay.atlassian.net/browse/M2P-698
#changelog M2P-698 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Plugin\QuotePluginTest

M2P-698 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Plugin\QuotePluginTest

---

Test/Unit/Plugin/ClearQuoteTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Plugin\ClearQuoteTest
Fixes: https://boltpay.atlassian.net/browse/M2P-699
#changelog M2P-699 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Plugin\ClearQuoteTest

M2P-699 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Plugin\ClearQuoteTest

---

Test/Unit/Block/BlockTraitTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Block\BlockTraitTest
Fixes: https://boltpay.atlassian.net/browse/M2P-677
#changelog M2P-677 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Block\BlockTraitTest

M2P-677 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\Block\BlockTraitTest

---

Test/Unit/Plugin/Magento/Quote/Observer/Frontend/Quote/Address/AddressCollectTotalsObserverPluginTest.php

Revert PR 1411

---

Plugin/SalesRuleModelUtilityPlugin.php
Test/Unit/Plugin/SalesRuleModelUtilityPluginTest.php

Bugfix: free shipping discount not applying
Fixes: https://app.asana.com/0/951157735838091/1201280882926170/f
#changelog Bugfix: free shipping discount not applying

Bugfix: free shipping discount not applying

---

Helper/Discount.php
Model/Api/DiscountCodeValidation.php
Model/Api/UpdateDiscountTrait.php
Model/EventsForThirdPartyModules.php
Test/Unit/Model/Api/UpdateDiscountTraitTest.php
ThirdPartyModules/Mexbs/Tieredcoupon.php

Add support for Mexbs Tiered Coupons
Fixes: https://boltpay.atlassian.net/browse/EN-5653
#changelog EN-5653 Add support for Mexbs Tiered Coupons

EN-5653 Add support for Mexbs Tiered Coupons

---

CHANGELOG.md
Test/Unit/Block/JsTest.php
composer.json
etc/module.xml

#changelog Bump plugin version to 2.24.1

Bump plugin version to 2.24.1

---

Test/Unit/ThirdPartyModules/IDme/GroupVerificationTest.php

Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\ThirdPartyModules\IDme\GroupVerificationTest
Fixes: https://boltpay.atlassian.net/browse/M2P-739
#changelog M2P-739 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\ThirdPartyModules\IDme\GroupVerificationTest

M2P-739 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\ThirdPartyModules\IDme\GroupVerificationTest

---

view/frontend/templates/button_product_page.phtml

Fix bug: interrupting site content in product page checkout
Fixes: https://boltpay.atlassian.net/browse/ON-1416
#changelog Fix bug: Bolt interrupting site content in product page checkout

Fix bug: Bolt interrupting site content in product page checkout

---

Test/Unit/ThirdPartyModules/Magento/RewardTest.php

Fixes: https://boltpay.atlassian.net/browse/M2P-738
#changelog M2P-738 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\ThirdPartyModules\Magento\RewardTest

M2P-738 Use integration test instead of unit test for all methods in class Bolt\Boltpay\Test\Unit\ThirdPartyModules\Magento\RewardTest

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

Be able to display the MSRP in our Bolt checkout for M2 merchants.
Fixes: [(link Jira ticket)](https://app.asana.com/0/1201104538767801/1201356677984885/f)
#changelog Add MSRP support for m2 

Add MSRP support for m2 

---

Helper/GiftOptionsHandler.php
Helper/Order.php
Test/Unit/Helper/GiftOptionsHandlerTest.php

Add gift options support.
As discussed, the gift options info would be added in the comments, as same as custom fields.
Fixes: https://app.asana.com/0/941920570700290/1201119571405782/f
#changelog Add gift options support

Add gift options support

---

Model/Api/OAuthRedirect.php

Send welcome email after creating new account
Fixes: https://boltpay.atlassian.net/browse/ON-781
#changelog SSO feature: Send welcome email after creating new account

SSO feature: Send welcome email after creating new account

---

ThirdPartyModules/Amasty/Rewards.php

From Amasty reward points 1.15.0, it changes the key of applied reward points data in quote object, also it adjusts the discount calculation for quote, as a result, the Bolt plugin can not collect the related discounts. 
So we need to get applied reward points with new key and update the code to calculate discount amount properly.
Fixes: https://app.asana.com/0/632578947811321/1201218874560411/f
#changelog Add support for Amasty reward points 1.15.0+

Add support for Amasty reward points 1.15.0+

---

Api/Data/GetMaskedQuoteIDDataInterface.php
Api/GetMaskedQuoteIDInterface.php
Model/Api/Data/GetMaskedQuoteIDData.php
Model/Api/GetMaskedQuoteID.php
Test/Unit/Model/Api/GetMaskedQuoteIDTest.php
etc/di.xml
etc/webapi.xml

Asana:
https://app.asana.com/0/1201161314919732/1201352093435110/f
#changelog Implement get masked id endpoint

Implement get masked id endpoint

---

Helper/Cart.php
Model/Api/UpdateDiscountTrait.php

**Preconditions:**
Magento 2.4.3
**The coupon condition**: 
* Fixed amount for whole cart 
* Apply to shipping
* Make the discount amount < the quote subtotal
**The Bolt condition**:
* Enable split shipping&tax endpoint
**Steps to reproduce:**
1. Add product to cart and go to cart page
2. Open Bolt modal and apply the coupon in the Bolt modal
3. Estimate shipping and tax
4. Go to the payment step and an error occurs.
In step #4, the discounts.code.apply api request payload is sent to Magento including the shipment info, we save the address data into the quote shipping address and calculate discount. In this case, logic $this->sessionHelper->getCheckoutSession()->getBoltCollectSaleRuleDiscounts([])[$ruleId] doesn’t caculate the discount properly.
My solution is to correct the logic as the …

Correct the logic to get discount amount of cart rule (fixed amount for whole cart and apply to shipping) in the Bolt modal

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

When merging PR https://github.com/BoltApp/bolt-magento2/pull/1469, the commit related to comments https://github.com/BoltApp/bolt-magento2/pull/1469#discussion_r757645433 and https://github.com/BoltApp/bolt-magento2/pull/1469#discussion_r757672361 was missing. Then this PR is to add the fixes.
#changelog Add missing fixes

Add missing fixes

---

Model/Api/UpdateDiscountTrait.php

Correct the bugsnag property in class UpdateDiscountTrait
#changelog Correct the bugsnag property in class UpdateDiscountTrait

Correct the bugsnag property in class UpdateDiscountTrait

---

Helper/Cart.php
Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Test/Unit/Helper/CartTest.php

1. Exclude free shipping promotion if it is "NO_COUPON" type, that's what we used to do.
2. Add feature switch to disable all refactoring from [PR 1469](https://github.com/BoltApp/bolt-magento2/pull/1469) if needed
Fixes: [(link Jira ticket)](https://app.asana.com/0/0/1201459670192138/f)
#changelog Code refactoring for collecting discounts

Code refactoring for collecting discounts

---

Block/System/Config/IntegrationConnection.php
Controller/Adminhtml/System/ProcessIntegrationToken.php
Helper/Config.php
Helper/IntegrationManagement.php
Plugin/Magento/Integration/Model/IntegrationServicePlugin.php
etc/adminhtml/di.xml
etc/adminhtml/system.xml
etc/config.xml
etc/integration/api.xml
etc/integration/config.xml
view/adminhtml/templates/system/config/integrationconnection.phtml

Refer to https://docs.google.com/document/d/15FVx3OXPN-yy0Wlhx5HZStpN3CsJld09F2LXvGOPBm0/edit#heading=h.cunzcjjb9kz , section **Integration creation**
#changelog Send integration access token from Magento plugin to bolt

Send integration access token from magento plugin to bolt

---

Block/Info.php
Model/Payment.php
Observer/TrackingSaveObserver.php
Plugin/Magento/Framework/View/Element/UiComponent/DataProvider/DataProviderPlugin.php
Test/Unit/Model/PaymentTest.php

Details:
https://app.asana.com/0/1201161314919732/1201531702752390
#changelog Use existing payment fields rather than additional info

Use existing payment fields rather than additional info

---

Api/OrderManagementInterface.php
Helper/Order.php
Model/Api/OrderManagement.php
Test/Unit/Helper/OrderTest.php
Test/Unit/Model/Api/OrderManagementTest.php
etc/webapi.xml

#changelog Implement delete order endpoint

Implement delete order endpoint

---

Api/CartManagementInterface.php
Model/Api/CartManagement.php
Test/Unit/Model/Api/CartManagementTest.php
etc/di.xml
etc/webapi.xml

Refactor get masked id endpoint in order to eventually have all bolt API related to carts/quotes under one interface
#changelog Refactor get masked id endpoint

Refactor get masked id endpoint

---

Api/CartManagementInterface.php
Model/Api/CartManagement.php
Test/Unit/Model/Api/CartManagementTest.php
etc/webapi.xml

#changelog Implement set quote active endpoint

Implement set quote active endpoint

---

Api/CartManagementInterface.php
Model/Api/CartManagement.php
Test/Unit/Model/Api/CartManagementTest.php
etc/webapi.xml

Update endpoint for cart changing to allow set cart isActive to false
#changelog Change cart update endpoint

Change cart update endpoint

---

Model/EventsForThirdPartyModules.php
ThirdPartyModules/J2t/Rewardpoints.php

Adds support for J2t Rewardpoints
Fixes: https://boltpay.atlassian.net/browse/M2P-576
#changelog Adds support for J2t Rewardpoints

M2P-576 Adds support for J2t Rewardpoints

---

etc/integration/api.xml

#changelog Magento integration: add necessary rights for resources

Magento integration: add necessary rights for resources

---

Block/Js.php
Helper/Config.php
Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Test/Unit/Block/JsTest.php

Fixes: https://app.asana.com/0/1200879031426307/1201636980993406/f
#changelog Allow custom URL for pay by link under feature switch

Allow custom URL for pay by link under feature switch

---

Helper/Cart.php

Steps to reproduce an issue:
- set feature APIDrivenIntegrationEnabled to true (not necessary to change settings on bolt side)
- add discount to quote via Magento API
- open bolt modal
**Actual behavior:**
no discount in bolt cart
#changelog Collect total if discount did not found

Collect total if discount did not found

---

CHANGELOG.md
Test/Unit/Block/JsTest.php
composer.json
etc/module.xml

#changelog Bump plugin version to 2.25.0

Bump plugin version to 2.25.0

---

Helper/Cart.php

As discussed with @vitaliyreznikov and @mikeshutov-bolt this is refactoring for [PR 1494](https://github.com/BoltApp/bolt-magento2/pull/1494)
#changelog Refactoring for collecting total if discount did not found

Refactoring for collecting total if discount did not found

---

view/adminhtml/templates/system/config/integrationconnection.phtml

#changelog Temporarily remove link to bolt help site

Temporarily remove link to bolt help site

---

Helper/Order.php

Add stripe id into the payment info object
Fixes: https://app.asana.com/0/1201495896048972/1201728895813778
#changelog Add stripe id into the payment info object

Add authorization id into the payment info object

---

CHANGELOG.md

Adding content to changelog for release 2.25.0
#changelog Changelog Update (M2 2.25.0) (WIP)

Changelog Update (M2 2.25.0)

---

.circleci/config.yml

Updates deprecated circleci php image per [this](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034) article.
Fixes: https://app.asana.com/0/1200228121876494/1201724719435423/f
#changelog Update deprecated circleci php image
Update deprecated circleci php image
---
- https://app.asana.com/0/0/1201724719435431

Update deprecated circleci php image

---

CHANGELOG.md
Test/Unit/Block/JsTest.php
composer.json
etc/module.xml

#changelog Bump plugin version to 2.25.1

Bump plugin version to 2.25.1

---

etc/integration/api.xml

Add additional scope for our api calls. Its used during order creation. Our existing permission Magento_Sales::invoice only affects invoice creation. To support all other invoice endpoints we need to include: Magento_Sales::sales_invoice
#changelog M2 API: Add sales_invoice scope

M2 API: Add sales_invoice scope

---

Block/Adminhtml/System/Config/Form/Version.php
etc/adminhtml/system.xml

#changelog Add banner to visualize plugin version.
- [+] New feature (change which adds functionality)
- [+] Successfully tested locally (or docker image)
- [+] My code follows the style guidelines of this project.
- [+] I have performed a self-review of my own code.
- [+] I have commented my code, particularly in hard-to-understand areas.
- [+] New and existing unit tests pass locally with my changes.

Add banner to visualize plugin version.

---

CHANGELOG.md

Changelog update for M2 2.25.1 hotfix.
#changelog M2 2.25.1 Changelog Update

M2 2.25.1 Changelog Update

---

Api/OrderTransactionsInterface.php
Model/Api/OrderTransactions.php
Test/Unit/Model/Api/OrderTransactionsTest.php
etc/di.xml
etc/webapi.xml

Added new endpoint for order transactions creationg: "/V1/bolt/boltpay/transactions"
#changelog API order transactions save endpoint

API order transactions save endpoint

---

Plugin/Magento/Framework/View/Element/UiComponent/DataProvider/RegularFilterPlugin.php
etc/adminhtml/di.xml

Fixed admin sales order grid filter by bolt payment metods with card type enabled
Fixes: https://app.asana.com/0/1200879031426307/1201833577871965/f
#changelog Sales order grid filter by bolt payments method credit card types fix

Sales order grid filter by bolt payments method credit card types fix

---

Block/BlockTrait.php
Block/Js.php
Helper/Config.php
Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Test/Unit/Block/JsTest.php
view/frontend/layout/default.xml
view/frontend/templates/js/boltjs.phtml
view/frontend/templates/js/custom_sso_buttons.phtml

This PR includes the integration JS and CSS from this page https://help.bolt.com/developers/guides/checkout-guides/managed-checkout/adobe-commerce-setup-guide/adobe-sso into the plugin, essentially making M2 SSO implementation touch-less.
Fixes: https://app.asana.com/0/1201020360328169/1201644545259936/f
#changelog SSO - Include required scripts and css tags directly in the M2 plugin

SSO - Include required scripts and css tags directly in the M2 plugin

---

Model/EventsForThirdPartyModules.php
ThirdPartyModules/Amasty/Rewards.php

Add supporting for latest Amasty_Rewards module with supporting earliest versions.
#changelog Add supporting of latest versions of Amasty_Rewards module.

Add supporting of latest versions of Amasty_Rewards module.

---

Model/Api/OAuthRedirect.php

Currently, there is a caching issue that causes the customer-data JS object to be calculated incorrectly if the customer logged in by SSO. This indirectly causes errors for the third-party extensions. 
See the detail here: https://app.asana.com/0/1201495896048972/1201952226733725
So the fix is to delete the mage_cache_sessid cookie.  This is the same logic as Magento core
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Customer/Controller/Account/LoginPost.php#L193-L197
Fixes: https://app.asana.com/0/1201495896048972/1201952226733725
#changelog Delete the mage_cache_sessid cookie if customer logged in via SSO

Delete the mage_cache_sessid cookie if customer logged in via SSO

---

Block/Js.php
view/frontend/templates/js/replacejs.phtml

Currently, the javascript on the replacejs.phtml template is being rendered and run on the native checkout page even when the Bolt ‘Native Checkout Page’ setting is disabled. This causes the checkout page to be slower than it should be, it also tries to create a Bolt order when the ‘Publishable Key - Payment Only’ is being set.
See the Bugsnag error here - https://app.bugsnag.com/bolt/magento-2/errors/6113c899c1d72800074bc6ac?filters[event.since]=30d&filters[app.release_stage]=production&filters[release.seen_in]=2.25.*&filters[error.status]=open
This PR fixes it by not rendering the javascript when the Bolt ‘Native Checkout Page’ setting is disabled.
#changelog Optimize logic to render replacejs.phtml for the native checkout page
Please validate that you have …

Optimize logic to render replacejs.phtml for the native checkout page

---

Plugin/Amasty/CommonRules/Model/ResourceModel/Rule/CollectionPlugin.php
Plugin/Amasty/Shiprestriction/Model/ShippingRestrictionRulePlugin.php
etc/di.xml

For each rule created by the plugin Amasty Shiprestriction, there is a field to determine whether it can be applied in the admin area, and in the code it depends on the conditional statement `$this->appState->getAreaCode() == \Magento\Backend\App\Area\FrontNameResolver::AREA_CODE;`.
But for the Bolt pre-auth create order webhook, $this->appState->getAreaCode() returns \Magento\Framework\App\Area::AREA_WEBAPI_REST, therefore, an invalid rule can be applied to the cart by mistake.
Solution: Add filter('for_admin', 1) to rules collection when getting restriction rules for Bolt backoffice order via plugin methods.
Fixes: https://app.asana.com/0/1124368832381302/1202087335187579/f
#changelog Add support for Amasty Shiprestriction
Please validate that you have tested your change in at least one …

Add support for Amasty Shiprestriction

---

ThirdPartyModules/Amasty/GiftCardAccount.php

When the field "Use a Gift Card to Pay for Shipping" and "Use a Gift Card to Pay for Tax" of Amasty Gift Card configuration are set to "No", the Bolt plugin still sends full balance of gift card account to Bolt server and causes this issue.
Solution: Only count in the amount applied to cart item in such a case.
Fixes: https://app.asana.com/0/1124368832381302/1202147357445502/f
#changelog Bugfix: unable to checkout with Amasty Gift Card applied

Bugfix: unable to checkout with Amasty Gift Card applied

---

Observer/TrackingSaveObserver.php
Test/Unit/Observer/TrackingSaveObserverTest.php

#changelog Add additional information to tracking payload.

Add additional information to tracking payload.

---

Model/Api/CartManagement.php

Log exception to Bugsnag in class Api/CartManagement for debugging issue
#changelog Log exception to Bugsnag in class Api/CartManagement

Log exception to Bugsnag in class Api/CartManagement

---

ThirdPartyModules/Aheadworks/Giftcard.php

Fixed aheadworks giftcards discounts: in some cases aheadworks are not using "bolt_parent_quote_id" quote attribute, instead we have extension attribute - aw_giftcard_codes.
#changelog aheadworks giftcards fix

aheadworks giftcards fix

---

etc/integration/api.xml

Add Scopes to oauth used for API's to fetch store configurations and make calls to the credit memo endpoint directly.
#changelog M2 API add oauth scopes
---
- https://app.asana.com/0/0/1202255000722071

M2 API add oauth scopes

---

Test/Unit/Block/JsTest.php
composer.json
etc/module.xml

#changelog Bump version to 2.25.2

Bump version to 2.25.2

---

Model/Api/OrderManagement.php

Log exception to Bugsnag in the delete order endpoint
Fixes: https://app.asana.com/0/564264490825835/1202220048404129
#changelog Log exception to Bugsnag in the delete order endpoint

Log exception to Bugsnag in the delete order endpoint

---

Plugin/Magento/Framework/View/Element/UiComponent/DataProvider/RegularFilterPlugin.php
Plugin/Magento/Framework/View/Element/UiComponent/DataProvider/ReportingPlugin.php
Plugin/Magento/Ui/Model/Export/MetadataProviderPlugin.php
etc/di.xml

Fixed payment_method name in sales order grid export csv/xml file. Now it supports Bolt payment method including CC type (visa/master card etc.) -> Bolt-Visa, etc.
Fixes: [(link ticket)](https://app.asana.com/0/1201931884901947/1202378108020023/f)
#changelog fix payment method code in csv to use cc_type name if enabled
---
- https://app.asana.com/0/0/1202378108020023

fix payment method code in csv to use cc_type name if enabled

---

ThirdPartyModules/Aheadworks/Giftcard.php

Fix two bugs:
1. The second parameter of Aheadworks\Giftcard\Api\GiftcardRepositoryInterface::getByCode should be websiteId, not storeid
2. When cloning quote data, the aw gift card should be added to destination quote by Aheadworks\Giftcard\Api\GiftcardCartManagementInterface::set explicitly.
Fixes: https://app.asana.com/0/951157735838091/1201921117553941/f
#changelog Bugfix:  unable to apply aheadworks gift card via Bolt modal

Bugfix:  unable to apply aheadworks gift card via Bolt modal

---

Api/Data/ProductEventInterface.php
Api/ProductEventRepositoryInterface.php
Helper/Config.php
Model/CatalogIngestion/ProductEvent.php
Model/CatalogIngestion/ProductEventRepository.php
Model/Config/Source/Catalog/Ingestion/Attributes.php
Model/Config/Source/Catalog/Ingestion/Events.php
Model/ResourceModel/CatalogIngestion/ProductEvent.php
Model/ResourceModel/CatalogIngestion/ProductEvent/Collection.php
Setup/UpgradeSchema.php
etc/adminhtml/system.xml
etc/config.xml
etc/di.xml

Implemented database schema, base models/resources/repositories for CRUD operations. Added system configuration and config.xml with default values.
https://app.asana.com/0/1201931884901947/1201906341917644/f
#changelog Catalog Ingestion DB Schema / Models and Configuration

Catalog Ingestion DB Schema / Models and Configuration

---

Api/ProductEventManagerInterface.php
Cron/CatalogIngestion.php
Model/CatalogIngestion/ProductEventManager.php
Model/CatalogIngestion/ProductEventProcessor.php
Model/CatalogIngestion/ProductEventPublisher.php
Model/CatalogIngestion/ProductEventRequestBuilder.php
Model/CatalogIngestion/Request/Product/DataProcessor.php
etc/cron_groups.xml
etc/crontab.xml
etc/di.xml
etc/webapi.xml

Product Event Manager class implementation for manipulating product event data in magento.
Main Request Builder class implementation to build "v1/catalog/m2/product" request.
https://app.asana.com/0/1201931884901947/1201906341917644/f
#changelog Catalog Ingestion Product Event Manager Implementation

Catalog Ingestion Product Event Manager Implementation

---

Api/StoreConfigurationManagerInterface.php
Model/CatalogIngestion/StoreConfigurationManager.php
Model/CatalogIngestion/StoreConfigurationRequestBuilder.php
etc/di.xml

Store Configuration Manager implemented for manipulation of store information data (currently we have only send request method)
Store Configuration Request Builder class implementtion to build "v1/catalog/store" bold request.
https://app.asana.com/0/1201931884901947/1202261971151215/f
#changelog Catalog Ingestion Store Configuration Manager Implementation

Catalog Ingestion Store Configuration Manager Implementation

---

Helper/Cart.php
Test/Unit/Helper/CartTest.php

Include a few additional properties for product for the data team.
Fixes: [Asana](https://app.asana.com/0/1201307079775363/1202415806600585/f)
#changelog Catalog Ingestion Add Product and Variant ID properties.

Catalog Ingestion Add Product and Variant ID properties.

---

Helper/Shared/ApiUtils.php
Test/Unit/Helper/Shared/ApiUtilsTest.php

Adding source headers to all requests
Fixes: [Asana](https://app.asana.com/0/1201931884901947/1202126683405343/f)
#changelog Add Source Headers

Add Source Headers

---

Helper/Cart.php
Helper/Discount.php
Test/Unit/Helper/CartTest.php
Test/Unit/Helper/DiscountTest.php

Discount type refactoring:
- return to bolt proper discount type for free shipping discount
https://app.asana.com/0/1201931884901947/1201594901813539/f
#changelog Proper discount label for free shipping discount

Discount type refactoring

---

Model/Api/OAuthRedirect.php

When we user logins with existing cart via bolt SSO the cart is not updated properly which leads to some issue.
In this PR we find quote_id in the session and update it
#changelog Update user's quote during SSO login
https://app.asana.com/0/1201931884901947/1202396691087893/f

Update user's quote during SSO login

---

Model/CatalogIngestion/ProductEventManager.php
Model/CatalogIngestion/ProductEventProcessor.php
Model/CatalogIngestion/ProductEventPublisher.php
Model/CatalogIngestion/Request/Product/DataProcessor.php
Plugin/Magento/Inventory/Model/SourceItem/Command/DecrementSourceItemQtyPlugin.php
Plugin/Magento/Inventory/Model/SourceItem/Command/SourceItemSavePlugin.php
Plugin/Magento/Inventory/Model/SourceItem/Command/SourceItemsDeletePlugin.php
Plugin/Magento/InventorySalesApi/Api/PlaceReservationsForSalesEventPlugin.php
etc/adminhtml/system.xml
etc/di.xml

- Refactored 2.2.8/2.3.0 support, added isModuleEnabled method instead di.xml class name insertion as string
- Changed in_stock/out_of_stock catalog ingestion triggering: now it's support multiple sales channels and multiple store sources assigned instead triggering each time when at least one of source item was changed.
#changelog Catalog ingestion: code refactoring

Catalog ingestion: code refactoring

---

Cron/CatalogIngestion.php
Model/CatalogIngestion/ProductEventManager.php
Model/CatalogIngestion/ProductEventProcessor.php
Model/CatalogIngestion/ProductEventPublisher.php
Model/CatalogIngestion/ProductEventRequestBuilder.php
Model/CatalogIngestion/Request/Product/DataProcessor.php
Model/CatalogIngestion/StoreConfigurationManager.php
Model/CatalogIngestion/StoreConfigurationRequestBuilder.php
Plugin/Magento/Config/Model/ConfigPlugin.php
Plugin/Magento/Inventory/Model/SourceItem/Command/DecrementSourceItemQtyPlugin.php
Plugin/Magento/Inventory/Model/SourceItem/Command/SourceItemSavePlugin.php
Plugin/Magento/Inventory/Model/SourceItem/Command/SourceItemsDeletePlugin.php
Plugin/Magento/InventorySalesApi/Api/PlaceReservationsForSalesEventPlugin.php
etc/adminhtml/system.xml
etc/di.xml

Added response status checks for bolt requests.
#changelog Catalog Ingestion: response code status checks added

Catalog Ingestion: response code status checks added

---

Cron/CatalogIngestion.php
Model/CatalogIngestion/ProductEventManager.php
Model/CatalogIngestion/ProductEventProcessor.php
Model/CatalogIngestion/ProductEventPublisher.php
Model/CatalogIngestion/ProductEventRequestBuilder.php
Model/CatalogIngestion/Request/Product/DataProcessor.php
Model/CatalogIngestion/StoreConfigurationManager.php
Model/CatalogIngestion/StoreConfigurationRequestBuilder.php
Plugin/Magento/Config/Model/ConfigPlugin.php
Plugin/Magento/Inventory/Model/SourceItem/Command/DecrementSourceItemQtyPlugin.php
Plugin/Magento/Inventory/Model/SourceItem/Command/SourceItemSavePlugin.php
Plugin/Magento/Inventory/Model/SourceItem/Command/SourceItemsDeletePlugin.php
Plugin/Magento/InventorySalesApi/Api/PlaceReservationsForSalesEventPlugin.php
Test/Unit/Cron/CatalogIngestionTest.php
Test/Unit/Model/CatalogIngestion/ProductEventManagerTest.php
Test/Unit/Model/CatalogIngestion/ProductEventProcessorTest.php
Test/Unit/Model/CatalogIngestion/ProductEventRequestBuilderTest.php
Test/Unit/Model/CatalogIngestion/StoreConfigurationManagerTest.php
Test/Unit/Model/CatalogIngestion/StoreConfigurationRequestBuilderTest.php
etc/adminhtml/system.xml
etc/di.xml

- Added integration tests for catalog ingestion.
#changelog Catalog ingestion: integration tests

Catalog ingestion: integration tests

---

etc/di.xml

Removed custom logger virtual type for catalog ingestion.
#changelog catalog ingestion: remove custom logger

catalog ingestion: remove custom logger

---

Api/OrderManagementInterface.php
Helper/Order.php
Model/Api/OrderManagement.php
Test/Unit/Helper/OrderTest.php
Test/Unit/Model/Api/OrderManagementTest.php
etc/webapi.xml

Implement API endpoint to create a partial invoice
https://app.asana.com/0/1200879031426307/1202157490713738/f
#changelog Implement API endpoint to create a partial invoice

Implement API endpoint to create a partial invoice

---

Helper/Order.php

Save token alias into payment info object if processor is Adyen 
#changelog Save token alias into payment info object if processor is Adyen

Save token alias into payment info object if processor is Adyen

---

Helper/Order.php

Save expiration into payment info object
#changelog Save expiration into payment info object

Save expiration into payment info object

---

etc/integration/api.xml

Module Magento Commerce Gift Card plugin introduces its own resource "Magento_GiftCardAccount::customer_giftcardaccount" 
#changelog Add scope for Magento Commerce Gift Card plugin

Add scope for Magento Commerce Gift Card plugin

---

Helper/Order.php

Fixes: https://app.asana.com/0/1201495896048972/1202496986980963
#changelog Save bin into payment info object

Save BIN into payment info object

---

Model/CatalogIngestion/Request/Product/DataProcessor.php
Test/Unit/Model/CatalogIngestion/ProductEventRequestBuilderTest.php

Changed prices format in request to int64 using CurrencyUtils::toMinor static method
Fixes: [(link ticket)](https://app.asana.com/0/1201748965125532/1202568681897387)
#changelog catalog ingestion: fix price format

catalog ingestion: fix price format

---

Model/CatalogIngestion/Request/Product/DataProcessor.php

Instead of the list of properties we pass the team would prefer us to send "standard"
Fixes: ([Asana](https://app.asana.com/0/1201931884901947/1202584370008319/f))
#changelog Catalog Sizename

Catalog Sizename

---

Plugin/Magento/Framework/View/Element/UiComponent/DataProvider/DataProviderPlugin.php

Fix runtime-error with PHP8.1
Fixes: https://app.asana.com/0/951157735838091/1202599162998023/f
#changelog Fix runtime-error with PHP8.1

Fix runtime-error with PHP8.1

---

Block/Js.php
Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Test/Unit/Block/JsTest.php
view/frontend/templates/js/boltjs.phtml

Adds shopper assistant script to M2 plugin. I tested this change on my M2 devbox running against a merchant in staging.
#changelog Add shopper assistant script
https://user-images.githubusercontent.com/55464043/179085992-fedc5c20-27ee-4b64-8a56-da343401fd8f.mov

Add shopper assistant script

---

Block/System/Config/IntegrationConnection.php
etc/adminhtml/system.xml

Added comment with explanation why we need magento auth creds & changed oauth label & btn text
#changelog Changed oauth btn name and added explanation
---
- https://app.asana.com/0/0/1201756522263682

Changed oauth btn name and added explanation

---

Helper/Cart.php
Model/EventsForThirdPartyModules.php
ThirdPartyModules/Amasty/Extrafee.php

This PR is to add support for the Amasty_Extrafee extension
See video link for testing: 
https://watch.screencastify.com/v/Qb8KxejHDk4icGsprRzE
Fixes: https://app.asana.com/0/564264490825835/1202488104601528
#changelog Add support for Amasty Extrafee extension

Add support for Amasty Extrafee extension

---

Helper/Cart.php
Helper/Order.php
Model/Api/CreateOrder.php
Model/Api/DiscountCodeValidation.php
Model/Api/OrderManagement.php
Model/Api/ShippingMethods.php
Model/Api/ShippingTax.php
Model/Api/UpdateCart.php
Model/Service/InvoiceService.php
Test/Unit/Helper/CartTest.php
Test/Unit/Helper/OrderTest.php
Test/Unit/Model/Service/InvoiceServiceTest.php

For Bolt api requests, the httpContext could lose currency info for some reasons. So we have to add currency info for each api request.
Fixes: https://app.asana.com/0/951157735838091/1202452720391991/f
#changelog Support multiple currencies in checkout

Support multiple currencies in checkout

---

Helper/ArrayHelper.php
Plugin/Magento/Fedex/Model/CacheFedexResultPlugin.php

The use of PHP functions serialize & unserialize is forbidden, so we have to use Magento\Framework\Serialize\SerializerInterface::serialize() and Magento\Framework\Serialize\SerializerInterface::unserialize () instead.
Since the response of Fedex API is a mixed array&object, we also have to create function to restore the serialized cache data properly.
Fixes: https://app.asana.com/0/1201931884901947/1202625580645047/f
#changelog Serialize&unserialize fedex cache with Magento functions

Serialize&unserialize fedex cache with Magento functions

---

CHANGELOG.md
Test/Unit/Block/JsTest.php
composer.json
etc/module.xml

#changelog Bump version to 2.26.1

Bump version to 2.26.1

---

Block/BlockTrait.php
Block/Checkout/Success.php
Block/Customer/CreditCard.php
Block/Js.php
Model/EventsForThirdPartyModules.php
Plugin/Magento/Framework/App/Action/AbstractActionPlugin.php
Test/Unit/Block/JsTest.php
ThirdPartyModules/Magento/CompanyPayment.php
etc/frontend/di.xml

Using B2B feature, the merchant can specifies each payment method that is available to B2B buyers. Then we need to support this feature for Bolt payment method.
Fixes: https://app.asana.com/0/951157735838091/1202786747358167/f
#changelog Add support for Magento B2B Features

Add support for Magento B2B Features

---

Api/Data/PluginVersionNotificationInterface.php
Api/PluginVersionNotificationRepositoryInterface.php
Cron/VersionNotifier.php
Helper/Config.php
Model/ResourceModel/VersionNotifier/PluginVersionNotification.php
Model/ResourceModel/VersionNotifier/PluginVersionNotification/Collection.php
Model/System/Message/NewVersionNotification.php
Model/VersionNotifier/PluginVersionNotification.php
Model/VersionNotifier/PluginVersionNotificationRepository.php
Model/VersionNotifier/VersionValidator.php
Service/GitApiService.php
etc/adminhtml/di.xml
etc/adminhtml/system.xml
etc/config.xml
etc/crontab.xml
etc/db_schema.xml
etc/db_schema_whitelist.json
etc/di.xml

Added cron job to check for a new version of Boltpay plugin available & render notification on the admin dashboard
https://app.asana.com/0/0/1202585470711886
#changelog Created new plugin version notifier feature for Bolt M2 plugin
---
- https://app.asana.com/0/0/1202585470711886

Created new plugin version notifier feature for Bolt M2 plugin

---

ThirdPartyModules/Mirasvit/Credit.php

#changelog M2 Change Mirasvit Reference

M2 Change Mirasvit Reference

---

view/frontend/templates/button_product_page.phtml

during button initialization in incognito mode the form_key cookie can be unavailable
Fixes: [(link ticket)](https://app.asana.com/0/1200879031426307/1202835151439363/f)
#changelog Product page button cookie

Product page button cookie

---

Helper/Order.php
Test/Unit/Helper/OrderTest.php

Added event dispatch for coupon deinscrement event
https://app.asana.com/0/1201931884901947/1202923667345154
#changelog Add dispatch for couon deincrement event

Add dispatch for coupon deincrement event

---

CHANGELOG.md
Test/Unit/Block/JsTest.php
composer.json
etc/module.xml

#changelog Bump version to 2.26.2

Bump version to 2.26.2

---

Model/Api/RouteInsuranceManagement.php
Plugin/WebapiRest/Magento/Checkout/Api/GuestPaymentInformationManagementPlugin.php
Plugin/WebapiRest/Magento/Checkout/Api/PaymentInformationManagementPlugin.php
etc/webapi_rest/di.xml

Added plugins to add quote id into checkout session, to let route ext support order creation
#changelog Added plugins to add quote id into checkout session, to let route ext support order creation

Added plugins to add quote id into checkout session, to let route ext support order creation

---

ThirdPartyModules/Route/Route.php

This reverts commit 95839172a5fb2edf7ee85d99e54ed78c003f2516.
#changelog Revert "M2 API: collect totals if route is enabled"

Revert "M2 API: collect totals if route is enabled"

---

Plugin/Magento/Checkout/CustomerData/Cart.php
etc/frontend/di.xml

Added quote masked id to the customer cart section.
Fixes: https://app.asana.com/0/1201931884901947/1203149984454968/f
#changelog Add quote masked id to native cart customer section

Fetch cart: quote masked id to native cart customer section

---

Plugin/Magento/Checkout/CustomerData/Cart.php

#changelog Fetch Cart: add bolt hints to customer-data cart

Fetch Cart: add bolt hints to customer-data cart

---

Helper/FeatureSwitch/Decider.php
Helper/FeatureSwitch/Definitions.php
Plugin/Magento/Checkout/CustomerData/Cart.php
Section/CustomerData/BoltCart.php
Test/Unit/Helper/CartTest.php

Added new feature switcher: 'M2_FETCH_CART_VIA_API' which is disabling "bolt_cart" customer section.
Fixes: https://app.asana.com/0/1201931884901947/1203149984454972/f
#changelog new feature switcher M2_FETCH_CART_VIA_API

Fetch cart: feature switcher

---

Model/Api/OAuthRedirect.php

Fixed sso cart items mismatch between customer / guest cards through the sso login process:
1. Added merging customer cart into guest cart and making guest cart as current active card for customers which is login via sso not in bolt modal (before this fix we are replacing customer cart by guest cart)
2. Added replacing customer cart by guest cart and making guest cart as current active card for customers which is login via sso in bolt modal. (before this fix we have situation when customer have 2 active carts after login in bolt pupup)
Fixes: https://app.asana.com/0/1200682492091884/1203162263301489/f
#changelog fix sso cart items mismatch between customer / guest cards after login.

Fix cart items mismatch with swithcing guest/registered accounts

---

CHANGELOG.md
Test/Unit/Block/JsTest.php
composer.json
etc/module.xml

#changelog Bump version to 2.26.3

Bump version to 2.26.3

---

Block/BlockTrait.php
Block/MinifiedJs.php
Block/MinifiedJsCartApiDriven.php
Test/Unit/Block/MinifiedJsTest.php
view/frontend/layout/default.xml
view/frontend/templates/js/replacejs-cart-api-driven.phtml
view/frontend/web/js/bolt-api-driven-checkout.js

Fixes: https://app.asana.com/0/1201931884901947/1203149984454974/f
#changelog ReplaceJs Api Driven Implementation

Fetch Cart: ReplaceJs Api Driven Implementation

---

Block/BlockTrait.php
view/frontend/web/js/bolt-api-driven-checkout.js

#changelog Fetch Cart: minicart initialisation
---
- https://app.asana.com/0/0/1203268043628389

Fetch Cart: minicart initialisation

---

Block/BlockTrait.php
view/frontend/web/js/bolt-api-driven-checkout.js

#changelog Fetch Cart: order management
---
- https://app.asana.com/0/0/1203408972505987

Fetch Cart: order management

---

Model/CatalogIngestion/Request/Product/DataProcessor.php

Catalog ingestion: don't add product variant per each store in the given website
https://app.asana.com/0/1201307079775363/1203427964879730/f
#changelog Catalog ingestion: don't add product variant per each store in the given website

Catalog ingestion: don't add product variant per each store in the given website

---

Model/CatalogIngestion/Request/Product/DataProcessor.php
Test/Unit/Model/CatalogIngestion/ProductEventRequestBuilderTest.php

Catalog Ingestion:
- updated ListPrice/SalePrice to magento regular_price/final_price.
- added related test with special price.
Fixes: https://app.asana.com/0/1201931884901947/1203456209413871/f
#changelog Catalog Ingestion: price values updated

Catalog Ingestion: list price, sale price

---

.github/CODEOWNERS

#changelog Set more specific github group for codeowneres

Set more specific github group for codeowneres

---

Model/CatalogIngestion/Request/Product/DataProcessor.php
Test/Unit/Model/CatalogIngestion/ProductEventRequestBuilderTest.php

Removed MerchantVariantID field as unsupported in magento
Fixes: https://app.asana.com/0/1201931884901947/1203456209413864/f
#changelog Catalog ingestion: variant products

Catalog ingestion: Remove MerchantVariantID field

---

Model/CatalogIngestion/Request/Product/DataProcessor.php
Test/Unit/Model/CatalogIngestion/ProductEventRequestBuilderTest.php

- Added bundle product variants as his child products
- added integration test for bundle product case
Fixes: https://app.asana.com/0/1201931884901947/1203456209413864/f
#changelog Catalog Ingestion: bundle product variants support

Catalog Ingestion: bundle product support

---

Model/CatalogIngestion/Request/Product/DataProcessor.php
Test/Unit/Model/CatalogIngestion/ProductEventRequestBuilderTest.php

Catalog ingestion:
- added support for grouped product type
- added related test case
#changelog Catalog Ingestion: grouped products

Catalog Ingestion: grouped products

---

Model/CatalogIngestion/Request/Product/DataProcessor.php
Test/Unit/Model/CatalogIngestion/ProductEventRequestBuilderTest.php

Catalog ingestion:
- added configurable options support
- updated related tests
#changelog Catalog Ingestion: configurable product

Catalog Ingestion: configurable product

---

Model/CatalogIngestion/Request/Product/DataProcessor.php
Test/Unit/Model/CatalogIngestion/ProductEventRequestBuilderTest.php

Catalog ingestion
- added "ParentProductIDs" param
- updated related tests
#changelog Catalog Ingestion: added parent product ids param

Catalog Ingestion: added parent product ids param

---

view/frontend/web/js/bolt-api-driven-checkout.js

Added "payment only" flow to api fetch cart.
Fixes: https://app.asana.com/0/1201931884901947/1203363135297443/f
#changelog Fetch Cart: payment only

Fetch Cart: payment only

---

Plugin/WebapiRest/Magento/Checkout/Api/PaymentInformationManagementPlugin.php

Because the route plugin doesn't support API order creation (it saves data in the checkout session), [we built a workaround in our plugin](https://github.com/BoltApp/bolt-magento2/blob/2d88e4f032ba2736af6ed85574a361c302a018a1/Plugin/WebapiRest/Magento/Checkout/Api/PaymentInformationManagementPlugin.php#L77), which emulates the session data.
But if between our code and actual order creation, any third party module read the quote from the session [this code cleaned it up](https://github.com/magento/magento2/blob/78dd0652658ced5b0e93cc6629e774bf1958c5e9/app/code/Magento/Checkout/Model/Session.php#L257) (introduced in Magento 2.3.2)
Solution: set in session customer object as well to prevent quote clean up.
Asana: https://app.asana.com/0/1201931884901947/1203441506208729/f
#changelog M2 API …

M2 API route support: set customer object to the session

---

Helper/FeatureSwitch/Debug.php
Model/Api/Data/DebugInfo.php
Model/Api/Debug.php
Model/CatalogIngestion/Debug.php

Added new data to the "/V1/bolt/boltpay/debug" api endpoint and universal api "debug" event "V2/bolt/boltpay/api"
- catalog ingestion: "product_event_rows_count" -> current database rows count in table "bolt_product_event"
- cron_log -> last 5 rows related to "bolt_catalog_ingestion" cronjob
- feature_switches list of all feature switches with data from table "bolt_feature_switches"
Response example:
```
"catalog_ingestion": {
"product_event_rows_count": 5,
"cron_log": [
{
"schedule_id": "257",
"job_code": "bolt_catalog_ingestion",
"status": "pending",
"messages": null,
"created_at": "2022-12-06 15:57:46",
"scheduled_at": "2022-12-06 16:00:00",
"executed_at": null,
"finished_at": null
}
]
},
"feature_switches": [
{
"id": "1",
"switch_name": "M2_ENABLE_API_DRIVEN_INTEGRAION", …
```

Update debug api endpoint data

---

Model/Api/Tax.php

This  filter is used for split shipping integration for Metroplex
We added this filter event so we can adjust tax result for split shipping case. See the integration change here: https://github.com/BoltApp/bolt-magento2/commit/f3bc6c75ff0cde46ddd362ce166f3a14427ee407#diff-65b5adc1ff2b56cd3f79b134a092e74f2e28d0d61c23729b457d49011edca73cR773
Fixes: https://app.asana.com/0/564264490825835/1202685233839443
#changelog Add filterTaxResult filter in tax endpoint

Add filterTaxResult filter in tax endpoint

---

Api/Data/GetProductDataInterface.php
Model/CatalogIngestion/Request/Product/DataProcessor.php
Test/Unit/Model/CatalogIngestion/ProductEventRequestBuilderTest.php

Catalog ingestion: clean up product payload
#changelog Catalog ingestion: clean up product payload

Catalog ingestion: clean up product payload

---

Api/OrderManagementInterface.php
Model/Api/OrderManagement.php
etc/webapi.xml

A lot of merchants have customizations for order place process which is assigned to sales_order_place_before & sales_order_place_after observer events. In order to fix issue that we've had at past we've created around plugin for place method [here](https://github.com/BoltApp/bolt-magento2/pull/746). With our new M2 native integration we're having issues now with these events, as many of them is not working as expected. So we're introducing api endpoint which will trigger order->place() method & run through all observer events properly.
#changelog Add endpoint to trigger order->palce() method to trigger before & after place events
---
- To see the specific tasks where the Asana app …

Add endpoint to trigger order->palce() method to trigger before & after place events

---

Plugin/Magento/Framework/View/Element/UiComponent/DataProvider/RegularFilterPlugin.php

Fixed sales order grid payment method column filter:
Code refactored:
- removed `"!"` before `($filterValue = $filter->getValue())`
- added support for multiple filter values
- made code more readable
Tested locally:
- multiple payment filter (only bolt)
- multiple payment filter (bolt + other)
- bolt single payment filter
- single payment filter
- multiple payment filter (only bolt) + other filters
- multiple payment filter (bolt + other) + other filters
- bolt single payment filter + other filters
- single payment filter + other filters
Fixes: https://app.asana.com/0/474713171217346/1203469295711778/f
Before fix:
After fix:
#changelog Fixed sales order grid payment method column filter

Fixed sales order grid payment method column filter

---

CHANGELOG.md
Test/Unit/Block/JsTest.php
composer.json
etc/module.xml

#changelog Bump version to 2.26.4

Bump version to 2.26.4

---

Helper/Cart.php

Fix a possible null pointer exception if getSignResponse return null
https://app.asana.com/0/1200879031426307/1203536836635305/f
#changelog Vincent/bugfix/prevent null invocation

Prevent Null Error on getSignResponse

---

view/frontend/templates/js/replacejs.phtml

#changelog Add 0 delay before invalidate bolt cart in close callback

Add 0 delay before invalidate bolt cart in close callback

---

Setup/UpgradeSchema.php
etc/db_schema.xml
etc/db_schema_whitelist.json

Moved table declaration from db_schema to upgrade schema in order to avoid issues with converting upgrade schema to db_schema & backword compatibility
Fixes: 
https://app.asana.com/0/1201931884901947/1203677046550285
#changelog Move table declaration from db_schema to upgrade schema

Move table declaration from db_schema to upgrade schema

---

Plugin/WebapiRest/Magento/Checkout/Api/GuestPaymentInformationManagementPlugin.php
Plugin/WebapiRest/Magento/Checkout/Api/PaymentInformationManagementPlugin.php

Currently, if the quote doesn't have billing address, the exception will throw
TypeError: Argument 5 passed to Bolt\Boltpay\Plugin\WebapiRest\Magento\Checkout\Api\GuestPaymentInformationManagementPlugin::beforeSavePaymentInformationAndPlaceOrder() must be an instance of Magento\Quote\Api\Data\AddressInterface, null given, called in /home/bolt/public_html/m2api.bolt.devzn.com/vendor/magento/framework/Interception/Interceptor.php on line 121 and defined in /home/bolt/public_html/m2api.bolt.devzn.com/app/code/Bolt/Boltpay/Plugin/WebapiRest/Magento/Checkout/Api/GuestPaymentInformationManagementPlugin.php:66
So this PR is to correct argument in beforeSavePaymentInformationAndPlaceOrder method (accept null value as Magento core logic here …

Correct argument in beforeSavePaymentInformationAndPlaceOrder method

---

Helper/ModuleRetriever.php

Updated debug endpoint added composer package module version, example:
```
{
"name": "Magento_Swagger",
"version": "100.4.2"
},
{
"name": "Magento_SwaggerWebapi",
"version": "100.4.0"
},
{
"name": "Magento_SwaggerWebapiAsync",
"version": "100.4.0"
},
{
"name": "Magento_Swatches",
"version": "100.4.3"
},
{
"name": "Magento_SwatchesGraphQl",
"version": "100.4.2"
},
{
"name": "Magento_SwatchesLayeredNavigation",
"version": "100.4.0"
},
{
"name": "Magento_Tax",
"version": "100.4.3"
},
{
"name": "Magento_TaxGraphQl",
"version": "100.4.0"
},
{
"name": "Magento_TaxImportExport",
"version": "100.4.3"
},
{
"name": "Magento_AsynchronousOperations",
"version": "100.4.3"
},
{
"name": "Magento_ThemeGraphQl",
"version": "100.4.1"
},
{
"name": "Magento_Translation",
"version": "100.4.3"
},
{
"name": …
```

M2 update debug endpoint: added package module version

---

CHANGELOG.md
Test/Unit/Block/JsTest.php
composer.json
etc/module.xml

#changelog Bump version to 2.26.5

Bump version to 2.26.5

---

Model/Api/OAuthRedirect.php

- Fixed missed quote error for case when customer quote was in status "inactive" during double SSO authorization requests to magento by already authorized customer
Fixes: https://app.asana.com/0/1201931884901947/1203861445772872/f
#changelog SSO double authorization missed quote issue fix

SSO double authorization missed active quote issue

---

Model/CatalogIngestion/Request/Product/DataProcessor.php
Test/Unit/Model/CatalogIngestion/ProductEventRequestBuilderTest.php

Fixed syntax error in catalog ingestion custom product options collector
Fixes: https://app.asana.com/0/951157735838091/1204026223834768/f
#changelog php syntax error fix in catalog ingestion custom options collector

Catalog ingestion: syntax error fix

---

view/frontend/web/js/bolt-api-driven-checkout.js

Fetch Cart:
- fixed bolt checkout button initialization for case when cart is loaded from browser cache without calling customer-data events.
Fixes: https://app.asana.com/0/1201931884901947/1204096542237715/f
#changelog fetch cart fixed bolt initialization

Fetch Cart: bolt checkout initialization from browser cache

---

Helper/Config.php

#changelog Remove duplicated key from CONFIG_SETTING_PATHS array
Asana:
https://app.asana.com/0/1201931884901947/1204028793252855/f

Remove duplicated key from CONFIG_SETTING_PATHS array

---

Model/CatalogIngestion/Request/Product/DataProcessor.php

#changelog Remove unused function getMediaImageEntry
Asana:
https://app.asana.com/0/1201931884901947/1204028793252855/f

Remove unused function getMediaImageEntry

---

CHANGELOG.md
Test/Unit/Block/JsTest.php
etc/module.xml

Bump plugin version to 2.27.0
#changelog Bump version to 2.27.0

Bump version to 2.27.0

---

Block/Adminhtml/MinifiedJsCartApiDriven.php
Controller/Adminhtml/Cart/Data.php
Helper/Cart.php
Plugin/Magento/Checkout/CustomerData/Cart.php
view/adminhtml/layout/sales_order_create_index.xml
view/adminhtml/templates/js/replacejs-cart-api-driven.phtml
view/adminhtml/web/js/bolt-api-driven-checkout.js

Fetch Cart: implemented support for back-office orders.
- added separate js library
- updated `boltpay/cart/data` adminhtml controller, now it is just returns prefill-address-hints and quote masked id.
- `getQuoteMaskedId` method moved to cart helper class, added support for latest magento version.
Fixes: https://app.asana.com/0/1201931884901947/1203149984455032/f
#changelog implemented fetch cart support for back-office orders

Fetch Cart: backoffice support implementation

---

Api/OrderManagementInterface.php
Model/Api/OrderManagement.php

In order to simplify customizations of custom placeOrder API request, $additionalTransactionInfo parameter introduced. 
Fixes: 
https://app.asana.com/0/1201931884901947/1203775885401238
#changelog Added additional transaction info parameter for easier use in customizations

Added additional transaction info parameter for easier use in customizations

---

Controller/Adminhtml/Cart/Data.php

Fetch cart backoffice
- fix backoffice order success redirect to frontend issue
Fixes: https://app.asana.com/0/1201931884901947/1203149984455032/f
#changelog fix backoffice redirect to frontend issue

Fetch cart: backoffice redirect issue fix

---

Test/Unit/Model/Api/FeatureSwitchesHookTest.php
Test/Unit/Model/CustomerCreditCardTest.php

Fixed integration tests failures:
Under magento 2.3.0 zend framework couldn't parse header line like: "HTTP/2 403" and throws excpetion "Invalid header line detected". During the test execution we are sending request to api sandbox, looks like the response was changed there therefore we have this response which can't be parsed on old magento version.
Response which couldn't be parsed:
```
HTTP/2 403 
date: Wed, 29 Mar 2023 08:20:34 GMT
content-type: application/json; charset=UTF-8
content-length: 109
public-key-pins-report-only: max-age=2592000;pin-sha256="OGAVOYhLZd3ADKYGFZOED1c5m1ObMlRv9PyIWrO4Nd0=";pin-sha256="RRM1dGqnDFsCJXBTHky16vi1obOlCgFFn/yOhI/y+ho=";pin-sha256="IXHYSIdST+XY22J5ivybYkntMIfjA5P6pMKX2hWG1BE=";report-uri="https://77aa1bd121ef22d50247a23390ce6cff.report-uri.io/r/defaul …
```

Integration tests fix

---

composer.json

#changelog Bump composer version to 2.27.0

Bump composer version to 2.27.0

---

CHANGELOG.md

Creating release notes manually as we need to get a release out today.
#changelog M2 2.27.0 Release Notes
Just release notes.

M2 2.27.0 Release Notes

---

Model/Api/Tax.php

This PR is to the public the getShippingDiscount method in the tax model class so we can use the method easier to do the integration
Here is example: https://github.com/BoltApp/bolt-magento2/blob/2.26.1.metroplex/ThirdPartyModules/Grabagun/InStorePickup.php#L830
#changelog Public getShippingDiscount in tax model class

Public getShippingDiscount in tax model class

---

CHANGELOG.md

#changelog Add changelog for version 2.27.1

Add changelog for version 2.27.1

---

etc/integration/api.xml

Adding a new scope to the oauth token to allow us to use transactions api.
#changelog Add fetch transactions scope to oauth

Add fetch transactions scope to oauth

---

Section/CustomerData/BoltCart.php
Section/CustomerData/BoltHints.php
Test/Unit/Section/CustomerData/BoltCartTest.php
Test/Unit/Section/CustomerData/BoltHintsTest.php

Prevent Bolt cart creation if bolt pay is disabled
#changelog Prevent Bolt cart creation if bolt pay is disabled

Prevent Bolt cart creation if bolt pay is disabled

---

Model/EventsForThirdPartyModules.php
ThirdPartyModules/MageWorx/Donations.php

Add support for Mageworx_Donation extension
Fixes: https://app.asana.com/0/1204419514580775/1204781325200965
#changelog Add support for Mageworx_Donation extension

Add support for Mageworx_Donation extension

---

Block/Info.php

M2 order admin page payment information updated:
- added CVV response
- added AVS response
Fixes: https://app.asana.com/0/1201931884901947/1204920567358237
#changelog M2 order admin page payment information data updated: added CVV and AVS data response
https://github.com/BoltApp/source/pull/57923

Payment information data update: added cvv and avs with text

---

view/frontend/web/js/bolt-api-driven-checkout.js

Sometimes, when window.BoltCheckout isn't initialized, we use this method whenDefined(window, 'BoltCheckout', BoltCheckoutApiDriven.init, 'BoltCheckoutApiDrivenInit') to wait for the window.BoltCheckout to be defined and re-execute the BoltCheckoutApiDriven.init method. However, the issue here is that when executing BoltCheckoutApiDriven.init method https://github.com/BoltApp/bolt-magento2/blob/master/view/frontend/web/js/bolt-api-driven-checkout.js#L1084, it throw exception since the **this** variable is undefined. 
See screenshot here: https://prnt.sc/B8gIXh6NHOgj 
This causes Bolt button disappears in minicart
See screenshot here: https://prnt.sc/gViBbU5P98fi
So in order to fix this, we need to use BoltCheckoutApiDriven instead of this. 
Fixes: …

Fetch Cart API: Fix bug that sometimes, bolt button disappears in minicart

---

CHANGELOG.md
Test/Unit/Block/JsTest.php
composer.json
etc/module.xml

#changelog Bump version to 2.27.4

Bump version to 2.27.4

---

Helper/Cart.php
Helper/Config.php
Helper/MetricsClient.php
Helper/Order.php
Model/Api/CreateOrder.php
Model/Api/UniversalApi.php
Test/scripts/phpcs_meqp2.sh
ThirdPartyModules/Amasty/Affiliate.php
ThirdPartyModules/Amasty/GiftCard.php
ThirdPartyModules/Amasty/GiftCardAccount.php
ThirdPartyModules/Amasty/Rewards.php
ThirdPartyModules/MageWorld/Affiliate.php
ThirdPartyModules/Zonos/DutyTax.php
view/adminhtml/templates/boltpay/button.phtml
view/adminhtml/templates/order/comment.phtml
view/adminhtml/templates/system/config/integrationconnection.phtml
view/frontend/templates/button_product_page.phtml
view/frontend/templates/js/custom_sso_buttons.phtml

Fix error issues reported by phpcs with severity 9
Fixes: https://app.asana.com/0/1204419514580775/1206148918307666
#changelog Fix error issues reported by phpcs with severity 9

Fix error issues reported by phpcs with severity 9
